Repository o3de/o3de, pull requests merged in 2021-11, with the labels that each got.

#5132 Fixed memory leak of the in the AssetBrowserComponent
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
Labels: feature/editor, kind/bug

#5080 Fix frozen metrics on the timestamp view when using the 'Once per Second' update frequency mode
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.inl
Labels: sig/graphics-audio

#4995 Fix asset type retrieval in AssetCatalogModel::GetAssetType
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.h
Labels: kind/bug, sig/content

#5166 Removing redundant registration of script assets
  Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/EditorCommonSystemComponent.cpp
  Gems/LmbrCentral/Code/Source/LmbrCentral.cpp
Labels: sig/graphics-audio

#5021 Fix innocuous release build error in RPIUtils LoadStreamingTexture
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
Labels: sig/graphics-audio

#5152 Created custom JSON serializer for editor material component
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSerializer.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSerializer.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
Labels: sig/graphics-audio

#5115 Perform sse float comparisons with the floating-point intrinsics
  Code/Framework/AzCore/AzCore/Math/Internal/SimdMathCommon_sse.inl
  Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec1_sse.inl
  Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec2_sse.inl
  Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec3_sse.inl
  Code/Framework/AzCore/AzCore/Math/Internal/SimdMathVec4_sse.inl
Labels: pr-ready-to-merge

#5153 ATOM-16747 RPISystemInterface::GetDefaultScene returns the scene crea…
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/LuxCore/LuxCoreTexture.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystemInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/System/SceneDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/InputController/MaterialEditorViewportInputController.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/InputController/RotateEnvironmentBehavior.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportRenderer.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomBridgeSystemComponent.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.h
  Gems/AtomLyIntegration/AtomFont/Code/Include/AtomLyIntegration/AtomFont/FFont.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/DiffuseGlobalIllumination/DiffuseGlobalIlluminationComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/DisplayMapper/DisplayMapperComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkinnedMesh/SkinnedMeshDebugDisplay.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/Blast/Code/Source/Components/BlastSystemComponent.cpp
  Gems/LyShine/Code/Source/Draw2d.cpp
  Gems/LyShine/Code/Source/LyShine.cpp
  Gems/LyShine/Code/Source/UiRenderer.cpp
  Gems/LyShine/Code/Source/UiRenderer.h
Labels: sig/graphics-audio

#5138 Convert several physics automated tests with Base test level file converted to prefab file
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_BoxShapeEditing.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_CapsuleShapeEditing.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_SphereShapeEditing.py
  AutomatedTesting/Levels/Base/Base.prefab
Labels: sig/content, sig/core

#5144 Add missing exclamation mark for documentation
  Code/Framework/AzFramework/AzFramework/Matchmaking/IMatchmakingRequests.h
  Code/Framework/AzFramework/AzFramework/Matchmaking/MatchmakingNotifications.h
  Code/Framework/AzFramework/AzFramework/Matchmaking/MatchmakingRequests.h
  Code/Framework/AzFramework/AzFramework/Session/ISessionHandlingRequests.h
  Code/Framework/AzFramework/AzFramework/Session/ISessionRequests.h
  Code/Framework/AzFramework/AzFramework/Session/SessionConfig.h
  Code/Framework/AzFramework/AzFramework/Session/SessionNotifications.h
  Code/Framework/AzFramework/AzFramework/Session/SessionRequests.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftCreateSessionOnQueueRequest.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftCreateSessionRequest.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftSearchSessionsRequest.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Include/Request/AWSGameLiftStartMatchmakingRequest.h
Labels: sig/network

#5093 Scroll to and Select Gem When Gem Tag is Clicked
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemFilterWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemFilterWidget.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemSortFilterProxyModel.cpp
  Code/Tools/ProjectManager/Source/GemsSubWidget.cpp
  Code/Tools/ProjectManager/Source/GemsSubWidget.h
  Code/Tools/ProjectManager/Source/TagWidget.cpp
  Code/Tools/ProjectManager/Source/TagWidget.h
Labels: sig/content, sig/ui-ux

#5031 Fixed o3de python unit_test_register test on Linux/Mac
  scripts/o3de/tests/unit_test_register.py
Labels: platform/linux, platform/macos, sig/core, sig/testing

#4969 [development] Consolidated programmatic profiler capture API
  AutomatedTesting/Editor/Scripts/Profiler/__init__.py
  AutomatedTesting/Editor/Scripts/Profiler/profiler_system_example.py
  Code/Framework/AzCore/AzCore/Debug/Profiler.cpp
  Code/Framework/AzCore/AzCore/Debug/ProfilerBus.h
  Code/Framework/AzCore/AzCore/Debug/ProfilerReflection.cpp
  Code/Framework/AzCore/AzCore/Debug/ProfilerReflection.h
  Code/Framework/AzCore/AzCore/Debug/Trace.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/StreamerComponent.cpp
  Code/Framework/AzCore/AzCore/RTTI/BehaviorInterfaceProxy.h
  Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Debug/Trace_WinAPI.cpp
  Code/Legacy/CrySystem/AZCoreLogSink.h
  Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
  Gems/Profiler/Code/Include/Profiler/ProfilerBus.h
  Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp
  Gems/Profiler/Code/Source/ImGuiCpuProfiler.h
  Gems/Profiler/Code/Source/ProfilerSystemComponent.cpp
  Gems/Profiler/Code/Source/ProfilerSystemComponent.h
  Gems/Profiler/Code/profiler_files.cmake
  Registry/profiler.setreg
Labels: sig/core, sig/graphics-audio

#5141 Add benchmarks for SpawnAllEntities call in SpawnableEntitiesManager
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnAllEntitiesBenchmarks.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnableBenchmarkFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnableBenchmarkFixture.h
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content

#5136 Fix bug in LocalFileIO::ConvertToAliasBuffer when a resolved alias ends in a path separator.
  Code/Framework/AzFramework/AzFramework/IO/LocalFileIO.cpp
Labels: sig/core

#4778 LYN-6770 Automated Test Network Input
  AutomatedTesting/Gem/Code/CMakeLists.txt
  AutomatedTesting/Gem/Code/Source/AutoGen/NetworkTestPlayerComponent.AutoComponent.xml
  AutomatedTesting/Gem/Code/Source/AutomatedTestingModule.cpp
  AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.cpp
  AutomatedTesting/Gem/Code/automatedtesting_autogen_files.cmake
  AutomatedTesting/Gem/Code/automatedtesting_files.cmake
  AutomatedTesting/Gem/Code/enabled_gems.cmake
  AutomatedTesting/Gem/PythonTests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/__init__.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/AutoComponent_NetworkInput.prefab
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/AutoComponent_NetworkInput.scriptcanvas
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/Player.prefab
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/tags.txt
  Gems/LyShine/Code/CMakeLists.txt
  Gems/Multiplayer/Code/CMakeLists.txt
  Gems/Multiplayer/Code/Include/Multiplayer/Editor/MultiplayerPythonEditorEventsBus.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorGem.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/multiplayer_editor_shared_files.cmake
Labels: sig/network

#5018 [Linux] Terminate AssetProcessor when spawned by the parent project process
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Asset/AssetSystemComponentHelper_Linux.cpp
Labels: pr-ready-to-merge

#5196 ReflectionProbe cubemap visual quality improvements
  Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapForwardMSAA.pass
  Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapForwardSubsurfaceMSAA.pass
  Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapPipeline.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
Labels: sig/graphics-audio

#5117 Enable Atom CullingScene to use TaskGraph
  Code/Framework/AzCore/AzCore/Task/TaskExecutor.cpp
  Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
  Code/Framework/AzCore/AzCore/Task/TaskGraph.h
  Code/Framework/AzCore/AzCore/Task/TaskGraph.inl
  Code/Framework/AzCore/Tests/TaskTests.cpp
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Labels: sig/graphics-audio

#5193 LYN-7547 | Focus Mode - It is possible to create a child entity of a closed container
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Labels: sig/content

#5186 Fix for crash when using Simple LOD distance component
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Labels: sig/core

#5142 Shaders changes require two or more change cycles before updating
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderVariant.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderVariant.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/DiffuseGlobalIllumination/EditorDiffuseProbeGridComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.cpp
Labels: sig/graphics-audio

#5121 Fixed the chicken mohawk material to address depth sorting issues.
  Gems/NvCloth/Assets/Objects/cloth/Chicken/Actor/chicken_mohawkmat.material
Labels: sig/core

#5002 Added setreg option for network spawnables serialization format
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.h
  Gems/Multiplayer/Registry/prefab.tools.setreg
Labels: feature/networking, sig/network

#5033 Fixes the test_BasicLevelSetup_SetsUpLevel() test and adds proper asserts for screenshot comparisons.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_LightComponent.py
  Gems/Atom/TestData/TestData/Objects/plane.fbx
Labels: sig/graphics-audio, sig/testing

#5048 bugfix: cycle mouse to the other side of the screen when using scrollbox
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SpinBox.cpp
Labels: sig/content, status/ux-approved

#5284 Test parallel P0 HDR Color Grading Component
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRColorGradingAdded.py
Labels: sig/graphics-audio

#5240 Ensure ImGui menu is displayed when the Viewport UI viewport border is showing
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Framework/AzFramework/AzFramework/Viewport/ViewportBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplay.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplayLayout.h
  Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
Labels: feature/viewport

#5088 Animation Editor: Clicking Visualization in Anim Graph in the animation editor has no effect
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraph.cpp
Labels: feature/animation, sig/content

#5279 Correcting system requirements for the startup
  AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.cpp
Labels: sig/network

#5273 Fix material editor crash on shutdown if graph canvas gem is loaded
  Gems/GraphCanvas/Code/Source/Translation/TranslationBuilder.cpp
Labels: sig/graphics-audio

#5159 Update material editor and exporter to use relative paths for external references
  Gems/Atom/RPI/Code/CMakeLists.txt
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Tests/Common/RPITestFixture.h
  Gems/Atom/RPI/Code/atom_rpi_tests_files.cmake
  Gems/Atom/Tools/AtomToolsFramework/Code/CMakeLists.txt
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/MaterialPropertyUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_tests_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Utils/Code/CMakeLists.txt
  Gems/Atom/Utils/Code/Include/Atom/Utils/TestUtils/AssetSystemStub.h
  Gems/Atom/Utils/Code/Source/TestUtils/AssetSystemStub.cpp
  Gems/Atom/Utils/Code/atom_utils_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
Labels: sig/graphics-audio

#4944 bugfix: resolve crash with FBX Settings (#4813)
  Code/Legacy/CryCommon/ISystem.h
  Code/Legacy/CryCommon/platform_impl.cpp
  Code/Legacy/CrySystem/SystemInit.cpp
Labels: feature/asset-pipeline, kind/bug, pr-ready-to-merge

#4992 Remove virtual keyword in AssetEditorMainWindow
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasEditor/GraphCanvasAssetEditorMainWindow.h
Labels: sig/content, review-required

#5312 Fix minor repeated AMAZON_LINUX in the code comment
  Gems/AWSGameLift/cdk/aws_gamelift/fleet_configurations.py
Labels: sig/network

#5309 SpotLight debug draw to include display cone
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DiskLightDelegate.cpp
Labels: sig/graphics-audio

#5275 [Linux] Unify Editor and Game raw mouse event handling
  Code/Editor/Platform/Linux/Editor/Core/QtEditorApplication_linux.cpp
  Code/Editor/Platform/Linux/Editor/Core/QtEditorApplication_linux.h
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbApplication.cpp
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbConnectionManager.h
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbEventHandler.h
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/Actions.h
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.cpp
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.h
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbBaseTestFixture.h
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceKeyboardTests.cpp
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceMouseTests.cpp
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/azframework_xcb_tests_files.cmake
Labels: sig/core, sig/platform

#5323 Test parallel Add P0 Bloom
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_BloomAdded.py
Labels: sig/graphics-audio

#5318 [MacOS] Launching Editor from ProjectManager and other misc. fixes
  Code/Framework/AzFramework/Platform/Mac/AzFramework/Asset/AssetSystemComponentHelper_Mac.cpp
  Code/Tools/BundleLauncher/O3DE_SDK_Launcher.cpp
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: pr-ready-to-merge

#5274 Fix for alignment issue with terrain heights.
  Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
Labels: sig/content, sig/graphics-audio

#5358 ATOM-15086 Image Pipeline Unexpectedly Pre-Multiplying Alpha into Col…
  Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageObject.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/ColorChart.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/Cubemap.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/HighPass.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/PresetInfoPopup.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvertJob.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageFlags.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageObjectImpl.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageObjectImpl.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageToProcess.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Tests/ImageProcessing_Test.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/imageprocessing_files.cmake
Labels: sig/graphics-audio

#5325 Fix issue with Server Launcher debug console not accepting keystrokes
  Code/LauncherUnified/launcher_generator.cmake
  Code/Legacy/CrySystem/XConsole.cpp
Labels: kind/bug, pr-ready-to-merge, sig/core, feature/systems

#5354 Test parallel Add P0 Deferred Fog
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DeferredFogAdded.py
Labels: sig/graphics-audio

#5375 Modify Atom DrawWireCircle2d to account for viewport aspect ratio
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
Labels: sig/graphics-audio

#5385 StandardMultilayerPBR_ForwardPass.azsl. the type of input.m_normal is
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
Labels: sig/graphics-audio

#5301 Update default camera orbit behavior
  Code/Editor/EditorModularViewportCameraComposer.cpp
  Code/Editor/EditorPreferencesPageViewportCamera.cpp
  Code/Editor/EditorPreferencesPageViewportCamera.h
  Code/Editor/EditorViewportSettings.cpp
  Code/Editor/EditorViewportSettings.h
  Code/Editor/EditorViewportWidget.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
Labels: sig/content, feature/viewport

#4948 Asset Browser Tests
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.h
  Code/Framework/AzToolsFramework/Tests/UI/AssetBrowserTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content, sig/testing

#5389 ATOM-16747 RPISystemInterface::GetDefaultScene returns the scene crea…
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/LuxCore/LuxCoreTexture.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystemInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/System/SceneDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRenderer.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/InputController/MaterialEditorViewportInputController.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/InputController/RotateEnvironmentBehavior.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportRenderer.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomBridgeSystemComponent.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.h
  Gems/AtomLyIntegration/AtomFont/Code/Include/AtomLyIntegration/AtomFont/FFont.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/DiffuseGlobalIllumination/DiffuseGlobalIlluminationComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/DisplayMapper/DisplayMapperComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkinnedMesh/SkinnedMeshDebugDisplay.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/Blast/Code/Source/Components/BlastSystemComponent.cpp
  Gems/LyShine/Code/Source/Draw2d.cpp
  Gems/LyShine/Code/Source/LyShine.cpp
  Gems/LyShine/Code/Source/UiRenderer.cpp
  Gems/LyShine/Code/Source/UiRenderer.h
Labels: sig/graphics-audio

#5232 Improve handling of cached data limits.
  Gems/Profiler/Code/Source/CpuProfilerImpl.cpp
  Gems/Profiler/Code/Source/CpuProfilerImpl.h
Labels: sig/graphics-audio

#5417 Queuing inspector invalidation to remove stall opening/closing several documents
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/InspectorPropertyGroupWidget.cpp
Labels: sig/graphics-audio

#5416 Add missing runtime dependency to atom ly integration
  Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt
Labels: sig/graphics-audio

#5359 Wait to Activate Editor-server Until the Logging System is Ready
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
Labels: sig/network

#5317 Allow using gem repos page without losing changes
  Code/Framework/AzQtComponents/AzQtComponents/Components/ToastNotification.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/ToastNotification.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/ToastNotificationConfiguration.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Notifications/ToastNotificationsView.cpp
  Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/CreateProjectCtrl.h
  Code/Tools/ProjectManager/Source/DownloadController.cpp
  Code/Tools/ProjectManager/Source/DownloadController.h
  Code/Tools/ProjectManager/Source/EngineScreenCtrl.cpp
  Code/Tools/ProjectManager/Source/EngineScreenCtrl.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoInspector.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.h
  Code/Tools/ProjectManager/Source/GemsSubWidget.cpp
  Code/Tools/ProjectManager/Source/GemsSubWidget.h
  Code/Tools/ProjectManager/Source/TagWidget.cpp
  Code/Tools/ProjectManager/Source/TagWidget.h
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.h
Labels: sig/content, sig/ui-ux, WF1, RTE

#5414 Fix Additional Gem Info Handling and Display
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
Labels: sig/content, sig/ui-ux

#5360 Fixed PBR Material Transmission ThinObject Mode
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/BackLighting.azsli
  Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/015_SubsurfaceScattering_Transmission_Thin.material
Labels: sig/graphics-audio

#5382 Fixed .bat chain for launching maya for AtomContent gems
  Gems/AtomContent/ReferenceMaterials/Tools/Launch_Cmd.bat
  Gems/AtomContent/ReferenceMaterials/Tools/Launch_Maya.bat
  Gems/AtomContent/ReferenceMaterials/Tools/Project_Env.bat
  Gems/AtomContent/Sponza/Tools/Launch_Cmd.bat
  Gems/AtomContent/Sponza/Tools/Launch_Maya.bat
  Gems/AtomContent/Sponza/Tools/Project_Env.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Maya.bat
Labels: sig/graphics-audio

#4426 Fixed potential render scene time precision issues.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Labels: sig/graphics-audio

#5368 EMotion FX: Taskify dual quat skinning deformer
  Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.h
Labels: feature/animation

#5401 EMotion FX: Apply motion extraction only in game-mode and for anim editor entities
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.h
Labels: feature/animation

#5406 EMotion FX: Fix for the Y motion coordinate not being editable in blend space nodes
  Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/BlendSpaceMotionContainerHandler.cpp
Labels: feature/animation

#5380 [LYN-8041] Enable relocation of the Project Game Release Layout
  Code/Editor/CryEdit.cpp
  Code/Editor/Include/IFileUtil.h
  Code/Editor/Util/FileUtil.cpp
  Code/Editor/Util/FileUtil.h
  Code/Editor/Util/FileUtil_impl.cpp
  Code/Editor/Util/FileUtil_impl.h
  Code/Editor/Util/PathUtil.cpp
  Code/Editor/WelcomeScreen/WelcomeScreenDialog.cpp
  Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
  Code/Framework/AzCore/AzCore/Component/ComponentApplication.h
  Code/Framework/AzCore/AzCore/Component/ComponentApplicationBus.h
  Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
  Code/Framework/AzCore/AzCore/StringFunc/StringFunc.cpp
  Code/Framework/AzCore/AzCore/StringFunc/StringFunc.h
  Code/Framework/AzCore/AzCore/UnitTest/MockComponentApplication.h
  Code/Framework/AzCore/Tests/BehaviorContextFixture.h
  Code/Framework/AzCore/Tests/Components.cpp
  Code/Framework/AzCore/Tests/Serialization.cpp
  Code/Framework/AzFramework/AzFramework/API/ApplicationAPI.h
  Code/Framework/AzFramework/AzFramework/Application/Application.cpp
  Code/Framework/AzFramework/AzFramework/Application/Application.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Thumbnails/SourceThumbnail.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/SourceControlThumbnail.cpp
  Code/Framework/AzToolsFramework/Tests/ComponentAddRemove.cpp
  Code/Framework/AzToolsFramework/Tests/UI/EntityPropertyEditorTests.cpp
  Code/Tools/AssetBundler/source/utils/GUIApplicationManager.cpp
  Code/Tools/AssetBundler/source/utils/applicationManager.cpp
  Code/Tools/AssetBundler/source/utils/utils.cpp
  Code/Tools/AssetBundler/source/utils/utils.h
  Code/Tools/AssetBundler/tests/UtilsTests.cpp
  Code/Tools/AssetBundler/tests/applicationManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/platformconfiguration/platformconfigurationtests.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/PythonBindingsExample/source/Application.cpp
  Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
  Code/Tools/SerializeContextTools/Converter.cpp
  Code/Tools/SerializeContextTools/Converter.h
  Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h
  Gems/AssetValidation/Code/Source/AssetValidationSystemComponent.cpp
  Gems/AssetValidation/Code/Tests/AssetValidationTestShared.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Tests/ImageProcessing_Test.cpp
  Gems/Atom/Feature/Common/Code/Source/LuxCore/LuxCoreRenderer.cpp
  Gems/Atom/RPI/Code/Tests.Builders/BuilderTestFixture.h
  Gems/Atom/RPI/Code/Tests/Common/AssetManagerTestFixture.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
  Gems/AudioSystem/Code/Source/Editor/ImplementationManager.cpp
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonTestingUtility.h
  Gems/LmbrCentral/Code/Tests/Builders/SliceBuilderTests.cpp
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
  Gems/PhysX/Code/Source/Debug/PhysXDebug.cpp
  Gems/ScriptCanvas/Code/Tests/ScriptCanvasBuilderTests.cpp
  Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestFixture.h
  cmake/Projects.cmake
Labels: sig/core

#5420 Test Parallel Add P0 test for Diffuse Probe Grid component
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DiffuseProbeGridAdded.py
Labels: sig/graphics-audio

#5435 Some fixes for clang-12
  scripts/build/Platform/Linux/build_config.json
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt
Labels: sig/build, sig/platform

#5376 Better compiler detection on Linux
  CMakeLists.txt
  Templates/DefaultProject/Template/CMakeLists.txt
  Templates/DefaultProject/Template/cmake/CompilerSettings.cmake
  Templates/DefaultProject/Template/cmake/EngineFinder.cmake
  Templates/DefaultProject/Template/cmake/Platform/Linux/CompilerSettings.cmake
  Templates/DefaultProject/template.json
  Templates/MinimalProject/Template/CMakeLists.txt
  Templates/MinimalProject/Template/cmake/CompilerSettings.cmake
  Templates/MinimalProject/Template/cmake/EngineFinder.cmake
  Templates/MinimalProject/Template/cmake/Platform/Linux/CompilerSettings.cmake
  Templates/MinimalProject/template.json
  cmake/CompilerSettings.cmake
  cmake/Platform/Linux/CompilerSettings.cmake
Labels: platform/linux, sig/build, sig/platform

#5388 ATOM-16749 [Linux] UI Editor viewport flashes after dragging
  Gems/Atom/RHI/Code/Include/Atom/RHI/SwapChain.h
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphAttachmentDatabase.cpp
  Gems/Atom/RHI/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Labels: platform/linux, sig/content, WF2, RTE

#5431 ReflectionProbe exposure controls
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/DefaultObjectSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ibl.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Skin/SkinObjectSrg.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionProbeRenderInner.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionProbeRenderObjectSrg.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionProbeRenderOuter.azsl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ReflectionProbe/ReflectionProbeFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ReflectionProbe/ReflectionProbeFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.h
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.h
Labels: sig/graphics-audio

#5108 Ability to setup aliases for entities spawned from spawnables.
  Code/Framework/AzCore/AzCore/Asset/AssetDataStream.h
  Code/Framework/AzFramework/AzFramework/Spawnable/RootSpawnableInterface.h
  Code/Framework/AzFramework/AzFramework/Spawnable/Spawnable.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/Spawnable.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetBus.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetHandler.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetHandler.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesContainer.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesContainer.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesManager.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesManager.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Code/Framework/AzFramework/Tests/Mocks/MockSpawnableEntitiesInterface.h
  Code/Framework/AzFramework/Tests/Spawnable/SpawnableEntitiesManagerTests.cpp
  Code/Framework/AzFramework/Tests/Spawnable/SpawnableTests.cpp
  Code/Framework/AzFramework/Tests/frameworktests_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabCatchmentProcessor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabConversionPipeline.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabProcessorContext.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabProcessorContext.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/ProcesedObjectStore.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/ProcesedObjectStore.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.h
  Gems/Prefab/PrefabBuilder/PrefabBuilderComponent.cpp
Labels: sig/content, sig/core, sig/ui-ux

#5347 Create download UI once
  Code/Tools/ProjectManager/Source/DownloadController.cpp
  Code/Tools/ProjectManager/Source/DownloadController.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
Labels: sig/content, sig/ui-ux

#5281 Update AWS gem info content
  Gems/AWSClientAuth/gem.json
  Gems/AWSCore/gem.json
  Gems/AWSGameLift/gem.json
  Gems/AWSMetrics/gem.json
Labels: sig/network

#5464 Improved messaging on assert about argument types lacking reflection …
  Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp
Labels: feature/scripting

#5393 Updated 002_wrinkle_regression_test.material to avoid subsurface scattering artifacts
  Gems/Atom/TestData/TestData/Materials/SkinTestCases/002_wrinkle_regression_test.material
Labels: sig/graphics-audio

#5311 Fixed client hierarchy construction to check for authority instead of controller
  Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
Labels: feature/networking, sig/network

#5320 Fix a bug where a rigid body with multiple shapes would ignore all shapes except the first
  Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
Labels: feature/physics, sig/core

#5449 Animation Editor: Remove preview label
  Code/Editor/LyViewPaneNames.h
  Code/Editor/MainWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MorphTargetsWindow/MorphTargetGroupWidget.cpp
Labels: feature/animation, sig/ui-ux

#5421 Fix Editor crashes on asset failures
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/BlendColorGradingLutsPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
  Registry/Platform/Mac/bootstrap_overrides.setreg
Labels: pr-ready-to-merge

#5451 Fix Editor crashes on asset failures
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/BlendColorGradingLutsPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
  Registry/Platform/Mac/bootstrap_overrides.setreg
Labels: pr-ready-to-merge

#5109 Material editor creates material assets from source JSON data instead of relying on AP
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/AssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/LuaMaterialFunctorSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/ShaderCollection.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
Labels: sig/graphics-audio

#4625 Add missing shape failure test, tidying up.
  Gems/Terrain/Code/Tests/LayerSpawnerTests.cpp
Labels: sig/content

#5481 Atom CPU threading optimization
  Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Reflect/DX12/PlatformLimitsDescriptor.h
  Gems/Atom/RHI/Metal/Code/Include/Atom/RHI.Reflect/Metal/PlatformLimitsDescriptor.h
  Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/PlatformLimitsDescriptor.h
Labels: sig/graphics-audio

#5468 [AWSMetrics] Fail to build the project when including AWSMetricsBus header in the project C++ code
  Gems/AWSMetrics/Code/Include/Public/MetricsAttribute.h
  Gems/AWSMetrics/Code/awsmetrics_files.cmake
Labels: sig/network

#5506 Fixed a typo with pass filter
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassFilter.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFilter.cpp
Labels: sig/graphics-audio

#5512 cherry pick material source data loading from stabilization to development
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/AssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/LuaMaterialFunctorSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/ShaderCollection.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
Labels: sig/graphics-audio

#5482 Fixed issue where skin material wouldn't render if applied to a model…
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
Labels: sig/graphics-audio

#5514 Added a null pointer check to EMFX system component
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Labels: feature/animation, sig/graphics-audio

#5111 {lyn3736} adding init files to module paths
  Gems/EditorPythonBindings/Code/Source/PythonLogSymbolsComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonProxyObject.cpp
Labels: sig/content

#5465 Fix track view bug where postfxs do not render correctly.
  Code/Editor/TrackView/AtomOutputFrameCapture.cpp
  Code/Editor/TrackView/AtomOutputFrameCapture.h
  Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcess/PostProcessFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcess/PostProcessFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EyeAdaptationPass.cpp
Labels: sig/graphics-audio

#4628 Terrain/sphrose/surface materials list tests
  Gems/Terrain/Code/Tests/SurfaceMaterialsListTest.cpp
Labels: sig/content

#5467 Fix to Allow Compiling the 4 Types of RPCs
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#5521 ASV Trace::Assert Environment.h(438) You are using an invalid variable,
  Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
Labels: sig/graphics-audio

#5410 Entering the Game Mode when the SlideAlongAxisBasedOnAngle in the Camera Rig is set results in an assert
  Gems/StartingPointCamera/Code/Include/StartingPointCamera/StartingPointCameraConstants.h
  Gems/StartingPointCamera/Code/Include/StartingPointCamera/StartingPointCameraUtilities.h
  Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.cpp
  Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.h
  Gems/StartingPointCamera/Code/Source/StartingPointCamera/StartingPointCameraUtilities.cpp
Labels: sig/content, feature/viewport

#5255 Fixed crash if you save a bundle outside the default bundle folder (#4974)
  Code/Tools/AssetBundler/source/models/AssetBundlerAbstractFileTableModel.cpp
Labels: sig/core

#5456 Test Parallel Add P0 test for Entity Reference component
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_EntityReferenceAdded.py
Labels: sig/graphics-audio

#5447 Fix brute force mesh intersection function
  Code/Framework/AzCore/AzCore/Math/Vector3.h
  Code/Framework/AzCore/AzCore/Math/Vector3.inl
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAsset.cpp
  Gems/Atom/RPI/Code/Tests/Model/ModelTests.cpp
Labels: sig/core, sig/graphics-audio

#5135 Tick tests
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/tick/Tick_CharacterGameplayComponentMotionIsSmooth.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/tick/Tick_InterpolatedRigidBodyMotionIsSmooth.py
  pytest.ini
Labels: sig/core

#5530 SSAO component P0 automation
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SSAOAdded.py
Labels: sig/graphics-audio

#5558 Remove the legacy ViewSystem and some other related legacy code.
  Code/Editor/2DViewport.h
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Editor/Include/HitContext.h
  Code/Editor/Include/IDisplayViewport.h
  Code/Editor/Objects/BaseObject.cpp
  Code/Editor/Objects/BaseObject.h
  Code/Editor/Objects/DisplayContext.h
  Code/Editor/Objects/DisplayContextShared.inl
  Code/Editor/Objects/LineGizmo.cpp
  Code/Editor/Objects/ObjectManager.cpp
  Code/Editor/Settings.cpp
  Code/Editor/Settings.h
  Code/Editor/Viewport.cpp
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/ViewportTitleDlg.h
  Code/Framework/AzCore/Tests/Math/FrustumTests.cpp
  Code/Legacy/CryCommon/Cry_Camera.h
  Code/Legacy/CryCommon/HMDBus.h
  Code/Legacy/CryCommon/IMovieSystem.h
  Code/Legacy/CryCommon/IRenderAuxGeom.h
  Code/Legacy/CryCommon/IRenderer.h
  Code/Legacy/CryCommon/IShader.h
  Code/Legacy/CryCommon/ISystem.h
  Code/Legacy/CryCommon/IViewSystem.h
  Code/Legacy/CryCommon/Mocks/IRemoteConsoleMock.h
  Code/Legacy/CryCommon/Mocks/ISystemMock.h
  Code/Legacy/CryCommon/Mocks/ITextureMock.h
  Code/Legacy/CryCommon/VRCommon.h
  Code/Legacy/CryCommon/crycommon_files.cmake
  Code/Legacy/CryCommon/crycommon_testing_files.cmake
  Code/Legacy/CrySystem/CrySystem_precompiled.h
  Code/Legacy/CrySystem/System.cpp
  Code/Legacy/CrySystem/System.h
  Code/Legacy/CrySystem/SystemInit.cpp
  Code/Legacy/CrySystem/ViewSystem/DebugCamera.cpp
  Code/Legacy/CrySystem/ViewSystem/DebugCamera.h
  Code/Legacy/CrySystem/ViewSystem/View.cpp
  Code/Legacy/CrySystem/ViewSystem/View.h
  Code/Legacy/CrySystem/ViewSystem/ViewSystem.cpp
  Code/Legacy/CrySystem/ViewSystem/ViewSystem.h
  Code/Legacy/CrySystem/crysystem_files.cmake
  Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYAssetExplorer.cpp
  Gems/LyShine/Code/Source/Animation/AzEntityNode.cpp
  Gems/LyShine/Code/Source/Animation/UiAnimationSystem.cpp
  Gems/LyShine/Code/Tests/SpriteTest.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp
  Gems/PhysXDebug/Code/Source/SystemComponent.h
Labels: sig/core, sig/platform, sig/graphics-audio

#5529 Skybox hot reloading - fix black screen when running the editor for the first time with a clean cache
  Gems/Atom/RPI/Assets/Textures/Defaults/DefaultFallback.png
  Gems/Atom/RPI/Assets/Textures/Defaults/Missing.png
  Gems/Atom/RPI/Assets/Textures/Defaults/Processing.png
  Gems/Atom/RPI/Assets/Textures/Defaults/ProcessingFailed.png
  Gems/Atom/RPI/Assets/seedList.seed
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/StreamingImageAssetHandler.h
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAssetHandler.cpp
  Gems/Atom/RPI/Registry/atom_rpi.release.setreg
  Gems/Atom/RPI/Registry/atom_rpi.setreg
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ImageBasedLights/ImageBasedLightComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyBox/HDRiSkyboxComponentController.cpp
Labels: sig/graphics-audio

#5350 Fix for r_skinnedMeshInstanceMemoryPoolSize not being set correctly from a .setreg file
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshOutputStreamManager.cpp
Labels: sig/graphics-audio

#5470 AWS Core CDK: Add option to cleanup resources that are retained by default
  Gems/AWSCore/cdk/README.md
  Gems/AWSCore/cdk/core/core_stack.py
  Gems/AWSCore/cdk/example/example_resources_stack.py
  scripts/build/Platform/Windows/deploy_cdk_applications.cmd
Labels: sig/network

#5513 Adds Update and Uninstall Options for Downloaded Remote Gems to Gem Catalog
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Source/DownloadWorker.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemInfo.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemSortFilterProxyModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemSortFilterProxyModel.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemUninstallDialog.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemUninstallDialog.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemUpdateDialog.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemUpdateDialog.h
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.h
  Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
  Code/Tools/ProjectManager/project_manager_files.cmake
  scripts/o3de/o3de/repo.py
  scripts/o3de/o3de/utils.py
Labels: sig/content, sig/ui-ux

#5561 Fixed the other call to CreateVariable
  Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
Labels: sig/graphics-audio

#5357 Fixed editor log path and improved editor log not found error string
  AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
  Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
  Tools/LyTestTools/ly_test_tools/_internal/managers/platforms/linux.py
  Tools/LyTestTools/ly_test_tools/_internal/managers/platforms/mac.py
  Tools/LyTestTools/ly_test_tools/_internal/managers/platforms/windows.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_manager_platforms_mac.py
  Tools/LyTestTools/tests/unit/test_manager_platforms_windows.py
Labels: sig/testing

#5563 Look Modification P0 Automation
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
Labels: sig/graphics-audio

#5568 Script Canvas added text generation for BehaviorContext properties
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
  Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
  Gems/ScriptCanvas/Code/Tools/TranslationGeneration.h
Labels: feature/scripting

#5564 Update asset files, & update golden image files to match new smaller asset file.
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_1.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_2.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_3.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_4.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_5.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AtomBasicLevelSetup.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_1.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_2.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_3.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_4.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_5.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_6.ppm
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GlobalSkylightIBLAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_BasicLevelSetup.py
Labels: sig/graphics-audio

#5569 [Resource Mapping Tool] make top-level Account id optional in ResourceMapping tool schema
  Gems/AWSCore/Code/Tools/ResourceMappingTool/controller/view_edit_controller.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/controller/test_view_edit_controller.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_json_utils.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/json_utils.py
Labels: sig/network

#5557 LYN-4946 | Merge Game Mode buttons in the Play Controls toolbar
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/MainWindow.cpp
  Code/Editor/Resource.h
  Code/Editor/ToolbarManager.cpp
  Code/Editor/ToolbarManager.h
Labels: sig/content, sig/ui-ux

#5536 Create desktop shortcut functionality
  Code/Tools/ProjectManager/Platform/Linux/ProjectManager_Traits_Linux.h
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/ProjectManager/Platform/Mac/ProjectManager_Traits_Mac.h
  Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectManager_Traits_Windows.h
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
Labels: sig/content, sig/ui-ux

#5578 RPCs Without Parameters Compile
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#5584 Removing references and builders for legacy MTL assets
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/Include/IEditorMaterialManager.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
  Gems/LmbrCentral/Code/Source/Builders/MaterialBuilder/MaterialBuilderComponent.cpp
  Gems/LmbrCentral/Code/Source/Builders/MaterialBuilder/MaterialBuilderComponent.h
  Gems/LmbrCentral/Code/Source/LmbrCentral.cpp
  Gems/LmbrCentral/Code/Source/LmbrCentralEditor.cpp
  Gems/LmbrCentral/Code/Source/Unhandled/Material/MaterialAssetTypeInfo.cpp
  Gems/LmbrCentral/Code/Source/Unhandled/Material/MaterialAssetTypeInfo.h
  Gems/LmbrCentral/Code/Tests/Builders/MaterialBuilderTests.cpp
  Gems/LmbrCentral/Code/lmbrcentral_editor_files.cmake
  Gems/LmbrCentral/Code/lmbrcentral_editor_tests_files.cmake
  Gems/LmbrCentral/Code/lmbrcentral_files.cmake
  Gems/Vegetation/Code/Source/InstanceSystemComponent.cpp
Labels: sig/graphics-audio

#5373 The Build Time Stamp of ShaderAsset And
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.h
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdatecolumn.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdatecolumn_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdatecolumn_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdatecolumn_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdaterow.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdaterow_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdaterow_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridborderupdaterow_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridclassification.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridclassification_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridclassification_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridclassification_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrelocation.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrelocation_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrelocation_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrelocation_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_vulkan_0.azshadervariant
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderVariantAssetCreator.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderVariantAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderVariantAssetCreator.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderVariantAsset.cpp
Labels: sig/graphics-audio

#5585 Cherry pick material editor saves relative paths to external references and test support to stabilization
  Gems/Atom/RPI/Code/CMakeLists.txt
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Tests/Common/RPITestFixture.h
  Gems/Atom/RPI/Code/atom_rpi_tests_files.cmake
  Gems/Atom/Tools/AtomToolsFramework/Code/CMakeLists.txt
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/MaterialPropertyUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_tests_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Utils/Code/CMakeLists.txt
  Gems/Atom/Utils/Code/Include/Atom/Utils/TestUtils/AssetSystemStub.h
  Gems/Atom/Utils/Code/Source/TestUtils/AssetSystemStub.cpp
  Gems/Atom/Utils/Code/atom_utils_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
Labels: sig/graphics-audio

#5593 Fully Replaces Remote Gems in Model and Selects Them When Downloading and Deleting
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.cpp
Labels: sig/content

#5075 feat: add whitebox module support for linux(#4654)
  Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
  Gems/WhiteBox/Code/Source/Core/WhiteBoxToolApi.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
  Gems/WhiteBox/Code/Source/Platform/Linux/PAL_linux.cmake
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxBuffer.h
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxEdgeRestoreMode.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeTranslationModifier.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonTranslationModifier.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxVertexTranslationModifier.cpp
  Gems/WhiteBox/Code/Tests/WhiteBoxTest.cpp
  Gems/WhiteBox/Code/Tests/WhiteBoxTestRailsAutomation.cpp
Labels: platform/linux, sig/content, sig/platform, feature/viewport

#5546 CameraRigComponent - Disable Component Checkbox when the two others are toggled
  Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.cpp
  Gems/StartingPointCamera/Code/Source/CameraLookAtBehaviors/SlideAlongAxisBasedOnAngle.h
Labels: sig/content, feature/viewport

#5586 Fixed IMGUI Entity Outliner to show net entities
  Code/Framework/AzFramework/AzFramework/Components/TransformComponent.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
Labels: feature/networking, sig/network

#4929 HttpRequestorGem: Add basic autogen documentation to headers
  Gems/HttpRequestor/Code/Include/HttpRequestor/HttpRequestParameters.h
  Gems/HttpRequestor/Code/Include/HttpRequestor/HttpRequestorBus.h
  Gems/HttpRequestor/Code/Include/HttpRequestor/HttpTextRequestParameters.h
  Gems/HttpRequestor/Code/Include/HttpRequestor/HttpTypes.h
Labels: sig/docs-community, sig/network

#5548 Asset bundler test fixes
  AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/bundler_batch_setup_fixture.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_bundler_batch_tests.py
Labels: sig/content, sig/core

#5509 Fix for cascade shadow map clipping out too close to the camera
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
Labels: sig/graphics-audio

#5607 Fix for CSM shimmering
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
Labels: sig/graphics-audio

#5606 Fixing double registration of hair asset
  Gems/AtomTressFX/Code/Builders/HairBuilderComponent.cpp
Labels: sig/graphics-audio

#5531 Enable python-based tests in Linux AR
  AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_SerializeContextTools_Works.py
  AutomatedTesting/Gem/PythonTests/smoke/test_Editor_NewExistingLevels_Works.py
  Tools/LyTestTools/ly_test_tools/environment/process_utils.py
  Tools/LyTestTools/tests/unit/test_editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_process_utils.py
  cmake/Platform/Linux/PAL_linux.cmake
  scripts/build/Platform/Linux/build_config.json
Labels: sig/build, sig/testing

#5614 Revert Asset Picker View to previous one
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp
Labels: sig/content, sig/ui-ux

#5612 EMotion FX: Deleting a corresponding anim graph when a Reference node is open crashes the Editor
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphReferenceNode.cpp
Labels: feature/animation, sig/content

#5621 Added user option to define the size of the Script Canvas node palette context menu
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/EditorContextMenu.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/EditorContextMenu.h
  Gems/ScriptCanvas/Code/Editor/Settings.cpp
  Gems/ScriptCanvas/Code/Editor/Settings.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptCanvasContextMenus.cpp
Labels: feature/scripting

#5591 {lyn7352} adding more logging to mock asset builder test
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/AssetBuilder_test_case.py
Labels: sig/core

#5618 AWS Core CDK: Add option to cleanup resources that are retained by default (#5470)
  Gems/AWSCore/cdk/README.md
  Gems/AWSCore/cdk/core/core_stack.py
  Gems/AWSCore/cdk/example/example_resources_stack.py
  scripts/build/Platform/Windows/deploy_cdk_applications.cmd
Labels: sig/network

#4917 Atom/mriegger/normaloffsetbiasarealight
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DiskLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PointLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/PointLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/PointLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/AreaLightBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/AreaLightComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DiskLightDelegate.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DiskLightDelegate.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/LightDelegateBase.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/LightDelegateInterface.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/SphereLightDelegate.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/SphereLightDelegate.h
Labels: sig/graphics-audio

#5507 Add cvar for aws log level
  Code/Legacy/CrySystem/SystemInit.cpp
  Code/Tools/AWSNativeSDKInit/CMakeLists.txt
  Code/Tools/AWSNativeSDKInit/aws_native_sdk_init_tests_files.cmake
  Code/Tools/AWSNativeSDKInit/source/AWSLogSystemInterface.cpp
  Code/Tools/AWSNativeSDKInit/source/AWSNativeSDKInit.cpp
  Code/Tools/AWSNativeSDKInit/tests/AWSLogSystemInterfaceTest.cpp
  Code/Tools/AWSNativeSDKInit/tests/AWSNativeSDKInitTest.cpp
  Gems/AWSClientAuth/Code/Tests/Authorization/AWSCognitoAuthorizationControllerTest.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/CMakeLists.txt
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientManager.cpp
Labels: sig/core, sig/network

#5592 Create file in project directory on successful build for Project Manager
  Code/Tools/ProjectManager/Source/ProjectBuilderController.cpp
  Code/Tools/ProjectManager/Source/ProjectManagerSettings.cpp
  Code/Tools/ProjectManager/Source/ProjectManagerSettings.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
  Code/Tools/ProjectManager/project_manager_files.cmake
Labels: sig/content

#5554 Move gamelift client usage into each activity scope
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientManager.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/AWSGameLiftClientManager.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftAcceptMatchActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftAcceptMatchActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionOnQueueActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftCreateSessionOnQueueActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftLeaveSessionActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftSearchSessionsActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftSearchSessionsActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStartMatchmakingActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStartMatchmakingActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStopMatchmakingActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftStopMatchmakingActivity.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftCreateSessionActivityTest.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftCreateSessionOnQueueActivityTest.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftJoinSessionActivityTest.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftSearchSessionsActivityTest.cpp
Labels: sig/network

#5627 Fix for python load errors on Linux
  Code/Framework/AzToolsFramework/AzToolsFramework/API/PythonLoader.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Platform/Common/Default/AzToolsFramework/API/PythonLoader_Default.cpp
  Code/Framework/AzToolsFramework/Platform/Linux/AzToolsFramework/API/PythonLoader_Linux.cpp
  Code/Framework/AzToolsFramework/Platform/Linux/platform_linux_files.cmake
  Code/Framework/AzToolsFramework/Platform/Mac/platform_mac_files.cmake
  Code/Framework/AzToolsFramework/Platform/Windows/platform_windows_files.cmake
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkModule.h
  Gems/EditorPythonBindings/Code/Source/EditorPythonBindingsModule.cpp
  Gems/PythonAssetBuilder/Code/Source/PythonAssetBuilderModule.cpp
  Templates/PythonToolGem/Template/Code/Source/${Name}EditorModule.cpp
Labels: feature/python-bindings, kind/bug, sig/core

#5525 AWSClientAuth updated to use custom CognitoCachingCredentialsProvider
  AutomatedTesting/Gem/PythonTests/AWS/Windows/client_auth/aws_client_auth_automation_test.py
  Gems/AWSClientAuth/Code/Include/Private/Authorization/AWSClientAuthCognitoCachingAuthenticatedCredentialsProvider.h
  Gems/AWSClientAuth/Code/Include/Private/Authorization/AWSCognitoAuthorizationController.h
  Gems/AWSClientAuth/Code/Source/Authorization/AWSClientAuthCognitoCachingAuthenticatedCredentialsProvider.cpp
  Gems/AWSClientAuth/Code/Source/Authorization/AWSCognitoAuthorizationController.cpp
  Gems/AWSClientAuth/Code/Tests/Authorization/AWSCognitoAuthorizationControllerTest.cpp
  Gems/AWSClientAuth/Code/awsclientauth_files.cmake
Labels: sig/network

#5379 Adding P0 HDRi Skybox test
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRiSkyboxAdded.py
Labels: sig/graphics-audio

#5672 Fix for shadowmaps not behaving properly with two viewports in the Editor
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
Labels: sig/graphics-audio

#5638 Fix: Display Repo Gems on Repo Screen Correctly
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoInfo.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoInspector.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.h
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.h
  Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
Labels: sig/content, sig/ui-ux

#5661 ShaderMetricsSystem spawns a lot of warnings
  Gems/Atom/RPI/Code/Tests/Common/RPITestFixture.cpp
Labels: sig/graphics-audio

#5610 render solid skeleton option
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
Labels: feature/animation

#5460 Terrain detail textures support with bindless arrays
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/ViewSrgAll.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/MultiIndexedDataVector.h
  Gems/Atom/Feature/Common/Code/Tests/IndexedDataVectorTests.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h
  Gems/Terrain/Assets/Materials/Terrain/PbrTerrain.materialtype
  Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Assets/Shaders/Terrain/ViewSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Labels: sig/content, sig/graphics-audio

#5684 Cherrypick GPU test changes (that also fix issues) to stabilization
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_1.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_2.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_3.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_4.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_5.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AtomBasicLevelSetup.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_1.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_2.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_3.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_4.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_5.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_6.ppm
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GlobalSkylightIBLAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_BasicLevelSetup.py
Labels: sig/graphics-audio

#5692 Reduce material editor update interval when inactive
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: sig/graphics-audio

#5689 Follow up fix for ATOM-13512
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Reflectance.preset
Labels: sig/graphics-audio

#5673 Adds Configure Gems Options to Project Dropdown + Misc. Project Manager Fixes
  Code/Tools/ProjectManager/Source/EngineScreenCtrl.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.h
  Code/Tools/ProjectManager/Source/ProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.h
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.h
  Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
  Code/Tools/ProjectManager/Source/ScreenWidget.h
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.h
  Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp
Labels: sig/content, sig/ui-ux

#5691 Replacing material editor lighting preset selection dialog exr previews with lighting preset thumbnails
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/ModelPreset.h
  Gems/Atom/Feature/Common/Code/Source/Utils/EditorModelPreset.cpp
  Gems/Atom/Feature/Common/Code/Source/Utils/ModelPreset.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/CMakeLists.txt
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/MaterialEditor/Code/CMakeLists.txt
  Gems/Atom/Tools/MaterialEditor/Code/Include/Atom/Viewport/MaterialViewportRequestBus.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/LightingPresetBrowserDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/ModelPresetBrowserDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/PresetBrowserDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/PresetBrowserDialog.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.h
Labels: sig/graphics-audio

#5637 Display Gem Cart in Gem Catalog Right Panel
  Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.h
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
Labels: sig/content, sig/ui-ux

#5613 Update RPISystem::GetCurrentTime() to use TimeSystem
  Code/Framework/AzCore/AzCore/Time/ITime.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
Labels: sig/graphics-audio

#5685 Render joint names
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ViewportContextBus.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ViewportContextManager.h
  Gems/Atom/RPI/Code/Source/RPI.Public/ViewportContextManager.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderActorSettings.h
Labels: feature/animation

#5737 Fixed capsule auxgeom draw for lights and other aux geom issues
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomBase.h
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.h
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AuxGeom/AuxGeomDraw.h
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
Labels: sig/graphics-audio

#5750 Renamed RequestTaggedEntities to Get Entity By Tag as it only returns the first entity
  Gems/LmbrCentral/Code/Source/Scripting/TagComponent.cpp
Labels: feature/scripting, sig/content

#5349 [LYN-7520] Wildcard Source Dependencies include files in cache/excluded files
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.cpp
  Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.h
  Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCacheInterface.h
  Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp
  Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
Labels: sig/core
