Repository o3de/o3de, pull requests merged in 2021-07, with the labels that each got.

#1910 Update Wwise version info in Readme.md
  README.md
Labels: feature/audio, kind/documentation

#1925 Update readme LFS instructions
  README.md
Labels: pr-ready-to-merge

#1876 Clang compile fixes
  Code/Framework/AzCore/Tests/Platform/Windows/Tests/IO/Streamer/StorageDriveTests_Windows.cpp
  Gems/Atom/RPI/Code/CMakeLists.txt
  Gems/Atom/RPI/Code/Source/Platform/Common/Clang/atom_rpi_public_clang.cmake
  Gems/Atom/RPI/Code/Source/Platform/Common/MSVC/atom_rpi_public_msvc.cmake
  Gems/Atom/RPI/Code/Source/Platform/Windows/PAL_windows.cmake
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MotionMetaDataRule.h
Labels: pr-ready-to-merge

#1926 ATOM-14322 Random crashes when exist RHI/Raytracing sample running __…
  Gems/Atom/RHI/Code/Source/RHI/RayTracingPipelineState.cpp
Labels: pr-ready-to-merge

#1934 Convert Incremental scripts to Python3
  scripts/build/Jenkins/Jenkinsfile
  scripts/build/bootstrap/incremental_build_util.py
Labels: review-required

#1920 Fixed Material Editor not launching
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
Labels: review-required

#1930 Fix Mac Editor crash when adding PhysX Collider component to an entity.
  Code/Framework/AzFramework/AzFramework/Physics/Material.cpp
  Code/Framework/AzFramework/AzFramework/Physics/Material.h
Labels: pr-ready-to-merge

#1940 Fix EBS unmounting error.
  scripts/build/bootstrap/incremental_build_util.py
Labels: o3de-dco: no, review-required

#1877 Create 3rd-party directory if not exists
  cmake/3rdParty.cmake
Labels: pr-ready-to-merge

#1938 Adding header to resolve undefined type error
  Code/LauncherUnified/Platform/iOS/Launcher_iOS.mm
Labels: review-required

#1943 Removing some unused files from Code/Editor/Plugins
  Code/Editor/Plugins/EditorCommon/EditorCommon.def
  Code/Editor/Plugins/EditorCommon/res/EditorCommon.rc2
  Code/Editor/Plugins/QtMocRule.props
  Code/Editor/Plugins/QtMocRule.targets
  Code/Editor/Plugins/QtMocRule.xml
  Code/Editor/Plugins/QtRccRule.props
  Code/Editor/Plugins/QtRccRule.targets
  Code/Editor/Plugins/QtRccRule.xml
  Code/Editor/Plugins/QtUicRule.props
  Code/Editor/Plugins/QtUicRule.targets
  Code/Editor/Plugins/QtUicRule.xml
Labels: review-required

#1931 [development] Mobile settings tool validator and save fixes
  Code/Editor/Plugins/ProjectSettingsTool/ProjectSettingsToolWindow.cpp
  Code/Editor/Plugins/ProjectSettingsTool/Validators.cpp
Labels: pr-ready-to-merge

#1954 Allow running scripts using msys2/mingw/git bash
  python/python.sh
Labels: review-required

#2027 Disable GPU test that shouldn't be in main
  AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
Labels: pr-ready-to-merge

#2058 Issues/2045 3rdParty runtime dependencies copied multiple times
  cmake/3rdPartyPackages.cmake
  cmake/Platform/Common/runtime_dependencies_common.cmake.in
  cmake/Platform/Mac/runtime_dependencies_mac.cmake.in
Labels: review-required

#2041 Increase test timeout for AutomatedTesting::AtomRenderer_HydraTests_GPUTests to diagnose AR node issue (might require RDP to fix).
  AutomatedTesting/Gem/PythonTests/atom_renderer/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/atom_renderer/test_Atom_GPUTests.py
Labels: pr-ready-to-merge

#2097 Remove git lfs steps
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/build

#1952 Git Issue 1948: LoadLevel Console Command Requires Full Asset Path Instead of Level Name
  Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp
Labels: pr-ready-to-merge

#2042 Added a Warning When VS2019 is not Installed with Link to Download it
  Code/Tools/ProjectManager/Platform/Linux/PAL_linux_files.cmake
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/ProjectManager/Platform/Mac/PAL_mac_files.cmake
  Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
  Code/Tools/ProjectManager/Platform/Windows/PAL_windows_files.cmake
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
  Code/Tools/ProjectManager/Source/CreateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: pr-ready-to-merge

#2117 Fix Atom GPU test by enabling autotest_mode
  AutomatedTesting/Gem/PythonTests/atom_renderer/test_Atom_GPUTests.py
Labels: pr-ready-to-merge

#2105 Fix positional desync of network objects plus related log spam
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocketManager_Select.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/PropertyPublisher.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/ReplicationRecord.cpp
Labels: sig/network

#2144 Generate install layout for Mac
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Mac/Configurations_mac.cmake
  cmake/Platform/Mac/Install_mac.cmake
Labels: pr-ready-to-merge

#2184 Clear Build and Cache Directory After Project Move or Copy
  Code/Tools/ProjectManager/Platform/Linux/PAL_linux_files.cmake
  Code/Tools/ProjectManager/Platform/Linux/ProjectManagerDefs_linux.cpp
  Code/Tools/ProjectManager/Platform/Mac/PAL_mac_files.cmake
  Code/Tools/ProjectManager/Platform/Mac/ProjectManagerDefs_mac.cpp
  Code/Tools/ProjectManager/Platform/Windows/PAL_windows_files.cmake
  Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectManagerDefs_windows.cpp
  Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
  Code/Tools/ProjectManager/Source/ProjectBuilderWorker.h
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.h
  Code/Tools/ProjectManager/Source/ProjectManagerDefs.h
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.h
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
  Code/Tools/ProjectManager/tests/UtilsTests.cpp
Labels: pr-ready-to-merge

#2195 Change the way the Mute Audio button works depending on the Gem availability
  Code/Editor/ViewportTitleDlg.cpp
Labels: feature/audio

#2182 Update audio cvars from legacy to AZ_CVARs
  Code/Legacy/CrySystem/System.cpp
  Code/Legacy/CrySystem/System.h
  Code/Legacy/CrySystem/SystemInit.cpp
  Gems/AudioSystem/Code/Include/Engine/AudioLogger.h
  Gems/AudioSystem/Code/Source/AudioSystemGemSystemComponent.cpp
  Gems/AudioSystem/Code/Source/Engine/ATL.cpp
  Gems/AudioSystem/Code/Source/Engine/ATLAudioObject.cpp
  Gems/AudioSystem/Code/Source/Engine/ATLComponents.cpp
  Gems/AudioSystem/Code/Source/Engine/AudioInternalInterfaces.h
  Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp
  Gems/AudioSystem/Code/Source/Engine/FileCacheManager.cpp
  Gems/AudioSystem/Code/Source/Engine/FileCacheManager.h
  Gems/AudioSystem/Code/Source/Engine/SoundCVars.cpp
  Gems/AudioSystem/Code/Source/Engine/SoundCVars.h
Labels: feature/audio, pr-ready-to-merge, sig/presentation

#1370 Use SampleLevel instead of Sample to sample shadow maps.
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli
Labels: pr-ready-to-merge, review-required

#2134 Remove Redundant Scope from Mutliplayer Autocomponent Functions
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#2153 Autonomous to Authority Net Properties
  Gems/Multiplayer/Code/Include/Multiplayer/ReplicationWindows/IReplicationWindow.h
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicator.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/PropertyPublisher.cpp
  Gems/Multiplayer/Code/Source/ReplicationWindows/NullReplicationWindow.cpp
  Gems/Multiplayer/Code/Source/ReplicationWindows/NullReplicationWindow.h
  Gems/Multiplayer/Code/Source/ReplicationWindows/ServerToClientReplicationWindow.cpp
  Gems/Multiplayer/Code/Source/ReplicationWindows/ServerToClientReplicationWindow.h
Labels: sig/network

#2284 Reduce inclusion overhead a little bit
  Code/Framework/AzCore/AzCore/EBus/Event.h
  Code/Framework/AzCore/AzCore/Math/Frustum.h
  Code/Framework/AzCore/AzCore/Math/Transform.cpp
  Code/Framework/AzCore/AzCore/Math/Transform.h
  Code/Framework/AzCore/AzCore/Math/Vector3.h
  Code/Framework/AzFramework/AzFramework/Physics/Common/PhysicsSceneQueries.h
  Code/Framework/AzFramework/AzFramework/UnitTest/TestDebugDisplayRequests.h
  Code/Framework/AzFramework/AzFramework/Visibility/OctreeSystemComponent.cpp
  Code/Framework/AzFramework/Platform/Common/Default/AzFramework/Input/User/LocalUserId_Default.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorSpace.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestComponent.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/CoordinateSystemConverter.h
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/GradientWeightModifier/GradientWeightModifierController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/RadiusWeightModifier/RadiusWeightModifierComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ShapeWeightModifier/ShapeWeightModifierComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Scripting/EntityReferenceComponentController.cpp
  Gems/AudioSystem/Code/Platform/Common/Default/AudioSystemGemSystemComponent_default.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Mesh.h
  Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYAssetExplorer.h
  Gems/LmbrCentral/Code/Source/Asset/AssetSystemDebugComponent.cpp
  Gems/LyShine/Code/Source/UiFlipbookAnimationComponent.cpp
  Gems/LyShine/Code/Source/UiFlipbookAnimationComponent.h
  Gems/PhysX/Code/Source/System/PhysXJointInterface.cpp
Labels: review-required

#2242 [GHI #2165] GPU Buffer/Image memory visualizer
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/BufferDescriptor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ImageEnums.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystem.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystemInterface.h
  Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Vulkan.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.inl
Labels: review-required

#2299 MikkT tangent generation support
  Code/Tools/SceneAPI/SceneCore/DataTypes/GraphData/IMeshVertexTangentData.h
  Code/Tools/SceneAPI/SceneData/GraphData/MeshVertexBitangentData.cpp
  Code/Tools/SceneAPI/SceneData/GraphData/MeshVertexTangentData.cpp
  Code/Tools/SceneAPI/SceneData/ManifestMetaInfoHandler.cpp
  Code/Tools/SceneAPI/SceneData/Rules/TangentsRule.cpp
  Code/Tools/SceneAPI/SceneData/Rules/TangentsRule.h
  Code/Tools/SceneAPI/SceneData/Tests/GraphData/GraphDataBehaviorTests.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.cpp
  Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerateComponent.h
  Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerators/MikkTGenerator.cpp
  Gems/SceneProcessing/Code/Source/Generation/Components/TangentGenerator/TangentGenerators/MikkTGenerator.h
Labels: feature/animation, feature/atom, sig/presentation

#2306 Added .vs/ (Visual Studio cache when using CMake builds instead of so…
  .gitignore
Labels: review-required

#2334 Ninja compile and link pool CMake settings
  cmake/Platform/Common/Configurations_common.cmake
  cmake/Platform/Linux/Configurations_linux.cmake
Labels: pr-ready-to-merge

#2356 Fixed Project Manager to enable save/restore of the window geometry.
  Code/Framework/AzQtComponents/AzQtComponents/Components/WindowDecorationWrapper.cpp
  Code/Tools/ProjectManager/Source/Application.cpp
Labels: feature/editor

#2359 Improved auto-resizing when centering dialogs when they are first displayed.
  Code/Framework/AzQtComponents/AzQtComponents/Components/WindowDecorationWrapper.cpp
Labels: feature/editor

#2354 Fixing missing definition of GpuCrashTracker for Aftermath.
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.h
Labels: pr-ready-to-merge

#2366 Removed slice based context menu options from the RPE when prefabs are enabled.
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
Labels: feature/editor

#2358 Removing dependencies on legacy code
  Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
  Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp
  Gems/AudioSystem/Code/Source/Engine/FileCacheManager.cpp
Labels: feature/audio, kind/cleanup

#2382 Replaces usage of legacy XML apis with RapidXml
  Code/Editor/Util/UndoUtil.h
  Gems/AudioEngineWwise/Code/Source/Editor/AudioSystemEditor_wwise.cpp
  Gems/AudioEngineWwise/Code/Source/Editor/AudioSystemEditor_wwise.h
  Gems/AudioEngineWwise/Code/Source/Editor/AudioWwiseLoader.cpp
  Gems/AudioSystem/Code/Include/Editor/ACETypes.h
  Gems/AudioSystem/Code/Include/Editor/IAudioSystemEditor.h
  Gems/AudioSystem/Code/Include/Engine/ATLCommon.h
  Gems/AudioSystem/Code/Include/Engine/AudioFileUtils.h
  Gems/AudioSystem/Code/Source/Editor/ATLControlsPanel.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControl.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControl.h
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorPlugin.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsLoader.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsLoader.h
  Gems/AudioSystem/Code/Source/Editor/AudioControlsWriter.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsWriter.h
  Gems/AudioSystem/Code/Source/Editor/AudioResourceSelectors.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioSystemPanel.cpp
  Gems/AudioSystem/Code/Source/Editor/ImplementationManager.cpp
  Gems/AudioSystem/Code/Source/Editor/ImplementationManager.h
  Gems/AudioSystem/Code/Source/Editor/InspectorPanel.cpp
  Gems/AudioSystem/Code/Source/Editor/QAudioControlEditorIcons.h
  Gems/AudioSystem/Code/Source/Editor/QConnectionsWidget.cpp
  Gems/AudioSystem/Code/Source/Engine/ATLComponents.cpp
  Gems/AudioSystem/Code/Tests/AudioSystemEditorTest.cpp
Labels: feature/audio, kind/cleanup, kind/deprecation, pr-ready-to-merge

#2225 Adding rapidjson.natvis file to the AzCore project to Visualizers to VS
  Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/rapidjson.natvis
  Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake
Labels: priority/minor

#2484 Don't require a specific version of Wwise SDK, allow for later versions to be used
  Gems/AudioEngineWwise/gem.json
  README.md
  cmake/3rdParty/FindWwise.cmake
Labels: feature/audio, kind/documentation, pr-ready-to-merge

#2407 Fixing typos in comments in AffineParts.h file
  Code/Editor/Util/AffineParts.h
Labels: kind/cleanup, o3de-dco: yes

#2601 Minor corrections in code gen for usability
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Common.jinja
Labels: sig/network

#2621 Fixes resource selectors not showing
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorPlugin.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioResourceSelectors.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioResourceSelectors.h
  Gems/AudioSystem/Code/audiosystem_editor_files.cmake
Labels: feature/audio, kind/bug, pr-ready-to-merge
