Repository o3de/o3de, pull requests merged in 2021-09, with the labels that each got.

#3764 Misc fixes for Linux SDK
  Code/Framework/AzFramework/AzFramework/IO/LocalFileIO.cpp
  cmake/Platform/Linux/Install_linux.cmake
Labels: platform/linux, kind/bug, pr-ready-to-merge, kind/task, feature/sdk

#3786 [Mac] Fix crash in Editor and AssetProcessor.
  Code/Editor/Platform/Mac/main_dummy.cpp
  Code/Tools/AssetProcessor/Platform/Mac/main_dummy.cpp
Labels: pr-ready-to-merge

#3853 Fix the DefaultGem template's Editor target
  Gems/LyShine/Code/CMakeLists.txt
  Gems/Terrain/Code/CMakeLists.txt
  Templates/DefaultGem/Template/Code/CMakeLists.txt
Labels: kind/bug, pr-ready-to-merge, feature/sdk

#3157 Multiplayer Auto-Components Using NetworkInput Now Require MultiplayerInputDriver Service
  Gems/Multiplayer/Code/Include/Multiplayer/Components/LocalPredictionPlayerInputComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
Labels: sig/network

#3905 Set target_file variable since it's still being used in Mac runtime dependencies cmake file
  cmake/Platform/Common/RuntimeDependencies_common.cmake
Labels: pr-ready-to-merge

#3911 update revision of lz4 package used by o3de
  Gems/MultiplayerCompression/Code/Source/LZ4Compressor.cpp
  cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
  cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Labels: pr-ready-to-merge

#3989 Fix compile errors in the Wwise Gem
  Gems/AudioEngineWwise/Code/Source/Engine/Config_wwise.cpp
  Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
Labels: feature/audio, kind/bug

#3111 Build time reduction: AzStdOnDemandReflection
  Code/Framework/AzCore/AzCore/Asset/AssetSerializer.h
  Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
  Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflectionSpecializations.cpp
  Code/Framework/AzCore/AzCore/Settings/SettingsRegistryScriptUtils.cpp
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/Settings/SettingsRegistryScriptUtilsTests.cpp
  Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.cpp
  Code/Tools/SceneAPI/SceneCore/Events/ExportProductList.cpp
  Gems/AWSClientAuth/Code/Include/Public/Authorization/ClientAuthAWSCredentials.h
  Gems/AWSClientAuth/Code/Source/Authorization/ClientAuthAWSCredentials.cpp
  Gems/AWSClientAuth/Code/awsclientauth_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/RadiusWeightModifier/RadiusWeightModifierComponentController.cpp
  Gems/Blast/Code/Source/Asset/BlastChunksAsset.cpp
  Gems/EditorPythonBindings/Code/Source/PythonReflectionComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
  Gems/LmbrCentral/Code/Source/Shape/ShapeComponent.cpp
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
  Gems/WhiteBox/Code/Source/WhiteBoxToolApiReflection.cpp
Labels: review-required

#4035 Color Grading Workflow: minor bug fixes based on finding defects while using
  Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/exr_to_3dl_azasset.py
  Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/from_3dl_to_azasset.py
  Gems/Atom/Feature/Common/Tools/ColorGrading/Resources/TestData/Nuke/HDR/Test_Grade/test-grade_inv-Log2-48nits_32_LUT.azasset
  Gems/Atom/Feature/Common/Tools/ColorGrading/cmdline/CMD_ColorGradingTools.bat
  Gems/Atom/Feature/Common/Tools/ColorGrading/cmdline/Env_Core.bat
  Gems/Atom/Feature/Common/Tools/ColorGrading/cmdline/User_Env.bat.template
Labels: sig/graphics-audio

#4027 fix infinite loop due to thin triangles
  Gems/LmbrCentral/Code/Source/Shape/ShapeGeometryUtil.cpp
  Gems/LmbrCentral/Code/Tests/ShapeGeometryUtilTest.cpp
Labels: kind/bug, sig/content, triage/accepted

#3990 Network Input Exposed to Script
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerController.h
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Common.jinja
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Labels: sig/network

#4125 new postfx layer categories and ordering values
  Gems/AtomLyIntegration/CommonFeatures/Assets/PostProcess/default.postfxlayercategories
Labels: sig/graphics-audio

#4151 Atom/gallowj/clean up atom content
  Gems/AtomContent/.gitignore
  Gems/AtomContent/ReferenceMaterials/Launch_WingIDE-7-1.bat
  Gems/AtomContent/ReferenceMaterials/LyProjectRootStub
  Gems/AtomContent/ReferenceMaterials/Project_Env.bat
  Gems/AtomContent/ReferenceMaterials/Tools/Launch_Cmd.bat
  Gems/AtomContent/ReferenceMaterials/Tools/Launch_Maya.bat
  Gems/AtomContent/ReferenceMaterials/Tools/Project_Env.bat
  Gems/AtomContent/ReferenceMaterials/Tools/User_Env.bat.template
  Gems/AtomContent/ReferenceMaterials/gem.json
  Gems/AtomContent/Sponza/Project_Env.bat
  Gems/AtomContent/Sponza/Tools/Launch_Cmd.bat
  Gems/AtomContent/Sponza/Tools/Launch_Maya.bat
  Gems/AtomContent/Sponza/Tools/Maya/Scripts/stub
  Gems/AtomContent/Sponza/Tools/Project_Env.bat
  Gems/AtomContent/Sponza/Tools/User_Env.bat.template
  Gems/AtomContent/Sponza/User_env.bat.template
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Launchers/Windows/Env_Maya.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/config_utils.py
Labels: sig/graphics-audio, feature/tech-art

#4184 LYN6729: Fix AzAutoGen to Output to Proper Path
  cmake/AzAutoGen.py
Labels: sig/build

#4172 Add Initial Gem Repository Management Screen
  Code/Tools/ProjectManager/Resources/Delete.svg
  Code/Tools/ProjectManager/Resources/Edit.svg
  Code/Tools/ProjectManager/Resources/ProjectManager.qrc
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Resources/Refresh.svg
  Code/Tools/ProjectManager/Source/EngineScreenCtrl.cpp
  Code/Tools/ProjectManager/Source/EngineScreenCtrl.h
  Code/Tools/ProjectManager/Source/EngineSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/EngineSettingsScreen.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoInfo.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoInfo.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoItemDelegate.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoItemDelegate.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoListView.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoListView.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoModel.h
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.cpp
  Code/Tools/ProjectManager/Source/GemRepo/GemRepoScreen.h
  Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.h
  Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
  Code/Tools/ProjectManager/Source/ScreenDefs.h
  Code/Tools/ProjectManager/Source/ScreenFactory.cpp
  Code/Tools/ProjectManager/project_manager_files.cmake
Labels: pr-ready-to-merge

#4120 Move Multiplayer Sample Components into Multiplayer Gem
  Gems/Multiplayer/Code/CMakeLists.txt
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHitVolumesComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkRigidBodyComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponentTypes_Source.jinja
  Gems/Multiplayer/Code/Source/AutoGen/NetworkCharacterComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/AutoGen/NetworkHitVolumesComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/AutoGen/NetworkRigidBodyComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkHitVolumesComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/network

#4206 Re-structure Atom test folders in AutomatedTesting.
  AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Atom/__init__.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/__init__.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/benchmark_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/screenshot_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_1.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_2.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_3.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_4.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AreaLight_5.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/AtomBasicLevelSetup.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_1.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_2.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_3.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_4.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_5.ppm
  AutomatedTesting/Gem/PythonTests/Atom/golden_images/SpotLight_6.ppm
  AutomatedTesting/Gem/PythonTests/Atom/tests/TestAssets/ShaderAssetBuilder/DependencyValidation.azsl.txt
  AutomatedTesting/Gem/PythonTests/Atom/tests/TestAssets/ShaderAssetBuilder/DependencyValidation.shader.txt
  AutomatedTesting/Gem/PythonTests/Atom/tests/TestAssets/ShaderAssetBuilder/Test1Color.azsli.txt
  AutomatedTesting/Gem/PythonTests/Atom/tests/TestAssets/ShaderAssetBuilder/Test2Color.azsli.txt
  AutomatedTesting/Gem/PythonTests/Atom/tests/TestAssets/ShaderAssetBuilder/Test3Color.azsli.txt
  AutomatedTesting/Gem/PythonTests/Atom/tests/__init__.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_AddedToEntity.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DecalAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DepthOfFieldAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DirectionalLightAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_ExposureControlAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GlobalSkylightIBLAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightComponent.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PhysicalSkyAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXRadiusWeightModifierAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_AtomFeatureIntegrationBenchmark.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_LightComponent.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges.py
  AutomatedTesting/Gem/PythonTests/CMakeLists.txt
Labels: pr-ready-to-merge

#3983 Jobify view culling
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Labels: pr-ready-to-merge

#4023 Reworked net entities instantiation in order to fix entity references…
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/INetworkEntityManager.h
  Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.h
  Gems/Multiplayer/Code/Source/Pipeline/NetBindMarkerComponent.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetBindMarkerComponent.h
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkSpawnableHolderComponent.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkSpawnableHolderComponent.h
  Gems/Multiplayer/Code/Tests/MainTools.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/network

#4096 Hierarchical Components, phase 1 with unit tests
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHierarchyBus.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHierarchyChildComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHierarchyRootComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkTransformComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/NetworkHierarchyChildComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/AutoGen/NetworkHierarchyRootComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/Components/NetworkHierarchyChildComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkHierarchyRootComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicator.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicator.h
  Gems/Multiplayer/Code/Tests/ClientHierarchyTests.cpp
  Gems/Multiplayer/Code/Tests/CommonHierarchySetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
  Gems/Multiplayer/Code/Tests/ServerHierarchyTests.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
  Gems/Multiplayer/Code/multiplayer_tests_files.cmake
Labels: feature/networking, sig/network

#4266 Update deployment targets for MacOS and iOS
  cmake/Platform/Mac/PAL_mac.cmake
  cmake/Platform/iOS/Toolchain_ios.cmake
Labels: pr-ready-to-merge

#4286 Debug build clang fixes for Multiplayer.Tests
  Gems/Multiplayer/Code/Tests/ClientHierarchyTests.cpp
  Gems/Multiplayer/Code/Tests/ServerHierarchyTests.cpp
Labels: sig/network

#4261 Updated NetworkSpawnableHolderComponent to use TransformBus instead o…
  Code/Framework/AzCore/AzCore/Component/Entity.cpp
  Code/Framework/AzCore/AzCore/Component/Entity.h
  Gems/Multiplayer/Code/Source/Pipeline/NetworkSpawnableHolderComponent.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkSpawnableHolderComponent.h
Labels: sig/network

#4287 LYN6657 Misc Improvements for Multiplayer Scripting
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkRigidBodyComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
Labels: sig/network

#4144 Product/Source differentiation AssetBrowser Search View.
  Assets/Editor/Icons/AssetBrowser/TreeBranch_First.svg
  Assets/Editor/Icons/AssetBrowser/TreeBranch_Last.svg
  Assets/Editor/Icons/AssetBrowser/TreeBranch_Middle.svg
  Assets/Editor/Icons/AssetBrowser/TreeBranch_OneChild.svg
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.h
Labels: feature/asset-pipeline, kind/feature

#4328 [Mac] Set working directory to the install directory so that cmake can find includes in the engine root's cmake directory.
  cmake/Platform/Mac/InstallUtils_mac.cmake.in
Labels: pr-ready-to-merge

#4321 Move public Multiplayer AutoGen jinja to Include dir
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Common.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/network

#4087 Asset Browser Search View Column Resizing
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.ui
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.h
Labels: feature/asset-pipeline, kind/feature

#4401 Quick updates to AzNetworking unit tests
  Code/Framework/AzNetworking/AzNetworking/DataStructures/FixedSizeBitsetView.inl
  Code/Framework/AzNetworking/Tests/DataStructures/FixedSizeBitsetTests.cpp
  Code/Framework/AzNetworking/Tests/DataStructures/FixedSizeBitsetViewTests.cpp
  Code/Framework/AzNetworking/Tests/TcpTransport/TcpTransportTests.cpp
  Code/Framework/AzNetworking/Tests/UdpTransport/UdpTransportTests.cpp
  Code/Framework/AzNetworking/Tests/Utilities/IpAddressTests.cpp
  Code/Framework/AzNetworking/Tests/Utilities/QuantizedValuesTests.cpp
Labels: sig/network
