Repository o3de/o3de, pull requests merged in 2021-12, with the labels that each got.

#5820 Pipe Editor-Server Logs Back to the Editor
  Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.cpp
  Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Code/Legacy/CryCommon/ICmdLine.h
  Code/Legacy/CrySystem/AZCoreLogSink.h
  Code/Legacy/CrySystem/CmdLineArg.cpp
  Code/Legacy/CrySystem/CmdLineArg.h
  Code/Legacy/CrySystem/SystemInit.cpp
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Labels: sig/core, sig/network, sig/testing

#5999 Added Tests for Gem Catalog Filtering
  Code/Tools/ProjectManager/CMakeLists.txt
  Code/Tools/ProjectManager/Source/GemCatalog/GemInfo.h
  Code/Tools/ProjectManager/tests/GemCatalogTests.cpp
Labels: sig/content

#5695 LYN-6430 Add debug draw for heightfields.
  Gems/PhysX/Code/Editor/DebugDraw.cpp
Labels: sig/content

#5914 Expand the Display Mapper component p0 test so that it modifies at least 1 property before passing.
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
Labels: sig/graphics-audio

#6059 LYN-8629 | Read-Only Entities - Setup
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntityBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntityInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntitySystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntitySystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Entity/ReadOnly/ReadOnlyEntityFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Entity/ReadOnly/ReadOnlyEntityFixture.h
  Code/Framework/AzToolsFramework/Tests/Entity/ReadOnly/ReadOnlyEntityTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: feature/editor, sig/content

#5948 Audio System - Fix for bug while deleting file
  Gems/AudioSystem/Code/Source/Editor/AudioControlsWriter.cpp
Labels: feature/audio, pr-ready-to-merge

#5945 Fix for bug cause by null pointer when loading audio library
  Gems/AudioSystem/Code/Source/Engine/FileCacheManager.cpp
Labels: feature/audio, pr-ready-to-merge

#5028 Update the folder structure for the AWSMetrics gem following the latest O3DE guidline
  Gems/AWSMetrics/Code/CMakeLists.txt
  Gems/AWSMetrics/Code/Include/AWSMetricsBus.h
  Gems/AWSMetrics/Code/Include/MetricsAttribute.h
  Gems/AWSMetrics/Code/Source/AWSMetricsConstant.h
  Gems/AWSMetrics/Code/Source/AWSMetricsModule.h
  Gems/AWSMetrics/Code/Source/AWSMetricsServiceApi.h
  Gems/AWSMetrics/Code/Source/AWSMetricsSystemComponent.h
  Gems/AWSMetrics/Code/Source/ClientConfiguration.h
  Gems/AWSMetrics/Code/Source/DefaultClientIdProvider.h
  Gems/AWSMetrics/Code/Source/GlobalStatistics.h
  Gems/AWSMetrics/Code/Source/IdentityProvider.h
  Gems/AWSMetrics/Code/Source/MetricsEvent.h
  Gems/AWSMetrics/Code/Source/MetricsEventBuilder.h
  Gems/AWSMetrics/Code/Source/MetricsManager.h
  Gems/AWSMetrics/Code/Source/MetricsQueue.h
  Gems/AWSMetrics/Code/awsmetrics_files.cmake
  Gems/AWSMetrics/Code/awsmetrics_shared_files.cmake
Labels: sig/network

#5178 Move the header files in the AWS Core gem based on the latest gem structure guideline
  Gems/AWSCore/Code/CMakeLists.txt
  Gems/AWSCore/Code/Include/AWSCoreBus.h
  Gems/AWSCore/Code/Include/Credential/AWSCredentialBus.h
  Gems/AWSCore/Code/Include/Framework/AWSApiClientJob.h
  Gems/AWSCore/Code/Include/Framework/AWSApiClientJobConfig.h
  Gems/AWSCore/Code/Include/Framework/AWSApiJob.h
  Gems/AWSCore/Code/Include/Framework/AWSApiJobConfig.h
  Gems/AWSCore/Code/Include/Framework/AWSApiRequestJob.h
  Gems/AWSCore/Code/Include/Framework/AWSApiRequestJobConfig.h
  Gems/AWSCore/Code/Include/Framework/Error.h
  Gems/AWSCore/Code/Include/Framework/HttpClientComponent.h
  Gems/AWSCore/Code/Include/Framework/HttpRequestJob.h
  Gems/AWSCore/Code/Include/Framework/HttpRequestJobConfig.h
  Gems/AWSCore/Code/Include/Framework/JobExecuter.h
  Gems/AWSCore/Code/Include/Framework/JsonObjectHandler.h
  Gems/AWSCore/Code/Include/Framework/JsonWriter.h
  Gems/AWSCore/Code/Include/Framework/MultipartFormData.h
  Gems/AWSCore/Code/Include/Framework/RequestBuilder.h
  Gems/AWSCore/Code/Include/Framework/ServiceClientJob.h
  Gems/AWSCore/Code/Include/Framework/ServiceClientJobConfig.h
  Gems/AWSCore/Code/Include/Framework/ServiceJob.h
  Gems/AWSCore/Code/Include/Framework/ServiceJobConfig.h
  Gems/AWSCore/Code/Include/Framework/ServiceJobUtil.h
  Gems/AWSCore/Code/Include/Framework/ServiceRequestJob.h
  Gems/AWSCore/Code/Include/Framework/ServiceRequestJobConfig.h
  Gems/AWSCore/Code/Include/Framework/Util.h
  Gems/AWSCore/Code/Include/ResourceMapping/AWSResourceMappingBus.h
  Gems/AWSCore/Code/Include/ScriptCanvas/AWSScriptBehaviorDynamoDB.h
  Gems/AWSCore/Code/Include/ScriptCanvas/AWSScriptBehaviorLambda.h
  Gems/AWSCore/Code/Include/ScriptCanvas/AWSScriptBehaviorS3.h
  Gems/AWSCore/Code/Include/ScriptCanvas/AWSScriptBehaviorsComponent.h
  Gems/AWSCore/Code/Source/AWSCoreEditorModule.h
  Gems/AWSCore/Code/Source/AWSCoreEditorSystemComponent.h
  Gems/AWSCore/Code/Source/AWSCoreInternalBus.h
  Gems/AWSCore/Code/Source/AWSCoreModule.h
  Gems/AWSCore/Code/Source/AWSCoreSystemComponent.h
  Gems/AWSCore/Code/Source/Configuration/AWSCoreConfiguration.h
  Gems/AWSCore/Code/Source/Credential/AWSCVarCredentialHandler.h
  Gems/AWSCore/Code/Source/Credential/AWSCredentialManager.h
  Gems/AWSCore/Code/Source/Credential/AWSDefaultCredentialHandler.h
  Gems/AWSCore/Code/Source/Editor/AWSCoreEditorManager.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSAttributionServiceApi.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionConsentDialog.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionConstant.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionManager.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionMetric.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionSystemComponent.h
  Gems/AWSCore/Code/Source/Editor/Constants/AWSCoreEditorMenuLinks.h
  Gems/AWSCore/Code/Source/Editor/Constants/AWSCoreEditorMenuNames.h
  Gems/AWSCore/Code/Source/Editor/UI/AWSCoreEditorMenu.h
  Gems/AWSCore/Code/Source/Editor/UI/AWSCoreResourceMappingToolAction.h
  Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingConstants.h
  Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingManager.h
  Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingUtils.h
  Gems/AWSCore/Code/awscore_editor_files.cmake
  Gems/AWSCore/Code/awscore_editor_shared_files.cmake
  Gems/AWSCore/Code/awscore_files.cmake
  Gems/AWSCore/Code/awscore_shared_files.cmake
Labels: sig/network

#5177 Move the header files in the AWS ClientAuth gem based on the latest gem structure guideline
  Gems/AWSClientAuth/Code/CMakeLists.txt
  Gems/AWSClientAuth/Code/Include/Authentication/AuthenticationProviderBus.h
  Gems/AWSClientAuth/Code/Include/Authentication/AuthenticationTokens.h
  Gems/AWSClientAuth/Code/Include/Authorization/AWSCognitoAuthorizationBus.h
  Gems/AWSClientAuth/Code/Include/Authorization/ClientAuthAWSCredentials.h
  Gems/AWSClientAuth/Code/Include/UserManagement/AWSCognitoUserManagementBus.h
  Gems/AWSClientAuth/Code/Source/AWSClientAuthBus.h
  Gems/AWSClientAuth/Code/Source/AWSClientAuthModule.h
  Gems/AWSClientAuth/Code/Source/AWSClientAuthResourceMappingConstants.h
  Gems/AWSClientAuth/Code/Source/AWSClientAuthSystemComponent.h
  Gems/AWSClientAuth/Code/Source/Authentication/AWSCognitoAuthenticationProvider.h
  Gems/AWSClientAuth/Code/Source/Authentication/AuthenticationNotificationBusBehaviorHandler.h
  Gems/AWSClientAuth/Code/Source/Authentication/AuthenticationProviderInterface.h
  Gems/AWSClientAuth/Code/Source/Authentication/AuthenticationProviderManager.h
  Gems/AWSClientAuth/Code/Source/Authentication/AuthenticationProviderScriptCanvasBus.h
  Gems/AWSClientAuth/Code/Source/Authentication/AuthenticationProviderTypes.h
  Gems/AWSClientAuth/Code/Source/Authentication/GoogleAuthenticationProvider.h
  Gems/AWSClientAuth/Code/Source/Authentication/LWAAuthenticationProvider.h
  Gems/AWSClientAuth/Code/Source/Authentication/OAuthConstants.h
  Gems/AWSClientAuth/Code/Source/Authorization/AWSClientAuthCognitoCachingAuthenticatedCredentialsProvider.h
  Gems/AWSClientAuth/Code/Source/Authorization/AWSClientAuthPersistentCognitoIdentityProvider.h
  Gems/AWSClientAuth/Code/Source/Authorization/AWSCognitoAuthorizationController.h
  Gems/AWSClientAuth/Code/Source/Authorization/AWSCognitoAuthorizationNotificationBusBehaviorHandler.h
  Gems/AWSClientAuth/Code/Source/UserManagement/AWSCognitoUserManagementController.h
  Gems/AWSClientAuth/Code/Source/UserManagement/UserManagementNotificationBusBehaviorHandler.h
  Gems/AWSClientAuth/Code/awsclientauth_files.cmake
  Gems/AWSClientAuth/Code/awsclientauth_shared_files.cmake
Labels: sig/network

#6071 Add CLI option to enable PIX GPU events without expressing loading the Pix runtime
  Gems/Atom/RHI/Code/Include/Atom/RHI/Factory.h
  Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp
Labels: sig/graphics-audio

#6065 BUGFIX improve the start up time of the atom render plugin
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
Labels: feature/animation, kind/bug

#5827 chore: remove duplicate instance of FancyDockingDropZoneConstants
  Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDocking.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDockingDropZoneWidget.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/FancyDockingDropZoneWidget.h
Labels: sig/content, sig/ui-ux

#5911 Bug motion set removal h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetWindow.cpp
Labels: feature/animation

#5823 UI Editor - bugfix: prevent Anchor buttons from overlapping when shrinking layout(#5552)
  Gems/LyShine/Code/Editor/AnchorPresetsWidget.cpp
  Gems/LyShine/Code/Editor/PropertiesWidget.cpp
Labels: sig/content, sig/ui-ux

#6060 Adding Macbeth level to AutomatedTesting and converting to Prefab
  AutomatedTesting/Levels/macbeth_shaderballs/macbeth_shaderballs.prefab
  AutomatedTesting/Levels/macbeth_shaderballs/tags.txt
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/00_illuminant.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/00_illuminant_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/01_dark_skin.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/01_dark_skin_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/02_light_skin.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/02_light_skin_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/03_blue_sky.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/03_blue_sky_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/04_foliage.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/04_foliage_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/05_blue_flower.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/05_blue_flower_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/06_bluish_green.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/06_bluish_green_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/07_orange.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/07_orange_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/08_purplish_blue.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/08_purplish_blue_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/09_moderate_red.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/09_moderate_red_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/10_purple.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/10_purple_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/11_yellow_green.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/11_yellow_green_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/12_orange_yellow.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/12_orange_yellow_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/13_blue.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/13_blue_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/14_green.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/14_green_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/15_red.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/15_red_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/16_yellow.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/16_yellow_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/17_magenta.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/17_magenta_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/18_cyan.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/18_cyan_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/19_white_9-5_0-05D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/19_white_9-5_0-05D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/20_neutral_8-0_0-23D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/20_neutral_8-0_0-23D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/21_neutral_6-5_0-44D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/21_neutral_6-5_0-44D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/22_neutral_5-0_0-70D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/22_neutral_5-0_0-70D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/23_neutral_3-5_1-05D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/23_neutral_3-5_1-05D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/24_black_2-0_1-50D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/24_black_2-0_1-50D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/macbeth_lab_16bit_2014_sRGB.material
Labels: sig/graphics-audio

#5890 shadow fixes
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Math/Filter.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PointLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ESM.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli
Labels: sig/graphics-audio

#6016 Fix for artifact with thin-film materials and shadows
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/BackLighting.azsli
Labels: sig/graphics-audio

#5944 Improvement to filter types
  Gems/AudioEngineWwise/Code/Source/Editor/AudioSystemEditor_wwise.cpp
Labels: feature/audio

#5941 Fix - Entity ID
  Gems/LmbrCentral/Code/Source/Audio/AudioListenerComponent.cpp
Labels: feature/audio

#5937 Bug undo error
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorUndo.cpp
Labels: feature/audio

#6088 Atom/antonmic/depth of field vulkan fix
  Gems/Atom/Feature/Common/Assets/Passes/NewDepthOfFieldComposite.pass
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/PostProcessing/ViewSrg.azsli
Labels: sig/graphics-audio

#6097 Removing PythonAssetBuilderSystemComponent from GetRequiredSystemComponents
  Gems/PythonAssetBuilder/Code/Source/PythonAssetBuilderModule.cpp
Labels: sig/graphics-audio

#6102 Removing warnings from material editor viewport
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportRenderer.cpp
Labels: sig/graphics-audio

#6106 Fixing warnings caused by system components not added to serialize context
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerToolsSystemComponent.cpp
Labels: sig/graphics-audio

#6058 [Mac] Update AWS package version
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
Labels: pr-ready-to-merge

#6095 Update the deformer in the atom debug draw class
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
Labels: sig/graphics-audio

#6098 LYN-5843. Fixed an issue when exit from full screen game mode in Editor.
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
Labels: sig/graphics-audio

#5959 Manipulator Bounds updates
  Code/Editor/EditorPreferencesPageViewportManipulator.cpp
  Code/Editor/EditorPreferencesPageViewportManipulator.h
  Code/Editor/EditorViewportSettings.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/BaseManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/BaseManipulator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/LinearManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/MultiLinearManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/PlanarManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ScaleManipulators.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/LmbrCentral/Code/Tests/EditorPolygonPrismShapeComponentTests.cpp
  Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsSubComponentModeAngleCone.cpp
Labels: sig/content

#5946 Fix for bug in switch group
  Gems/AudioSystem/Code/Source/Editor/QSimpleAudioControlListWidget.cpp
Labels: feature/audio

#6076 disabling unused test results jobs
  scripts/build/Platform/Linux/build_config.json
  scripts/build/Platform/Mac/build_config.json
Labels: sig/testing

#5775 LyTestTools artifact collection
  Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/tests/unit/test_launcher_base.py
  cmake/LYTestWrappers.cmake
Labels: sig/testing

#6134 Resaved LY_SC_UnitTest_NodeableDelay.scriptcanvas to update to json f…
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_NodeableDelay.scriptcanvas
Labels: feature/scripting

#6101 Fixing build fail when Renderdoc is enabled
  Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
Labels: sig/graphics-audio

#6124 Fixed pass warning in ASV
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassDefines.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Labels: sig/graphics-audio

#6140 Multiplayer benchmark cleanup
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
Labels: sig/network

#6110 Changing trace logger to clear log file when opened
  Code/Framework/AzToolsFramework/AzToolsFramework/Logger/TraceLogger.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Logger/TraceLogger.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: sig/graphics-audio

#6082 Atom Level component test support in editor_entity_utils.py and tests for level components
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DiffuseGlobalIlluminationAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
Labels: sig/graphics-audio

#6145 Optimizations to graph canvas translation json serializer
  Gems/GraphCanvas/Code/Source/Translation/TranslationSerializer.cpp
Labels: feature/scripting, sig/graphics-audio

#6160 LYN-8631 + LYN-8632 | Display appropriate read-only icons and procedural prefabs ui in the Outliner
  Code/Framework/AzQtComponents/AzQtComponents/Images/Entity/prefab_edit_open_readonly.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Entity/readonly.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/resources.qrc
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/ReadOnly/ReadOnlyEntitySystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/Procedural/ProceduralPrefabReadOnlyHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/Procedural/ProceduralPrefabReadOnlyHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/Procedural/ProceduralPrefabUiHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/Procedural/ProceduralPrefabUiHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Entity/ReadOnly/ReadOnlyEntityTests.cpp
Labels: sig/content, sig/ui-ux

#6175 Updated viewport to hide the transform manipulators for entities marked as read only.
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
Labels: sig/content

#6119 Atom/mriegger/overflow
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/LightCulling/LightCullingTileIterator.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/LightCulling/NVLC.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCullingHeatmap.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCullingRemap.azsl
Labels: sig/graphics-audio

#6137 Modified Color Swatch Fix
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/00_illuminant_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/01_dark_skin.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/01_dark_skin_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/02_light_skin.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/02_light_skin_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/03_blue_sky.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/03_blue_sky_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/04_foliage_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/05_blue_flower_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/06_bluish_green.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/06_bluish_green_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/07_orange_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/08_purplish_blue.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/08_purplish_blue_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/09_moderate_red.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/09_moderate_red_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/10_purple.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/10_purple_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/11_yellow_green.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/11_yellow_green_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/12_orange_yellow.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/12_orange_yellow_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/13_blue.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/13_blue_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/14_green.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/14_green_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/15_red.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/15_red_sRGB.tif
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/15_red_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/16_yellow.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/16_yellow_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/17_magenta.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/17_magenta_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/18_cyan.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/18_cyan_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/19_white_9-5_0-05D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/19_white_9-5_0-05D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/20_neutral_8-0_0-23D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/20_neutral_8-0_0-23D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/21_neutral_6-5_0-44D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/21_neutral_6-5_0-44D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/22_neutral_5-0_0-70D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/22_neutral_5-0_0-70D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/23_neutral_3-5_1-05D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/23_neutral_3-5_1-05D_tex.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/24_black_2-0_1-50D.material
  Gems/Atom/Feature/Common/Assets/Materials/Presets/MacBeth/24_black_2-0_1-50D_tex.material
Labels: sig/graphics-audio

#5784 Terrain/sphrose/vegetation tests
  AutomatedTesting/Assets/Prefabs/PinkFlower.prefab
  AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/TerrainSystem_VegetationSpawnsOnTerrainSurfaces.py
  AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
  Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
Labels: sig/content

#5619 Update default project to include PrefabBuilder
  Templates/DefaultProject/Template/Code/enabled_gems.cmake
Labels: sig/content

#4960 LYN-6431 Added materials support to TerrainPhysicsCollider, added uni…
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
  Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
Labels: sig/content

#5659 LYN-6357 Terrain Macro Material tests
  AutomatedTesting/Assets/Textures/image.png
  AutomatedTesting/Assets/Textures/normal.png
  AutomatedTesting/Gem/PythonTests/Terrain/EditorScripts/TerrainMacroMaterialComponent_MacroMaterialActivates.py
  AutomatedTesting/Gem/PythonTests/Terrain/TestSuite_Main.py
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainMacroMaterialComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialBus.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialBus.h
  Gems/Terrain/Code/Tests/TerrainMacroMaterialTests.cpp
  Gems/Terrain/Code/terrain_files.cmake
  Gems/Terrain/Code/terrain_tests_files.cmake
Labels: sig/content

#6176 Jobify the draw item list sort in View::FinalizeDrawLists
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RHI/Code/Source/RHI/DrawListContext.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/FeatureProcessor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RasterPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Labels: sig/graphics-audio

#6079 Add verbosity option to some o3de.py sub-commands
  scripts/o3de.py
  scripts/o3de/o3de/cmake.py
  scripts/o3de/o3de/disable_gem.py
  scripts/o3de/o3de/download.py
  scripts/o3de/o3de/enable_gem.py
  scripts/o3de/o3de/engine_properties.py
  scripts/o3de/o3de/engine_template.py
  scripts/o3de/o3de/gem_properties.py
  scripts/o3de/o3de/get_registration.py
  scripts/o3de/o3de/global_project.py
  scripts/o3de/o3de/manifest.py
  scripts/o3de/o3de/print_registration.py
  scripts/o3de/o3de/project_properties.py
  scripts/o3de/o3de/register.py
  scripts/o3de/o3de/repo.py
  scripts/o3de/o3de/sha256.py
  scripts/o3de/o3de/utils.py
  scripts/o3de/o3de/validation.py
Labels: pr-ready-to-merge, sig/core, kind/enhancement, feature/sdk

#6085 Enable optimized GPU tests and make them the main GPU tests.
  AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU_Optimized.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_AreaLightScreenshotTest.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_SpotLightScreenshotTest.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_GPUTest_LightComponent.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
Labels: sig/graphics-audio

#6077 Fix loaded procprefabs not going through the asset hint fixup process…
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabAssetFixupTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content

#5511 Generic DOM: Add DomBackend abstraction and JSON support
  Code/Framework/AzCore/AzCore/DOM/Backends/JSON/JsonBackend.h
  Code/Framework/AzCore/AzCore/DOM/Backends/JSON/JsonSerializationUtils.cpp
  Code/Framework/AzCore/AzCore/DOM/Backends/JSON/JsonSerializationUtils.h
  Code/Framework/AzCore/AzCore/DOM/DomBackend.cpp
  Code/Framework/AzCore/AzCore/DOM/DomBackend.h
  Code/Framework/AzCore/AzCore/DOM/DomUtils.cpp
  Code/Framework/AzCore/AzCore/DOM/DomUtils.h
  Code/Framework/AzCore/AzCore/DOM/DomVisitor.cpp
  Code/Framework/AzCore/AzCore/DOM/DomVisitor.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/DOM/DomJsonBenchmarks.cpp
  Code/Framework/AzCore/Tests/DOM/DomJsonTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/content, sig/core

#6223 Enable Pix markers if the Pix DLL is loaded
  Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
Labels: sig/graphics-audio

#6232 Some read-only prefab workflow updates.
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
Labels: sig/content

#6203 Prevent the camera from easily being set to an invalid orientation
  Code/Editor/EditorModularViewportCameraComposer.cpp
  Code/Editor/GotoPositionDlg.cpp
  Code/Editor/GotoPositionDlg.h
  Code/Editor/Lib/Tests/Camera/test_EditorCamera.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
  Code/Framework/AzFramework/Tests/CameraInputTests.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorBoxSelect.cpp
Labels: sig/content, feature/viewport

#6246 Fix debug compilation.
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Labels: sig/content

#6170 Print Entity name if Improperly Deleted
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Labels: sig/network

#6174 Fix quad light NAN on contact with other surfaces
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli
Labels: sig/graphics-audio

#6257 Additional read-only prefab workflow changes.
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Labels: sig/content

#6066 Updating Multiplayer PyTests To Check Server Logs
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/AutoComponent_NetworkInput.scriptcanvas
  Code/Framework/AzCore/AzCore/Console/Console.cpp
  Code/Framework/AzCore/AzCore/Console/LoggerSystemComponent.cpp
  Code/Legacy/CrySystem/SystemInit.cpp
  Gems/BarrierInput/Code/Source/BarrierInputClient.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#6221 Multiple bug fixes
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseProbeGridRender.pass
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ImageSubresource.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphAttachmentDatabase.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphCompileContext.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/ConstantsLayout.cpp
  Gems/Atom/RHI/Code/Source/RHI.Reflect/ImageSubresource.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphAttachmentDatabase.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompileContext.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/ResourcePool/ResourcePoolSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
Labels: sig/graphics-audio

#6279 Improve error messaging when duplicating entities before they are created
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/EditorEntityManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/EditorEntityManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: sig/content, sig/ui-ux

#6302 Fixed logic for when to cull entities from having their viewport manipulators regenerated.
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
Labels: sig/content

#6136 Procedural Prefabs: Python documentation cleanup
  AutomatedTesting/Editor/Scripts/scene_helpers.py
  AutomatedTesting/Editor/Scripts/scene_mesh_to_prefab.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/scene_data.py
Labels: sig/content

#6235 Fix warnings, add branch notifier
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/LightCulling/NVLC.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Decals.azsli
Labels: sig/graphics-audio

#6114 [development] updated editor event handling with respect to imgui
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
  Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
  Gems/ImGui/Code/Source/ImGuiManager.cpp
  Gems/Profiler/Code/Source/CpuProfilerImpl.cpp
  Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp
Labels: sig/content, sig/core

#6264 Modified Jenkinsfile to upload test artifacts on failure
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/testing

#6192 Preapre codebase for FileRequest compiletime improvements
  Code/Editor/GameEngine.cpp
  Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
  Code/Framework/AzCore/AzCore/Asset/AssetDataStream.cpp
  Code/Framework/AzCore/AzCore/Asset/AssetDataStream.h
  Code/Framework/AzCore/AzCore/IO/Streamer/BlockCache.h
  Code/Framework/AzCore/AzCore/IO/Streamer/DedicatedCache.h
  Code/Framework/AzCore/AzCore/IO/Streamer/FileRequest.h
  Code/Framework/AzCore/AzCore/IO/Streamer/FullFileDecompressor.h
  Code/Framework/AzCore/AzCore/IO/Streamer/Scheduler.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Scheduler.h
  Code/Framework/AzCore/AzCore/IO/Streamer/StorageDrive.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/StorageDrive.h
  Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/StreamerContext.h
  Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StorageDrive_Windows.cpp
  Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StorageDrive_Windows.h
  Code/Framework/AzCore/Tests/Streamer/FullDecompressorTests.cpp
  Code/Framework/AzCore/Tests/Streamer/ReadSplitterTests.cpp
  Code/Framework/AzCore/Tests/Streamer/SchedulerTests.cpp
  Code/Framework/AzCore/Tests/Streamer/StreamStackEntryConformityTests.h
  Code/Framework/AzCore/Tests/StreamerTests.cpp
  Code/Framework/AzFramework/AzFramework/IO/RemoteStorageDrive.cpp
  Code/Framework/AzFramework/AzFramework/IO/RemoteStorageDrive.h
  Code/Framework/AzFramework/AzFramework/Script/ScriptComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ToolsAssetCatalogComponent.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomTressFX/Code/Rendering/SharedBuffer.cpp
  Gems/AudioSystem/Code/Source/Engine/FileCacheManager.cpp
  Gems/AudioSystem/Code/Tests/AudioSystemTest.cpp
  Gems/AudioSystem/Code/Tests/Mocks/FileCacheManagerMock.h
  Gems/EMotionFX/Code/EMotionFX/Source/ActorInstance.cpp
  Gems/LmbrCentral/Code/Source/Asset/AssetSystemDebugComponent.cpp
  Gems/PhysX/Code/Source/Joint/PhysXJointUtils.cpp
  Gems/PhysX/Code/Source/Joint/PhysXJointUtils.h
  Gems/PhysX/Code/Source/JointComponent.cpp
  Gems/PhysX/Code/Source/JointComponent.h
  Gems/PhysX/Code/Source/Material.cpp
  Gems/PhysX/Code/Source/PhysXCharacters/API/CharacterUtils.cpp
  Gems/PhysX/Code/Source/PhysXCharacters/API/RagdollNode.cpp
  Gems/PhysX/Code/Source/Pipeline/HeightFieldAssetHandler.cpp
  Gems/PhysX/Code/Source/Pipeline/StreamWrapper.h
  Gems/PhysX/Code/Source/Scene/PhysXScene.cpp
  Gems/PhysX/Code/Source/Scene/PhysXScene.h
  Gems/PhysX/Code/Source/System/PhysXSystem.cpp
  Gems/PhysX/Code/Source/System/PhysXSystem.h
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasMemoryAsset.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasMemoryAsset.h
Labels: sig/core

#6315 Atom/qingtao/atom 16711
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroupPool.cpp
Labels: sig/graphics-audio

#6273 Remove NOT_USE_CRY_MEMORY_MANAGER
  Gems/Atom/Asset/Shader/Code/CMakeLists.txt
  Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
Labels: sig/content, sig/graphics-audio

#6179 Convert prefab to temp spawnable assets
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/hydra_test_utils.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/prefab_utils.py
  AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/AltitudeFilter_ComponentAndOverrides_InstancesPlantAtSpecifiedAltitude.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/AltitudeFilter_FilterStageToggle.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/AltitudeFilter_ShapeSample_InstancesPlantAtSpecifiedAltitude.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/AssetListCombiner_CombinedDescriptorsExpressInConfiguredArea.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/AssetWeightSelector_InstancesExpressBasedOnWeight.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/DistanceBetweenFilterOverrides_InstancesPlantAtSpecifiedRadius.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/DistanceBetweenFilter_InstancesPlantAtSpecifiedRadius.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/DynamicSliceInstanceSpawner_Embedded_E2E.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/InstanceSpawnerPriority_LayerAndSubPriority.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerBlender_E2E_Editor.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerBlocker_InstancesBlockedInConfiguredArea.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerSpawner_FilterStageToggle.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerSpawner_InstancesPlantInAllSupportedShapes.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/LayerSpawner_InstancesRefreshUsingCorrectViewportCamera.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/MeshBlocker_InstancesBlockedByMesh.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/MeshBlocker_InstancesBlockedByMeshHeightTuning.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PhysXColliderSurfaceTagEmitter_E2E_Editor.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PositionModifier_AutoSnapToSurfaceWorks.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/PositionModifier_ComponentAndOverrides_InstancesPlantAtSpecifiedOffsets.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/RotationModifierOverrides_InstancesRotateWithinRange.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/RotationModifier_InstancesRotateWithinRange.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ScaleModifierOverrides_InstancesProperlyScale.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ScaleModifier_InstancesProperlyScale.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ShapeIntersectionFilter_FilterStageToggle.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ShapeIntersectionFilter_InstancesPlantInAssignedShape.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SlopeAlignmentModifierOverrides_InstanceSurfaceAlignment.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SlopeAlignmentModifier_InstanceSurfaceAlignment.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SlopeFilter_ComponentAndOverrides_InstancesPlantOnValidSlope.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SpawnerSlices_SliceCreationAndVisibilityToggleWorks.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SurfaceMaskFilterOverrides_MultipleDescriptorOverridesPlantAsExpected.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SurfaceMaskFilter_ExclusionList.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SurfaceMaskFilter_InclusionList.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SystemSettings_SectorPointDensity.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/SystemSettings_SectorSize.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/VegetationInstances_DespawnWhenOutOfRange.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/largeworlds/large_worlds_utils/editor_dynveg_test_helper.py
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabConverterStackProfileNames.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Registry/prefab.test.setreg
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Labels: sig/core

#6215 {lyn2265} adding a Python API for MotionGroup rules
  AutomatedTesting/Assets/TestAnim/Test_Jack_Death_Fall_Back_ZUp.fbx
  AutomatedTesting/Assets/TestAnim/scene_export_motion.py
  AutomatedTesting/Assets/TestAnim/test_jack_death_fall_back_zup.fbx.assetinfo
  AutomatedTesting/Editor/Scripts/scene_export_utils.py
  AutomatedTesting/Editor/Scripts/scene_helpers.py
  Gems/PythonAssetBuilder/Editor/Scripts/__init__.py
  Gems/PythonAssetBuilder/Editor/Scripts/bootstrap.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/_init_.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/actor_group.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/common_rules.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/motion_group.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/physics_data.py
  Gems/PythonAssetBuilder/Editor/Scripts/scene_api/scene_data.py
Labels: sig/core

#6048 Fix issues with Bank dependency processing in Wwise Builder
  Gems/AudioEngineWwise/Code/Source/Builder/WwiseBuilderWorker.cpp
Labels: feature/audio, kind/cleanup, sig/graphics-audio

#6262 Let resource mapping tool save resources without an account ID
  Gems/AWSCore/Code/Tools/ResourceMappingTool/model/basic_resource_attributes.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/model/__init__.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/model/test_basic_resource_attributes.py
Labels: sig/network

#6296 Focus issue in editor settings menu #3921
  Code/Editor/EditorPreferencesDialog.cpp
  Code/Editor/EditorPreferencesDialog.h
Labels: sig/content

#6263 Enabled the Script Canvas Minimap. It will be tested and any performa…
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Labels: feature/scripting, sig/content

#6172 Refactor Project Manager Settings
  AutomatedTesting/project.json
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Source/Application.cpp
  Code/Tools/ProjectManager/Source/Application.h
  Code/Tools/ProjectManager/Source/ExternalLinkDialog.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemFilterWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInfo.h
  Code/Tools/ProjectManager/Source/LinkWidget.cpp
  Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectBuilderController.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.h
  Code/Tools/ProjectManager/Source/ProjectManagerSettings.cpp
  Code/Tools/ProjectManager/Source/ProjectManagerSettings.h
  Code/Tools/ProjectManager/Source/ProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Code/Tools/ProjectManager/Source/Settings.cpp
  Code/Tools/ProjectManager/Source/Settings.h
  Code/Tools/ProjectManager/Source/SettingsInterface.h
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.h
  Code/Tools/ProjectManager/project_manager_files.cmake
  Code/Tools/ProjectManager/project_manager_tests_files.cmake
  Code/Tools/ProjectManager/tests/SettingsTests.cpp
  Templates/DefaultProject/Template/project.json
  Templates/MinimalProject/Template/project.json
  engine.json
  scripts/o3de/o3de/engine_template.py
  scripts/o3de/o3de/project_properties.py
  scripts/o3de/o3de/register.py
  scripts/o3de/o3de/validation.py
  scripts/o3de/tests/unit_test_project_properties.py
Labels: sig/content, sig/ui-ux, status/ux-approved

#6377 Vulkan validation fixes for RayTracing
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/BufferDescriptor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingBufferPools.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/Vulkan/External/glad/2.0.0-beta/include/glad/vulkan.h
Labels: sig/graphics-audio

#4923 [LYN-7064] Hot Loading of Procedural Prefabs
  Code/Framework/AzCore/AzCore/UnitTest/UnitTest.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicNotificationBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/ProceduralPrefabSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/ProceduralPrefabSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/ProceduralPrefabSystemComponentInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Prefab/ProceduralPrefabSystemComponentTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabBehaviorTests.cpp
Labels: sig/content

#6359 LYN-8837 o3de Material Editor - Texture Settings Editor - Hangs when …
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/AlbedoWithGenericAlpha.preset
  Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/PixelFormats.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Compressors/ASTCCompressor.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/ImageLoaders.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageFlags.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/PixelFormatInfo.cpp
Labels: sig/graphics-audio

#6389 Remove unused trait AZ_TRAIT_DISABLE_FAILED_MULTIPLAYER_GRIDMATE_TESTS
  Code/Framework/AzTest/AzTest/Platform/Android/AzTest_Traits_Android.h
  Code/Framework/AzTest/AzTest/Platform/Linux/AzTest_Traits_Linux.h
Labels: sig/network, sig/platform

#6374 Fixed several material editor bugs related to file paths and hot reload prompts
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/MaterialPropertyUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/CreateMaterialDialog/CreateMaterialDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorBrowserInteractions.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
Labels: sig/graphics-audio

#6306 Fixed incorrect condition that led to badly named slots
  Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/EBusHandlerEventNodeDescriptorComponent.cpp
Labels: feature/scripting, sig/content

#6401 Fix for dx12 validation spam
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseProbeGridRender.pass
Labels: feature/graphics/shaders

#6333 Fix: Lua breakpoint error
  Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp
Labels: feature/scripting, sig/content

#6328 Fix: Lua script debugging loading problem
  Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp
Labels: sig/content

#6195 keyword bug fixed
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerWidget.cpp
Labels: sig/content

#6316 Atom/16852
  Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/initialize.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/.env.example
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/3rdParty/Python/README.txt
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Editor/Scripts/bootstrap.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Lumberyard/Scripts/set_menu.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/kitbash_converter/main.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/Python/kitbash_converter/standalone.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Maya/Scripts/userSetup.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/bootstrap.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/sb_gui_main.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/sbs_to_sbsar.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/sbsar_info.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/sbsar_render.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/sbsar_utils.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/substance_tools.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/SDK/Substance/builder/watchdog/__init__.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Maya/Scripts/userSetup.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/DCC/Launch_Maya_2020.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/DCC/Launch_Maya_2022.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/DCC/Launch_mayaPy_2020.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/DCC/Launch_mayaPy_2022.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Core.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Dev.bat.example
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Maya.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_PyCharm.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Python.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Qt.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_Substance.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_VScode.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Env_WingIDE.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/IDE/Launch_MayaPy_PyCharmPro.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/IDE/Launch_PyCharmPro.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/IDE/Launch_VScode.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/IDE/Launch_WingIDE-7-1.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/IDE/Launch_mayapy_WingIDE-7-1.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Launch_Env_Cmd.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Launch_PyMin_Cmd.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Launch_Qt_PyMin_Cmd.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Launch_pyBASE_Cmd.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Setuo_copy_oiio.bat
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Solutions/.idea/.gitignore
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Solutions/.idea/DccScriptingInterface.iml
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Solutions/.idea/misc.xml
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Solutions/.idea/vcs.xml
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/__init__.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/config_utils.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/constants.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/env_base.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/synthetic_env.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/azpy/test/entry_test.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/config.py
Labels: sig/graphics-audio

#6412 ATOM-16958 [Image Builder] Alpha data would be removed for source ima…
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
Labels: sig/graphics-audio

#6420 [Bugfix] Atom render viewport in animation editor - small fix
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
Labels: feature/animation

#6379 Garbled name when using Chinese charaters
  Gems/EMotionFX/Code/MysticQt/Source/MysticQtConfig.h
Labels: sig/content

#6440 Fix for missing meshes in the RayTracing Acceleration Structure
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Labels: sig/graphics-audio

#6331 Fix: Find function reports code with a line offset of 1
  Code/Tools/LuaIDE/Source/LUA/LUAEditorFindDialog.cpp
Labels: sig/content

#6432 Atom/qingtao/image builder fixes
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/AlbedoWithGenericAlpha.preset
  Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/PixelFormats.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Compressors/ASTCCompressor.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/ImageLoaders.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageFlags.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/PixelFormatInfo.cpp
Labels: feature/graphics/rpi

#6436 Add MainPipeline to pass hierarchy for when HDR color grading component requests for the lut generation's image attachment.
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
Labels: sig/graphics-audio

#6439 Atom/antonmic/clear pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Passes/SMAA1xApplyLinearHDRColor.pass
  Gems/Atom/Feature/Common/Assets/Passes/SMAA1xApplyPerceptualColor.pass
  Gems/Atom/Feature/Common/Assets/Passes/SlowClear.pass
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EyeAdaptationPass.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ParentPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/SlowClearPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/SlowClearPassData.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFactory.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/SlowClearPass.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
  Gems/Atom/RPI/Code/atom_rpi_reflect_files.cmake
Labels: sig/graphics-audio

#6411 [AudioSystem] ACE bug fix: Ctrl-S doesn't work correctly when a level is loaded.
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorMainWindow.ui
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.h
Labels: feature/audio, kind/bug, pr-ready-to-merge, sig/graphics-audio

#6461 Disable DiffuseProbeGridDownsamplePass
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseGlobalIllumination.pass
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseProbeGridDownsample.pass
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseGlobalIlluminationFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridDownsamplePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridDownsamplePass.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
Labels: sig/graphics-audio

#6373 chore: remove "using namespace " from AZCore Memory
  Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
  Code/Framework/AzCore/AzCore/Memory/AllocatorBase.cpp
  Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapAllocator.cpp
  Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapAllocator.h
  Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapSchema.cpp
  Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapSchema.h
  Code/Framework/AzCore/AzCore/Memory/PoolSchema.cpp
  Code/Framework/AzCore/AzCore/Memory/PoolSchema.h
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.h
Labels: sig/core

#6489 sandboxing DisplayMapper P0 test for investigation
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
Labels: sig/graphics-audio

#6405 Fix: AssetBrowserTest cannot be run in debug
  Code/Framework/AzToolsFramework/Tests/UI/AssetBrowserTests.cpp
Labels: feature/editor, kind/bug, sig/content

#6298 Hide the invalid parameters in the EnhancedPBR in the Material Editor
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Anisotropy.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin_SpecularF0.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ClearCoatState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_HandleOpacityMode.lua
Labels: sig/graphics-audio

#6456 Attachment: expose more function from AttachmentComponentRequestBus
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Animation/AttachmentComponent.cpp
Labels: feature/animation

#6477 Fixes rounding error display in Slider control
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.h
Labels: sig/content

#6259 Add pytest to Resource Mapping Tool requirements.txt
  Gems/AWSCore/Code/Tools/ResourceMappingTool/README.md
  Gems/AWSCore/Code/Tools/ResourceMappingTool/requirements.txt
Labels: sig/network

#6531 Fix the cmake issue for AWSI automation tests
  AutomatedTesting/Gem/PythonTests/AWS/CMakeLists.txt
Labels: sig/network

#6533 Fix compile issues blocking adoption of Pix 2108
  Code/Editor/IEditorImpl.cpp
  Code/Editor/Include/IEditorClassFactory.h
  Code/Editor/Include/IViewPane.h
  Code/Editor/Plugin.cpp
  Code/Editor/Plugins/PerforcePlugin/PerforceSourceControl.h
  Code/Editor/PreferencesStdPages.cpp
  Code/Editor/Util/FileUtil.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
Labels: feature/azcore

#6369 bugfix[Linux]: resolve Lua script file not found
  Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
Labels: sig/content, sig/platform

#6536 Add precise keyword to the depth and forward pass shaders.
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_DepthPass_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ForwardPass.azsl
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/BasePbrSurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
  Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
Labels: sig/graphics-audio

#6535 Change the nvidia Aftermath integration to use c strings directly
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermath_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandListBase.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandListBase.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/NsightAftermath.h
Labels: sig/graphics-audio

#6329 Lua Editor log - text ghosted
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/LogPanel_Panel.cpp
Labels: sig/content

#6210 Fix: jumps disordered
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorView.cpp
Labels: sig/content

#6208 Fix: next and prev tabs incorrectly implemented
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Labels: sig/content

#6214 Slice save path incorrect, and error message incomplete
  Code/Framework/AzToolsFramework/AzToolsFramework/Slice/SliceUtilities.cpp
Labels: sig/content

#6299 Breakpoints in Lua Editor
  Code/Tools/LuaIDE/Source/LUA/BreakpointPanel.cpp
Labels: sig/content

#6218 Cursor on the Node Palette does not cover the searched keywords completely
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/NodePalette/NodePaletteWidget.cpp
Labels: sig/content

#6244 Added pass class
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseComposite.pass
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseCompositePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseCompositePass.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
Labels: sig/graphics-audio

#6288 Negative distances invalid
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Labels: sig/content

#6327 Editor bug using find layer
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
Labels: sig/content

#6366 chore: remove "using namespace AZ" from AZCore Script
  Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp
  Code/Framework/AzCore/AzCore/Script/ScriptContext.h
  Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.cpp
  Code/Framework/AzCore/AzCore/Script/ScriptContextDebug.h
  Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
  Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.h
Labels: sig/core

#6372 chore: remove "using namespace " from AZCore Math
  Code/Framework/AzCore/AzCore/Math/IntersectSegment.cpp
  Code/Framework/AzCore/AzCore/Math/Sfmt.cpp
Labels: sig/core

#6211 Fix: search results not expanded when searching for .lua files
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Labels: sig/content

#6207 Fix: Lua directory empty and always loading in editor
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Labels: sig/content

#6559 Disambiguate null interface case
  Code/Framework/AzCore/AzCore/Interface/Interface.h
Labels: sig/core

#6240 Fix for bug in entity outliner search box
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
Labels: sig/content, sig/ui-ux, status/ux-approved

#6297 White box limit
  Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp
Labels: sig/content

#6250 Prevent some slice-related commands from being enabled when the slice…
  Code/Editor/Core/LevelEditorMenuHandler.cpp
  Code/Editor/CryEdit.cpp
  Code/Editor/MainWindow.cpp
Labels: sig/content

#6572 Optimized Terrain Debugger Wireframe rendering
  Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.h
Labels: sig/content

#6309 Multiplayer AR Testing RPCs
  AutomatedTesting/Gem/Code/Source/AutoGen/NetworkTestPlayerComponent.AutoComponent.xml
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_RPC.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.prefab
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.scriptcanvas
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC_NetLevelEntity.scriptcanvas
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/GlobalGameData.scriptcanvas
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/GlobalGameData.scriptevents
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/Player.prefab
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/tags.txt
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
Labels: sig/network, sig/testing

#6350 Terrain Feature Processor separated into several classes. Macro materials abstracted from meshes.
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/SceneSrgAll.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/ViewSrgAll.azsli
  Gems/Atom/Feature/Common/Code/Source/Utils/GpuBufferHandler.cpp
  Gems/Terrain/Assets/Materials/Terrain/DefaultPbrTerrain.material
  Gems/Terrain/Assets/Materials/Terrain/PbrTerrain.materialtype
  Gems/Terrain/Assets/Shaders/Terrain/SceneSrg.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Assets/Shaders/Terrain/Terrain_DepthPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/ViewSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/Aabb2i.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Aabb2i.h
  Gems/Terrain/Code/Source/TerrainRenderer/BindlessImageArrayHandler.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/BindlessImageArrayHandler.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialBus.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialBus.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/Vector2i.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Vector2i.h
  Gems/Terrain/Code/terrain_files.cmake
Labels: sig/content, sig/graphics-audio
