Repository o3de/o3de, pull requests merged in 2021-08, with the labels that each got.

#2146 Fix inconsistent client lerp and account for blend factor on server
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkTransformComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkInput/NetworkInput.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkTime/INetworkTime.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkTime/RewindableObject.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkTime/RewindableObject.inl
  Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Source/NetworkInput/NetworkInput.cpp
  Gems/Multiplayer/Code/Source/NetworkTime/NetworkTime.cpp
  Gems/Multiplayer/Code/Source/NetworkTime/NetworkTime.h
  Gems/Multiplayer/Code/Tests/RewindableContainerTests.cpp
  Gems/Multiplayer/Code/Tests/RewindableObjectTests.cpp
Labels: sig/network

#2309 Allow users to rename AnimGraph and Actor node groups to contain any string
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AnimGraphNodeCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AnimGraphNodeGroupCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AnimGraphNodeGroupCommands.h
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/NodeGroupCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/NodeGroupCommands.h
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/ParameterMixins.h
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/ChunkProcessors.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/NodeGroup.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/NodeGroup.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGroupWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeGroups/NodeGroupManagementWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeGroups/NodeGroupWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeGroups/NodeGroupWidget.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeGroups/NodeGroupsPlugin.cpp
  Gems/EMotionFX/Code/MCore/Source/Command.cpp
  Gems/EMotionFX/Code/MCore/Source/Command.h
Labels: pr-ready-to-merge

#2754 Add connection interface timeout config and remove Ctrl+G timer
  Code/Framework/AzNetworking/AzNetworking/Framework/INetworkInterface.h
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpNetworkInterface.cpp
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpNetworkInterface.h
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network

#2737 Update the cloth rule to look for optimized meshes
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/NvCloth/Code/Source/Pipeline/SceneAPIExt/ClothRule.cpp
Labels: pr-ready-to-merge

#2846 CCryEditDoc: fix a few bugs
  Code/Editor/CryEditDoc.cpp
  Code/Editor/CryEditDoc.h
Labels: review-required

#2092 LYN-3705 As a dev I want a toggle to clear console every time I hit ctrl+G
  Code/Editor/Controls/ConsoleSCB.cpp
  Code/Editor/Controls/ConsoleSCB.h
  Code/Editor/EditorPreferencesPageGeneral.cpp
  Code/Editor/EditorPreferencesPageGeneral.h
  Code/Editor/GameEngine.cpp
  Code/Editor/Settings.cpp
  Code/Editor/Settings.h
Labels: feature/editor, kind/enhancement, review-required, sig/ui-ux

#2825 Fix logic in ReadConnectionSettingsFromSettingsRegistry
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponentHelper.cpp
Labels: review-required

#2823 Fix memory leak in ProcessLauncher::LaunchProcess
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessWatcher_Linux.cpp
Labels: review-required

#2813 Bunch of small bug fixes
  Code/Editor/Settings.cpp
  Code/Framework/AzCore/AzCore/std/chrono/types.h
  Code/Framework/AzCore/AzCore/std/containers/ring_buffer.h
  Code/Framework/AzCore/AzCore/std/utils.h
  Gems/LyShine/Code/Editor/HierarchyMenu.cpp
Labels: review-required

#2877 Editor code: tidy up BOOLs,NULLs and overrides pt6.
  Code/Editor/LayoutWnd.h
  Code/Editor/LevelInfo.cpp
  Code/Editor/LogFile.cpp
  Code/Editor/MainWindow.cpp
  Code/Editor/NewLevelDialog.cpp
  Code/Editor/NewTerrainDialog.cpp
  Code/Editor/Plugin.cpp
  Code/Editor/PluginManager.cpp
  Code/Editor/PythonEditorFuncs.cpp
  Code/Editor/ResizeResolutionDialog.cpp
  Code/Editor/ResourceSelectorHost.cpp
  Code/Editor/SelectEAXPresetDlg.cpp
  Code/Editor/Settings.cpp
  Code/Editor/SettingsManager.cpp
  Code/Editor/SettingsManagerDialog.cpp
  Code/Editor/StartupLogoDialog.cpp
  Code/Editor/StringDlg.h
  Code/Editor/ToolBox.cpp
  Code/Editor/ToolBox.h
  Code/Editor/ToolsConfigPage.cpp
  Code/Editor/UIEnumsDatabase.cpp
  Code/Editor/UndoDropDown.cpp
  Code/Editor/ViewManager.cpp
  Code/Editor/ViewManager.h
  Code/Editor/ViewPane.cpp
  Code/Editor/Viewport.cpp
  Code/Editor/Viewport.h
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/WipFeatureManager.cpp
  Code/Editor/WipFeatureManager.h
  Code/Editor/WipFeaturesDlg.cpp
  Code/Editor/WipFeaturesDlg.h
Labels: review-required

#2875 Editor code: tidy up BOOLs,NULLs and overrides pt4.
  Code/Editor/Undo/Undo.cpp
  Code/Editor/Undo/Undo.h
  Code/Editor/Util/3DConnexionDriver.cpp
  Code/Editor/Util/DynamicArray2D.cpp
  Code/Editor/Util/EditorUtils.cpp
  Code/Editor/Util/EditorUtils.h
  Code/Editor/Util/FileChangeMonitor.cpp
  Code/Editor/Util/FileChangeMonitor.h
  Code/Editor/Util/FileEnum.cpp
  Code/Editor/Util/FileUtil.cpp
  Code/Editor/Util/FileUtil.h
  Code/Editor/Util/FileUtil_impl.h
  Code/Editor/Util/GdiUtil.h
  Code/Editor/Util/IXmlHistoryManager.h
  Code/Editor/Util/ImageASC.cpp
  Code/Editor/Util/ImageGif.cpp
  Code/Editor/Util/ImageTIF.cpp
  Code/Editor/Util/ImageUtil.cpp
  Code/Editor/Util/IndexedFiles.cpp
  Code/Editor/Util/IndexedFiles.h
  Code/Editor/Util/KDTree.cpp
  Code/Editor/Util/Math.h
  Code/Editor/Util/MemoryBlock.cpp
  Code/Editor/Util/NamedData.cpp
  Code/Editor/Util/PakFile.cpp
  Code/Editor/Util/PathUtil.cpp
  Code/Editor/Util/PathUtil.h
  Code/Editor/Util/StringHelpers.cpp
  Code/Editor/Util/UIEnumerations.cpp
  Code/Editor/Util/Variable.cpp
  Code/Editor/Util/Variable.h
  Code/Editor/Util/VariablePropertyType.cpp
  Code/Editor/Util/XmlHistoryManager.cpp
  Code/Editor/Util/XmlHistoryManager.h
  Code/Editor/Util/XmlTemplate.cpp
  Code/Editor/Util/bitarray.h
Labels: review-required

#2815 Add initial TaskGraph prototype
  Code/Framework/AzCore/AzCore/Task/Internal/Task.cpp
  Code/Framework/AzCore/AzCore/Task/Internal/Task.h
  Code/Framework/AzCore/AzCore/Task/Internal/Task.inl
  Code/Framework/AzCore/AzCore/Task/Internal/TaskConfig.h
  Code/Framework/AzCore/AzCore/Task/TaskDescriptor.h
  Code/Framework/AzCore/AzCore/Task/TaskExecutor.cpp
  Code/Framework/AzCore/AzCore/Task/TaskExecutor.h
  Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
  Code/Framework/AzCore/AzCore/Task/TaskGraph.h
  Code/Framework/AzCore/AzCore/Task/TaskGraph.inl
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/AzCore/std/parallel/thread.h
  Code/Framework/AzCore/Tests/TaskTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: api-review, sig/core

#2729 Fix a crash when reloading AudioControlEditor controls
  Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControl.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControl.h
  Gems/AudioSystem/Code/Source/Editor/AudioControlsLoader.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsWriter.cpp
Labels: feature/audio, kind/bug, pr-ready-to-merge

#2945 Fix issues with audio localization bank switching
  Code/Legacy/CrySystem/SystemInit.cpp
  Gems/AudioEngineWwise/Code/Source/Editor/AudioWwiseLoader.cpp
  Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
Labels: feature/audio, kind/bug, pr-ready-to-merge

#2771 Reduce size of AllocationInfo struct to 64 bytes ( was 72 )
  Code/Framework/AzCore/AzCore/Memory/AllocationRecords.h
Labels: review-required

#2876 Editor code: tidy up BOOLs,NULLs and overrides pt5.
  Code/Editor/AboutDialog.cpp
  Code/Editor/AnimationContext.cpp
  Code/Editor/BaseLibrary.cpp
  Code/Editor/BaseLibraryItem.cpp
  Code/Editor/BaseLibraryManager.cpp
  Code/Editor/CheckOutDialog.h
  Code/Editor/ConfigGroup.cpp
  Code/Editor/ConfigGroup.h
  Code/Editor/ControlMRU.cpp
  Code/Editor/CrtDebug.cpp
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/CryEditDoc.cpp
  Code/Editor/CryEditDoc.h
  Code/Editor/CryEditPy.cpp
  Code/Editor/CustomAspectRatioDlg.cpp
  Code/Editor/CustomResolutionDlg.cpp
  Code/Editor/CustomizeKeyboardDialog.cpp
  Code/Editor/EditorDefs.h
  Code/Editor/EditorFileMonitor.cpp
  Code/Editor/EditorFileMonitor.h
  Code/Editor/EditorPanelUtils.cpp
  Code/Editor/EditorPreferencesDialog.cpp
  Code/Editor/ErrorReport.cpp
  Code/Editor/ErrorReportDialog.cpp
  Code/Editor/ErrorReportTableModel.cpp
  Code/Editor/GameEngine.cpp
  Code/Editor/GameExporter.cpp
  Code/Editor/GenericSelectItemDialog.cpp
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/IconManager.cpp
  Code/Editor/LayoutConfigDialog.cpp
  Code/Editor/LayoutWnd.cpp
Labels: review-required

#2943 [Mac] Building and running game projects from an SDK
  CMakeLists.txt
  Code/Editor/Platform/Mac/editor_mac.cmake
  Code/Editor/Platform/Mac/gui_info.plist
  Code/Editor/Platform/Mac/main_dummy.cpp
  Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.h
  Code/Framework/AzCore/Platform/Common/Apple/AzCore/std/time_Apple.cpp
  Code/Framework/AzFramework/Platform/Mac/AzFramework/Process/ProcessWatcher_Mac.cpp
  Code/Tools/AssetProcessor/Platform/Mac/assetprocessor_mac.cmake
  Code/Tools/AssetProcessor/Platform/Mac/gui_info.plist
  Code/Tools/AssetProcessor/Platform/Mac/main_dummy.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Gems/Atom/RHI/Code/Source/RHI.Edit/Utils.cpp
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Mac/Install_mac.cmake
  cmake/Platform/Mac/LYWrappers_mac.cmake
Labels: pr-ready-to-merge

#2985 Replace MCore::SmallArray usage with AZStd::vector
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/MetaData.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/NodeGroupCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/Exporters/ExporterLib/Exporter/NodeExport.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.h
  Gems/EMotionFX/Code/EMotionFX/Source/ActorInstance.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/NodeGroup.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/NodeGroup.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeGroups/NodeGroupManagementWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeGroups/NodeGroupWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeWindow/ActorInfo.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeWindow/NodeGroupInfo.cpp
  Gems/EMotionFX/Code/MCore/Source/SmallArray.h
  Gems/EMotionFX/Code/MCore/mcore_files.cmake
Labels: pr-ready-to-merge

#2773 Migrated legacy multiplayer per entity analytics over to O3DE Multiplayer Gem
  Gems/Multiplayer/Code/CMakeLists.txt
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerDebug.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerStats.h
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugByteReporter.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugByteReporter.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugPerEntityReporter.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugPerEntityReporter.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicator.cpp
  Gems/Multiplayer/Code/multiplayer_debug_files.cmake
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/network

#3014 Replace `MCore::AlignedArray` with `AZStd::vector`
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.h
  Gems/EMotionFX/Code/MCore/Source/AlignedArray.h
  Gems/EMotionFX/Code/MCore/mcore_files.cmake
Labels: pr-ready-to-merge

#3046 Fix code that trips -Wsign-compare
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNewSequenceDialog.cpp
Labels: pr-ready-to-merge

#3045 Update EMotionFX layouts to deal with changed QObject names
  Gems/EMotionFX/Assets/Editor/Layouts/AnimGraph.layout
  Gems/EMotionFX/Assets/Editor/Layouts/SimulatedObjects.layout
Labels: pr-ready-to-merge

#3048 [EMotionFX] Avoid using invalid Aabbs
  Gems/EMotionFX/Code/EMotionFX/Source/ActorInstance.cpp
Labels: pr-ready-to-merge

#2969 Typo fix in duplicate project progress window
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
Labels: pr-ready-to-merge

#2924 Profiler: Runtime region name support
  Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfiler.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/CpuProfilerImpl.h
  Gems/Atom/RHI/Code/Source/RHI/CpuProfilerImpl.cpp
Labels: sig/presentation

#3050 Remove ResourceSelectorHost and clean up/refactor related bits
  Code/Editor/Controls/ReflectedPropertyControl/PropertyCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/PropertyGenericCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/PropertyGenericCtrl.h
  Code/Editor/Controls/ReflectedPropertyControl/PropertyResourceCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertiesPanel.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertiesPanel.h
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyItem.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVar.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVar.h
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.h
  Code/Editor/EditorPanelUtils.cpp
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/IEditorPanelUtils.h
  Code/Editor/Include/IResourceSelectorHost.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ComponentEntityEditorPlugin.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Editor/ResourceSelectorHost.cpp
  Code/Editor/ResourceSelectorHost.h
  Code/Editor/Util/Variable.cpp
  Code/Editor/Util/Variable.h
  Code/Editor/Util/VariablePropertyType.cpp
  Code/Editor/Util/VariablePropertyType.h
  Code/Editor/editor_lib_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAudioCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAudioCtrl.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAudioCtrlTypes.h
  Gems/AudioSystem/Code/Source/Editor/ATLControlsResourceDialog.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorPlugin.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorPlugin.h
  Gems/AudioSystem/Code/Source/Editor/AudioResourceSelectors.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioResourceSelectors.h
Labels: feature/audio, kind/cleanup, pr-ready-to-merge

#3283 Audio legacy cleanup - Move global functions to be handled by AudioSystemComponent
  Code/Editor/CryEditDoc.cpp
  Code/Editor/MainWindow.cpp
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/ViewportTitleDlg.h
  Code/Legacy/CryCommon/IViewSystem.h
  Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
  Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp
  Code/Legacy/CrySystem/System.cpp
  Code/Legacy/CrySystem/ViewSystem/DebugCamera.cpp
  Code/Legacy/CrySystem/ViewSystem/View.cpp
  Code/Legacy/CrySystem/ViewSystem/View.h
  Code/Legacy/CrySystem/ViewSystem/ViewSystem.cpp
  Code/Legacy/CrySystem/ViewSystem/ViewSystem.h
  Gems/LmbrCentral/Code/Source/Audio/AudioSystemComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/AudioSystemComponent.h
  Gems/LmbrCentral/Code/include/LmbrCentral/Audio/AudioSystemComponentBus.h
  Gems/LyShine/Code/Source/Animation/AzEntityNode.cpp
Labels: feature/audio, kind/cleanup, pr-ready-to-merge

#3304 Pressing Enter/Return Key While File Browse Widget is Focused Opens File Browser
  Code/Tools/ProjectManager/Source/FormBrowseEditWidget.cpp
  Code/Tools/ProjectManager/Source/FormBrowseEditWidget.h
  Code/Tools/ProjectManager/Source/FormFolderBrowseEditWidget.cpp
Labels: pr-ready-to-merge

#3327 Added the ability to look up a Net Entity ID for a given AZ Entity ID
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/INetworkEntityManager.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.inl
Labels: sig/network

#2639 Ensure network autonomy gets set before entity activation
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/INetworkEntityManager.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
Labels: sig/network

#3082 Fix Multiplayer AutoComponent Delete Incomplete Type Compile Error
  Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#3310 Fix type error with Server to Authority RPC generation
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Source/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#3364 Fixes AZ_PROFILE markers that failed release build
  Gems/AudioSystem/Code/Source/Engine/AudioInternalInterfaces.h
  Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp
Labels: feature/audio, pr-ready-to-merge, kind/nightlybuildfailure

#3370 Fix rpaths during o3de sdk install on Linux
  cmake/Platform/Linux/Install_linux.cmake
Labels: kind/task, feature/sdk

#3389 Improves Gem Catalog Search, Gem Display Names now used in Gem Catalog
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogHeaderWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemItemDelegate.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemRequirementDelegate.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemSortFilterProxyModel.cpp
Labels: pr-ready-to-merge

#3125 Corrected audio component links to documentation
  Gems/LmbrCentral/Code/Source/Audio/AudioProxyComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioAreaEnvironmentComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioEnvironmentComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioListenerComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioMultiPositionComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioPreloadComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioRtpcComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioSwitchComponent.cpp
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioTriggerComponent.cpp
Labels: pr-ready-to-merge

#3411 Added a helper function for constructing CollisionGroup from CollisionGroups::Id. Removed remaining touch bending related code
  Code/Framework/AzFramework/AzFramework/Physics/Collision/CollisionGroups.cpp
  Code/Framework/AzFramework/AzFramework/Physics/Collision/CollisionGroups.h
  Code/Framework/AzFramework/AzFramework/Physics/Collision/CollisionLayers.h
  Gems/PhysX/Code/Include/PhysX/UserDataTypes.h
  Gems/PhysX/Code/Include/PhysX/UserDataTypes.inl
Labels: feature/physics

#3325 Add linux equivalents for all the places that enumerate platforms
  Code/Framework/AzCore/AzCore/PlatformId/PlatformDefaults.cpp
  Code/Framework/AzCore/AzCore/PlatformId/PlatformDefaults.h
  Code/Framework/AzFramework/Tests/PlatformHelper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.h
  Code/Framework/AzToolsFramework/Tests/AssetFileInfoListComparison.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/testdata/config_regular/AssetProcessorPlatformConfig.setreg
  Code/Tools/AssetProcessor/testdata/config_regular_platform_scanfolder/AssetProcessorPlatformConfig.setreg
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp
  Registry/AssetProcessorPlatformConfig.setreg
  Registry/bootstrap.setreg
  scripts/build/Platform/Linux/build_config.json
Labels: pr-ready-to-merge

#3434 Move packet dispatch to return an enum that includes a pending option
  Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPacketDispatcher_Header.jinja
  Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPacketDispatcher_Inline.jinja
  Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/IConnectionListener.h
  Code/Framework/AzNetworking/AzNetworking/PacketLayer/IPacketHeader.h
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.cpp
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpConnection.h
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpFragmentQueue.cpp
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpFragmentQueue.h
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
  Code/Framework/AzNetworking/Tests/TcpTransport/TcpTransportTests.cpp
  Code/Framework/AzNetworking/Tests/UdpTransport/UdpTransportTests.cpp
  Gems/Multiplayer/Code/Source/AutoGen/Multiplayer.AutoPackets.xml
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Labels: sig/network

#3514 Create config files automatically and UX style updates
  Code/Editor/MainWindow.qrc
  Code/Editor/res/error_report_helper.svg
  Code/Editor/res/o3de_application_reverse.svg
  Gems/AWSCore/Code/Include/Private/ResourceMapping/AWSResourceMappingConstants.h
  Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingManagerTest.cpp
  Gems/AWSCore/Code/Tools/ResourceMappingTool/controller/view_edit_controller.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/manager/view_manager.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/model/error_messages.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/model/notification_label_text.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/model/view_size_constants.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/style/base_style_sheet.qss
  Gems/AWSCore/Code/Tools/ResourceMappingTool/style/editormainwindow_resources.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/controller/test_error_controller.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/controller/test_view_edit_controller.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_json_utils.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/json_utils.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/view/common_view_components.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/view/error_page.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/view/view_edit_page.py
  Templates/DefaultProject/Template/Config/default_aws_resource_mappings.json
  Templates/DefaultProject/Template/Registry/awscoreconfiguration.setreg
  Templates/DefaultProject/template.json
Labels: sig/ui-ux, status/ux-approved
