Repository o3de/o3de, pull requests merged in 2022-07, with the labels that each got.

#10466 Fixed OIIO include warning as compile error on nightly build
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
Labels: sig/content

#10331 remove legacy camera from EmotionFX
  Gems/EMotionFX/Code/CMakeLists.txt
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/Camera.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/Camera.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/Camera.inl
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/FirstPersonCamera.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/FirstPersonCamera.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/LookAtCamera.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/LookAtCamera.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/MCommonConfig.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/OrbitCamera.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/OrbitCamera.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/OrthographicCamera.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/OrthographicCamera.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/rendering_files.cmake
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/EMStudioPlugin.h
Labels: feature/animation, sig/simulation

#10322 remove Material and StandardMaterial from EmotionFX
  Gems/EMotionFX/Code/EMotionFX/Exporters/ExporterLib/Exporter/Exporter.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.h
  Gems/EMotionFX/Code/EMotionFX/Source/Material.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Material.h
  Gems/EMotionFX/Code/EMotionFX/Source/Mesh.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Node.h
  Gems/EMotionFX/Code/EMotionFX/Source/StandardMaterial.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/StandardMaterial.h
  Gems/EMotionFX/Code/EMotionFX/Source/SubMesh.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/SubMesh.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeWindow/SubMeshInfo.cpp
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
  Gems/EMotionFX/Code/Tests/AutoSkeletonLODTests.cpp
  Gems/EMotionFX/Code/Tests/TestAssetCode/MeshFactory.cpp
  Gems/EMotionFX/Code/Tests/UI/LODSkinnedMeshTests.cpp
Labels: feature/animation, sig/simulation

#10465 Fixed Gradient Baker not updating its dependency monitor when the configuration changes
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.h
Labels: sig/content

#10306 [LYN-13312] Asset Processor - Intermediate Assets - Auto test for unchanged products
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
Labels: sig/content

#10486 Motion Matching: Min-max scaler for feature normalization
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.cpp
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.h
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/FeaturePosition.cpp
  Gems/MotionMatching/Code/Source/FeaturePosition.h
  Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
  Gems/MotionMatching/Code/Source/FeatureTrajectory.h
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureVelocity.h
  Gems/MotionMatching/Code/Source/MotionMatchingData.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingData.h
  Gems/MotionMatching/Code/Source/MotionMatchingEditorSystemComponent.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
Labels: feature/animation, sig/simulation

#10401 Send the client disconnect signal on both of client and server
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
  Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
  Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_Client.names
  Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_ClientServer.names
  Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_DedicatedServer.names
  Gems/ScriptCanvas/Assets/TranslationAssets/Properties/MultiplayerAgentType_Uninitialized.names
Labels: sig/network

#10496 Fix an issue where the build for a project with AWSMetrics gem enabled may fail because of missing AWSCore headers
  Gems/AWSMetrics/Code/Include/MetricsAttribute.h
  Gems/AWSMetrics/Code/Source/MetricsAttribute.cpp
  Gems/AWSMetrics/Code/Source/MetricsEvent.cpp
  Gems/AWSMetrics/Code/Tests/MetricsAttributeTest.cpp
  Gems/AWSMetrics/Code/Tests/MetricsEventTest.cpp
  Gems/AWSMetrics/Code/Tests/MetricsQueueTest.cpp
Labels: sig/network

#10520 bugfix: correctly show memory usage in linux
  Code/Editor/ProcessInfo.cpp
Labels: platform/linux, kind/bug, sig/platform

#10473 feat: improve functionality of Vector3GizmoParameterEditor
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.h
Labels: feature/animation, sig/simulation

#10214 Fixes several spurious warnings that occur in the Asset Processor
  Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
  Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp
  Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.cpp
  Code/Framework/AzFramework/AzFramework/Process/ProcessCommunicatorTracePrinter.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/FilteredSearchWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/StyledTracePrintFLogPanel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/StyledTracePrintFLogPanel.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeModel.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
  Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/content

#10525 Asset Processor - Update test_validateDirectPreloadDependency_Found in asset_processor_batch_dependency_tests.py [LYN-11477]
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_direct_preload_dependency/testa.auto_test_input
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_direct_preload_dependency/testb.auto_test_input
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/testa.auto_test_input
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/testb.auto_test_input
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/testc.auto_test_input
  Gems/TestAssetBuilder/Code/Source/Builder/TestDependencyBuilderComponent.cpp
  Gems/TestAssetBuilder/Code/Source/Builder/TestDependencyBuilderComponent.h
  Gems/TestAssetBuilder/Code/Source/TestAssetBuilderModule.cpp
  Gems/TestAssetBuilder/Code/testassetbuilder_files.cmake
Labels: feature/asset-pipeline, sig/content

#10507 Fixes gem queue download issue in Gem Catalog ( #9685)
  Code/Tools/ProjectManager/Source/DownloadController.cpp
  Code/Tools/ProjectManager/Source/DownloadController.h
Labels: sig/content, feature/project-manager

#10487 Proposed fix for Issue #10479. Where downloading a gem doesn't work a…
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.h
Labels: sig/content, feature/project-manager

#10562 Fixed opportunistic connections not working in Landscape Canvas
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Labels: sig/content

#10456 Prefab/Fix the missing dialog when saving prefab to file
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.h
Labels: sig/content

#10482 [Terrain] Fix the clipmap rendering when macro normal map is not set
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
Labels: feature/terrain

#10497 [Terrain] Disable clipmap manager when clipmap is not enabled
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Labels: feature/terrain

#10546 Disable the terrain feature processor for anim editor
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
Labels: feature/animation

#10529 Prism/fix gem catalog text 7223
  Code/Tools/ProjectManager/Resources/ProjectManager.qrc
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Resources/Refresh_Hover.svg
  Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemFilterWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemListHeaderWidget.cpp
  Code/Tools/ProjectManager/Source/GemCatalog/GemListHeaderWidget.h
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
Labels: feature/project-manager

#9549 updated logging when asset builders fail to start to have a bit more details
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.h
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
Labels: sig/content

#9824 bugfix: limit the size of the pool to MaxUnboundedArrayDescriptors (GHI-9812)
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
Labels: sig/graphics-audio

#10561 Motion Matching: Added angular joint velocity feature
  Gems/MotionMatching/Code/Source/FeatureAngularVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureAngularVelocity.h
  Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
  Gems/MotionMatching/Code/motionmatching_files.cmake
Labels: feature/animation, sig/simulation

#3107 LYN-3803 Python Scripts - Edit option in context menu does not seem to work
  Code/Editor/EditorPreferencesDialog.cpp
  Code/Editor/EditorPreferencesDialog.h
  Code/Editor/EditorPreferencesPageFiles.cpp
  Code/Editor/Include/IFileUtil.h
  Code/Editor/Platform/Linux/platform_linux_files.cmake
  Code/Editor/Platform/Mac/platform_mac_files.cmake
  Code/Editor/Platform/Windows/platform_windows_files.cmake
  Code/Editor/Util/FileUtil.cpp
  Code/Editor/Util/FileUtil.h
  Code/Editor/Util/FileUtil_Common.cpp
  Code/Editor/Util/FileUtil_Common.h
  Code/Editor/Util/Platform/Linux/FileUtil_Linux.cpp
  Code/Editor/Util/Platform/Mac/FileUtil_Mac.cpp
  Code/Editor/Util/Platform/Windows/FileUtil_Windows.cpp
  Code/Editor/editor_lib_files.cmake
  Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ExeSelectPropertyHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ExeSelectPropertyHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content

#10544 Display Mapper component unable to set properties from python
  Gems/Atom/Feature/Common/Code/3rdParty/ACES/ACES/Aces.h
  Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperConfigurationDescriptor.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettings.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/DisplayMapper/EditorDisplayMapperComponent.cpp
Labels: sig/graphics-audio, sig/testing

#10538 Adding Multiplayer Client Connection Status to the Viewport
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerConnectionViewportMessage.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerEditorConnectionViewportMessage.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugModule.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorGem.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/multiplayer_debug_files.cmake
  Gems/Multiplayer/Code/multiplayer_editor_shared_files.cmake
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/network

#10622 Fixes the following lua script context error:
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettings.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettings.cpp
Labels: sig/graphics-audio

#10091 Fix viewport responsiveness when interacting in the Viewport
  Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
  Code/Framework/AzFramework/AzFramework/Input/Devices/Keyboard/InputDeviceKeyboard.h
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
  Code/Framework/AzFramework/AzFramework/Viewport/ViewportControllerList.cpp
  Code/Framework/AzFramework/Tests/CameraInputTests.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockViewportInteractionRequests.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframeworktestcommon_files.cmake
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
Labels: sig/content, sig/core, sig/graphics-audio

#10605 chore(EMotionFX): remove m_layerIDsToIgnore from Importer
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.h
Labels: feature/animation, sig/simulation

#10587 Fix for test script ScriptEvents_ReturnSetType_Successfully
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_ReturnSetType_Successfully.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
  AutomatedTesting/ScriptCanvas/T92569006_ScriptCanvas.scriptcanvas
Labels: feature/scripting, sig/content

#10595 Changing error on pass addition to warning until we can avoid...
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
Labels: feature/graphics/rpi

#10565 {lyn13480} Adding Shared Cache tab to the Asset Processor
  AutomatedTesting/Registry/asset_cache_server_settings.setreg
  Code/Tools/AssetProcessor/assetprocessor_gui_files.cmake
  Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.cpp
  Code/Tools/AssetProcessor/native/ui/CacheServerData.cpp
  Code/Tools/AssetProcessor/native/ui/CacheServerData.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/unittests/AssetCacheServerUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/AssetServerHandler.cpp
  Code/Tools/AssetProcessor/native/utilities/AssetServerHandler.h
  Code/Tools/AssetProcessor/native/utilities/AssetUtilEBusHelper.h
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
Labels: sig/content

#10705 bugfix(graphics): fix winding for debug sphere to render faces outward (GHI-6773)
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/mesh

#10500 Detailed timeout messages.
  Tools/LyTestTools/ly_test_tools/launchers/exceptions.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
  Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
Labels: sig/testing

#10688 Motion Matching: .CSV serializers for skeletal poses, query vectors and best matching frames
  Gems/MotionMatching/Code/Source/CsvSerializers.cpp
  Gems/MotionMatching/Code/Source/CsvSerializers.h
  Gems/MotionMatching/Code/Source/FeatureAngularVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureMatrix.cpp
  Gems/MotionMatching/Code/Source/FeatureSchema.cpp
  Gems/MotionMatching/Code/Source/FeatureSchema.h
  Gems/MotionMatching/Code/motionmatching_files.cmake
Labels: feature/animation, sig/simulation

#10584 Optimized gradient baker by using single GetValues call instead of many GetValue
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
Labels: sig/content

#7363 Remove -Wno-unused-but-set-variable suppression for GCC
  Code/Editor/Controls/TimelineCtrl.cpp
  Code/Editor/IEditorImpl.cpp
  Code/Editor/RenderHelpers/AxisHelperShared.inl
  Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
  Code/Framework/AzCore/AzCore/DOM/DomUtils.h
  Code/Framework/AzCore/AzCore/std/ranges/subrange.h
  Code/Framework/AzCore/Tests/Math/RayTests.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/LinearManipulator.cpp
  Code/Framework/AzToolsFramework/Tests/PropertyTreeEditorTests.cpp
  Code/Framework/AzToolsFramework/Tests/TransformComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/Normalize.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/ProjectedShadowmapsPass.cpp
  Gems/Atom/Feature/Common/Code/Tests/SparseVectorTests.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFootIKNode.cpp
  Gems/EMotionFX/Code/Tests/Prefabs/LeftArmSkeleton.h
  Gems/GradientSignal/Code/CMakeLists.txt
  Gems/GradientSignal/Code/Source/Platform/Common/Clang/gradient_signal_editor_clang.cmake
  Gems/GradientSignal/Code/Source/Platform/Common/GCC/gradient_signal_editor_gcc.cmake
  Gems/GradientSignal/Code/Source/Platform/Common/MSVC/gradient_signal_editor_msvc.cmake
  Gems/LmbrCentral/Code/Source/Ai/NavigationComponent.cpp
  Gems/LyShine/Code/Editor/Animation/Controls/UiTimelineCtrl.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewDopeSheetBase.cpp
  Gems/LyShine/Code/Source/LyShineDebug.cpp
  Gems/MotionMatching/Code/Source/FeaturePosition.cpp
  Gems/PhysX/Code/Editor/DebugDraw.cpp
  Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsSubComponentModeRotation.cpp
  Gems/PhysX/Code/Source/Utils.cpp
  cmake/Platform/Common/GCC/Configurations_gcc.cmake
Labels: sig/build, sig/platform

#10470 P1 tests added for PostFX Layer, PostFX Gradient and PostFX Shape
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXGradientWeightModifierAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXLayerAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFxShapeWeightModifierAdded.py
Labels: sig/graphics-audio

#10624 Asset Processor: Measure, show, store, and load analysis job (CreateJob) duration metrics
  Code/Tools/AssetProcessor/assetprocessor_gui_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.cpp
  Code/Tools/AssetProcessor/native/ui/AssetTreeItem.cpp
  Code/Tools/AssetProcessor/native/ui/AssetTreeItem.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeFilterModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeFilterModel.h
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeItemData.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeItemData.h
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.h
Labels: sig/content

#10729 Fix for test script ScriptEvents_DefaultSendReceiveSuccessful
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_Default_SendReceiveSuccessfully.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_ReturnSetType_Successfully.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
  AutomatedTesting/ScriptCanvas/T92567320.scriptcanvas
Labels: feature/scripting, sig/content

#10481 [Terrain] Expose clipmap config to editor
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Labels: feature/terrain

#10744 Motion Matching: Optimize memory usage in KD-tree + use median instead of average
  Code/Framework/AzCore/AzCore/std/algorithm.h
  Gems/EMotionFX/Code/EMotionFX/Source/TransformData.h
  Gems/MotionMatching/Code/Source/KdTree.cpp
  Gems/MotionMatching/Code/Source/KdTree.h
  Gems/MotionMatching/Code/Source/MotionMatchingEditorSystemComponent.cpp
Labels: feature/animation, sig/simulation

#10731 Fix for test script ScriptEvents_HappyPath_SendReceiveAcrossMultiple
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_HappyPath_SendReceiveAcrossMultiple.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/ScriptCanvas/T92567321A.scriptcanvas
  AutomatedTesting/ScriptCanvas/T92567321B.scriptcanvas
Labels: feature/scripting, sig/content

#7333 Remove -Wno-unused-variable suppression
  Code/Editor/EditorPreferencesPageGeneral.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ComponentEntityEditorPlugin.cpp
  Code/Editor/Plugins/ProjectSettingsTool/PlatformSettings_common.h
  Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemBus.h
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessWatcher_Linux.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/PushButton.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ToolButton.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/VectorInput.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Slice/SliceUtilities.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyQTConstants.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiDisplayLayout.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestDomUtils.h
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/SceneAPI/SceneCore/DataTypes/Rules/IMeshAdvancedRule.h
  Gems/AWSGameLift/Code/AWSGameLiftCommon/Source/AWSGameLiftSessionConstants.h
  Gems/AWSMetrics/Code/Source/MetricsEvent.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/DiffuseGlobalIllumination/DiffuseProbeGridFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/PostFxLayerCategoriesConstants.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderCommonTypes.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/EditorCubeMapRenderer.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ShapeWeightModifier/ShapeWeightModifierComponentController.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackSystemComponent.cpp
  Gems/Camera/Code/Source/ViewportCameraSelectorWindow.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MorphTargetRule.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h
  Gems/LmbrCentral/Code/Tests/SplineComponentTests.cpp
  Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ReferenceShapeComponentBus.h
  Gems/LyShine/Code/Source/UiTextComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicator.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityAuthorityTracker.cpp
  Gems/PhysX/Code/Source/PhysXCharacters/Components/RagdollComponent.cpp
  Gems/PhysXDebug/Code/Source/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Data/DataRegistry.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/PrimitivesDeclarations.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/ScriptCanvasNodeRegistry.h
  Gems/ScriptCanvasDeveloper/Code/Editor/Include/ScriptCanvasDeveloperEditor/EditorAutomation/EditorAutomationModelIds.h
  Gems/ScriptEvents/Code/Source/ScriptEventsAssetRef.cpp
  Gems/Vegetation/Code/Include/Vegetation/Editor/EditorVegetationComponentTypeIds.h
  Gems/Vegetation/Code/Source/EmptyInstanceSpawner.cpp
  cmake/Platform/Common/GCC/Configurations_gcc.cmake
Labels: sig/build, sig/platform

#10786 Fixed native visualizers for the AZStd forward_list and fixed_list classes
  Code/Framework/AzCore/Platform/Common/VisualStudio/AzCore/Natvis/azcore.natvis
Labels: sig/core

#10777 Editorsv_print_server_logs to Turn On/Off Seeing Server Logs in the Editor Console
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network

#10733 Fix for test script ScriptCanvas_ScriptTwoComponents_InteractSuccesfully
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvas_TwoComponents_InteractSuccessfully.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/content

#10806 Fix bug template to remove mac os typo
  .github/ISSUE_TEMPLATE/bug_template.md
Labels: platform/macos

#10809 Asset Processor: CreateJob stat refresh fix
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.h
Labels: sig/content

#10703 Fixed bug in loading script and full texture support
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/utils.py
Labels: sig/content, sig/graphics-audio, feature/graphics/asset

#10784 Multiplayer IMGUI Option To Host and LoadLevel
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.h
Labels: sig/network

#10802 {lny13480} Updated Shared Cached interface based on feedback from UX
  Code/Tools/AssetProcessor/native/ui/CacheServerData.cpp
  Code/Tools/AssetProcessor/native/ui/CacheServerData.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qrc
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qss
  Code/Tools/AssetProcessor/native/ui/style/Browse.png
  Code/Tools/AssetProcessor/native/ui/style/Browse_on.png
Labels: sig/content

#10670 Adding C++17 deduction guides for AZStd container types
  Code/Framework/AzCore/AzCore/std/containers/deque.h
  Code/Framework/AzCore/AzCore/std/containers/forward_list.h
  Code/Framework/AzCore/AzCore/std/containers/list.h
  Code/Framework/AzCore/AzCore/std/containers/vector.h
  Code/Framework/AzCore/AzCore/std/function/function_template.h
  Code/Framework/AzCore/AzCore/std/smart_ptr/shared_ptr.h
  Code/Framework/AzCore/AzCore/std/string/regex.h
  Code/Framework/AzCore/AzCore/std/string/string.h
  Code/Framework/AzCore/AzCore/std/string/string_view.h
  Code/Framework/AzCore/AzCore/std/utils.h
  Code/Framework/AzCore/Tests/AZStd/DequeAndSimilar.cpp
  Code/Framework/AzCore/Tests/AZStd/FunctionalBasic.cpp
  Code/Framework/AzCore/Tests/AZStd/Lists.cpp
  Code/Framework/AzCore/Tests/AZStd/String.cpp
  Code/Framework/AzCore/Tests/AZStd/VectorAndArray.cpp
Labels: sig/core

#10780 Reflect MarkForRemoval and ClearAllEntities from appropriate net components
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#10867 Atom/shawtar/blender scene exporter
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/README.md
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/__init__.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/constants.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/fbx_exporter.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/o3de_utils.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/projects.json
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/ui.py
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/DCC/Blender/AddOns/SceneExporter/utils.py
Labels: sig/graphics-audio, feature/tech-art

#10810 Add the previous time
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/ShaderResourceGroups/DefaultSceneSrg.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Labels: sig/graphics-audio

#10886 Added unit tests for the Gradient Baker component
  Gems/GradientSignal/Code/CMakeLists.txt
  Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientBakerComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Source/GradientSignalEditorModule.cpp
  Gems/GradientSignal/Code/Tests/EditorGradientSignalBakerTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.h
  Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
  Gems/GradientSignal/Code/gradientsignal_editor_tests_files.cmake
Labels: sig/content

#10892 Fixed missing punctuation in PhysX Configuration label
  Gems/PhysX/Code/Editor/SettingsWidget.cpp
Labels: sig/content, sig/simulation

#10781 Add names to several ComponentMode components
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/EditorComponentModeBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/BoxComponentMode.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/BoxComponentMode.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponentMode.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponentMode.h
  Code/Framework/AzToolsFramework/Tests/ComponentModeTestDoubles.cpp
  Code/Framework/AzToolsFramework/Tests/ComponentModeTestDoubles.h
  Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.cpp
  Gems/LmbrCentral/Code/Source/Shape/EditorPolygonPrismShapeComponentMode.h
  Gems/LmbrCentral/Code/Source/Shape/EditorTubeShapeComponentMode.cpp
  Gems/LmbrCentral/Code/Source/Shape/EditorTubeShapeComponentMode.h
  Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentMode.cpp
  Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentMode.h
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.h
Labels: feature/whitebox, sig/content

#10856 {lyn13480} Asset Cache Server UX update
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qrc
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qss
  Code/Tools/AssetProcessor/native/ui/style/Delete.png
Labels: sig/content

#10576 Changed two properties parameters in Deferred Fog Component
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/ScreenSpace/DeferredFogComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/EditorDeferredFogComponent.cpp
Labels: sig/graphics-audio

#10872 Lyn 4551/lyn 4491: Add two new FBX tests
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/cubewithline.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/scenedebug/cubewithline.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/scenedebug/cubewithline.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/fbx_tests.py
Labels: sig/content

#10829 displaymapper null-render test update
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
Labels: sig/graphics-audio

#10846 Bug fix for updating nav mesh tiles when all physical colliders were removed within that tile's volume
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.cpp
  Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
Labels: sig/simulation

#10901 Fix Multiplayer Component Archetype Property Init
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
Labels: sig/network

#10772 Making ImageBuilder.settings a bit more readable, no functional changes
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
Labels: feature/graphics

#10769 Fixing crash with skinned meshes when baking reflection probes
  Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetComputePass.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshComputePass.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.h
Labels: feature/graphics, sig/graphics-audio

#10734 Fix for test script ScriptCanvas_ChangingAssets_ComponentStable
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvas_ChangingAssets_ComponentStable.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/content

#10848 Quality of life improvements for writing AutoComponents
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Common.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerController.h
  Gems/Multiplayer/Code/Source/Components/MultiplayerController.cpp
  Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.cpp
Labels: sig/network

#10770 Fixed parallax correction for OOBB reflection probes
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/LightingUtils.azsli
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli
Labels: feature/graphics

#10903 Motion Matching: Use target facing direction for strafing
  Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
Labels: feature/animation, sig/simulation

#10864 Fixed issue with rapid reloads eventually causing asset loads to get stuck
  Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline, sig/content

#10873 Add the Host IP Address to the Multiplayer Viewport Connection Status
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
Labels: sig/network

#10118 Using a multicontext version of glad to prepare for multi GPU support.
  Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Loader/FunctionLoader.h
  Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Loader/Glad/vulkan/vulkan.h
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Android/RHI/WSISurface_Android.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Linux/RHI/WSISurface_Linux.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/RHI/WSISurface_Windows.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Loader/FunctionLoader.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Loader/Glad/GladFunctionLoader.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Loader/Glad/GladFunctionLoader.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferMemory.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferMemoryPageAllocator.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferPoolResolver.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandQueueContext.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ComputePipeline.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSetLayout.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/GraphicsPipeline.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImagePoolResolver.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Memory.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/NullDescriptorManager.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Pipeline.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLayout.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Query.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/QueryPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Queue.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Sampler.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Semaphore.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderModule.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Vulkan.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Vulkan.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/WSISurface.cpp
  Gems/Atom/RHI/Vulkan/Code/atom_rhi_vulkan_glad_files.cmake
  Gems/Atom/RHI/Vulkan/External/glad/2.0.0-beta/include/glad/vulkan.h
Labels: sig/graphics-audio

#10863 Asset Processor: Builder tab UI change & metrics
  Code/Tools/AssetProcessor/assetprocessor_gui_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.h
  Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderData.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderData.h
  Code/Tools/AssetProcessor/native/ui/BuilderDataItem.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderDataItem.h
  Code/Tools/AssetProcessor/native/ui/BuilderInfoMetricsModel.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderInfoMetricsModel.h
  Code/Tools/AssetProcessor/native/ui/BuilderInfoPatternsModel.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderInfoPatternsModel.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
Labels: feature/asset-pipeline, sig/content

#10669 Fix GammaSRGB Display Mapper to output sRGB
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DisplayMapperSRGB.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DisplayMapperSRGB.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/DisplayMapper/DisplayMapperPass.h
  Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperPass.cpp
Labels: sig/graphics-audio

#10894 Update Physical Sky automation to P1
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PhysicalSkyAdded.py
Labels: sig/graphics-audio

#10946 Added GradientBakerRequestBus so we can expose the gradient baker to script
  Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientBakerComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientBakerRequestBus.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Tests/EditorGradientSignalBakerTests.cpp
  Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
Labels: sig/content

#10919 [LYN-14130] Asset Processor - Removed job grace period and fingerprint-changing wait
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
Labels: feature/asset-pipeline, sig/content

#10945 [Terrain]Add a checkbox to turn on clipmap
  Gems/Terrain/Assets/Passes/TerrainDebugPassRequest.azasset
  Gems/Terrain/Assets/Passes/TerrainParentPass.pass
  Gems/Terrain/Assets/Passes/TerrainPassRequest.azasset
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.h
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapDebugPass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Labels: feature/terrain

#10954 Fix the root motion extraction rotation problem
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.cpp
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderFlag.h
Labels: feature/animation
