Repository o3de/o3de, pull requests merged in 2022-06, with the labels that each got.

#9852 Use sanitized name in skin weight data
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.cpp
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.h
Labels: feature/animation

#9798 Material Canvas: Moving graph view class to Atom Tools Framework
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/GraphView/GraphView.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/GraphView/GraphViewConfig.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasUtil.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/MaterialCanvas/Code/materialcanvas_files.cmake
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#9778 [Terrain] Debug pass for terrain clipmaps
  Gems/Terrain/Assets/Passes/TerrainClipmapDebugPass.pass
  Gems/Terrain/Assets/Passes/TerrainDebugPassRequest.azasset
  Gems/Terrain/Assets/Passes/TerrainParentPass.pass
  Gems/Terrain/Assets/Passes/TerrainPassTemplates.azasset
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainClipmapDebugPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainClipmapDebugPass.shader
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Assets/seedList.seed
  Gems/Terrain/Code/Source/Components/TerrainSystemComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapDebugPass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapDebugPass.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/terrain_files.cmake
Labels: sig/graphics-audio, feature/terrain

#9753 Update Atom test code asset paths to be lowercase for Linux and Mac support.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GlobalSkylightIBLAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRiSkyboxAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_BasicLevelSetup.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_SpotLightScreenshotTest.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_ShaderAssetBuilder_RecompilesShaderAsChainOfDependenciesChanges.py
Labels: sig/graphics-audio

#9847 Enabled Debug Output in AP-GUI
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
Labels: sig/content

#9826 bugfix(Whitebox): Destroy Physics Collider when whitebox mesh is submitted (GHI-7819)
  Gems/WhiteBox/Code/Source/Components/EditorWhiteBoxColliderComponent.cpp
Labels: sig/content, sig/simulation

#9814 Fix for test script ScriptEvents_AllParamDatatypes_CreationSuccess
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_AllParamDatatypes_CreationSuccess.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/__init__.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/testing

#9844 SSAO null render P1 test expansion
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SSAOAdded.py
Labels: sig/graphics-audio

#9899 Handle the command list index in the Diffuse GI passes
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBlendDistancePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBlendIrradiancePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdatePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridClassificationPass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridPreparePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridQueryPass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingPass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRelocationPass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationPreparePass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationRayTracingPass.cpp
Labels: sig/graphics-audio

#9331 feat(WhiteBox): implement transform mode
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.h
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentModeBus.h
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentModeTypes.h
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.h
  Gems/WhiteBox/Code/whitebox_editor_supported_files.cmake
Labels: feature/whitebox, kind/feature, sig/content, status/needs-ux-approval

#9394 feat: add Ray and LineSegment to AZCore/Math
  Code/Framework/AzCore/AzCore/Math/LineSegment.cpp
  Code/Framework/AzCore/AzCore/Math/LineSegment.h
  Code/Framework/AzCore/AzCore/Math/Ray.cpp
  Code/Framework/AzCore/AzCore/Math/Ray.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/Math/LineSegmentTests.cpp
  Code/Framework/AzCore/Tests/Math/RayTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/core

#9816 {lyn13016} output scene manifest during scene building
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/pythonassetbuildertests.py
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.cpp
Labels: sig/content

#9786 Made clear error messages in Source File Relocator
  Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
Labels: sig/content

#9878 Fixing the lack of a dot at the end of SpawnedEntitiesList parameter tooltip
  AutomatedTesting/Levels/Navigation/NavigationSample/city_generator.scriptcanvas
  AutomatedTesting/ScriptCanvas/ScriptCanvas_SpawnEntityWithPhysComponents.scriptcanvas
  AutomatedTesting/ScriptCanvas/Spawnables/DespawnOnEntityDeactivate.scriptcanvas
  AutomatedTesting/ScriptCanvas/Spawnables/MultipleSpawnsFromSingleTicket.scriptcanvas
  AutomatedTesting/ScriptCanvas/Spawnables/NestedSpawnerSpawner.scriptcanvas
  AutomatedTesting/ScriptCanvas/Spawnables/SimpleNestedSpawn.scriptcanvas
  AutomatedTesting/ScriptCanvas/Spawnables/SimpleSpawnDespawn.scriptcanvas
  AutomatedTesting/ScriptCanvas/Spawnables/SimpleSpawnNoDespawn.scriptcanvas
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.ScriptCanvasNodeable.xml
Labels: sig/content, sig/testing

#9834 feature(EmotionFX): remove deprecated opengl render window
  Gems/EMotionFX/Code/CMakeLists.txt
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/PluginManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/Source/OpenGLRender/GLWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/Source/OpenGLRender/GLWidget.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/Source/OpenGLRender/OpenGLRenderPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/Source/OpenGLRender/OpenGLRenderPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/Source/RenderPluginsConfig.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/renderplugins_files.cmake
  Gems/EMotionFX/Code/Tests/ProvidesUI/Motions/MotionPlaybacksTests.cpp
  Gems/EMotionFX/Code/Tests/UI/PersistentPluginTests.cpp
  Gems/EMotionFX/Code/emotionfx_editor_tests_files.cmake
Labels: sig/simulation

#9881 EMotion FX: Unassigning the actor re-parents the entity to root level
  Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
Labels: feature/animation, sig/simulation

#9946 EMotion FX: Remove GFxFramework
  Gems/EMotionFX/Code/CMakeLists.txt
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
  Gems/EMotionFX/Code/Tests/ActorBuilderTests.cpp
Labels: feature/animation, sig/simulation

#9930 P0 Atom Hair component null render test
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HairAdded.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
Labels: sig/graphics-audio

#9749 Updated OpenImageIO usage to new packages
  Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/exr_to_3dl_azasset.py
  Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/initialize.py
  Gems/Atom/Utils/Code/Platform/Windows/platform_windows.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Platform/Windows/platform_windows.cmake
  Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/Tools/Dev/Windows/Setuo_copy_oiio.bat
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: sig/core, sig/graphics-audio

#9887 Asset Processor - Fixed issue with AP waiting forever for builder registration
  Code/Tools/AssetProcessor/native/utilities/ApplicationManager.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
  Code/Tools/AssetProcessor/native/utilities/AssetUtilEBusHelper.h
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.h
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.h
  Registry/AssetProcessorPlatformConfig.setreg
Labels: feature/asset-pipeline, sig/content

#9924 chore: minor improvement replace push_back with emplace_back EnumValues
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEnumComboBoxCtrl.hxx
Labels: sig/content

#9945 Material Component: Updated data file with names and tooltips for script canvas nodes
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/MaterialComponentRequestBus.names
Labels: feature/scripting, sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9681 Removing .network.spawnables from the ImGui level select menu. Adding…
  Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
Labels: sig/core, sig/network

#9981 Skipping Lua Spawnable and Editor Transform tests
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py
Labels: sig/content

#9752 Updated detection of 3rdParty system libraries
  cmake/Platform/Common/RuntimeDependencies_common.cmake
Labels: sig/build, sig/core

#9963 Material Component: Returns default property values when there are no overrides
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9941 P1 Grid component null render test
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GridAdded.py
Labels: sig/graphics-audio

#9901 Material Component: More explicit menu option names and links to open files in material editor
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9940 fix an issue that causes the animation imported incorrectly for blender animation
  Code/Tools/SceneAPI/SceneCore/Tests/Utilities/CoordinateSystemConverterTests.cpp
  Code/Tools/SceneAPI/SceneCore/scenecore_testing_files.cmake
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Motion/MotionDataBuilder.cpp
  Gems/EMotionFX/Code/Tests/CoordinateSystemConverterTests.cpp
Labels: feature/animation

#9874 Submit testing asset for animation
  AutomatedTesting/TestAssets/Animation/AlphabetP/P_Freeze_Transforms.fbx
  AutomatedTesting/TestAssets/Animation/AlphabetP/P_Freeze_Transforms_DotName.fbx
  AutomatedTesting/TestAssets/Animation/AlphabetP/P_No_Freeze_Transforms.fbx
  AutomatedTesting/TestAssets/Animation/AlphabetP/P_No_Freeze_Transforms_DotName.fbx
  AutomatedTesting/TestAssets/Animation/AlphabetP/Readme.txt
Labels: feature/animation

#10035 Material Component: temporarily reverting default material asset function to fix tests
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/materials

#9828 Add support for storing and restoring last known location for view bookmarks
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/CryEditDoc.cpp
  Code/Editor/EditorPreferencesPageFiles.cpp
  Code/Editor/EditorPreferencesPageFiles.h
  Code/Editor/EditorViewportCamera.h
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Editor/MainWindow.cpp
  Code/Editor/Settings.cpp
  Code/Editor/Settings.h
  Code/Framework/AzFramework/AzFramework/Entity/EntityOwnershipServiceBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkLoaderInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkSystemComponent.cpp
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewBookmarkTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ModularViewportCameraController.cpp
Labels: sig/content, feature/viewport

#9650 Multiplayer IMGui Option to Host and Launch Local Client
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#9985 Implemented gradient baking and added node to LC
  Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyFilePathCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyFilePathCtrl.h
  Gems/GradientSignal/Code/CMakeLists.txt
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.h
  Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/GradientBakerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/GradientBakerNode.h
  Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
  Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Labels: sig/content

#9558 Multiplayer Spawnable Alias Multiplayer Pipeline: Phase 1 of 2
  Code/Framework/AzFramework/AzFramework/Spawnable/Spawnable.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/Spawnable.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceEntityIdMapper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceEntityMapper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceSerializer.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EditorInfoRemover.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EntityIdPathMapperInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabCatchmentProcessor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabCatchmentProcessor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabProcessorContext.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabProcessorContext.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerConstants.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.h
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.h
  Gems/Multiplayer/Code/Source/Pipeline/NetworkSpawnableHolderComponent.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkSpawnableHolderComponent.h
  Gems/Multiplayer/Code/Tests/MainTools.cpp
  Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
  Gems/Multiplayer/Registry/prefab.tools.setreg
Labels: sig/content, sig/core, sig/network

#10043 Fix array texture preview crash
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/Utils.cpp
Labels: sig/graphics-audio

#10044 Some crash fixes
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/LuaMaterialFunctor.cpp
  Gems/LyShine/Code/Source/UiCanvasComponent.cpp
  Gems/LyShine/Code/Source/World/UiCanvasAssetRefComponent.cpp
Labels: sig/graphics-audio

#10050 Fix crash when binding swapchain to imported texture attachment
  Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/LookModificationTransformPass.cpp
Labels: sig/graphics-audio

#10088 Injecting cmake code to export external recast navigation targets for installers
  Gems/RecastNavigation/Code/CMakeLists.txt
  Gems/RecastNavigation/Code/Include/RecastNavigation/RecastHelpers.h
  Gems/RecastNavigation/Code/Include/RecastNavigation/RecastNavigationMeshBus.h
  Gems/RecastNavigation/Code/Include/RecastNavigation/RecastNavigationProviderBus.h
  Gems/RecastNavigation/Code/Include/RecastNavigation/RecastSmartPointer.h
  Gems/RecastNavigation/Code/Source/Components/DetourNavigationComponent.cpp
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationDebugDraw.h
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.h
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.h
  Gems/RecastNavigation/Code/Source/Misc/RecastProcessing.h
  Gems/RecastNavigation/Code/recastnavigation_api_files.cmake
  Gems/RecastNavigation/Code/recastnavigation_private_files.cmake
  cmake/Platform/Common/Install_common.cmake
Labels: sig/build, sig/simulation

#9965 {ly97798} fix to handle mixed path slashes for ACS
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCJobTest.cpp
Labels: sig/content

#10094 Material Component: Updated and renamed material and property override functions
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
  Gems/Atom/Feature/Common/Assets/Scripts/material_find_overrides_demo.lua
  Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.lua
  Gems/Atom/Feature/Common/Assets/Scripts/material_property_overrides_demo.py
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Material/MaterialAssignment.h
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasViewportContent.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorViewportContent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Editor/Scripts/Materials/assign_material_to_all_entities.py
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
  Gems/Blast/Code/Source/Editor/EditorBlastMeshDataComponent.cpp
  Gems/Blast/Code/Source/Family/ActorRenderManager.cpp
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/MaterialComponentRequestBus.names
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#10074 Add PhysX collider to the default level ground
  Assets/Editor/Prefabs/Default_Level.prefab
Labels: sig/content

#10129 hair gem shadow LOD start distance property remove trailing space
  Gems/AtomTressFX/External/Code/src/TressFX/TressFXSettings.cpp
Labels: sig/graphics-audio

#10052 Material: Fix Compile() when NeedsCompile() = false
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
Labels: sig/graphics-audio

#10092 Made gradient image output baking async
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.h
Labels: sig/content

#9967 Updating Depth of Field automation with P1 tests
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DepthOfFieldAdded.py
Labels: sig/graphics-audio

#10148 Fix assert when creating network prefab
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
Labels: sig/content, sig/network

#5635 Minor cleanup and improvements to multiplayer ImGui functionality
  Gems/ImGui/Code/Include/LYImGuiUtils/HistogramContainer.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugMultiplayerMetrics.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugMultiplayerMetrics.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugNetworkMetrics.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugNetworkMetrics.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.h
  Gems/Multiplayer/Code/multiplayer_debug_files.cmake
Labels: sig/network

#10132 Fix Lua IDE breakpoint stall and failure to register self as host
  Code/Framework/AzFramework/AzFramework/Script/ScriptRemoteDebugging.cpp
  Code/Framework/AzNetworking/AzNetworking/Framework/INetworking.h
  Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.cpp
  Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.h
  Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
  Code/Tools/LuaIDE/Source/StandaloneToolsApplication.cpp
Labels: sig/content, sig/network

#10153 Correct payload size calculations for compressed TCP and missing compressor
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp
  Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
Labels: sig/network

#10139 Fix lua script with empty data crashing the engine
  Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
Labels: feature/scripting, sig/content

#10155 chore(EmotionFX): remove OpenGL2 rendering logic
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/DepthOfField.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/Downsample.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/HBloom.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/HBlur.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/HSmartBlur.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/Line_PS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/Line_VS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/PostProcessing_VS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/RenderUtil_PS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/RenderUtil_VS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/SSDO.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/ShadowMap_PS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/ShadowMap_VS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/StandardMaterial_PS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/StandardMaterial_VS.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/VBloom.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/VBlur.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Shaders/VSmartBlur.glsl
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GBuffer.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GBuffer.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLActor.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLExtensions.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLExtensions.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLRenderUtil.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLRenderUtil.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLSLShader.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GLSLShader.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GraphicsManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/GraphicsManager.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/IndexBuffer.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/IndexBuffer.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/Material.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/Material.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/PostProcessShader.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/PostProcessShader.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/RenderGLConfig.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/RenderTexture.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/RenderTexture.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/Shader.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/ShaderCache.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/StandardMaterial.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/StandardMaterial.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/TextureCache.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/TextureCache.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/VertexBuffer.cpp
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/VertexBuffer.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/glactor.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/OpenGL2/Source/shadercache.h
  Gems/EMotionFX/Code/EMotionFX/Rendering/rendering_files.cmake
  Gems/EMotionFX/Code/Tests/UI/CanUseFileMenu.cpp
Labels: sig/simulation

#10081 Fixing wrong hyperlink for the Scene Settings
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
Labels: sig/content

#10141 Adopt BinPackArguments: false in .clang-format.
  .clang-format
Labels: sig/build, sig/core

#10053 ImageProcessing: expose some functions and allows in-memory processing
  Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageProcessingBus.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.h
Labels: sig/graphics-audio

#9983 Use TreeView to show product dependencies; adjust UI to show the tree
  Code/Tools/AssetProcessor/assetprocessor_gui_files.cmake
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.h
  Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.ui
  Code/Tools/AssetProcessor/native/ui/ProductAssetTreeItemData.cpp
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeDelegate.cpp
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeDelegate.h
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeItemData.cpp
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeItemData.h
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/ProductDependencyTreeModel.h
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qss
Labels: sig/content, sig/ui-ux

#10159 Android build shows C++ files progression.
  Code/Framework/AzCore/AzCore/Math/Geometry3DUtils.cpp
  Code/Framework/AzFramework/Platform/Android/AzFramework/Application/Application_Android.cpp
  Code/Tools/Android/ProjectBuilder/gradle.properties.in
  cmake/Tools/Platform/Android/android_support.py
Labels: sig/build

#10046 [Terrain] Clipmap polishing and bug fixes
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Tests/ClipmapBoundsTests.cpp
Labels: feature/terrain

#9935 {lyn12590} red coding the RC.EXE code from AP
  Code/Tools/AssetProcessor/Platform/Linux/AssetProcessor_Traits_Linux.h
  Code/Tools/AssetProcessor/Platform/Mac/AssetProcessor_Traits_Mac.h
  Code/Tools/AssetProcessor/Platform/Windows/AssetProcessor_Traits_Windows.h
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCCommon.h
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.h
  Code/Tools/AssetProcessor/native/tests/platformconfiguration/platformconfigurationtests.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCBuilderTest.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCBuilderTest.h
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/MockApplicationManager.cpp
  Code/Tools/AssetProcessor/native/unittests/PlatformConfigurationUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
Labels: sig/content

#10209 Rename inspector widget variables to be consistent across atom tools.
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h
Labels: feature/graphics/tools

#10193 Address exception during rebuilding a not fully active networked entity hierarchy
  Gems/Multiplayer/Code/Source/Components/NetworkHierarchyRootComponent.cpp
Labels: sig/network

#9984 Fix for test script Node_HappyPath_DuplicateNode
  AutomatedTesting/Gem/PythonTests/scripting/Node_HappyPath_DuplicateNode.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/testing

#9916 Atom/antonmic/pass debug fix
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystem.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassTree.cpp
Labels: feature/graphics/rpi

#10183 Added support for automatically registering enums with edit context
  Code/Framework/AzCore/AzCore/Preprocessor/Enum.h
  Code/Framework/AzCore/AzCore/Preprocessor/EnumReflectUtils.h
  Code/Framework/AzCore/AzCore/Serialization/EditContext.h
  Code/Framework/AzCore/Tests/EnumTests.cpp
Labels: sig/content, sig/core, sig/graphics-audio, feature/graphics/tools

#9800 Fixed a mis-named material property in the FBX/scene builder that was…
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialConverterSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialConverterSystemComponent.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialConverterBus.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
Labels: sig/graphics-audio

#10026 Fix for test script VariableManager_UnpinVariableType_Works
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/VariableManager_UnpinVariableType_Works.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/testing

#10223 Fix and improve DX12 DRED handling
  Gems/Atom/RHI/Code/Source/RHI/Factory.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
Labels: feature/graphics/rhi

#10135 Added a test option to the assetprocessor.stop function to allow testing assetproces…
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests.py
  Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
  Tools/LyTestTools/tests/unit/test_asset_processor.py
Labels: feature/asset-pipeline, sig/content

#10038 add GetDuration to SimpleMotionComponentBus
  Gems/EMotionFX/Code/Include/Integration/SimpleMotionComponentBus.h
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.h
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorSimpleMotionComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorSimpleMotionComponent.h
Labels: sig/simulation

#10057 Motion Matching: Adding transformer interface and a min-max scaler used for feature normalization
  Gems/MotionMatching/Code/Source/FeatureMatrixMinMaxScaler.cpp
  Gems/MotionMatching/Code/Source/FeatureMatrixMinMaxScaler.h
  Gems/MotionMatching/Code/Source/FeatureMatrixTransformer.h
  Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
  Gems/MotionMatching/Code/motionmatching_files.cmake
  Gems/MotionMatching/Code/motionmatching_tests_files.cmake
Labels: feature/animation, sig/simulation

#10182 feat(EMotionFX): improve functionality rotation manipulator by following orientation of target
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
Labels: sig/simulation

#10164 chore(EmotionFX): remove MCommon::TranslateManipulator from Vector3GizmoParameterEditor
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/Vector3GizmoParameterEditor.h
Labels: sig/simulation

#10256 added some conventions used in loft sample
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
Labels: sig/graphics-audio

#10181 feat(EmotionFX): add rotation manipulator for RotationParameter
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterEditor/RotationParameterEditor.h
Labels: sig/simulation

#10259 Fix for TDR caused by fullscreen shadow shader
  Gems/Atom/Feature/Common/Assets/Passes/FullscreenShadow.pass
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Shadow/FullscreenShadow.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Shadow/FullscreenShadow.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Source/Shadows/FullscreenShadowPass.cpp
  Gems/Atom/Feature/Common/Code/Source/Shadows/FullscreenShadowPass.h
Labels: feature/graphics

#9532 Introducing the Compression Interface Gem
  Code/Framework/AzCore/AzCore/RTTI/TypeSafeIntegral.h
  Code/Framework/AzCore/AzCore/base.h
  Code/Framework/AzCore/AzCore/std/function/identity.h
  Gems/Compression/.gitignore
  Gems/Compression/CMakeLists.txt
  Gems/Compression/Code/CMakeLists.txt
  Gems/Compression/Code/Include/Compression/CompressionBus.h
  Gems/Compression/Code/Include/Compression/CompressionInterfaceAPI.h
  Gems/Compression/Code/Include/Compression/CompressionInterfaceAPI.inl
  Gems/Compression/Code/Include/Compression/CompressionInterfaceStructs.h
  Gems/Compression/Code/Include/Compression/DecompressionInterfaceAPI.h
  Gems/Compression/Code/Include/Compression/DecompressionInterfaceAPI.inl
  Gems/Compression/Code/Platform/Android/PAL_android.cmake
  Gems/Compression/Code/Platform/Android/compression_api_files.cmake
  Gems/Compression/Code/Platform/Android/compression_private_files.cmake
  Gems/Compression/Code/Platform/Android/compression_shared_files.cmake
  Gems/Compression/Code/Platform/Linux/PAL_linux.cmake
  Gems/Compression/Code/Platform/Linux/compression_api_files.cmake
  Gems/Compression/Code/Platform/Linux/compression_editor_api_files.cmake
  Gems/Compression/Code/Platform/Linux/compression_private_files.cmake
  Gems/Compression/Code/Platform/Linux/compression_shared_files.cmake
  Gems/Compression/Code/Platform/Mac/PAL_mac.cmake
  Gems/Compression/Code/Platform/Mac/compression_api_files.cmake
  Gems/Compression/Code/Platform/Mac/compression_editor_api_files.cmake
  Gems/Compression/Code/Platform/Mac/compression_private_files.cmake
  Gems/Compression/Code/Platform/Mac/compression_shared_files.cmake
  Gems/Compression/Code/Platform/Windows/PAL_windows.cmake
  Gems/Compression/Code/Platform/Windows/compression_api_files.cmake
  Gems/Compression/Code/Platform/Windows/compression_editor_api_files.cmake
  Gems/Compression/Code/Platform/Windows/compression_private_files.cmake
  Gems/Compression/Code/Platform/Windows/compression_shared_files.cmake
  Gems/Compression/Code/Platform/iOS/PAL_ios.cmake
  Gems/Compression/Code/Platform/iOS/compression_api_files.cmake
  Gems/Compression/Code/Platform/iOS/compression_private_files.cmake
  Gems/Compression/Code/Platform/iOS/compression_shared_files.cmake
  Gems/Compression/Code/Source/Clients/CompressionModule.cpp
  Gems/Compression/Code/Source/Clients/CompressionSystemComponent.cpp
  Gems/Compression/Code/Source/Clients/CompressionSystemComponent.h
  Gems/Compression/Code/Source/CompressionModuleInterface.h
  Gems/Compression/Code/Source/Tools/CompressionEditorModule.cpp
  Gems/Compression/Code/Source/Tools/CompressionEditorSystemComponent.cpp
  Gems/Compression/Code/Source/Tools/CompressionEditorSystemComponent.h
  Gems/Compression/Code/Source/Tools/CompressionFactoryImpl.cpp
  Gems/Compression/Code/Source/Tools/CompressionFactoryImpl.h
  Gems/Compression/Code/Tests/Clients/CompressionTest.cpp
  Gems/Compression/Code/Tests/Tools/CompressionEditorTest.cpp
  Gems/Compression/Code/compression_api_files.cmake
  Gems/Compression/Code/compression_editor_api_files.cmake
  Gems/Compression/Code/compression_editor_private_files.cmake
  Gems/Compression/Code/compression_editor_shared_files.cmake
  Gems/Compression/Code/compression_editor_tests_files.cmake
  Gems/Compression/Code/compression_private_files.cmake
  Gems/Compression/Code/compression_shared_files.cmake
  Gems/Compression/Code/compression_tests_files.cmake
  Gems/Compression/Registry/assetprocessor_settings.setreg
  Gems/Compression/gem.json
  Gems/Compression/preview.png
  engine.json
Labels: sig/core

#10274 chore: remove OrbitCamera from RenderOptions
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
Labels: feature/animation, sig/simulation

#10265 Fixed wrong hyperlink for the Animation Editor
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
Labels: feature/animation, sig/simulation

#10195 Asset Processor - Intermediate Assets
  AutomatedTesting/Gem/Code/enabled_gems.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsFileUtils/ToolsFileUtils_generic.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.h
  Code/Tools/AssetProcessor/native/AssetManager/ProductAsset.cpp
  Code/Tools/AssetProcessor/native/AssetManager/ProductAsset.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/AssetManager/assetScannerWorker.cpp
  Code/Tools/AssetProcessor/native/FileProcessor/FileProcessor.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.h
  Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.cpp
  Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.h
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.h
  Code/Tools/AssetProcessor/native/tests/platformconfiguration/platformconfigurationtests.cpp
  Code/Tools/AssetProcessor/native/tests/platformconfiguration/platformconfigurationtests.h
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCJobTest.cpp
  Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetScannerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
  Gems/TestAssetBuilder/Code/Source/Builder/TestIntermediateAssetBuilderComponent.cpp
  Gems/TestAssetBuilder/Code/Source/Builder/TestIntermediateAssetBuilderComponent.h
  Gems/TestAssetBuilder/Code/Source/TestAssetBuilderModule.cpp
  Gems/TestAssetBuilder/Code/testassetbuilder_files.cmake
Labels: feature/asset-pipeline, sig/content

#10294 Added collision group filtering to Recast Navigation PhysX Provider component
  Gems/RecastNavigation/Code/Source/EditorComponents/EditorRecastNavigationPhysXProviderComponent.cpp
  Gems/RecastNavigation/Code/Source/EditorComponents/EditorRecastNavigationPhysXProviderComponent.h
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationMeshComponentController.cpp
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.cpp
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.h
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderConfig.cpp
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderConfig.h
Labels: sig/simulation

#10300 Update image gradient's asset path after gradient baker finishes
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
Labels: sig/content

#10287 Fix for test script EditMenu_Default_UndoRedo
  AutomatedTesting/Gem/PythonTests/scripting/EditMenu_Default_UndoRedo.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/testing

#2772 When all else is equal, asset processing sorts jobs by source path instead of job run key now
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
Labels: sig/core

#10167 Fix sc source handle, remove all possible serialization of absolute paths
  Gems/ScriptCanvas/Code/Asset/EditorAssetSystemComponent.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasAssetHelpers.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasAssetHelpers.h
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorUtils.cpp
  Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasGraphUtilities.inl
  Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/FunctionNodeDescriptorComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/EditorScriptCanvasBus.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorDeprecationData.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponentSerializer.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorUtils.h
  Gems/ScriptCanvas/Code/Editor/Settings.cpp
  Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/SystemComponent.h
  Gems/ScriptCanvas/Code/Editor/Utilities/RecentAssetPath.cpp
  Gems/ScriptCanvas/Code/Editor/Utilities/RecentAssetPath.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/PivotTree/PivotTreeWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/FunctionNodePaletteTreeItemTypes.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/StatisticsDialog/ScriptCanvasStatisticsDialog.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/UnitTestPanel/UnitTestDockWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptEventMenu.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/FileSaver.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/FileSaver.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Modifier.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Scanner.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
Labels: sig/content

#10042 Editor: Allow to re-open the current level
  Code/Editor/Core/LevelEditorMenuHandler.cpp
  Code/Editor/CryEdit.cpp
  Code/Editor/EditorToolsApplication.cpp
Labels: sig/content

#10262 Material Canvas: Fixing bugs with input and property slots supporting multiple data types
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/add.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/add_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/combine.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/constant_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/constant_float.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/constant_float2.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/constant_float3.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/constant_float4.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/cosine.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/divide.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/example_pbr.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/multiply.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/sample_texture_2d.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/sine.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/split.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/subtract.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/subtract_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasGraphDataTypes.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasTestData.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/materialcanvas_files.cmake
  Gems/GraphModel/Code/Include/GraphModel/Model/DataType.h
  Gems/GraphModel/Code/Include/GraphModel/Model/GraphContext.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Node.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
  Gems/GraphModel/Code/Source/Model/DataType.cpp
  Gems/GraphModel/Code/Source/Model/GraphContext.cpp
  Gems/GraphModel/Code/Source/Model/Node.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Core/DataTypes.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Core/DataTypes.h
  Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.h
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/AltitudeFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/DistributionFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/ShapeIntersectionFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/PositionModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/RotationModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/ScaleModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/SlopeAlignmentModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/AreaBlenderNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/BaseAreaNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/BaseGradientModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/GradientMixerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/AltitudeGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/BaseGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/GradientBakerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ShapeAreaFalloffGradientNode.cpp
  Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Labels: feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#10359 bugfix: fix minimization/maximization button for the Editor Window
  Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.h
Labels: sig/content, sig/ui-ux

#10378 Atom Tools: Restoring settings dialog for ME, MC, SMC
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/SettingsDialog/SettingsDialog.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/SettingsDialog/SettingsDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsDialog.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsWidget.h
  Gems/Atom/Tools/MaterialEditor/Code/materialeditor_files.cmake
Labels: feature/graphics/tools

#10339 [LYN-13426] Asset Processor - Intermediate Assets - Prior Product Cleanup
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
Labels: feature/asset-pipeline, sig/content

#10266 [Terrain] Fix bugs in terrain clipmap
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
Labels: feature/terrain

#10406 Added setters and getters for nav mesh entity for DetourNavigationComponent
  Gems/RecastNavigation/Code/Include/RecastNavigation/DetourNavigationBus.h
  Gems/RecastNavigation/Code/Source/Components/DetourNavigationComponent.cpp
  Gems/RecastNavigation/Code/Source/Components/DetourNavigationComponent.h
  Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
Labels: sig/simulation

#10380 Remove smoke tests for flaky Asset Processor tools
  AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_AssetBuilder_Works.py
  AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_AssetBundlerBatch_Works.py
Labels: sig/content

#10278 Motion Matching: Additional min-max scaler tests
  Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
Labels: feature/animation, sig/simulation

#9938 Fixed a couple issues with the ShaderReloadDebugTracker.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderReloadDebugTracker.h
  Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderReloadDebugTracker.cpp
Labels: sig/graphics-audio

#10365 [Terrain] Add notification and the ability to refresh clipmaps when editor data changes
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
Labels: feature/terrain

#10303 Hair P1 null render automation
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HairAdded.py
  Gems/AtomTressFX/Code/Rendering/HairGlobalSettings.cpp
  Gems/AtomTressFX/External/Code/src/TressFX/TressFXSettings.cpp
Labels: sig/graphics-audio

#10018 Split editor batched test logs into logs for individual tests.
  Tools/LyTestTools/ly_test_tools/_internal/managers/artifact_manager.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Labels: sig/testing

#10419 Material Canvas: Initial support for undo redo
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/GraphView/GraphView.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Utils/GraphUtils.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Utils/GraphUtils.h
  Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
Labels: feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#10417 Pipeline pass improvements
  Gems/Atom/Feature/Common/Assets/Passes/CameraMotionVector.pass
  Gems/Atom/Feature/Common/Assets/Passes/MotionVectorParent.pass
  Gems/Atom/Feature/Common/Code/Source/CoreLights/CascadedShadowmapsPass.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/PipelinePassChanges.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/PipelinePassChanges.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
  Gems/Atom/RPI/Code/Tests/System/RenderPipelineTests.cpp
  Gems/Atom/RPI/Code/Tests/System/SceneTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
Labels: feature/graphics/rpi

#10363 Root Motion Extraction Rule (preview)
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpBoneImporter.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Motion/MotionDataBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionGroupBehavior.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/RootMotionExtractionRule.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/RootMotionExtractionRule.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/sceneapi_ext_files.cmake
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.h
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.h
Labels: feature/animation

#9658 8636 Crash in outliner treeview when closing nested prefabs with shortcut keys.
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusPublicInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabFocusChangeBehavior.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content

#10430 Fix Ui Canvas Invalid Render Target Crash
  Gems/LyShine/Code/Source/UiCanvasComponent.cpp
  Gems/LyShine/Code/Source/UiCanvasComponent.h
Labels: sig/content, feature/lyshine

#10442 Removing all SwapChainOutput uses, replaced with more generic PipelineOutput
  Gems/Atom/Feature/Common/Assets/Passes/CheckerboardResolveColor.pass
  Gems/Atom/Feature/Common/Assets/Passes/CheckerboardResolveDepth.pass
  Gems/Atom/Feature/Common/Assets/Passes/Depth.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthCheckerboard.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthMSAA.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthMSAA2x.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthMSAA4x.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthMSAA8x.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthMSAAParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthMax.pass
  Gems/Atom/Feature/Common/Assets/Passes/DisplayMapper.pass
  Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapPipeline.pass
  Gems/Atom/Feature/Common/Assets/Passes/Forward.pass
  Gems/Atom/Feature/Common/Assets/Passes/ForwardCheckerboard.pass
  Gems/Atom/Feature/Common/Assets/Passes/ForwardMSAA.pass
  Gems/Atom/Feature/Common/Assets/Passes/ForwardSubsurfaceMSAA.pass
  Gems/Atom/Feature/Common/Assets/Passes/FullscreenShadow.pass
  Gems/Atom/Feature/Common/Assets/Passes/LightAdaptationParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/LightCullingParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/LookModificationTransform.pass
  Gems/Atom/Feature/Common/Assets/Passes/LowEndForward.pass
  Gems/Atom/Feature/Common/Assets/Passes/LowEndPipeline.pass
  Gems/Atom/Feature/Common/Assets/Passes/MainPipeline.pass
  Gems/Atom/Feature/Common/Assets/Passes/MainPipelineRenderToTexture.pass
  Gems/Atom/Feature/Common/Assets/Passes/MeshMotionVector.pass
  Gems/Atom/Feature/Common/Assets/Passes/MotionVectorParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/OpaqueParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/PostProcessParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/ShadowParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/ToolsPipeline.pass
  Gems/Atom/Feature/Common/Assets/Passes/ToolsPipelineRenderToTexture.pass
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/DisplayMapper/DisplayMapperPass.h
  Gems/Atom/Feature/Common/Code/Source/DisplayMapper/DisplayMapperPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/LookModificationTransformPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/LookModificationTransformPass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/EnvironmentCubeMapPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/SwapChainPass.cpp
  Gems/AtomTressFX/Assets/Passes/AtomTressFX_PassRequest.azasset
Labels: feature/graphics

#10431 Asset Processor - Reserve Builder for CreateJobs
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.inl
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: feature/asset-pipeline, sig/content

#10459 Disable async Navigation unit tests to unblock AR
  Gems/RecastNavigation/Code/Tests/NavigationMeshTest.cpp
  Gems/RecastNavigation/Code/recastnavigation_editor_tests_files.cmake
Labels: sig/simulation
