Repository o3de/o3de, pull requests merged in 2022-04, with the labels that each got.

#8657 Material Component: fix prefab serialization for model UV overrides
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#8447 Consolidate default category name for behavior context node
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
Labels: sig/core

#8684 Fix the Android release build failure caused by unused variables
  Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp
Labels: platform/android, sig/core

#8683 Avoid assert from RemoteConsoleCore when use the prefab system
  Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
Labels: sig/content, sig/network

#8409 Disable source control by default.
  Code/Editor/Settings.cpp
Labels: feature/editor, sig/content

#8697 Update O3DE to use new version of Android OpenSSL
  cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
Labels: sig/network

#8424 Remove Multiplayer Gem from DefaultProject Template
  Templates/DefaultProject/Template/Gem/enabled_gems.cmake
Labels: sig/network

#8648 Adjust manipulator scale using scale manipulator
  Code/Editor/EditorPreferencesPageViewportManipulator.cpp
  Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/LinearManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
Labels: sig/content, feature/viewport

#8129 New Eye material type
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.shader
  Gems/Atom/Feature/Common/Assets/Materials/Types/EyeSurface_ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye_Common.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EvaluateEyeSurface.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/EyeLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/EyeSurface.azsli
Labels: sig/graphics-audio

#8704 Gave Entity Inspector window an object name
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/QComponentEntityEditorMainWindow.cpp
Labels: sig/content

#8494 [Terrain] Custom mip channel support for image gradients
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/StreamingImageAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAsset.cpp
  Gems/Atom/RPI/Code/Tests/Image/StreamingImageTests.cpp
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
Labels: sig/content, sig/graphics-audio

#8010 [development] refactored the StatisticalProfiler(Proxy) tests and benchmarks
  Code/Framework/AzCore/AzCore/Statistics/StatisticalProfiler.h
  Code/Framework/AzCore/AzCore/Statistics/StatisticalProfilerProxy.h
  Code/Framework/AzCore/AzCore/std/azstd_files.cmake
  Code/Framework/AzCore/AzCore/std/parallel/shared_spin_mutex.h
  Code/Framework/AzCore/Tests/StatisticalProfiler.cpp
  Code/Framework/AzCore/Tests/StatisticalProfilerBenchmarks.cpp
  Code/Framework/AzCore/Tests/StatisticalProfilerHelpers.h
  Code/Framework/AzCore/Tests/StatisticalProfilerTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/core

#8724 Fix a typo related to view hash
  Gems/Atom/RHI/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImageView.cpp
Labels: feature/graphics/rhi

#8612 Add ability to reposition manipulator by picking in the scene
  Code/Framework/AzToolsFramework/AzToolsFramework/Commands/EntityManipulatorCommand.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Commands/EntityManipulatorCommand.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
  Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
Labels: sig/content, feature/viewport

#8492 Default flag sytems to use TaskGraph
  Code/Framework/AzCore/AzCore/Task/TaskGraph.cpp
  Code/Framework/AzCore/AzCore/Task/TaskGraphSystemComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Labels: sig/core, sig/graphics-audio

#7042 Allow users to change type of SC variable / update get/set nodes by replacing them in live graph.
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilder.h
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Components/GraphUpgrade.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/NodeIdPair.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/RequestBus.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.cpp
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.h
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeUtils.h
  Gems/ScriptCanvas/Code/Editor/Settings.cpp
  Gems/ScriptCanvas/Code/Editor/Settings.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableConfigurationWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableConfigurationWidget.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableConfigurationWidget.ui
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableDockWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableDockWidget.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptCanvasContextMenus.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammar_Header.jinja
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammar_Source.jinja
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/NodeBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/SetVariable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/SetVariable.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Logic/Sequencer.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Logic/Sequencer.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Divide.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Multiply.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Subtract.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/Sum.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorArithmetic.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Operator.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Results/ErrorText.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/NodeUtils.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/NodeUtils.h
  Gems/ScriptCanvas/Code/scriptcanvasgem_editor_files.cmake
Labels: feature/scripting

#8585 Moved internals of AZ::IO::Streamer over to use AZ::IO::Path.
  Code/Framework/AzCore/AzCore/IO/CompressionBus.cpp
  Code/Framework/AzCore/AzCore/IO/CompressionBus.h
  Code/Framework/AzCore/AzCore/IO/Streamer/RequestPath.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/RequestPath.h
  Code/Framework/AzCore/AzCore/IO/Streamer/StorageDrive.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
  Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StorageDrive_Windows.cpp
  Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StorageDrive_Windows.h
  Code/Framework/AzCore/Tests/Platform/Windows/Tests/IO/Streamer/StorageDriveTests_Windows.cpp
  Code/Framework/AzCore/Tests/Streamer/BlockCacheTests.cpp
  Code/Framework/AzCore/Tests/Streamer/ReadSplitterTests.cpp
  Code/Framework/AzCore/Tests/StreamerTests.cpp
  Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
  Code/Framework/AzFramework/AzFramework/Archive/Archive.h
  Code/Framework/AzFramework/AzFramework/IO/RemoteStorageDrive.cpp
Labels: sig/core

#8545 Fixed incorrect RTTI declaration for the HairAssetBuilder
  Gems/AtomTressFX/Code/Builders/HairAssetBuilder.h
Labels: sig/graphics-audio

#8538 ATOM-17383 Adding support of using an attachment image for material t…
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/ImageAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/ImageAsset.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/PropertyEditor/PropertyImageAssetCtrl.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/PropertyEditor/PropertyImageAssetCtrl.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#8730 Adds a nullptr check for sprite in UiCustomImageComponent
  Gems/LyShineExamples/Code/Source/UiCustomImageComponent.cpp
Labels: sig/content

#7640 Added Chromatic Aberation PPFX w/ Component
  Gems/Atom/Feature/Common/Assets/Passes/ChromaticAberration.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Passes/PostProcessParent.pass
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/ChromaticAberration.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/ChromaticAberration.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/ChromaticAberration/ChromaticAberrationConstants.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/ChromaticAberration/ChromaticAberrationParams.inl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/ChromaticAberration/ChromaticAberrationSettingsInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/PostProcessSettings.inl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/PostProcessSettingsInterface.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationSettings.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationSettings.h
  Gems/Atom/Feature/Common/Code/Source/PostProcess/PostProcessSettings.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/ChromaticAberrationPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/ChromaticAberrationPass.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/PostProcess/ChromaticAberration/ChromaticAberrationBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/PostProcess/ChromaticAberration/ChromaticAberrationComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Module.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/ChromaticAberrationComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/EditorChromaticAberrationComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/EditorChromaticAberrationComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
Labels: sig/graphics-audio

#8764 Linux Pre-Built SDK CMake configure fix
  AutomatedTesting/CMakeLists.txt
  AutomatedTesting/cmake/CompilerSettings.cmake
  AutomatedTesting/cmake/Platform/Linux/CompilerSettings_linux.cmake
  Templates/CMakeLists.txt
  Templates/DefaultProject/Template/CMakeLists.txt
  Templates/DefaultProject/Template/cmake/CompilerSettings.cmake
  Templates/DefaultProject/Template/cmake/Platform/Linux/CompilerSettings_linux.cmake
  Templates/DefaultProject/template.json
  Templates/MinimalProject/Template/CMakeLists.txt
  Templates/MinimalProject/Template/cmake/CompilerSettings.cmake
  Templates/MinimalProject/Template/cmake/Platform/Linux/CompilerSettings_linux.cmake
  Templates/MinimalProject/template.json
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Linux/OpenSSL_linux.cmake
  cmake/CompilerSettings.cmake
  cmake/Findo3de.cmake
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Linux/CompilerSettings_linux.cmake
  cmake/install/Findo3de.cmake.in
Labels: platform/linux, sig/core, sig/network, sig/platform

#8780 Enabled ImGui for ScriptCanvasDeveloper gem
  Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
Labels: feature/scripting

#8765 Fix Multiplayer Editor Invalid Connection
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#8761 [development] unified the level (un)loading console commands
  Code/Legacy/CryCommon/ISystem.h
  Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
  Code/Legacy/CrySystem/System.cpp
  Code/Tools/RemoteConsole/Core/RemoteConsoleCore.cpp
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/android/launcher.py
  Tools/LyTestTools/tests/unit/test_launcher_android.py
Labels: sig/core, sig/platform, sig/testing

#8783 Atom Tools: Add settings to disallow previewing and editing certain materials
  Gems/Atom/Feature/Common/Registry/system_materials.setreg
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Resources/AtomLyIntegrationResources.qrc
  Gems/AtomLyIntegration/CommonFeatures/Code/Resources/Icons/material.svg
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.cpp
  Gems/Terrain/Registry/system_materials.setreg
Labels: sig/content, sig/graphics-audio, feature/terrain, feature/graphics/tools, feature/graphics/materials

#8802 Prefabs | Fix to z-indexing of capsule borders in the Outliner
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.h
Labels: sig/content, feature/prefabs

#8805 Focus Mode | Always expand ancestors when focusing on prefab
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.hxx
Labels: feature/editor, sig/content

#8788 Fixed Decal Error Message
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
Labels: sig/graphics-audio

#8775 Re-Enable Multiplayer AR
  AutomatedTesting/Gem/PythonTests/Multiplayer/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
Labels: sig/network

#8725 Update Camera Component's max FOV to 180 [RESOLVES #4081]
  Gems/Camera/Code/Source/CameraComponentController.cpp
Labels: sig/content, feature/viewport

#8803 Follow up change for ATOM-17383.
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialPropertyValue.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialAssetTestUtils.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialAssetTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
Labels: sig/graphics-audio, feature/graphics/materials

#8830 ATOM-17530 TimeStampQuery report error when use ImGui gpu profiler wi…
  Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/Query.cpp
Labels: feature/graphics/rpi

#8544 Add metadata to mark AMD Radeon driver 22.2.3 has issues.
  Gems/Atom/RHI/Registry/Platform/Windows/PhysicalDeviceDriverInfo.setreg
Labels: sig/graphics-audio

#8440 Adding Spawnable API support for Lua
  AutomatedTesting/Levels/Physics/ScriptCanvas_SpawnEntityWithPhysComponents/ScriptCanvas_SpawnEntityWithPhysComponents.prefab
  AutomatedTesting/ScriptCanvas/ScriptCanvas_SpawnEntityWithPhysComponents.scriptcanvas
  Code/Framework/AzFramework/AzFramework/Script/ScriptComponent.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.h
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptBus.h
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptMediator.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptMediator.h
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptNotificationsHandler.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.ScriptCanvasNodeable.xml
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.ScriptCanvasNodeable.xml
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.ScriptCanvasNodeable.xml
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnTicketInstance.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnTicketInstance.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnableAsset.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnableAsset.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/Spawning.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/Spawning.h
  Gems/ScriptCanvas/Code/scriptcanvasgem_common_files.cmake
  Gems/ScriptCanvas/Code/scriptcanvasgem_headers.cmake
Labels: sig/core

#8785 Upload crash artifacts in AR
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/testing

#8799 Implemented bilinear filtering sample type for image gradients
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/GradientTransform.h
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/GradientTransform.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
Labels: sig/content

#8824 EntityDebugDisplayBus SetColor Explicit Naming
  Code/Editor/EditorViewportWidget.cpp
  Code/Framework/AzFramework/AzFramework/Entity/EntityDebugDisplayBus.h
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.h
  Gems/PhysXDebug/Code/Source/SystemComponent.cpp
Labels: sig/content, sig/core, sig/graphics-audio

#8863 Fix State Transition After Building Again After A Failed Build
  Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: sig/content, feature/project-manager

#8827 Remove the step for creating Python virtual environment to unblock AWSI automation tests on Linux
  scripts/build/Platform/Linux/deploy_cdk_applications.sh
  scripts/build/Platform/Linux/destroy_cdk_applications.sh
Labels: sig/network

#8814 Prefabs | Introduce Notification EBus to detect when a prefab is saved to disk
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicNotificationBus.h
Labels: sig/content, feature/prefabs

#8812 Fixed AZSLc command line arguments on metal.
  Gems/Atom/Asset/Shader/Config/Platform/Mac/shader_build_options.json
Labels: sig/graphics-audio

#8495 Add support for the Enable IBL material option
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/ForwardPassOutput.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/BaseLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/EnhancedLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/SkinLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/StandardLighting.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseComposite.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionGlobalFullscreen.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionProbeRenderCommon.azsli
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli
Labels: sig/graphics-audio

#8826 Blast improvements
  Gems/Blast/Code/Include/Blast/BlastActor.h
  Gems/Blast/Code/Include/Blast/BlastSystemBus.h
  Gems/Blast/Code/Source/Actor/BlastActorImpl.cpp
  Gems/Blast/Code/Source/Actor/BlastActorImpl.h
  Gems/Blast/Code/Source/Components/BlastFamilyComponent.cpp
  Gems/Blast/Code/Source/Components/BlastFamilyComponent.h
  Gems/Blast/Code/Source/Components/BlastSystemComponent.cpp
  Gems/Blast/Code/Source/Components/BlastSystemComponent.h
  Gems/Blast/Code/Source/Family/BlastFamilyImpl.cpp
  Gems/Blast/Code/Source/Family/BlastFamilyImpl.h
  Gems/Blast/Code/Tests/Mocks/BlastMocks.h
Labels: sig/core

#8871 Atom gem release build fix
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuildArgumentsManager.cpp
Labels: sig/graphics-audio

#8789 reduce test setup in azframework tests
  Code/Framework/AzFramework/Tests/ArchiveCompressionTests.cpp
  Code/Framework/AzFramework/Tests/FileIO.cpp
Labels: sig/core, sig/testing

#8881 LYN-10155 RHI Null Renderer is still costing a dedicated server, non …
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHIUtils.h
  Gems/Atom/RHI/Code/Source/RHI/BufferPoolBase.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPISystemInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/RPISystemDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/RPISystemDescriptor.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/LyShine/Code/Source/LyShine.cpp
  Gems/NvCloth/Code/Source/Components/ClothComponentMesh/ClothComponentMesh.cpp
Labels: feature/graphics/rpi

#8918 Merge https://github.com/o3de/o3de/pull/8863 to stabilization
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: feature/project-manager

#8793 Fixed Dx12 shader stage visibility mask.
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
Labels: sig/graphics-audio

#8787 reduce sleeps in azcore tests
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
  Code/Framework/AzCore/Tests/EBus.cpp
  Code/Framework/AzCore/Tests/EBus/ScheduledEventTests.cpp
  Code/Framework/AzCore/Tests/Streamer/FullDecompressorTests.cpp
  Code/Framework/AzCore/Tests/Streamer/SchedulerTests.cpp
  Code/Framework/AzCore/Tests/StreamerTests.cpp
Labels: sig/core, sig/testing

#8904 [LYN-1623] Asset Processor: Use stdout instead of stderr
  Code/Tools/AssetProcessor/AssetBuilder/TraceMessageHook.cpp
Labels: sig/content

#8910 Multiplayer Editor: Display Debug Text While the Editor Connects to a Server
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerEditorConnectionViewportMessage.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnection.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorGem.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/multiplayer_editor_shared_files.cmake
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/network

#8922 Fixed deadlock due to asset.BlockUntilLoadComplete
  Gems/Atom/Utils/Code/Include/Atom/Utils/AssetCollectionAsyncLoader.h
  Gems/Atom/Utils/Code/Source/AssetCollectionAsyncLoader.cpp
Labels: sig/graphics-audio

#8929 Fix 8903 DetailMaps Screenshot Test Broken
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageLoader/TIFFLoader.cpp
Labels: feature/graphics/asset

#8838 Resubmitting P1 Exposure Control automation
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_ExposureControlAdded.py
Labels: sig/graphics-audio

#8804 reduce ap test calls to sleep
  Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
Labels: sig/content, sig/core, sig/testing

#8444 Added logging to json decode error.
  Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
  Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
Labels: sig/testing

#8949 Cherry-pick 6ddd3d3 from the development branch: Linux Pre-Built SDK CMake configure fix (#8764)
  AutomatedTesting/CMakeLists.txt
  AutomatedTesting/cmake/CompilerSettings.cmake
  AutomatedTesting/cmake/Platform/Linux/CompilerSettings_linux.cmake
  Templates/CMakeLists.txt
  Templates/DefaultProject/Template/CMakeLists.txt
  Templates/DefaultProject/Template/cmake/CompilerSettings.cmake
  Templates/DefaultProject/Template/cmake/Platform/Linux/CompilerSettings_linux.cmake
  Templates/DefaultProject/template.json
  Templates/MinimalProject/Template/CMakeLists.txt
  Templates/MinimalProject/Template/cmake/CompilerSettings.cmake
  Templates/MinimalProject/Template/cmake/Platform/Linux/CompilerSettings_linux.cmake
  Templates/MinimalProject/template.json
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Linux/OpenSSL_linux.cmake
  cmake/CompilerSettings.cmake
  cmake/Findo3de.cmake
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Linux/CompilerSettings_linux.cmake
  cmake/install/Findo3de.cmake.in
Labels: sig/network

#8951 Cherry-pick 8712cc3 and 7021b27 from development: Use O3DE Python to run cdk deploy
  scripts/build/Platform/Linux/deploy_cdk_applications.sh
  scripts/build/Platform/Linux/destroy_cdk_applications.sh
  scripts/build/Platform/Windows/deploy_cdk_applications.cmd
  scripts/build/Platform/Windows/destroy_cdk_applications.cmd
Labels: sig/network

#8817 #8651 Fix resource mapping tool unhandled exceptions
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_aws_utils.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/utils/aws_utils.py
Labels: sig/network

#8005 Jenkins replace content
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/testing

#8880 Move unused math generic node to testing gem
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/MathGenerics.h
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_FixBoundMultipleResults.scriptcanvas
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_GlobalMultipleReturnResults.scriptcanvas
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_GlobalMultipleReturnResultsByValue.scriptcanvas
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_MultipleReturnResultsByValue.scriptcanvas
  Gems/ScriptCanvasTesting/Code/Source/ScriptCanvasTestBus.h
  Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_GlobalMethods.cpp
  Gems/ScriptCanvasTesting/Code/Tests/ScriptCanvas_RuntimeInterpreted.cpp
  Gems/ScriptCanvasTesting/Code/scriptcanvastestingeditor_tests_files.cmake
Labels: sig/content, sig/core

#8617 Output a list of failed assets at the end of a batch asset processor run
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.cpp
Labels: sig/content

#8998 Graph Model: Removing overloaded template function to get data types from graph model contexts
  Gems/GraphModel/Code/Include/GraphModel/Model/IGraphContext.h
  Gems/GraphModel/Code/Tests/TestEnvironment.h
  Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.h
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/AltitudeFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/DistributionFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/ShapeIntersectionFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/PositionModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/RotationModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/ScaleModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/SlopeAlignmentModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/AreaBlenderNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/BaseAreaNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/BaseGradientModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/GradientMixerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/AltitudeGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/BaseGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ShapeAreaFalloffGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/BaseShapeNode.cpp
Labels: sig/content, feature/graphics/tools

#8723 Update ForceRegion_LinearDampingForceOnRigidBodies Level Setup test to report its state before testing
  AutomatedTesting/Gem/PythonTests/Physics/tests/force_region/ForceRegion_LinearDampingForceOnRigidBodies.py
Labels: sig/core

#8948 Added thread safety to shape components
  Gems/LmbrCentral/Code/Source/Shape/BoxShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/BoxShape.h
  Gems/LmbrCentral/Code/Source/Shape/CapsuleShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/CapsuleShape.h
  Gems/LmbrCentral/Code/Source/Shape/CylinderShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/CylinderShape.h
  Gems/LmbrCentral/Code/Source/Shape/DiskShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/DiskShape.h
  Gems/LmbrCentral/Code/Source/Shape/PolygonPrismShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/PolygonPrismShape.h
  Gems/LmbrCentral/Code/Source/Shape/QuadShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/QuadShape.h
  Gems/LmbrCentral/Code/Source/Shape/ReferenceShapeComponent.cpp
  Gems/LmbrCentral/Code/Source/Shape/ReferenceShapeComponent.h
  Gems/LmbrCentral/Code/Source/Shape/SphereShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/SphereShape.h
  Gems/LmbrCentral/Code/Source/Shape/TubeShape.cpp
  Gems/LmbrCentral/Code/Source/Shape/TubeShape.h
  Gems/LmbrCentral/Code/Tests/AxisAlignedBoxShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/BoxShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/CapsuleShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/CylinderShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/DiskShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/PolygonPrismShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/QuadShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/ReferenceShapeTests.cpp
  Gems/LmbrCentral/Code/Tests/ShapeThreadsafeTest.cpp
  Gems/LmbrCentral/Code/Tests/ShapeThreadsafeTest.h
  Gems/LmbrCentral/Code/Tests/SphereShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/TubeShapeTest.cpp
  Gems/LmbrCentral/Code/Tests/lmbrcentral_tests_files.cmake
  Gems/LmbrCentral/Code/include/LmbrCentral/Shape/ShapeComponentBus.h
Labels: sig/core

#8938 fix the issue where client can not connect to Server after disconnect
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#9001 Graph Model: Added more numeric and math types to json serializer
  Gems/GraphModel/Code/Source/Model/Slot.cpp
Labels: sig/content, feature/graphics/tools

#9019 Fixed bug about reparenting prefab
  AutomatedTesting/Gem/PythonTests/Prefab/tests/reparent_prefab/ReparentPrefab_UnderAnotherPrefab.py
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: sig/content

#8980 Asset Import: Remove the unneeded mesh node in the emfx node structure.
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpBoneImporter.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
Labels: sig/content

#9017 Graph Model: Move graph context implementation into base class
  Gems/GraphModel/Code/Include/GraphModel/Integration/EditorMainWindow.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Common.h
  Gems/GraphModel/Code/Include/GraphModel/Model/DataType.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
  Gems/GraphModel/Code/Include/GraphModel/Model/GraphContext.h
  Gems/GraphModel/Code/Include/GraphModel/Model/GraphElement.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Module/ModuleGraphManager.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
  Gems/GraphModel/Code/Source/Model/Graph.cpp
  Gems/GraphModel/Code/Source/Model/GraphContext.cpp
  Gems/GraphModel/Code/Source/Model/GraphElement.cpp
  Gems/GraphModel/Code/Source/Model/Module/ModuleGraphManager.cpp
  Gems/GraphModel/Code/Source/Model/Module/ModuleNode.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
  Gems/GraphModel/Code/Tests/TestEnvironment.cpp
  Gems/GraphModel/Code/Tests/TestEnvironment.h
  Gems/GraphModel/Code/graphmodel_editor_static_files.cmake
  Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.h
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Labels: sig/content, feature/graphics/tools

#9025 HDR Color Grading component's "Generate LUT" and
  Gems/Atom/Feature/Common/Editor/Scripts/ColorGrading/activate_lut_asset.py
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/PostProcess/ColorGrading/EditorHDRColorGradingBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
Labels: sig/graphics-audio

#6589 AP Gui Builders Tab
  Code/Tools/AssetProcessor/assetprocessor_gui_files.cmake
  Code/Tools/AssetProcessor/native/ui/BuilderListModel.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderListModel.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/ui/style/AssetsTab.qss
  Code/Tools/AssetProcessor/native/utilities/AssetUtilEBusHelper.h
Labels: sig/content, sig/ui-ux

#9027 Issues when loading RPI/AuxGeom sample #402
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomDrawQueue.cpp
Labels: feature/graphics

#9053 Initial gradient baker component
  Gems/GradientSignal/Assets/Editor/Icons/Components/GradientBaker.svg
  Gems/GradientSignal/Assets/Editor/Icons/Components/Viewport/GradientBaker.svg
  Gems/GradientSignal/Code/Include/GradientSignal/Editor/EditorGradientTypeIds.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.h
  Gems/GradientSignal/Code/Source/GradientSignalEditorModule.cpp
  Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
Labels: sig/content

#8821 Make Lua functor paths be relative to the asset system root path
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ClearCoatPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/DetailMapsPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/EmissivePropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/OpacityPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/SubsurfaceAndTransmissionPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR.materialtype
Labels: sig/content, sig/graphics-audio

#9062 Fixed an issue with CaptureScreenshotWithPreview
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
Labels: feature/graphics/rpi

#8952 [Terrain] Clipmap parameterizing
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
Labels: sig/content, sig/graphics-audio, feature/terrain

#9057 [Terrain] Fix shape area falloff to calculate either 2D or 3D falloff.
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ShapeAreaFalloffGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/Ebuses/ShapeAreaFalloffGradientRequestBus.h
  Gems/GradientSignal/Code/Source/Components/ShapeAreaFalloffGradientComponent.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalServicesTests.cpp
Labels: sig/content

#8945 RayTracing Performance Improvements
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialUtils.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneUtils.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingPass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingIndexList.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingResourceList.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
Labels: sig/graphics-audio

#9078 Remove unused crash handler code
  Code/Tools/CrashHandler/Tools/ToolsCrashHandler.cpp
Labels: sig/security

#9004 Fix crash due to nullptr dereference when gem requirements are moused over
  Code/Tools/ProjectManager/Source/GemCatalog/GemItemDelegate.cpp
Labels: sig/content

#9056 Fix lyn12116 test chunks crash
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
Labels: sig/content

#8624 Stars Feature
  .gitattributes
  AutomatedTesting/Gem/Code/enabled_gems.cmake
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/ShaderResourceGroups/DefaultSceneSrg.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Stars/Assets/Shaders/Stars/Stars.azsl
  Gems/Stars/Assets/Shaders/Stars/Stars.shader
  Gems/Stars/Assets/Stars/default.stars
  Gems/Stars/Assets/seedList.seed
  Gems/Stars/CMakeLists.txt
  Gems/Stars/Code/CMakeLists.txt
  Gems/Stars/Code/Include/Stars/StarsFeatureProcessorInterface.h
  Gems/Stars/Code/Source/EditorStarsComponent.cpp
  Gems/Stars/Code/Source/EditorStarsComponent.h
  Gems/Stars/Code/Source/EditorStarsModule.cpp
  Gems/Stars/Code/Source/EditorStarsSystemComponent.cpp
  Gems/Stars/Code/Source/EditorStarsSystemComponent.h
  Gems/Stars/Code/Source/StarsAsset.cpp
  Gems/Stars/Code/Source/StarsAsset.h
  Gems/Stars/Code/Source/StarsComponent.cpp
  Gems/Stars/Code/Source/StarsComponent.h
  Gems/Stars/Code/Source/StarsComponentConfig.h
  Gems/Stars/Code/Source/StarsComponentController.cpp
  Gems/Stars/Code/Source/StarsComponentController.h
  Gems/Stars/Code/Source/StarsFeatureProcessor.cpp
  Gems/Stars/Code/Source/StarsFeatureProcessor.h
  Gems/Stars/Code/Source/StarsModule.cpp
  Gems/Stars/Code/Source/StarsModule.h
  Gems/Stars/Code/Source/StarsSystemComponent.cpp
  Gems/Stars/Code/Source/StarsSystemComponent.h
  Gems/Stars/Code/stars_editor_files.cmake
  Gems/Stars/Code/stars_editor_shared_files.cmake
  Gems/Stars/Code/stars_files.cmake
  Gems/Stars/Code/stars_headers_files.cmake
  Gems/Stars/Code/stars_shared_files.cmake
  Gems/Stars/Registry/assetprocessor_settings.setreg
  Gems/Stars/gem.json
  Gems/Stars/preview.png
  engine.json
Labels: sig/graphics-audio

#9077 Fixed git issue 8649 and 8647
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.h
Labels: feature/graphics

#9126 updating sphere_5lod asset to use Atom testdata version
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
Labels: sig/graphics-audio

#9072 Fix static AZ::Name in AtomSampleViewer
  Code/Framework/AzCore/AzCore/Name/Name.cpp
  Code/Framework/AzCore/AzCore/Name/Name.h
  Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
  Code/Framework/AzCore/AzCore/Name/NameDictionary.h
  Code/Framework/AzCore/Tests/Name/NameTests.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
Labels: sig/core, sig/graphics-audio

#9164 changed node value from a child to a property for better encapsulation
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/Tests/DocumentPropertyEditor/AdapterBuilderTests.cpp
  Code/Framework/AzFramework/Tests/DocumentPropertyEditor/CvarAdapterTests.cpp
Labels: sig/core, sig/ui-ux

#9030 Fixing RHI Validation Failures for Dummy Input Streams
  Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp
Labels: sig/graphics-audio

#8941 Removed Unused DecalFeatureProcessor
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Decals/DecalFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Decals/AsyncLoadTracker.h
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Decals/DecalComponentController.cpp
Labels: sig/graphics-audio

#9070 Controller for Normal Shadow Bias parameter of the
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PhotometricValue.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
Labels: sig/graphics-audio

#9039 Action Manager | Introduce Settings Registry key to disable legacy Action Manager
  Code/Editor/Core/LevelEditorMenuHandler.cpp
  Code/Editor/CryEditDoc.cpp
  Code/Editor/KeyboardCustomizationSettings.cpp
  Code/Editor/MainWindow.cpp
  Code/Editor/MainWindow.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/QuickAccessBar.cpp
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/ViewportTitleDlg.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/ActionManagerUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: feature/editor, sig/content

#9172 Cherry-Pick Fix For Inconsistent Depth Calculations
  Gems/Atom/Feature/Common/Assets/Materials/Types/DepthPass_WithPS.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedSurface_ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EnhancedParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
Labels: sig/graphics-audio

#9170 Fixing a test model reference for sphere_5lod that fails AR in stabilization/2205
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
Labels: sig/graphics-audio

#8809 First pass of terrain shutdown optimizations. Fixed bug with physics terrain still active when terrain system is disabled
  Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
  Gems/LmbrCentral/Code/Source/Shape/BoxShape.cpp
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
  Gems/PhysX/Code/Source/HeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/HeightfieldColliderComponent.h
  Gems/PhysX/Code/Tests/EditorHeightfieldColliderComponentTests.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
  Gems/Terrain/Code/Tests/TerrainHeightGradientListTests.cpp
  Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
Labels: sig/content, sig/core, feature/terrain

#9040 Asset processor unit test error fixes
  Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
  Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp
Labels: sig/content

#9104 Material Canvas: Initial implementation of data driven graph model node
  Gems/Atom/Tools/AtomToolsFramework/Code/CMakeLists.txt
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNode.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeConfig.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManager.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodePaletteItem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeSlotConfig.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNode.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeManager.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodePaletteItem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeSlotConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/AtomToolsFramework/gem.json
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/add_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/blank.materialcanvastemplate.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/combine_color_channels.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/divide_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/multiply_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/split_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/subtract_color.materialcanvasnode.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Code/CMakeLists.txt
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasGraphDataTypes.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasGraphDataTypes.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasTestData.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasTestData.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasUtil.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/MaterialCanvas/Code/materialcanvas_files.cmake
  Gems/GraphModel/Code/Include/GraphModel/Model/DataType.h
  Gems/GraphModel/Code/Source/Model/DataType.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9136 Atom Tools: Adding test output redirect functions for QA
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9113 Fix lyn12116 test chunks crash (#9056)
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
Labels: sig/core

#9135 Fixed inconsistent depth calculations that resulted in noisy clipping…
  Gems/Atom/Feature/Common/Assets/Materials/Types/DepthPass_WithPS.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedSurface_ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EnhancedParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
Labels: sig/graphics-audio

#8940 Remove unused and partially implemented delete entities API
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/EditorEntityManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteTests.cpp
Labels: sig/content, sig/core

#9177 Cherry picking material editor bug fixes into stabilization
  Gems/Atom/Feature/Common/Registry/system_materials.setreg
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentNotificationBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/TestUtils/AssetSystemStub.h
  Gems/Atom/Utils/Code/Source/TestUtils/AssetSystemStub.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Resources/AtomLyIntegrationResources.qrc
  Gems/AtomLyIntegration/CommonFeatures/Code/Resources/Icons/material.svg
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.cpp
  Gems/Terrain/Registry/system_materials.setreg
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9074 Extending Reflection Probe component null renderer tests for P1 coverage
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_ReflectionProbeAdded.py
Labels: sig/graphics-audio

#9132 Material Canvas: Implemented document serialization, graph saving and loading
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/blank.materialcanvastemplate.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9182 Crash when baking a Reflection Probe (GPU device removed)
  Gems/Atom/Feature/Common/Assets/Passes/EnvironmentCubeMapPipeline.pass
Labels: sig/graphics-audio

#8892 converted AssetScannerUnitTest from the legacy test framework
  Code/Tools/AssetProcessor/native/unittests/AssetScannerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetScannerUnitTests.h
Labels: sig/content

#9023 moving AssetProcessorServerUnitTest out of legacy framework
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorServerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorServerUnitTests.h
Labels: sig/content

#9174 Change FindReflectionProbes to use the scene VisibilitySystem
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ReflectionProbe/ReflectionProbeFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RenderCommon.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.h
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.cpp
Labels: sig/graphics-audio

#9145 bugfix: resolve tab order problem with component window for propertyAssetCtrl
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
Labels: sig/content

#9208 Fix typos in lighting preset exposure control edit context descriptions
  Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#9196 Added property control for AZ::IO::Path
  Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyFilePathCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyFilePathCtrl.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content

#9198 Bug fix for asset appearing multiple times in material editor asset selectors
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9207 Fix material editor toolbar icon and tooltips for tonemapping button
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/Icons/toneMapping.svg
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/Icons/toneMapping.svg
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9014 Stramer/clean urls 2205 stabilization
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/fbx_tests.py
  Code/Editor/CryEdit.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Framework/AzCore/AzCore/Component/Component.h
  Code/Framework/AzCore/AzCore/EBus/BusImpl.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp
  Gems/LyShine/Code/Editor/Animation/UiAVTrackEventKeyUIControls.h
  Gems/LyShine/Code/Editor/EditorMenu.cpp
  Gems/LyShine/Code/Editor/FeedbackDialog.cpp
  Gems/LyShine/Code/Editor/FeedbackDialog.h
  Gems/LyShine/Code/lyshine_uicanvaseditor_files.cmake
Labels: sig/content

#9140 Use VP9 WebM by default for video encoding
  Code/Editor/Plugins/FFMPEGPlugin/FFMPEGPlugin.cpp
  Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
Labels: sig/core, sig/graphics-audio

#9238 Fix multiple issues with material overrides updating or previewing consistently
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9230 Double fix for stabilization branch
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ParallaxInput.azsli
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Labels: feature/graphics/rpi

#9240 [Terrain] Add bilinear and trilinear sampling and switched to ClipmapBounds
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
Labels: sig/content, sig/graphics-audio, feature/terrain

#9237 Fixing SpawnableScriptAssetRef display in SC
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.cpp
Labels: sig/content, sig/core

#9284 Change default irradiance color source to Manual
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/IrradiancePropertyGroup.json
Labels: sig/graphics-audio

#9218 Animation Editor: Moved motion event properties to unified inspector window
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventWidget.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventsPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventsPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TimeViewPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TimeViewPlugin.h
Labels: feature/animation, sig/content

#9195 Diffuse Probe Grid P1 null renderer test expansion
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DiffuseProbeGridAdded.py
Labels: sig/graphics-audio

#9229 Default test results into build directory, warn when unset
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
  Tools/LyTestTools/tests/unit/test_fixtures.py
Labels: sig/testing
