Repository o3de/o3de, pull requests merged in 2022-11, with the labels that each got.

#12826 Various multiplayer scripting improvements
  Gems/Multiplayer/Assets/TranslationAssets/AZEvents/MultiplayerTeleportNotifyEvent.names
  Gems/Multiplayer/Assets/TranslationAssets/AZEvents/OnResetCountChangedEvent.names
  Gems/Multiplayer/Assets/TranslationAssets/Classes/NetworkTransformComponent.names
  Gems/Multiplayer/Assets/TranslationAssets/Classes/NetworkTransformComponentBase.names
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkTransformComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/NetworkRigidBodyComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/AutoGen/NetworkTransformComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/ScriptCanvasMultiplayer/Assets/TranslationAssets/Nodes/IfEntityMultiplayerRole_B856E81C-4969-E7C6-3483-3A7F24965CE0.names
  Gems/ScriptCanvasMultiplayer/Assets/TranslationAssets/Nodes/IfMultiplayerAgentType_ECBE9056-5EB3-AA98-AFB8-EC57E6C1BEA6.names
  Gems/ScriptCanvasMultiplayer/CMakeLists.txt
  Gems/ScriptCanvasMultiplayer/Code/CMakeLists.txt
  Gems/ScriptCanvasMultiplayer/Code/Source/Nodes/Nodeables/IfAgentTypeNodeable.ScriptCanvasNodeable.xml
  Gems/ScriptCanvasMultiplayer/Code/Source/Nodes/Nodeables/IfAgentTypeNodeable.cpp
  Gems/ScriptCanvasMultiplayer/Code/Source/Nodes/Nodeables/IfAgentTypeNodeable.h
  Gems/ScriptCanvasMultiplayer/Code/Source/Nodes/Nodeables/IfNetRoleNodeable.ScriptCanvasNodeable.xml
  Gems/ScriptCanvasMultiplayer/Code/Source/Nodes/Nodeables/IfNetRoleNodeable.cpp
  Gems/ScriptCanvasMultiplayer/Code/Source/Nodes/Nodeables/IfNetRoleNodeable.h
  Gems/ScriptCanvasMultiplayer/Code/Source/ScriptCanvasMultiplayerModule.cpp
  Gems/ScriptCanvasMultiplayer/Code/Source/ScriptCanvasMultiplayerSystemComponent.cpp
  Gems/ScriptCanvasMultiplayer/Code/Source/ScriptCanvasMultiplayerSystemComponent.h
  Gems/ScriptCanvasMultiplayer/Code/scriptcanvas_autogen_files.cmake
  Gems/ScriptCanvasMultiplayer/Code/scriptcanvas_multiplayer_files.cmake
  Gems/ScriptCanvasMultiplayer/Code/scriptcanvas_multiplayer_shared_files.cmake
  Gems/ScriptCanvasMultiplayer/gem.json
  Gems/ScriptCanvasMultiplayer/preview.png
  engine.json
Labels: sig/network

#12765 bugfix(UI Editor): prevent zoom when canvas window loses focus
  Gems/LyShine/Code/Editor/ViewportInteraction.cpp
Labels: sig/content, feature/lyshine

#12709 {lyn98594} flag for the cached assets
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCJobTest.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qrc
  Code/Tools/AssetProcessor/native/ui/style/cached_asset_item.png
Labels: feature/asset-pipeline, sig/content

#12881 Asset Browser: add placeholders for new design
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
Labels: feature/asset-browser

#12607 Migrate asset processor manager unit tests to the modern test framework
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.h
  Code/Tools/AssetProcessor/native/unittests/MockApplicationManager.cpp
  Code/Tools/AssetProcessor/native/unittests/MockApplicationManager.h
  Code/Tools/AssetProcessor/native/unittests/MockConnectionHandler.h
Labels: feature/asset-pipeline

#12929 Moved ScriptCanvasMultiplayer gem to be a sub-gem of Multiplayer gem
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Assets/TranslationAssets/Nodes/IfEntityMultiplayerRole_B856E81C-4969-E7C6-3483-3A7F24965CE0.names
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Assets/TranslationAssets/Nodes/IfMultiplayerAgentType_ECBE9056-5EB3-AA98-AFB8-EC57E6C1BEA6.names
  Gems/Multiplayer/Multiplayer_ScriptCanvas/CMakeLists.txt
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/CMakeLists.txt
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/Nodes/Nodeables/IfAgentTypeNodeable.ScriptCanvasNodeable.xml
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/Nodes/Nodeables/IfAgentTypeNodeable.cpp
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/Nodes/Nodeables/IfAgentTypeNodeable.h
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/Nodes/Nodeables/IfNetRoleNodeable.ScriptCanvasNodeable.xml
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/Nodes/Nodeables/IfNetRoleNodeable.cpp
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/Nodes/Nodeables/IfNetRoleNodeable.h
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/ScriptCanvasMultiplayerModule.cpp
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/ScriptCanvasMultiplayerSystemComponent.cpp
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/Source/ScriptCanvasMultiplayerSystemComponent.h
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/scriptcanvas_autogen_files.cmake
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/scriptcanvas_multiplayer_files.cmake
  Gems/Multiplayer/Multiplayer_ScriptCanvas/Code/scriptcanvas_multiplayer_shared_files.cmake
  Gems/Multiplayer/Multiplayer_ScriptCanvas/gem.json
  Gems/Multiplayer/Multiplayer_ScriptCanvas/preview.png
  Gems/Multiplayer/gem.json
  engine.json
Labels: sig/network

#12757 Refactor and break the AP state data unit tests
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
Labels: feature/asset-pipeline, sig/content

#12171 Enable ray query and shader int64 atomics Vulkan device features
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
Labels: sig/graphics-audio

#12710 Add Radeon GPU analyzer tool and integrate to Asset Processor
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderVariantListSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderVariantListSourceData.cpp
  cmake/3rdParty.cmake
  cmake/3rdParty/FetchRGA.cmake
Labels: sig/graphics-audio

#12882 Camera settings improvement
  Code/Editor/EditorModularViewportCameraComposer.cpp
  Code/Editor/EditorPreferencesPageViewportCamera.cpp
  Code/Editor/EditorPreferencesPageViewportCamera.h
  Code/Editor/EditorViewportSettings.cpp
  Code/Editor/EditorViewportSettings.h
  Code/Editor/Lib/Tests/Camera/test_EditorCamera.cpp
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/ViewportTitleDlg.h
  Code/Framework/AzFramework/Tests/Utils/Printers.cpp
  Code/Framework/AzFramework/Tests/Utils/Printers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.h
Labels: sig/content, feature/viewport, status/needs-ux-approval

#10710 bugfix(Whitebox): fix crash where default_shapes.py is run with invalid arguments
  Gems/WhiteBox/Code/Source/WhiteBoxToolApiReflection.cpp
  Gems/WhiteBox/Editor/Scripts/default_shapes.py
Labels: feature/whitebox, sig/content

#12987 Asset processor test perforce check fix
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
  Tools/LyTestTools/ly_test_tools/o3de/pipeline_utils.py
Labels: feature/asset-pipeline

#12766 refactor(UI Canvas): remove crylegacy Vec2i and simplify pivot logic for SetCanvasToViewportScale
  Gems/LyShine/Code/Editor/ViewportInteraction.cpp
  Gems/LyShine/Code/Editor/ViewportInteraction.h
Labels: sig/content

#12833 bugfix(Whitebox): add disable state for button cluster
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
Labels: feature/whitebox

#12828 Asset Processor - Fix missing qRegisterMetaType call for SourceAssetReference
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
Labels: feature/asset-pipeline, sig/content

#12750 Removed duplicate test that was failing on Linux.
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/TestSuite_Periodic.py
Labels: feature/asset-pipeline, sig/content

#12953 Averaging metrics per save period
  Gems/Multiplayer/Code/Source/MultiplayerStatSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerStatSystemComponent.h
Labels: sig/network

#12988 Fix reflected property editor crash adding new elements to container types
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorApi.cpp
Labels: sig/content, sig/graphics-audio

#13012 Fixed a case sensitivity bug in MaterialTypeBuilder on Linux.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
Labels: sig/graphics-audio

#12836 bugfix(Whitebox): fix uniform scale for manipulator mode
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
Labels: feature/whitebox, kind/bug

#13016 Fix compile error that toolId was unused
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
Labels: sig/graphics-audio

#13052 Fix miscellaneous minor Multiplayer Gem issues
  Code/Framework/AzFramework/AzFramework/Components/TransformComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
Labels: sig/network

#12992 AWSCore: fix unit tests and handling of platform value
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionManager.cpp
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionManager.h
  Gems/AWSCore/Code/Source/Editor/Attribution/AWSCoreAttributionMetric.h
  Gems/AWSCore/Code/Tests/Editor/Attribution/AWSCoreAttributionManagerTest.cpp
  Gems/AWSCore/Code/Tests/Editor/UI/AWSCoreResourceMappingToolActionTest.cpp
  Gems/AWSCore/Code/Tests/TestFramework/AWSCoreFixture.h
Labels: feature/cloud-service, sig/network

#12506 Prefab | Improve create prefab code in public handler
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteTests.cpp
Labels: sig/content, feature/prefabs

#12761 Improve prefab instance API and add Doxygen comments
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EditorInfoRemover.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateWithPatchesTests.cpp
  Code/Tools/SerializeContextTools/SliceConverter.cpp
Labels: sig/content, feature/prefabs

#13027 Asset Processor - Disable file state cache for asset processor batch
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.h
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.h
Labels: feature/asset-pipeline, sig/content

#13051 Asset Processor - Fix APB early termination
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
Labels: feature/asset-pipeline, sig/content

#13072 Adds application frametime to multiplayer metrics
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerMetrics.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerStats.h
  Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
  Gems/Multiplayer/Code/multiplayerstats_api_files.cmake
Labels: sig/network

#12722 Update Multiplayer IMGUI to Suggest Hosting a Level if No Level Loaded
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
Labels: sig/network

#13087 Asset Processor - Fix crash due to referencing out of scope captured pointer
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Labels: feature/asset-pipeline, sig/content

#12994 Null renderer Directional Light automation
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DirectionalLightAdded.py
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Labels: sig/graphics-audio, sig/testing

#13076 {ghi12844} fixing the product asset reference for procedural prefab
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterDocument.cpp
  Code/Editor/Plugins/EditorAssetImporter/SceneSerializationHandler.cpp
  Code/Editor/Plugins/EditorAssetImporter/SceneSerializationHandler.h
  Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
  Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.h
  Code/Tools/SceneAPI/SceneCore/Events/SceneSerializationBus.h
  Code/Tools/SceneAPI/SceneCore/Tests/Events/AssetImporterRequestTests.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MetaDataRule.inl
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Commands.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneSerializationHandler.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneSerializationHandler.h
  Gems/SceneProcessing/Code/Tests/SceneBuilder/SceneBuilderPhasesTests.cpp
Labels: feature/prefabs, feature/scene-pipeline

#13090 RHI/Vulkan: Fix error message in ImageView.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.cpp
Labels: sig/graphics-audio

#12898 Address serveral issues in SMC
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
  Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py
Labels: sig/graphics-audio

#13138 Fix for linux unused compile error on Linux
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
Labels: sig/graphics-audio

#13030 Improve separator rendering in Breadcrumbs
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/img/UI20/Breadcrumb/Next_level_arrow.svg
  Code/Framework/AzQtComponents/AzQtComponents/Components/resources.qrc
Labels: sig/ui-ux

#13018 Turned off a test on Linux that was failing because file permissions …
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
  Tools/LyTestTools/ly_test_tools/environment/file_system.py
Labels: sig/content

#13116 AZ Networking ISerialize Support for AZ::s64 and AZ::u64
  Code/Framework/AzNetworking/AzNetworking/Serialization/ISerializer.h
  Code/Framework/AzNetworking/AzNetworking/Serialization/ISerializer.inl
Labels: sig/network

#13133 Fixes a crash on AP shutdown
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
Labels: feature/asset-pipeline, sig/content

#13153 Material Canvas: Center and show entire graph when first opened + other fixes
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManager.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManagerRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNode.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeManager.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodePaletteItem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Constants/color.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Constants/float3.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Constants/float3x3.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Constants/float4.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Constants/float4x3.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Constants/float4x4.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/cross.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/split3.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/transform3.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/transform4.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/experimental_pbr.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/experimental_pbr.materialgraphtemplate
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocumentNotificationBus.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasTestData.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.h
  Gems/GraphModel/Code/Source/Model/Slot.cpp
Labels: sig/content, sig/graphics-audio

#12958 CVE-2007-4559 Patch
  Tools/LyTestTools/ly_test_tools/environment/file_system.py
Labels: sig/security, sig/testing

#13125 Asset Processor - Fix missing scanfolder crash
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.cpp
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
Labels: feature/asset-pipeline, sig/content

#13156 Calling asset bundler in bundle mode with an invalid asset list file now reports an error instead of silently doing nothing.
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_bundler_batch_tests.py
  Code/Tools/AssetBundler/source/utils/applicationManager.cpp
Labels: feature/asset-pipeline, sig/content

#13170 Organizational updates and test fix for Prefab TestSuite_Periodic
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
  AutomatedTesting/Levels/Prefab/SC_Spawnables_MultipleSpawnsFromSingleTicket/SC_Spawnables_MultipleSpawnsFromSingleTicket.prefab
Labels: sig/content, feature/prefabs

#12927 Added missing sandbox definitions for asset processing tests.
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
Labels: feature/asset-pipeline

#11862 O3de extras ar
  AutomatedTesting/project.json
  scripts/build/Jenkins/Jenkinsfile
  scripts/build/Jenkins/o3de.json
  scripts/o3de/o3de/register.py
Labels: sig/build, sig/core

#13171 [Prefab Overrides] Add support for delete entity and prefab as override
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntityAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoBase.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoBase.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content, feature/prefabs

#13214 Asset Processor - Avoid FindFirstMatchingFile on absolute path
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
Labels: feature/asset-pipeline, sig/content

#13244 Updates android project generation scripts
  Code/Tools/Android/ProjectBuilder/build.gradle.in
  cmake/LYTestWrappers.cmake
  cmake/Platform/Android/PAL_android.cmake
  cmake/Tools/Platform/Android/android_support.py
  cmake/Tools/Platform/Android/generate_android_project.py
Labels: platform/android, sig/platform

#12975 Multiplayer Component Version Mismatch Detection
  Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPackets_Header.jinja
  Code/Framework/AzNetworking/AzNetworking/Serialization/AzContainerSerializers.h
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponentRegistry.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerDebug.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h
  Gems/Multiplayer/Code/Source/AutoGen/Multiplayer.AutoPackets.xml
  Gems/Multiplayer/Code/Source/Components/MultiplayerComponentRegistry.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
  cmake/AzAutoGen.py
Labels: feature/networking, sig/network

#13241 New automated tests for delete entity or prefab as overrides
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/PrefabTestUtils.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeleteEntity_UnderImmediateInstance.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeleteEntity_UnderNestedInstance.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeletePrefab_UnderImmediateInstance.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/overrides/DeletePrefab_UnderNestedInstance.py
Labels: sig/content, feature/prefabs

#13186 Material Canvas: Remove material hot reload notification bus from material system classes and assets
  Code/Framework/AtomCore/AtomCore/Instance/InstanceDatabase.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Material/Material.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Material/MaterialReloadNotificationBus.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroup.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAsset.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
Labels: sig/graphics-audio

#13253 Material Canvas: Improving startup time
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetSelection/AssetSelectionComboBox.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetSelection/AssetSelectionGrid.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/acos.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg
  Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg
  Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
Labels: sig/content, sig/graphics-audio

#12343 {lyn14508} scene builder script configuration
  Code/Tools/SceneAPI/SceneCore/Events/ScriptConfigEventBus.h
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.h
  Code/Tools/SceneAPI/SceneData/CMakeLists.txt
  Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneManifestRuleTests.cpp
  Gems/SceneProcessing/Code/Source/Config/Components/SceneProcessingConfigSystemComponent.cpp
  Gems/SceneProcessing/Code/Source/Config/Components/SceneProcessingConfigSystemComponent.h
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.h
  Gems/SceneProcessing/Code/Tests/InitSceneAPIFixture.h
  Gems/SceneProcessing/Code/Tests/SceneBuilder/SceneBuilderConfigTests.cpp
  Gems/SceneProcessing/Code/Tests/SceneBuilder/SceneBuilderTests.cpp
  Gems/SceneProcessing/Code/sceneprocessing_editor_tests_files.cmake
Labels: sig/content, feature/scene-pipeline

#13181 Asset Processor - Clean up inconsistencies in GetSource* APIs
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/PathDependencyManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
Labels: feature/asset-pipeline, sig/content

#13261 Prefab Bug Fix - Remove unexpected transform update of container entity for add-entity
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp
Labels: kind/bug, sig/content

#13211 Connect PrefabTestFixture to EditorRequestBus
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
  Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabOverrideTestFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDuplicateTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabFocus/PrefabFocusTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstantiateTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoAddEntityTestFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateInstancesTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateTemplateTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateWithPatchesTests.cpp
  Code/Framework/AzToolsFramework/Tests/TransformComponent.cpp
  Code/Framework/AzToolsFramework/Tests/UI/EntityOutlinerTests.cpp
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewBookmarkTests.cpp
Labels: sig/content

#13316 Add logger config to Multiplayer gem and shorted AppFrametime metrics…
  Gems/Multiplayer/Code/Source/MultiplayerStatSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#13237 Enable View Switcher without Search Text
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
Labels: sig/content, feature/asset-browser

#13293 The browse action on the motion set window should point to the source folder
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetWindow.cpp
Labels: feature/animation

#13287 Switch to reset deleted entity in prefab delete-entity operation
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: sig/content

#13175 Asset Processor - Metadata System
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/MetadataManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
  Code/Tools/AssetProcessor/AssetBuilder/AssetBuilderApplication.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp
Labels: feature/asset-pipeline, sig/content

#13306 Material Canvas: New app icon
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Platform/Windows/MaterialCanvas.ico
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/Icons/application.svg
  Gems/Atom/Tools/MaterialCanvas/preview.svg
Labels: sig/content, sig/graphics-audio

#13301 Material Canvas: Renaming material template nodes to material output nodes and support for material graph node templates
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsAnyDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/StyleSheet/materialcanvas_style.json
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName.material
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName.materialtype
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_Common.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_DepthPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_DepthPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_ForwardPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_ForwardPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_ShadowPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/MaterialGraphName_ShadowPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/experimental_pbr.materialgraphnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialOutputs/ExperimentalPBR/experimental_pbr.materialgraphtemplate
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/blank_node.materialgraphnodetemplate
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/material_input_node.materialgraphnodetemplate
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/material_output_node.materialgraphnodetemplate
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/blank_graph.materialgraphtemplate
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
Labels: sig/content, sig/graphics-audio

#13300 Material Canvas: Revision to previous change improving preset enumeration startup times
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialEditor/Assets/MaterialEditor/LightingPresets/_TEMPLATE_.lightingconfig.json.template
Labels: sig/content, sig/graphics-audio

#13082 Added a flag to disable shadow casting on the core material types.
  Gems/Atom/Feature/Common/Assets/Materials/Special/ShadowCatcher.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/BasePBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/CastShadows.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/GeneralCommonPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ShaderEnable.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ShaderEnable.lua
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DirectionalLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialPropertyDescriptor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialTypeAssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialPropertyConnectionSerializer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialPropertyDescriptor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialTypeAssetCreator.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialPropertySerializerTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeAssetTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
Labels: sig/graphics-audio

#13302 Added render pipeline selection to Material Editor.
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/LightingPreset.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/ModelPreset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/System/RenderPipelineDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportScene.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsNotificationBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportToolBar.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportScene.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportToolBar.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportWidget.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
Labels: sig/graphics-audio

#13164 Jjjoness/drag and drop in asset browser 4962
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntryCache.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntryCache.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntryUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/FolderAssetBrowserEntry.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/FolderAssetBrowserEntry.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
Labels: sig/content, feature/asset-browser

#13103 Multiplayer Version Mismatch: AZ::Events and Debug Viewport Messaging
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
Labels: sig/network, WF6

#13347 Material Canvas: Fixing graph canvas crashes on shut down
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_MaterialCanvas_01.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_tools_utils.py
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.cpp
Labels: sig/content, sig/graphics-audio

#13357 EMFX: Improve the solid skeleton render
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
Labels: feature/animation

#13315 Change label in motion sets editor
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp
Labels: sig/content, sig/simulation

#13379 Enabled the material pipeline for the Automated Testing project
  AutomatedTesting/Registry/material_pipelines.setreg
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.h
Labels: sig/graphics-audio

#13173 {ghi13064} protect large file copies for AP
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
Labels: feature/asset-pipeline, sig/content

#13323 Asset Processor GUI tests now pass on Linux + Windows
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests.py
Labels: feature/asset-pipeline

#13351 Asset Processor - Fix absolute path source dependency handling
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
Labels: feature/asset-pipeline, sig/content

#13377 Promoting several consistently passing tests to the main suite
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
Labels: sig/content, feature/prefabs

#13414 Add missing reflection of AZ::Component base class for MetadataManager
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
Labels: feature/asset-pipeline, sig/content

#13418 [Issue Template] Remove duplicated security policy lines
  .github/ISSUE_TEMPLATE/config.yml
Labels: sig/security

#13341 Added launcher as a dependency for AP GUI tests that use it
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
Labels: feature/asset-pipeline, sig/content

#13405 Material Canvas: Fixing creation and serialization of node groups, bookmarks, comments
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Types/ConstructPresets.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Types/ConstructPresets.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/ConstructMenuActions/ConstructPresetMenuActions.cpp
  Gems/GraphModel/Code/Include/GraphModel/Integration/GraphCanvasMetadata.h
  Gems/GraphModel/Code/Source/Integration/GraphCanvasMetadata.cpp
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
  Gems/ScriptCanvas/Code/Editor/Settings.cpp
Labels: sig/content, sig/graphics-audio

#13215 Refactor ScriptCanvas_ChangingAssets_ComponentStable and remove Hydra dependancy
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/editor_component_validation.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/editor_script_canvas.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvas_ChangingAssets_ComponentStable.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/VariableManager_ExposeVarsToComponent.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/script_canvas_component.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
Labels: feature/scripting, sig/testing

#13443 Mac build fixes to do with long being 64 bits on Mac and 32 bits elsewhere.
  Gems/Atom/RHI/Metal/Code/Source/RHI/BindlessArgumentBuffer.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/ClothJointWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/HitDetectionJointWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/RagdollNodeWidget.cpp
Labels: sig/platform

#13417 {lyn15164} auto test for the default scene script feature
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/default_script/cube_icosphere.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/default_script/default_script.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/default_script/default_script.setreg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/scene_scripting_tests.py
Labels: sig/content, feature/scene-pipeline

#13378 Prefab API | Rename CreatePrefabInDisk to CreatePrefabAndSaveToDisk
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Labels: sig/content, feature/prefabs

#13403 Toggle Filter For Project and Source Assets
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.h
Labels: sig/content, feature/asset-browser
