Repository o3de/o3de, pull requests merged in 2022-01, with the labels that each got.

#6485 AP: Load QIcons once for asset tree and share with each Asset Tree Item t…
  Code/Tools/AssetProcessor/native/ui/AssetTreeItem.cpp
  Code/Tools/AssetProcessor/native/ui/AssetTreeItem.h
  Code/Tools/AssetProcessor/native/ui/AssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/AssetTreeModel.h
Labels: sig/content

#6603 Fix Network Binding Component Icon
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Labels: sig/network, sig/ui-ux

#6442 ActorInstanceId default to -1 when no %lastresult matches
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/ActorInstanceCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AnimGraphCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/ActorManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/ActorManager.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
  Gems/EMotionFX/Code/MCore/Source/MCoreCommandManager.cpp
Labels: feature/animation, sig/content

#6496 chore: add assertions to plane to ensure normalization
  Code/Framework/AzCore/AzCore/Math/Plane.inl
Labels: sig/core

#6480 [AudioSystem] Audio Controls Editor minor improvements.
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorMainWindow.ui
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorWindow.h
Labels: feature/audio, kind/bug, pr-ready-to-merge, sig/graphics-audio, sig/ui-ux

#6290 Parameters of LOD distance component still take effect when anim graph disabled
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleLODComponent.cpp
Labels: sig/content

#6590 [MacOS] Fix crash caused by trying to dereference a nullptr
  Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp
Labels: sig/graphics-audio

#6518 Define AWSI automation tests pipe for Jenkins
  scripts/build/Platform/Linux/build_config.json
  scripts/build/Platform/Linux/deploy_cdk_applications.sh
  scripts/build/Platform/Linux/destroy_cdk_applications.sh
  scripts/build/Platform/Linux/pipeline.json
Labels: sig/network

#6287 Illegal exe name and version no. when opening Project Settings Tool
  AutomatedTesting/project.json
Labels: sig/platform

#6490 Fix for file-save-as-new and open asset
  Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Labels: sig/content

#6592 IMGui: Enabling Default Clipboard Functions
  Gems/ImGui/Code/Source/Platform/Windows/imgui_windows.cmake
Labels: sig/content

#6616 Add benchmarks to GradientSignal.
  Gems/GradientSignal/Code/CMakeLists.txt
  Gems/GradientSignal/Code/Include/GradientSignal/ImageAsset.h
  Gems/GradientSignal/Code/Tests/EditorGradientSignalPreviewTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalBenchmarks.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalReferencesTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalServicesTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalSurfaceTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTest.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.h
  Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.h
  Gems/GradientSignal/Code/Tests/GradientSignalTransformTests.cpp
  Gems/GradientSignal/Code/gradientsignal_editor_tests_files.cmake
  Gems/GradientSignal/Code/gradientsignal_tests_files.cmake
Labels: sig/content

#6620 Removed legacy QtUi/ClickableLabel and re-worked the About dialog accordingly
  Code/Editor/AboutDialog.cpp
  Code/Editor/AboutDialog.h
  Code/Editor/AboutDialog.ui
  Code/Editor/Lib/Tests/test_ClickableLabel.cpp
  Code/Editor/QtUI/ClickableLabel.cpp
  Code/Editor/QtUI/ClickableLabel.h
  Code/Editor/editor_lib_files.cmake
  Code/Editor/editor_lib_test_files.cmake
Labels: sig/content

#6300 Script Canvas Groups
  Code/Editor/EditorPanelUtils.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/AssetEditorToolbar/AssetEditorToolbar.ui
Labels: sig/content

#6613 EMotion FX: Linear and angular velocity calculation and debug visualization helpers
  Gems/EMotionFX/Code/EMotionFX/Source/Velocity.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Velocity.h
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
Labels: feature/animation

#6437 chore[EmotionFX]: replace usage of SafeNormalize
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFootIKNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTwoLinkIKNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Mesh.cpp
  Gems/EMotionFX/Code/MCore/Source/Vector.h
Labels: sig/content

#6519 Adding better decal culling
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl
Labels: feature/graphics, sig/graphics-audio

#6181 Adding cascade blending for pcf
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DirectionalLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Labels: sig/graphics-audio

#6570 ProcessWatcher fixes.
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Code/Framework/AzFramework/Platform/Common/Default/AzFramework/Process/ProcessWatcher_Default.cpp
Labels: sig/core

#6571 Reflow Project Tiles Everytime They Are Updated
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: sig/content

#6426 Make 'test_WindowsMacPlatforms_MoveCorruptedSliceFile_MoveSuccess' to use prefab instead
  AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/clear_moveoutput_fixture.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C21968388/DependencyScannerAsset.prefab
Labels: sig/content

#6365 Temporary fix for material component losing image overrides with prefabs
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Labels: sig/graphics-audio

#6674 Removed unused bone name class.
  Code/Editor/Animation/AnimationBipedBoneNames.cpp
  Code/Editor/Animation/AnimationBipedBoneNames.h
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#6505 Wind bug
  Gems/PhysX/Code/Source/WindProvider.cpp
Labels: sig/core

#6675 Removed unused images under Editor/Common
  Code/Editor/Common/spline_edit-00.png
  Code/Editor/Common/spline_edit-01.png
  Code/Editor/Common/spline_edit-02.png
  Code/Editor/Common/spline_edit-03.png
  Code/Editor/Common/spline_edit-04.png
  Code/Editor/Common/spline_edit-05.png
  Code/Editor/Common/spline_edit-06.png
  Code/Editor/Common/spline_edit-07.png
  Code/Editor/Common/spline_edit-08.png
  Code/Editor/Common/spline_edit-09.png
  Code/Editor/Common/spline_edit-10.png
  Code/Editor/Common/spline_edit-11.png
  Code/Editor/Common/spline_edit-12.png
  Code/Editor/Common/spline_edit-13.png
  Code/Editor/Common/spline_edit-14.png
  Code/Editor/Common/spline_edit-15.png
  Code/Editor/Common/spline_edit-16.png
Labels: sig/content

#6618 Update to use AWSNativeSDK 1.9.50
  Code/Tools/AWSNativeSDKInit/include/AWSNativeSDKInit/AWSLogSystemInterface.h
  Code/Tools/AWSNativeSDKInit/include/AWSNativeSDKInit/AWSMemoryInterface.h
  Code/Tools/AWSNativeSDKInit/include/AWSNativeSDKInit/AWSNativeSDKInit.h
  Gems/AWSCore/Code/CMakeLists.txt
  Gems/AWSCore/Code/Platform/Windows/AWSCore_Traits_Windows.h
  Gems/AWSCore/Code/Tests/AWSCoreSystemComponentTest.cpp
  Gems/AWSCore/Code/Tests/Configuration/AWSCoreConfigurationTest.cpp
  Gems/AWSCore/Code/Tests/Credential/AWSCVarCredentialHandlerTest.cpp
  Gems/AWSCore/Code/Tests/Credential/AWSCredentialBusTest.cpp
  Gems/AWSCore/Code/Tests/Credential/AWSDefaultCredentialHandlerTest.cpp
  Gems/AWSCore/Code/Tests/Editor/Attribution/AWSAttributionServiceApiTest.cpp
  Gems/AWSCore/Code/Tests/Editor/Attribution/AWSCoreAttributionManagerTest.cpp
  Gems/AWSCore/Code/Tests/Framework/AWSApiClientJobConfigTest.cpp
  Gems/AWSCore/Code/Tests/Framework/AWSApiJobConfigTest.cpp
  Gems/AWSCore/Code/Tests/Framework/HttpRequestJobTest.cpp
  Gems/AWSCore/Code/Tests/Framework/JsonObjectHandlerTest.cpp
  Gems/AWSCore/Code/Tests/Framework/JsonWriterTest.cpp
  Gems/AWSCore/Code/Tests/Framework/RequestBuilderTest.cpp
  Gems/AWSCore/Code/Tests/Framework/ServiceClientJobConfigTest.cpp
  Gems/AWSCore/Code/Tests/Framework/ServiceJobUtilTest.cpp
  Gems/AWSCore/Code/Tests/Framework/ServiceRequestJobTest.cpp
  Gems/AWSCore/Code/Tests/Framework/UtilTest.cpp
  Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingManagerTest.cpp
  Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingUtilsTest.cpp
  Gems/AWSCore/Code/Tests/ScriptCanvas/AWSScriptBehaviorDynamoDBTest.cpp
  Gems/AWSCore/Code/Tests/ScriptCanvas/AWSScriptBehaviorLambdaTest.cpp
  Gems/AWSCore/Code/Tests/ScriptCanvas/AWSScriptBehaviorS3Test.cpp
  Gems/AWSCore/Code/Tests/ScriptCanvas/AWSScriptBehaviorsComponentTest.cpp
  Gems/AWSCore/Code/Tests/TestFramework/AWSCoreFixture.h
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: sig/network

#6516 Fix LyShine debug display to work with Atom
  Gems/LyShine/Code/Include/LyShine/Draw2d.h
  Gems/LyShine/Code/Source/Draw2d.cpp
  Gems/LyShine/Code/Source/RenderGraph.cpp
  Gems/LyShine/Code/Source/UiCanvasManager.cpp
  Gems/LyShine/Code/Source/UiRenderer.cpp
  Gems/LyShine/Code/Source/UiRenderer.h
Labels: sig/graphics-audio

#6639 EMotion FX: Extendable pose data and pose debug visualization
  Gems/EMotionFX/Code/EMotionFX/Source/EMotionFXManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/EMotionFXManager.h
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.h
  Gems/EMotionFX/Code/EMotionFX/Source/PoseData.h
  Gems/EMotionFX/Code/EMotionFX/Source/PoseDataFactory.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/PoseDataFactory.h
Labels: feature/animation, sig/content

#6292 Fix: Blend node applies both poses at value 1
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeBlendNNode.cpp
Labels: sig/content

#6682 Removed some unused classes from Editor/Controls
  Code/Editor/Controls/ConsoleSCBMFC.h
  Code/Editor/Controls/ConsoleSCBMFC.ui
  Code/Editor/Controls/HotTrackingTreeCtrl.cpp
  Code/Editor/Controls/HotTrackingTreeCtrl.h
  Code/Editor/Controls/ImageListCtrl.cpp
  Code/Editor/Controls/ImageListCtrl.h
  Code/Editor/Controls/MultiMonHelper.cpp
  Code/Editor/Controls/MultiMonHelper.h
  Code/Editor/Controls/NumberCtrl.cpp
  Code/Editor/Controls/NumberCtrl.h
  Code/Editor/Controls/TextEditorCtrl.cpp
  Code/Editor/Controls/TextEditorCtrl.h
  Code/Editor/Controls/TreeCtrlUtils.h
  Code/Editor/EditorPanelUtils.cpp
  Code/Editor/EditorPanelUtils.h
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/IEditorPanelUtils.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#6499 bugfix: update attenuation when light intensity changed for mode Automatic
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/AreaLightComponentController.cpp
Labels: sig/graphics-audio

#6685 Debug render aabb now include node, mesh and static aabb.
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderActorSettings.h
Labels: feature/animation

#6708 Removed unused Editor code from EditMode/Geometry/Include/LightmapCompiler
  Code/Editor/EditMode/DeepSelection.cpp
  Code/Editor/EditMode/DeepSelection.h
  Code/Editor/Geometry/TriMesh.cpp
  Code/Editor/Geometry/TriMesh.h
  Code/Editor/Include/HitContext.h
  Code/Editor/Include/IAnimationCompressionManager.h
  Code/Editor/Include/IAssetItem.h
  Code/Editor/Include/IAssetItemDatabase.h
  Code/Editor/Include/IAssetViewer.h
  Code/Editor/Include/IFileUtil.h
  Code/Editor/LightmapCompiler/SimpleTriangleRasterizer.cpp
  Code/Editor/LightmapCompiler/SimpleTriangleRasterizer.h
  Code/Editor/Objects/ObjectManager.cpp
  Code/Editor/Util/FileUtil.cpp
  Code/Editor/Util/FileUtil.h
  Code/Editor/Util/FileUtil_impl.cpp
  Code/Editor/Util/FileUtil_impl.h
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#6713 Move and convert ShadowTest level and include object files
  AutomatedTesting/Levels/Graphics/ShadowTest/ShadowTest.prefab
  AutomatedTesting/Levels/Graphics/ShadowTest/tags.txt
  AutomatedTesting/Objects/ShaderBall_simple.fbx
  AutomatedTesting/Objects/bunny.fbx
  AutomatedTesting/Objects/cone.fbx
  AutomatedTesting/Objects/cube.fbx
  AutomatedTesting/Objects/cylinder.fbx
  AutomatedTesting/Objects/plane.fbx
  AutomatedTesting/Objects/suzanne.fbx
Labels: sig/graphics-audio

#6726 Removed legacy editor DatabaseLibrary code.
  Code/Editor/BaseLibrary.cpp
  Code/Editor/BaseLibrary.h
  Code/Editor/BaseLibraryItem.cpp
  Code/Editor/BaseLibraryItem.h
  Code/Editor/BaseLibraryManager.cpp
  Code/Editor/BaseLibraryManager.h
  Code/Editor/ErrorRecorder.cpp
  Code/Editor/ErrorRecorder.h
  Code/Editor/ErrorReport.cpp
  Code/Editor/ErrorReport.h
  Code/Editor/ErrorReportDialog.cpp
  Code/Editor/ErrorReportTableModel.cpp
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Include/IBaseLibraryManager.h
  Code/Editor/Include/IDataBaseItem.h
  Code/Editor/Include/IDataBaseLibrary.h
  Code/Editor/Include/IDataBaseManager.h
  Code/Editor/Include/IEditorMaterial.h
  Code/Editor/Include/IEditorMaterialManager.h
  Code/Editor/Include/IErrorReport.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/Objects/EntityObject.h
  Code/Editor/Objects/ObjectLoader.h
  Code/Editor/TrackView/TrackViewSequence.h
  Code/Editor/TrackView/TrackViewSequenceManager.cpp
  Code/Editor/TrackView/TrackViewSequenceManager.h
  Code/Editor/Viewport.h
  Code/Editor/editor_core_files.cmake
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#6715 [Linux] Update to use AWSNativeSDK 1.9.50
  Gems/AWSCore/Code/Platform/Linux/AWSCore_Traits_Linux.h
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
Labels: sig/network

#6468 Spawnable Entity Alias improvements
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesManager.cpp
  Code/Framework/AzFramework/Tests/Spawnable/SpawnableEntitiesManagerTests.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EditorInfoRemover.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EditorInfoRemover.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EntityAliasTypes.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabCatchmentProcessor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabCatchmentProcessor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabDocument.inl
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabProcessorContext.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabProcessorContext.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/SpawnableUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Spawnable/SpawnAllEntitiesBenchmarks.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/SpawnableRemoveEditorInfoTestFixture.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.h
  Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp
  Gems/Prefab/PrefabBuilder/PrefabBuilderComponent.cpp
  Gems/Prefab/PrefabBuilder/PrefabBuilderComponent.h
  Gems/Prefab/PrefabBuilder/PrefabBuilderTests.cpp
  Gems/Vegetation/Code/Source/PrefabInstanceSpawner.cpp
Labels: sig/content

#6717 Improved DiffuseProbeGrid blending
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseComposite.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGrid.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGrid.h
Labels: sig/graphics-audio

#6546 Fixing character controller triggering collision on creation
  Gems/PhysX/Code/Source/PhysXCharacters/API/CharacterUtils.cpp
Labels: sig/core

#6740 Add missing `precise` attribute to depth prepass output
  Gems/Atom/Feature/Common/Assets/Shaders/Depth/DepthPassCommon.azsli
Labels: kind/bug, sig/graphics-audio

#6036 AssetBrowser SearchFilteringTest: Added delay when inserting a string to the search file.
  AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetBrowser_SearchFiltering.py
Labels: feature/editor, kind/test, sig/content

#6493 bugfix: correct mouseMove under AzToolsFrameworkHelper
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
  Code/Framework/AzToolsFramework/Tests/AzToolsFrameworkTestHelpersTest.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content, feature/viewport

#6606 LYN-8935 Bundle Mode Test Update
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/bundle_mode_tests.py
  AutomatedTesting/Levels/TestDependenciesLevel/LevelData/Environment.xml
  AutomatedTesting/Levels/TestDependenciesLevel/LevelData/TerrainTexture.xml
  AutomatedTesting/Levels/TestDependenciesLevel/LevelData/TimeOfDay.xml
  AutomatedTesting/Levels/TestDependenciesLevel/LevelData/VegetationMap.dat
  AutomatedTesting/Levels/TestDependenciesLevel/TerrainTexture.pak
  AutomatedTesting/Levels/TestDependenciesLevel/TestDependenciesLevel.ly
  AutomatedTesting/Levels/TestDependenciesLevel/TestDependenciesLevel.prefab
  AutomatedTesting/Levels/TestDependenciesLevel/filelist.xml
  AutomatedTesting/Levels/TestDependenciesLevel/level.pak
Labels: sig/content

#6778 Removing redundant Editor test
  AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/smoke/Editor_NewExistingLevels_Works.py
  AutomatedTesting/Gem/PythonTests/smoke/test_Editor_NewExistingLevels_Works.py
Labels: sig/content

#6460 Fixed CMake use with Android NDK 23
  cmake/Platform/Android/Toolchain_android.cmake
  cmake/Tools/Platform/Android/android_support.py
  cmake/Tools/Platform/Android/generate_android_project.py
  scripts/build/Platform/Android/build_config.json
Labels: sig/build, sig/platform

#6788 LYN-9183 Fix Terrain Heightfield Collider component to list physics materials from the library
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
Labels: feature/physics, sig/core, feature/terrain

#6794 Move Material Editor Basic test from sandbox to main suite
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
Labels: sig/graphics-audio

#6819 Fixed tab order for default input focus on new level dialog
  Code/Editor/NewLevelDialog.cpp
  Code/Editor/NewLevelDialog.ui
Labels: sig/content

#6791 Moving AutomatedTesting Atom levels into the Graphics subfolder
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/PbrMaterialChart.prefab
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r00.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r01.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r02.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r03.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r04.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r05.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r06.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r07.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r08.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r09.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m00_r10.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r00.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r01.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r02.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r03.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r04.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r05.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r06.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r07.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r08.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r09.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/materials/basic_m10_r10.material
  AutomatedTesting/Levels/Graphics/PbrMaterialChart/tags.txt
  AutomatedTesting/Levels/Graphics/Sponza/Sponza.prefab
  AutomatedTesting/Levels/Graphics/Sponza/tags.txt
  AutomatedTesting/Levels/Graphics/macbeth_shaderballs/macbeth_shaderballs.prefab
  AutomatedTesting/Levels/Graphics/macbeth_shaderballs/tags.txt
Labels: sig/graphics-audio

#6797 [Mac] Update to use AWSNativeSDK 1.9.50
  Gems/AWSCore/Code/Platform/Mac/AWSCore_Traits_Mac.h
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
Labels: sig/network

#6825 Fixed test materials since all the "lucy" stuff was renamed to "hermanubis"
  Gems/Atom/TestData/TestData/Materials/SkinTestCases/001_hermanubis_regression_test.material
  Gems/Atom/TestData/TestData/Materials/SkinTestCases/002_wrinkle_regression_test.material
  Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/101_DetailMaps_BaseNoDetailMaps.material
  Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/102_DetailMaps_All.material
  Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/103_DetailMaps_BaseColor.material
  Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/104_DetailMaps_Normal.material
  Gems/Atom/TestData/TestData/Materials/StandardPbrTestCases/105_DetailMaps_BlendMaskUsingDetailUVs.material
Labels: sig/graphics-audio

#6721 Node name change cursor missing
  Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/AnimGraphNodeNameHandler.cpp
  Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/AnimGraphNodeNameHandler.h
Labels: sig/content

#6658 AnimAudioComponentRequestBus canvas script function failure
  Gems/EMotionFX/Code/Source/Integration/Components/AnimAudioComponent.cpp
Labels: pr-ready-to-merge, sig/content, sig/graphics-audio

#6837 Fixed depth clipping artifacts for parallax PDO.
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_DepthPass_WithPS.azsl
Labels: sig/graphics-audio

#6654 Ragdoll saving issue
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
Labels: sig/content

#6660 Right hand bones misplaced
  Gems/EMotionFX/Code/EMotionFX/Rendering/Common/RenderUtil.cpp
Labels: sig/content

#6714 Crash log test tools bug
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_fixtures.py
  Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Labels: sig/testing

#6356 Removed file size limit on .shadervariantlist files.
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderVariantAssetBuilder.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/JsonUtils.h
Labels: sig/graphics-audio

#5221 Changed PassBuilder's job dependencies to be OrderOnce.
  Gems/Atom/RPI/Code/Source/RPI.Builders/Pass/PassBuilder.cpp
Labels: sig/graphics-audio

#6617 Update behavior reflection of EMotionFX's MotionEvent to use nullptr …
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Labels: sig/content

#5939 Bug hide window
  Gems/AudioSystem/Code/Source/Editor/QConnectionsWidget.cpp
Labels: pr-ready-to-merge, sig/content, sig/core

#6882 Removed some unused EditorUtils functions
  Code/Editor/Util/EditorUtils.cpp
  Code/Editor/Util/EditorUtils.h
  Gems/LyShine/Code/Editor/Animation/Util/UiEditorUtils.cpp
Labels: sig/content

#6884 Add SetEnv and UnSetEnv for environment variable to util
  Code/Framework/AzTest/AzTest/Platform/Android/platform_android_files.cmake
  Code/Framework/AzTest/AzTest/Platform/Common/Unimplemented/AzTest/Utils_Unimplemented.cpp
  Code/Framework/AzTest/AzTest/Platform/Common/UnixLike/AzTest/Utils_UnixLike.cpp
  Code/Framework/AzTest/AzTest/Platform/Common/WinAPI/AzTest/Utils_WinAPI.cpp
  Code/Framework/AzTest/AzTest/Platform/Linux/platform_linux_files.cmake
  Code/Framework/AzTest/AzTest/Platform/Mac/platform_mac_files.cmake
  Code/Framework/AzTest/AzTest/Platform/Windows/platform_windows_files.cmake
  Code/Framework/AzTest/AzTest/Platform/iOS/platform_ios_files.cmake
  Code/Framework/AzTest/AzTest/Utils.h
Labels: sig/core, sig/platform

#6676 Remove 'INF' from integer widget and replace it with better formatted…
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyIntCtrlCommon.h
  Code/Framework/AzToolsFramework/Tests/PropertyIntCtrlCommonTests.h
Labels: feature/editor

#6395 Add a generic Value type to the Generic DOM
  Code/Framework/AzCore/AzCore/DOM/Backends/JSON/JsonSerializationUtils.cpp
  Code/Framework/AzCore/AzCore/DOM/DomUtils.cpp
  Code/Framework/AzCore/AzCore/DOM/DomUtils.h
  Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
  Code/Framework/AzCore/AzCore/DOM/DomValue.h
  Code/Framework/AzCore/AzCore/DOM/DomValueWriter.cpp
  Code/Framework/AzCore/AzCore/DOM/DomValueWriter.h
  Code/Framework/AzCore/AzCore/DOM/DomVisitor.cpp
  Code/Framework/AzCore/AzCore/DOM/DomVisitor.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/DOM/DomJsonBenchmarks.cpp
  Code/Framework/AzCore/Tests/DOM/DomValueBenchmarks.cpp
  Code/Framework/AzCore/Tests/DOM/DomValueTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/content, sig/core

#6881 Fixed physics periodic tests on linux platform
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_SameCollisionGroupSameCustomLayerCollide.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/force_region/ForceRegion_MultipleForcesInSameComponentCombineForces.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/material/Material_DefaultLibraryUpdatedAcrossLevels_after.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/material/Material_DefaultLibraryUpdatedAcrossLevels_before.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/material/Material_LibraryUpdatedAcrossLevels.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/script_canvas/ScriptCanvas_SpawnEntityWithPhysComponents.py
  AutomatedTesting/Levels/Physics/Joints_HingeNoLimitsConstrained/Joints_HingeNoLimitsConstrained.ly
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/0/0.ly
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/0/filelist.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/0/level.pak
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/0/tags.txt
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/0/terraintexture.pak
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/1/1.ly
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/1/filelist.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/1/level.pak
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/1/tags.txt
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/1/terraintexture.pak
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/C15425935_Material_LibraryUpdatedAcrossLevels_0.ly
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/filelist.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/level.pak
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/leveldata/Environment.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/leveldata/GameTokens.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/leveldata/TerrainTexture.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/leveldata/TimeOfDay.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/leveldata/VegetationMap.dat
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_0/terrain/terrain.pxheightfield
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/C15425935_Material_LibraryUpdatedAcrossLevels_1.ly
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/filelist.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/level.pak
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/leveldata/Environment.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/leveldata/GameTokens.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/leveldata/TerrainTexture.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/leveldata/TimeOfDay.xml
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/leveldata/VegetationMap.dat
  AutomatedTesting/Levels/Physics/Material_LibraryUpdatedAcrossLevels/C15425935_Material_LibraryUpdatedAcrossLevels_1/terrain/terrain.pxheightfield
  AutomatedTesting/Levels/Physics/RigidBody_KinematicModeWorks/RigidBody_KinematicModeWorks.ly
Labels: sig/core

#6861 Updating assimp to the v12 packages
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: sig/content

#6786 Updated AnimNode registration in LyShine and Maestro to register to a member variable map
  Code/Editor/Lib/Tests/test_DisplaySettingsPythonBindings.cpp
  Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
  Code/Framework/AzCore/AzCore/std/string/string.h
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/SelectorImplementations.h
  Gems/LyShine/Code/Source/Animation/AnimNode.h
  Gems/LyShine/Code/Source/Animation/UiAnimationSystem.cpp
  Gems/LyShine/Code/Source/Animation/UiAnimationSystem.h
  Gems/LyShine/Code/Source/LyShine.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimPostFXNode.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.h
  Gems/TextureAtlas/Code/Source/TextureAtlasImpl.h
Labels: sig/content

#6902 Add missing 'precise' keyword for Vertex shaders
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_DepthPass_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_ForwardPass.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_DepthPass_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
  Gems/Atom/TestData/TestData/Materials/Types/AutoBrick_ForwardPass.azsl
  Gems/Atom/TestData/TestData/Materials/Types/MinimalPBR_ForwardPass.azsl
Labels: sig/graphics-audio

#6866 Disable flaky HttpRequestor test
  Gems/HttpRequestor/Code/CMakeLists.txt
Labels: sig/network

#6470 Extension of editor_entity_utils.py to expose more functionality
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
Labels: sig/testing

#6893 Different Pso cache per vendor/driver
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/PhysicalDeviceDescriptor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/FrameScheduler.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystem.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystemInterface.h
  Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
Labels: sig/graphics-audio

#6900 ATOM-17132 Image builder failed to build some images after preset wa…
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
Labels: feature/graphics/rpi

#6890 [iOS] Update to use AWSNativeSDK 1.9.50
  Gems/AWSCore/Code/Platform/iOS/AWSCore_Traits_iOS.h
  cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Labels: sig/network

#6919 [Mac] Fix AssetProcessor failures on MacOS
  cmake/Platform/Mac/runtime_dependencies_mac.cmake.in
Labels: pr-ready-to-merge

#6905 Allow InstanceDatabase<Shader> to support multiple instances with different supervariants
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderVariantAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderVariantAsset.cpp
Labels: sig/graphics-audio

#6133 Asset Browser Search Entries Highlight
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: feature/editor, sig/content, sig/ui-ux

#6954 Fix Camera angle on switch levels
  Code/Editor/EditorViewportWidget.cpp
Labels: kind/bug, feature/viewport

#6818 Adding ray tracing toggle to mesh component UI
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Mesh/MeshComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
  Gems/Vegetation/Code/Tests/VegetationMocks.h
Labels: feature/graphics/mesh

#6921 Atom Tools: added function to get the number of active documents
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
Labels: feature/graphics/tools

#6942 Atom Tools: Bind exit function for python tests
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: feature/graphics/tools

#6980 Atom Tools: move asset processor connection to fix thumbnails
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: feature/graphics/tools

#6977 Material Editor tests for window pane function
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
Labels: sig/graphics-audio

#6562 chore: Rename Graph to EditorGraph
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.h
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorkerUtility.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasUndoHelper.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasUndoHelper.h
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorUtils.cpp
  Gems/ScriptCanvas/Code/Editor/Components/GraphUpgrade.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorUtils.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/GraphUpgrade.h
  Gems/ScriptCanvas/Code/Editor/ScriptCanvasEditorGem.cpp
  Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Undo/ScriptCanvasGraphCommand.cpp
  Gems/ScriptCanvas/Code/Editor/Undo/ScriptCanvasGraphCommand.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.h
Labels: sig/content, sig/ui-ux

#6506 Wind Info
  Gems/PhysX/Code/Source/WindProvider.cpp
Labels: sig/core

#6917 Atom Tools: Created base class for document-based applications
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.h
Labels: feature/graphics/tools

#6988 Atom Tools: disabling auto load of unused gems in some atom tools
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Registry/gem_autoload.materialeditor.setreg
  Registry/gem_autoload.shadermanagementconsole.setreg
Labels: feature/graphics/tools

#6998 ImGui: Added new histogram group helper
  Gems/ImGui/Code/Include/LYImGuiUtils/HistogramGroup.h
  Gems/ImGui/Code/Source/LYImGuiUtils/HistogramGroup.cpp
  Gems/ImGui/Code/imgui_lyutils_static_files.cmake
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#6983 Fix: Entity Outliner: Outliner is unusable with the Editor in slice mode
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/RichTextHighlighter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Labels: feature/editor, kind/bug, sig/content, priority/critical

#6979 Updating NetworkingSpawnableLibrary to Only Store Network Spawnables
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerConstants.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkSpawnableLibrary.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkSpawnableLibrary.h
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
  Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp
Labels: sig/network

#6994 System shortcuts crash the Editor when Global Preferences are open
  Code/Editor/EditorPreferencesDialog.cpp
  Code/Editor/EditorPreferencesDialog.h
Labels: sig/content

#6910 [AWSMetrics] Update the auto-generated code to follow O3DE coding standard
  Gems/AWSMetrics/Code/Source/AWSMetricsConstant.h
  Gems/AWSMetrics/Code/Source/AWSMetricsServiceApi.cpp
  Gems/AWSMetrics/Code/Source/AWSMetricsServiceApi.h
  Gems/AWSMetrics/Code/Source/MetricsManager.cpp
  Gems/AWSMetrics/Code/Source/MetricsManager.h
  Gems/AWSMetrics/Code/Tests/AWSMetricsServiceApiTest.cpp
  Gems/AWSMetrics/Code/Tests/MetricsManagerTest.cpp
  Gems/AWSMetrics/cdk/api_spec.json
Labels: sig/network

#6959 Support supervariants in the PrecompiledShaderBuilder
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/PrecompiledShaderBuilder.cpp
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBlendDistance.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBlendIrradiance.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdateColumn.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridBorderUpdateRow.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridClassification.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRayTracing.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingClosestHit.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingMiss.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRelocation.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridRender.precompiledshader
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/PrecompiledShaderAssetSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/PrecompiledShaderAssetSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAssetCreator.cpp
Labels: sig/graphics-audio

#6958 Fix missing ImGui::End in multiplayer windows
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
Labels: sig/network

#6865 Silence aws logging for unit test and have a new AWSNativeSDK as entry point for test env
  Code/Tools/AWSNativeSDKInit/CMakeLists.txt
  Code/Tools/AWSNativeSDKInit/aws_native_sdk_test_files.cmake
  Code/Tools/AWSNativeSDKInit/source/AWSNativeSDKInit.cpp
  Code/Tools/AWSNativeSDKInit/tests/libs/AWSNativeSDKTestManager.cpp
  Code/Tools/AWSNativeSDKInit/tests/libs/AWSNativeSDKTestManager.h
  Gems/AWSClientAuth/Code/CMakeLists.txt
  Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h
  Gems/AWSCore/Code/CMakeLists.txt
  Gems/AWSCore/Code/Tests/AWSCoreSystemComponentTest.cpp
  Gems/AWSCore/Code/Tests/TestFramework/AWSCoreFixture.h
  Gems/AWSGameLift/Code/AWSGameLiftClient/CMakeLists.txt
  Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/AWSGameLiftClientFixture.h
Labels: sig/network

#6916 Removes the old log lines test for Light component.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightComponent.py
Labels: sig/graphics-audio

#6722 Fix: only files can be selected
  Code/Editor/AssetImporter/AssetImporterManager/AssetImporterManager.cpp
Labels: sig/content, sig/ui-ux

#6996 Asset Browser Collapse All Fix
  Assets/Editor/Icons/AssetBrowser/Collapse_All.svg
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
Labels: sig/content, sig/ui-ux, needs-ux-action

#6441 feature: add Exception Handler support for unix
  Code/Framework/AzCore/Platform/Android/AzCore/AzCore_Traits_Android.h
  Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Debug/Trace_UnixLike.cpp
  Code/Framework/AzCore/Platform/Linux/AzCore/AzCore_Traits_Linux.h
  Code/Framework/AzCore/Platform/Mac/AzCore/AzCore_Traits_Mac.h
  Code/Framework/AzCore/Platform/Windows/AzCore/AzCore_Traits_Windows.h
  Code/Framework/AzCore/Platform/iOS/AzCore/AzCore_Traits_iOS.h
  Code/Legacy/CrySystem/SystemInit.cpp
Labels: sig/platform

#6429 Cherry pick changes to 2111RTE for installer version build number
  cmake/Version.cmake
Labels: sig/build

#6935 issue5299: Resolved via change to not disable custom window decorations.
  Code/Tools/AssetBundler/Platform/Linux/source/utils/GUIApplicationManager_Linux.cpp
Labels: sig/content, sig/platform, sig/ui-ux

#7001 Fix issues when configuring projects and gems
  Templates/DefaultGem/Template/CMakeLists.txt
  Templates/DefaultGem/Template/Code/CMakeLists.txt
  Templates/MinimalProject/Template/Gem/CMakeLists.txt
  cmake/3rdParty.cmake
  cmake/3rdParty/BuiltInPackages.cmake
  cmake/Configurations.cmake
  cmake/Install.cmake
  cmake/LYTestWrappers.cmake
  cmake/LYWrappers.cmake
  cmake/PAL.cmake
  cmake/Packaging.cmake
  cmake/RuntimeDependencies.cmake
Labels: pr-ready-to-merge

#7016 Atom Tools: Removing unnecessary modules, components, and dead code from SMC
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/CMakeLists.txt
  Gems/Atom/Tools/ShaderManagementConsole/Code/Include/Atom/Document/ShaderManagementConsoleDocumentModule.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Include/Atom/Window/ShaderManagementConsoleWindowModule.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentModule.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentSystemComponent.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentSystemComponent.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Linux/ShaderManagementConsole_Traits_Linux.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Mac/ShaderManagementConsole_Traits_Mac.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Windows/ShaderManagementConsole_Traits_Windows.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleRequestBus.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleBrowserWidget.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindowComponent.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindowComponent.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindowModule.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ToolBar/ShaderManagementConsoleToolBar.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ToolBar/ShaderManagementConsoleToolBar.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/shadermanagementconsole_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/shadermanagementconsoledocument_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/shadermanagementconsolewindow_files.cmake
Labels: sig/graphics-audio, feature/graphics/tools

#6762 Fixing crash when opening different level during simulation mode
  Code/Editor/CryEdit.cpp
Labels: sig/content

#6763 Allowing instantiating of prefab without selecting an entity in outliner
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Labels: sig/content, sig/ui-ux

#7051 Atom Tools: removing unused traits for ME executable extension
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Linux/MaterialEditor_Traits_Linux.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Mac/MaterialEditor_Traits_Mac.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Windows/MaterialEditor_Traits_Windows.h
Labels: feature/graphics/tools

#7052 Atom Tools: updating gem autoload settings registry for ME and SMC to disable script canvas developer gem
  Registry/gem_autoload.materialeditor.setreg
  Registry/gem_autoload.shadermanagementconsole.setreg
Labels: feature/graphics/tools

#7075 Addressed a few Script Canvas translation issues
  Gems/ScriptCanvas/Assets/TranslationAssets/Classes/MaterialData.names
  Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Input_InputHandler.names
  Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.h
Labels: feature/scripting

#7084 Refactored the styling of TableView header sections
  Code/Framework/AzQtComponents/AzQtComponents/Components/Style.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.qss
  Code/Framework/AzQtComponents/AzQtComponents/Gallery/TableViewPage.cpp
Labels: sig/content

#7040 LYN-7640 Terrain Physics Materials hooked up all the way down to PhysX
  Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/HeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/Utils.cpp
  Gems/PhysX/Code/Source/Utils.h
  Gems/PhysX/Code/Tests/EditorHeightfieldColliderComponentTests.cpp
  Gems/PhysX/Code/Tests/EditorTestUtilities.cpp
  Gems/PhysX/Code/Tests/EditorTestUtilities.h
Labels: feature/physics, feature/terrain

#6452 Ensure render geometry is refreshed when the mesh component controller is moved
  Code/Framework/AzFramework/AzFramework/Render/Intersector.h
  Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Tests/Main.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Tests/MeshComponentControllerTests.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_test_files.cmake
Labels: sig/content, sig/graphics-audio, feature/viewport

#7089 Removing lux core (whats left of it)
  Gems/Atom/Feature/Common/Code/CMakeLists.txt
  Gems/Atom/Feature/Common/Code/Source/Platform/Common/Clang/atom_feature_common_clang.cmake
  Gems/Atom/Feature/Common/Code/Source/Platform/Common/GCC/atom_feature_common_gcc.cmake
  Gems/Atom/Feature/Common/Code/Source/Platform/Common/MSVC/atom_feature_common_msvc.cmake
Labels: feature/graphics/lighting

#5155 feat: add cursor wrapped mode
  Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.h
  Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
Labels: sig/content, sig/ui-ux, review-required

#6930 [development] enabled mouse wheel scrolling in the Profiler gem visualizer
  Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp
Labels: sig/core, sig/graphics-audio

#6993 Added base level for tests, updated automation to use prefabs, and restored sandboxed tests
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DiffuseGlobalIlluminationAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_BloomAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DecalAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DeferredFogAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DepthOfFieldAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DiffuseProbeGridAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DirectionalLightAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_EntityReferenceAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_ExposureControlAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GlobalSkylightIBLAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GridAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRColorGradingAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRiSkyboxAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_OcclusionCullingPlaneAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PhysicalSkyAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXGradientWeightModifierAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXLayerAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXRadiusWeightModifierAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFxShapeWeightModifierAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_ReflectionProbeAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SSAOAdded.py
  AutomatedTesting/Levels/Graphics/base_empty/base_empty.prefab
  AutomatedTesting/Levels/Graphics/base_empty/tags.txt
Labels: sig/graphics-audio

#7105 Atom Tools: Replaced custom help dialog with generic message box
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/HelpDialog/HelpDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/HelpDialog/HelpDialog.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/HelpDialog/HelpDialog.ui
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/materialeditor_files.cmake
Labels: sig/content, sig/graphics-audio, sig/ui-ux, feature/graphics/tools

#7107 Atom Tools: Combined ME viewport widget and renderer classes
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportRenderer.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportRenderer.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.h
  Gems/Atom/Tools/MaterialEditor/Code/materialeditor_files.cmake
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7104 Atom Tools: Changed ME preset browser dialog into generic asset grid dialog in ATF
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetGridDialog/AssetGridDialog.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetGridDialog/AssetGridDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetGridDialog/AssetGridDialog.ui
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/LightingPresetBrowserDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/LightingPresetBrowserDialog.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/ModelPresetBrowserDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/ModelPresetBrowserDialog.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/PresetBrowserDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/PresetBrowserDialogs/PresetBrowserDialog.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
  Gems/Atom/Tools/MaterialEditor/Code/materialeditor_files.cmake
Labels: sig/content, sig/graphics-audio, sig/ui-ux, feature/graphics/tools

#7038 Update deployment scripts to support AWSI automation tests on Linux
  AutomatedTesting/Gem/PythonTests/AWS/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/AWS/README.md
  AutomatedTesting/Gem/PythonTests/AWS/common/aws_credentials.py
  AutomatedTesting/Gem/PythonTests/AWS/common/aws_utils.py
  AutomatedTesting/Gem/PythonTests/AWS/common/constants.py
  scripts/build/Platform/Linux/build_config.json
  scripts/build/Platform/Linux/deploy_cdk_applications.sh
  scripts/build/Platform/Linux/destroy_cdk_applications.sh
  scripts/build/Platform/Linux/pipeline.json
  scripts/build/Platform/Windows/deploy_cdk_applications.cmd
  scripts/build/Platform/Windows/destroy_cdk_applications.cmd
  scripts/build/Platform/Windows/pipeline.json
Labels: sig/network

#7095 Introduce shortcut labeling in "Find in Viewport" context menu item
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
Labels: feature/editor, sig/content

#6671 Fix: LOD stops animation
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
Labels: sig/content

#7117 Fixed missing include compile issue
  Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
Labels: sig/content

#7094 Prefab Focus Mode | Fixes to viewport top toolbar
  Code/Editor/ViewPane.cpp
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/ViewportTitleDlg.h
  Code/Editor/ViewportTitleDlg.ui
  Code/Framework/AzQtComponents/AzQtComponents/Components/ToolBarArea.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabViewportFocusPathHandler.cpp
Labels: feature/editor, sig/content, feature/prefabs

#7054 Made MaterialPropertyId Be More Generic
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialPropertyId.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialPropertyId.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialPropertyIdTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialSourceDataTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_tests_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialModelUvNameMapInspector.cpp
Labels: sig/graphics-audio

#6719 Model drag causes crash
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
Labels: sig/content

#7088 Reimplement the GCC fix for the AWS jobs using forward declare
  Gems/AWSCore/Code/Include/Framework/AWSApiRequestJob.h
  Gems/AWSCore/Code/Include/Framework/ServiceRequestJob.h
Labels: sig/network

#7087 Adding missing dependency on LyShine to the VirtualGamepad
  Gems/VirtualGamepad/Code/CMakeLists.txt
  Gems/VirtualGamepad/gem.json
Labels: sig/content, sig/ui-ux

#7123 Merged `stabilization/2111RTE` to `development`
  Code/Tools/ProjectManager/Source/Application.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignmentSerializer.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
  scripts/o3de/o3de/manifest.py
Labels: sig/content

#6851 {lyn9135} Adding a default prefab during scene processing
  AutomatedTesting/Assets/TestAnim/parent_tops.fbx
  AutomatedTesting/Assets/TestAnim/parenting_test_default.fbx
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabBehaviorTests.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
Labels: sig/content

#6473 Initial fix for geometry being intersected when not visible
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntitySelectionBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorSelectionUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.cpp
  Gems/LmbrCentral/Code/Source/Shape/EditorBaseShapeComponent.h
  Gems/LmbrCentral/Code/Tests/EditorShapeComponentIntersectionTests.cpp
  Gems/LmbrCentral/Code/Tests/EditorTubeShapeComponentTests.cpp
  Gems/LmbrCentral/Code/Tests/lmbrcentral_editor_tests_files.cmake
Labels: sig/content, feature/viewport

#7031 Fix Editor Play-Mode RequestNetSpawnable Error
  AutomatedTesting/Gem/Code/Source/AutoGen/NetworkTestLevelEntityComponent.AutoComponent.xml
  AutomatedTesting/Gem/Code/Source/AutoGen/NetworkTestPlayerComponent.AutoComponent.xml
  AutomatedTesting/Gem/Code/automatedtesting_files.cmake
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_SimpleNetworkLevelEntity.py
  AutomatedTesting/Levels/Multiplayer/SimpleNetworkLevelEntity/Player.prefab
  AutomatedTesting/Levels/Multiplayer/SimpleNetworkLevelEntity/SimpleNetworkLevelEntity.prefab
  AutomatedTesting/Levels/Multiplayer/SimpleNetworkLevelEntity/SimpleNetworkLevelEntity.scriptcanvas
  AutomatedTesting/Levels/Multiplayer/SimpleNetworkLevelEntity/tags.txt
  Code/Framework/AzCore/AzCore/Component/Component.cpp
  Code/Framework/AzCore/AzCore/Component/Entity.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
Labels: sig/network

#6723 Shortcut keys issue
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
Labels: sig/content

#7046 adding editor level load automation script
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_Atom_LevelLoadTest.py
Labels: sig/graphics-audio

#7068 Add manipulator for atom render plugin in animation editor.
  Code/Editor/ViewportManipulatorController.cpp
  Code/Editor/ViewportManipulatorController.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportInteractionHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportInteractionHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/Resources.qrc
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/Rotate.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/Scale.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/Translate.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportInputController.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportInputController.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRequestBus.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/emotionfx_atom_editor_files.cmake
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderViewWidget.cpp
Labels: feature/animation, sig/content, sig/ui-ux

#7144 Android devices have alignment issue with ASTC_6X6 textures. Swith to…
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Albedo.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/AlbedoWithCoverage.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/AlbedoWithGenericAlpha.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Emissive.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Reflectance.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/UserInterface_Compressed.preset
Labels: feature/graphics/rpi

#7092 P1 Entity Reference Component tests
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_EntityReferenceAdded.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
Labels: sig/graphics-audio

#7126 Only use a deterministic random when network option is enabled.
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphInstance.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphTimeCondition.cpp
  Gems/EMotionFX/Code/MCore/Source/Random.h
Labels: feature/animation

#7156 Editor crashes upon adding entity to Procedural Prefab via Landscape Canvas or Track View tools
  Code/Editor/TrackView/TrackViewDialog.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
Labels: feature/editor, sig/content, feature/prefabs

#7152 Disable render pipeline for EditorViewportWidget until a level has been loaded
  Code/Editor/EditorViewportWidget.cpp
Labels: sig/content, sig/graphics-audio

#7159 Focus Mode - Introduce API to return a list of EntityIds for all entities in the focused subtree
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.h
  Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeTests.cpp
Labels: feature/editor, sig/content, feature/prefabs

#7109 Implemented Support to allow project's to reference gems via the gem name
  CMakeLists.txt
  Gems/PhysXDebug/Code/CMakeLists.txt
  cmake/FileUtil.cmake
  cmake/PAL.cmake
  cmake/Platform/Common/Install_common.cmake
  cmake/Projects.cmake
  cmake/Subdirectories.cmake
  cmake/cmake_files.cmake
  engine.json
  scripts/o3de/o3de/cmake.py
  scripts/o3de/o3de/disable_gem.py
  scripts/o3de/o3de/enable_gem.py
  scripts/o3de/o3de/engine_properties.py
  scripts/o3de/o3de/project_properties.py
  scripts/o3de/tests/CMakeLists.txt
  scripts/o3de/tests/test_cmake.py
  scripts/o3de/tests/test_disable_gem.py
  scripts/o3de/tests/test_enable_gem.py
  scripts/o3de/tests/test_engine_properties.py
  scripts/o3de/tests/test_engine_template.py
  scripts/o3de/tests/test_gem_properties.py
  scripts/o3de/tests/test_global_project.py
  scripts/o3de/tests/test_manifest.py
  scripts/o3de/tests/test_print_registration.py
  scripts/o3de/tests/test_project_properties.py
  scripts/o3de/tests/test_register.py
  scripts/o3de/tests/test_utils.py
Labels: sig/core

#6909 Remove error state when user attempts to save empty script event.
  Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventDefinition.cpp
Labels: sig/content, sig/core, sig/ui-ux

#7150 Exposing / Unifying the rasterstate depth bias values for all the sha…
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Shadowmap_WithPS.shader
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Shadowmap_WithPS.shader
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_Shadowmap_WithPS.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Shadow/Shadowmap.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Shadow/ShadowmapSkin.shader
Labels: feature/graphics/shaders

#7170 Removed legacy Editor config spec
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyItem.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.h
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEditPy.cpp
  Code/Editor/EditorPreferencesPageGeneral.cpp
  Code/Editor/EditorPreferencesPageGeneral.h
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/Lib/Tests/test_CryEditPythonBindings.cpp
  Code/Editor/Objects/BaseObject.cpp
  Code/Editor/Objects/BaseObject.h
  Code/Editor/Objects/EntityObject.cpp
  Code/Editor/Objects/EntityObject.h
  Code/Editor/Settings.cpp
  Code/Editor/Settings.h
  Code/Editor/UIEnumsDatabase.cpp
  Code/Editor/UIEnumsDatabase.h
  Code/Editor/UndoConfigSpec.cpp
  Code/Editor/UndoConfigSpec.h
  Code/Editor/Util/Variable.cpp
  Code/Editor/Util/Variable.h
  Code/Editor/Util/VariablePropertyType.cpp
  Code/Editor/Util/VariablePropertyType.h
  Code/Editor/editor_core_files.cmake
  Code/Editor/editor_lib_files.cmake
  Code/Legacy/CryCommon/ISystem.h
Labels: sig/content

#7158 Atom viewport render option bugfix
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/Cloth.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/HitDetection.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/RagdollCollider.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/RagdollJointLimit.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/Resources.qrc
  Gems/AtomLyIntegration/EMotionFXAtom/Assets/Icons/SimulatedObjectCollider.svg
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.h
Labels: feature/animation

#7160 EMotion FX: Recent files menu in Animation Editor also shows files from external gems
  Gems/EMotionFX/Code/MysticQt/Source/RecentFiles.cpp
Labels: feature/animation, kind/bug, sig/content

#6758 Added pixel retrieval API to StreamingImageAsset
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/Atom/RPI/Code/Tests/Image/StreamingImageTests.cpp
Labels: sig/graphics-audio

#7177 Atom Tools: move performance metrics status bar widgets to base window
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.h
Labels: feature/graphics/tools

#7201 Removed legacy IViewPane Editor class
  Code/Editor/Include/IEditorClassFactory.h
  Code/Editor/Include/IViewPane.h
  Code/Editor/Plugin.cpp
  Code/Editor/Plugin.h
  Code/Editor/QtViewPane.h
  Code/Editor/QtViewPaneManager.h
  Code/Editor/TrackView/2DBezierKeyUIControls.cpp
  Code/Editor/TrackView/AssetBlendKeyUIControls.cpp
  Code/Editor/TrackView/CaptureKeyUIControls.cpp
  Code/Editor/TrackView/CommentKeyUIControls.cpp
  Code/Editor/TrackView/ConsoleKeyUIControls.cpp
  Code/Editor/TrackView/EventKeyUIControls.cpp
  Code/Editor/TrackView/GotoKeyUIControls.cpp
  Code/Editor/TrackView/ScreenFaderKeyUIControls.cpp
  Code/Editor/TrackView/SelectKeyUIControls.cpp
  Code/Editor/TrackView/SequenceKeyUIControls.cpp
  Code/Editor/TrackView/SoundKeyUIControls.cpp
  Code/Editor/TrackView/TimeRangeKeyUIControls.cpp
  Code/Editor/TrackView/TrackEventKeyUIControls.cpp
  Code/Editor/ViewManager.h
  Code/Editor/editor_lib_files.cmake
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorPlugin.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.cpp
Labels: sig/content

#7211 Multiplayer Test Script: Replacing an Out-Dated Script Node
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC_NetLevelEntity.scriptcanvas
Labels: sig/network
