Repository o3de/o3de, pull requests merged in 2022-10, with the labels that each got.

#10471 chore(EmotionFX): replace MCore::CreateFromAxisAndAngle with AZ::Quaternion::CreateFromAxisAngle
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeAccumTransformNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTwoLinkIKNode.cpp
  Gems/EMotionFX/Code/MCore/Source/AzCoreConversions.h
Labels: sig/simulation

#11133 bugfix(Whitebox): fix crash when switching modes while dragging manipulator
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/MultiLinearManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/MultiLinearManipulator.h
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxVertexTranslationModifier.cpp
  Gems/WhiteBox/Code/Tests/WhiteBoxComponentTest.cpp
Labels: feature/whitebox, sig/content

#12088 Asset Processor - Allow UUID source dependencies
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/PathOrUuid.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/PathOrUuid.h
  Code/Framework/AzToolsFramework/AzToolsFramework/SQLite/SQLiteBoundColumnSet.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SQLite/SQLiteBoundColumnSet.h
  Code/Framework/AzToolsFramework/AzToolsFramework/SQLite/SQLiteConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SQLite/SQLiteConnection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/SQLite/SQLiteQuery.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SQLite/SQLiteQuery.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Slice/SliceDependencyBrowserComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
Labels: feature/asset-pipeline, sig/content

#12346 Asset Database Future version check can now be downgraded from an error, via a command line flag + set this flag on Jenkins.
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
  scripts/build/Platform/Android/build_config.json
  scripts/build/Platform/Linux/build_config.json
  scripts/build/Platform/Mac/build_config.json
  scripts/build/Platform/Windows/build_config.json
  scripts/build/Platform/iOS/build_config.json
Labels: status/ux-approved

#12361 Reduce Diffuse GI artifacts on thin geometry with low-density DiffuseProbeGrids
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe1008_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe1008_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe1008_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe144_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe144_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe144_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe288_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe288_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe288_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe432_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe432_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe432_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe576_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe576_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe576_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe720_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe720_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe720_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe864_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe864_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance-numraysperprobe864_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblenddistance_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe1008_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe1008_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe1008_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe144_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe144_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe144_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe288_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe288_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe288_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe432_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe432_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe432_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe576_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe576_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe576_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe720_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe720_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe720_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe864_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe864_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance-numraysperprobe864_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridblendirradiance_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.cpp
Labels: sig/graphics-audio

#12351 Prefab | Fix crash on escaping prefab edit mode
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
Labels: feature/editor, kind/bug, sig/content, feature/prefabs, status/ux-approved

#12402 Material Canvas: Fix include paths broken after shader refactor
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.azsl.template
Labels: sig/content, sig/graphics-audio

#12404 Material Canvas: Fix warnings with mesh feature processor setting irradiance properties on shadow catcher
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Labels: sig/content, sig/graphics-audio

#12403 Material Canvas: Fix warnings caused by missing translation files
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/Translation/materialcanvas_en_us.ts
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
Labels: sig/content, sig/graphics-audio

#12423 Material Canvas: Register crash function Python binding for automated testing failure cases
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: sig/content, sig/graphics-audio

#12433 Material Component: Hiding AZStd::any property value functions from script canvas
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
Labels: sig/content, sig/graphics-audio

#11692 Add to AWSCore support for retrieving AWS creds from EC2 instance profile
  Gems/AWSCore/Code/Source/AWSCoreInternalBus.h
  Gems/AWSCore/Code/Source/Configuration/AWSCoreConfiguration.cpp
  Gems/AWSCore/Code/Source/Configuration/AWSCoreConfiguration.h
  Gems/AWSCore/Code/Source/Credential/AWSDefaultCredentialHandler.cpp
  Gems/AWSCore/Code/Source/Credential/AWSDefaultCredentialHandler.h
  Gems/AWSCore/Code/Tests/Configuration/AWSCoreConfigurationTest.cpp
  Gems/AWSCore/Code/Tests/Credential/AWSDefaultCredentialHandlerTest.cpp
  Gems/AWSCore/Code/Tests/ResourceMapping/AWSResourceMappingManagerTest.cpp
Labels: feature/cloud-service, sig/network

#12119 Prefab | Add scope for prefab template DOM value pointers [prevent memory issue]
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: sig/content, feature/prefabs

#11826 [AWSNativeSDK] Prevent accidental calls to EC2 instance metadata service
  Code/Tools/AWSNativeSDKInit/include/AWSNativeSDKInit/AWSNativeSDKInit.h
  Code/Tools/AWSNativeSDKInit/source/AWSNativeSDKInit.cpp
  Gems/HttpRequestor/Code/Tests/HttpRequestorTest.cpp
Labels: sig/network

#12357 Multiplayer: Stop Connection When Client Connects to a Server Without Any Level Loaded
  Code/Framework/AzNetworking/AzNetworking/ConnectionLayer/ConnectionEnums.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
Labels: sig/network

#12473 Asset Processor - Add registry reverse lookup for real id -> legacy id
  Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.h
  Code/Framework/AzFramework/Tests/AssetRegistry.cpp
  Code/Framework/AzFramework/Tests/frameworktests_files.cmake
Labels: feature/asset-pipeline, sig/content

#12472 Prefab - Fix memory issue in create entity operation
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: kind/bug, sig/content, feature/prefabs

#12452 Added a label on exit slot of On Entity Activated and Deactivated
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Handlers/EntityBus.names
Labels: feature/scripting

#11620 10964 move event presets
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/CardHeader.cpp
  Gems/EMotionFX/Assets/Editor/Layouts/AnimGraph.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Animation.layout
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/PluginManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphViewWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventPresetsWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventPresetsWidget.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventsPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventsPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TimeViewPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TimeViewPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TrackDataHeaderWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TrackDataWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/standardplugins_files.cmake
Labels: feature/animation, sig/simulation

#12441 Scene settings save button updates
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/Jack_Death_Fall_Back_ZUp.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/Jack_Death_Fall_Back_ZUp.fbx.assetinfo
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/scene_settings_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_manifest_vector_widget_tests_in_editor.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_test_helpers.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_test_messages.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_tests_in_editor.py
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterPlugin.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterPlugin.h
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.cpp
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.h
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.ui
  Code/Tools/SceneAPI/SceneUI/RowWidgets/ManifestVectorWidget.cpp
Labels: feature/asset-pipeline, sig/content

#12060 11314 create joint properties widget
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Card.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Card.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/Card.qss
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/CardHeader.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/CardHeader.h
  Gems/EMotionFX/Assets/Editor/Layouts/Physics.layout
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Inspector/InspectorWindow.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/JointPropertyWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/JointPropertyWidget.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/SkeletonOutlinerPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/SkeletonOutlinerPlugin.h
  Gems/EMotionFX/Code/Source/Editor/SkeletonModelJointWidget.h
  Gems/EMotionFX/Code/emotionfx_editor_files.cmake
Labels: feature/animation, sig/simulation

#12446 Fix Asset Processor test failures caused by the future database version
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.h
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
  Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.cpp
  Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.cpp
  Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.h
  Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp
  Code/Tools/AssetProcessor/native/tests/MockAssetDatabaseRequestsHandler.h
  Code/Tools/AssetProcessor/native/tests/PathDependencyManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/Validators/LfsPointerFileValidatorTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/Validators/LfsPointerFileValidatorTests.h
  Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.cpp
  Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.h
  Code/Tools/AssetProcessor/native/tests/utilities/StatsCaptureTest.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/StatsCapture.cpp
Labels: feature/asset-pipeline, sig/content

#12401 Update the LFS pointer checking for autofail jobs
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Labels: feature/asset-pipeline, sig/content

#11958 Added a mechanism to cache EntitySpawnTickets from script
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptMediator.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptMediator.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesContainer.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableSystemComponent.h
Labels: feature/scripting

#12457 Material Canvas: Updated experimental PBR template, node sorting, sampler state reflection, material input and SRG handling
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/SamplerState.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/RenderStates.cpp
  Gems/Atom/RHI/Code/Source/RHI.Reflect/SamplerState.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/MaterialPropertyUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/SettingsDialog/SettingsDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/bool.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/color.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/float.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/float2.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/float3.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/float4.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/int.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialInputs/uint.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName.material
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName.materialtype
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_Common.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_DepthPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_DepthPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.shader.template
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ShadowPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ShadowPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/experimental_pbr.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Textures/sample_texture_2d.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialModelUvNameMapInspector.cpp
  Gems/GraphModel/Code/Include/GraphModel/Model/Node.h
  Gems/GraphModel/Code/Source/Model/Node.cpp
Labels: sig/content, sig/graphics-audio

#12431 Shader Changes to Support Deferred Pipelines
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/DefaultObjectSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/StandardLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/LightingOptions.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ibl.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/IblForward.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Lights.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/ReflectionProbeData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/ScreenSpace/ScreenSpaceUtil.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Skin/SkinObjectSrg.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_LightingEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MultilayerPBR/StandardMultilayerPBR_ForwardPass.azsl
  Gems/Atom/TestData/TestData/Materials/Types/AutoBrick_ForwardPass.azsl
  Gems/Atom/TestData/TestData/Materials/Types/MinimalPBR_ForwardPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.azsl
  Gems/Meshlets/ASV_GPU_and_CPU_Demo/DebugShaderPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
Labels: sig/graphics-audio

#12436 Improved some error messages in the pass system.
  Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Labels: sig/graphics-audio

#12229 Demonstration of the expansion and implementation of QtPy test framework
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/consts/asset_editor.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/consts/general.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyAssetEditor.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyCommon.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyO3DEEditor.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyScriptCanvasEditor.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyScriptCanvasNodePalette.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/QtPyScriptCanvasVariableManager.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/script_canvas_tools_qt.py
  AutomatedTesting/Gem/PythonTests/scripting/EditMenu_Default_UndoRedo.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvent_AddRemoveMethod_UpdatesInSC.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
Labels: feature/scripting

#12057 Add basic image mip stream in/on machanism to streaming image pool controller
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryStatistics.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Image.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/PageTileAllocator.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/StreamingImagePool.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/MemoryUsage.cpp
  Gems/Atom/RHI/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Code/Source/RHI/ResourcePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/AttachmentImagePool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueueContext.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueueContext.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Image.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/ImagePool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/ResourcePoolResolver.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/TileAllocator.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/TileAllocator.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/DefaultStreamingImageController.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/ImageSystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/ImageSystemInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImage.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImageContext.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImageController.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImagePool.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/DefaultStreamingImageControllerAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/ImageMipChainAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/ImageSystemDescriptor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/StreamingImagePoolAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/StreamingImagePoolAssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/ResourcePool/ResourcePoolBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/DefaultStreamingImageController.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImageController.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImagePool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/DefaultStreamingImageControllerAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/ImageSystemDescriptor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImagePoolAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImagePoolAssetCreator.cpp
  Gems/Atom/RPI/Code/Tests/Common/RHI/Stubs.h
  Gems/Atom/RPI/Code/Tests/Image/StreamingImageTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
  Gems/Atom/RPI/Code/atom_rpi_reflect_files.cmake
  Gems/Atom/RPI/Registry/atom_rpi.setreg
  Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
Labels: sig/graphics-audio

#12516 EMFX: Add GUI access to rootMotionExtraction inside emfx editor -> motion inspector
  Gems/EMotionFX/Code/EMotionFX/Exporters/ExporterLib/Exporter/SkeletalMotionExport.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Motion/MotionDataBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/RootMotionExtractionRuleBehavior.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/RootMotionExtractionRule.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/RootMotionExtractionRule.h
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/ChunkProcessors.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/ChunkProcessors.h
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/MotionFileFormat.h
  Gems/EMotionFX/Code/EMotionFX/Source/Motion.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Motion.h
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.h
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/RootMotionExtractionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/RootMotionExtractionData.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Commands.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.h
Labels: feature/animation

#12459 Added support for shader options to FullscreenTrianglePass and establ…
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderOptionValuesSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderVariantListSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/FullscreenTrianglePass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderOptionValuesSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAssetCreator.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderOptionGroup.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
  Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_edit_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleTableView.cpp
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiShaderUtils.inl
Labels: sig/graphics-audio

#12214 Prefab | Improve output DOM check for prefab instance/entity DOM generator
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGeneratorInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateInstancesTests.cpp
Labels: sig/content, feature/prefabs

#12544 Migrate the legacy AssetProcessingStateDataUnitTest to the modern test framework
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.h
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorServerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorServerUnitTests.h
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorUnitTests.h
Labels: feature/asset-pipeline

#12640 Clean up AP tests to make sure that database connection is closed before destroy the temp testing folder
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
Labels: feature/asset-pipeline, sig/content

#12515 added sv_terminateOnPlayerExit and deprecated sv_isTransient
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#12591 Enable disabled asset manager test
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline

#12652 Migrate the legacy ConnectionManagerUnitTests
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/unittests/ConnectionManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/ConnectionManagerUnitTests.h
Labels: feature/asset-pipeline, sig/content

#12635 Missing dependency test fix
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/missing_dependency_tests.py
  AutomatedTesting/TestAssets/OnlyMatchesCorrectLengthUUIDs.txt
Labels: feature/asset-pipeline, sig/content

#12678 Asset builder test fix
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/AssetBuilder_test.py
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/AssetBuilder_test_case.py
Labels: feature/asset-pipeline, sig/content

#12601 Fixed an issue that DiffuseProbeGrid doesn't work after MainPipeline pass was changed and hot-reloaded.
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.h
Labels: feature/graphics

#12655 Automatically set the matching Diffuse or Specular IBL image in the Editor
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ImageBasedLights/EditorImageBasedLightComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ImageBasedLights/EditorImageBasedLightComponent.h
Labels: sig/graphics-audio

#12653 Migrate the legacy AssetRequestHandlerUnitTests
  Code/Tools/AssetProcessor/native/unittests/AssetRequestHandlerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetRequestHandlerUnitTests.h
Labels: feature/asset-pipeline, sig/content

#12669 Migrate the legacy FileWatcherUnitTests
  Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/FileWatcherUnitTests.h
Labels: feature/asset-pipeline, sig/content

#12673 Migrate the legacy PlatformConfigurationUnitTests
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/unittests/PlatformConfigurationUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/PlatformConfigurationUnitTests.h
Labels: feature/asset-pipeline, sig/content

#12695 Migrate the legacy RCcontrollerUnitTests
  Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.h
Labels: feature/asset-pipeline, sig/content

#12679 [Vegetation] Delete old slice test assets
  Gems/Vegetation/Assets/Slices/Examples/AreaBlender_Combined_Weighted.slice
  Gems/Vegetation/Assets/Slices/Examples/SimpleFlowers_Area_02.slice
  Gems/Vegetation/Assets/Slices/Examples/SimpleGrass_Area_01.slice
Labels: sig/content, feature/vegetation

#12481 Added networking event logger events
  Gems/Multiplayer/Code/CMakeLists.txt
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerConstants.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerPerformanceStats.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerStatSystemInterface.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerStats.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
  Gems/Multiplayer/Code/Source/MultiplayerStatSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerStatSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
  Gems/Multiplayer/Code/multiplayerstats_api_files.cmake
Labels: sig/network

#12675 Fix intermediate asset infinite loop
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
Labels: feature/asset-pipeline, sig/content

#12698 Migrate the legacy ConnectionUnitTest
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/unittests/ConnectionUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/ConnectionUnitTests.h
Labels: feature/asset-pipeline, sig/content

#12740 EMotionFX: Don't use magic numbers for snapping
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraphWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraphWidget.h
Labels: sig/simulation

#12656 Adds support for client-server multiplayer mode in the Editor with CTRL-G
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesContainer.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesContainer.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Tests/AutoGen/RpcUnitTesterComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Tests/LocalRpcTests.cpp
  Gems/Multiplayer/Code/Tests/RpcUnitTesterComponent.cpp
  Gems/Multiplayer/Code/Tests/RpcUnitTesterComponent.h
  Gems/Multiplayer/Code/multiplayer_tests_files.cmake
Labels: sig/network

#12744 Add optional whitespace capture to AP regex in root cause analysis config
  scripts/build/build_failure_rca/rca_patterns/Asset-Processing.json
Labels: sig/build

#12752 Editor names for archetype and network properties are more human readable
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#12753 LyShine shutdown assert/crash fix
  Gems/LyShine/Code/Source/Sprite.cpp
Labels: feature/lyshine

#12630 Removing Cry Dependency for Getting the Current Level Name
  Code/Framework/AzFramework/AzFramework/API/ApplicationAPI.h
  Code/Legacy/CryCommon/ILevelSystem.h
  Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
  Code/Legacy/CrySystem/LevelSystem/LevelSystem.h
  Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp
  Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.h
  Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Labels: sig/core, sig/network

#12637 Asset Processor - Use absolute paths internally
  AutomatedTesting/test1.lua
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.h
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.cpp
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCCommon.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCCommon.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.h
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.cpp
  Code/Tools/AssetProcessor/native/tests/AssetProcessorTest.h
  Code/Tools/AssetProcessor/native/tests/SourceAssetReferenceTests.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.h
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCControllerTest.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCControllerTest.h
  Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.cpp
  Code/Tools/AssetProcessor/native/tests/utilities/JobModelTest.h
  Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderData.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/AssetServerHandler.cpp
  Code/Tools/AssetProcessor/native/utilities/IPathConversion.h
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: feature/asset-pipeline, sig/content

#12776 Fixes interpolation when re-connecting or re-entering game mode
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#12717 Material Pipeline System Phase 1
  AutomatedTesting/Registry/material_pipelines.setreg
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp
  Gems/Atom/Asset/Shader/Code/Tests/ShaderBuilderUtilityTests.cpp
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/Common/DepthPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/Common/DepthPass.shader.template
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/Common/ShadowmapPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/Common/ShadowmapPass.shader.template
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/LowEndPipeline/ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/LowEndPipeline/ForwardPass.shader.template
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/LowEndPipeline/LowEndPipeline.materialpipeline
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/MainPipeline/ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/MainPipeline/ForwardPass.shader.template
  Gems/Atom/Feature/Common/Assets/Materials/Pipelines/MainPipeline/MainPipeline.materialpipeline
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_LightingBrdf.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_LightingBrdf.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_LightingBrdf.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_LightingBrdf.azsli
  Gems/Atom/Feature/Common/Registry/material_pipelines.setreg
  Gems/Atom/RHI/Code/Source/RHI.Edit/Utils.cpp
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/MaterialPipelineCallbacks.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialPipelineSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/BuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialPipelineSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
  Gems/Atom/RPI/Code/atom_rpi_edit_files.cmake
  Gems/Atom/TestData/TestData/Materials/Types/MaterialPipelineTest_Animated.azsli
  Gems/Atom/TestData/TestData/Materials/Types/MaterialPipelineTest_Animated.materialtype
  Gems/Atom/TestData/TestData/Materials/Types/MaterialPipelineTest_Basic.azsli
  Gems/Atom/TestData/TestData/Materials/Types/MaterialPipelineTest_Basic.materialtype
Labels: sig/graphics-audio

#12780 GraphModel: Fix bug where hidden graph model slots reappear after copy paste duplicate
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
  Gems/GraphModel/Code/Source/Model/DataType.cpp
  Gems/GraphModel/Code/Source/Model/Node.cpp
Labels: sig/content, sig/graphics-audio

#12777 Atom Tools: Stop application from shutting down if user cancels saving modified files
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
Labels: sig/content, sig/graphics-audio

#12775 Fixed warning caused by dynamic property edit context range attributes being out of bounds for some types
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
Labels: sig/content, sig/graphics-audio

#12785 Atom Tools: disable python test coverage gem in material canvas to stop warnings until it can be configured
  Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg
  Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg
  Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
Labels: sig/content, sig/graphics-audio

#12774 Fix spam caused by preview and thumbnail render request before the asset catalog was loaded
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.h
Labels: sig/content, sig/graphics-audio

#12790 Material Canvas: Registering matrix slot data types
  Code/Framework/AzCore/AzCore/Serialization/Json/AnySerializer.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
Labels: sig/content, sig/graphics-audio

#12749 Add string converters for Multiplayer typesafe integrals
  Code/Framework/AzCore/AzCore/RTTI/TypeSafeIntegral.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h
Labels: sig/core, sig/network

#12760 Terminate server on player exit if configured for it
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#12789 Atom Tools: Deferring open document actions to the system tick bus and fixing other timer usage
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Scripts/TestOpenClose.py
  Gems/Atom/Tools/MaterialEditor/Scripts/UpgradeAllMaterials.py
Labels: sig/content, sig/graphics-audio

#12788 Fixed warnings "Attempting to compile SRG that's already been queued…
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/Shader.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
Labels: sig/graphics-audio

#12733 EMFX: Allow multi edit on root motion extractions
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.cpp
Labels: feature/animation

#12803 Material Canvas: Menu parenting and recycling fixes
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/GraphView/GraphView.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasGraphView.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
Labels: sig/content, sig/graphics-audio

#12832 Fixed typo in `recursive` option in the Project Template asset processor settings
  Templates/DefaultProject/Template/Registry/assetprocessor_settings.setreg
  Templates/MinimalProject/Template/Registry/assetprocessor_settings.setreg
Labels: feature/asset-pipeline

#12796 Address issue for #11388: Add cancel button to save shader variant list process
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
Labels: sig/graphics-audio

#12851 chore: remove unused variables to compile for clang-15
  Code/Framework/AzCore/Tests/StatisticalProfilerTests.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Tests/ImageProcessing_Test.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
Labels: platform/linux, sig/platform

#12811 bugfix(Editor): crash with searching/renaming fields in the AssetBrowser
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/EntryDelegate.h
Labels: kind/bug, sig/content

#12889 Material canvas: fixing typo in clamp node config
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/clamp.materialcanvasnode
Labels: sig/content, sig/graphics-audio

#12852 feat: add disable option for switcher and cluster
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/Button.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ButtonGroup.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ButtonGroup.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiCluster.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiRequestBus.h
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewportUiManagerTests.cpp
Labels: sig/content

#12827 bugfix(Whitebox, AZToolsFramework): correctly generate unique ids for new Cluster, Switcher, TextField
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportUi/ViewportUiManager.h
Labels: feature/whitebox, kind/bug, sig/core
