Repository o3de/o3de, pull requests merged in 2022-03, with the labels that each got.

#7925 Reenable tests on Linux, remove secondary skip
  AutomatedTesting/Gem/PythonTests/smoke/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/smoke/test_CLITool_SerializeContextTools_Works.py
  Tools/LyTestTools/tests/CMakeLists.txt
Labels: sig/testing

#7880 Adding an util function to get a render pipeline descriptor from an…
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/LyShine/Code/Source/UiRenderer.cpp
Labels: sig/content, sig/graphics-audio

#7968 Ragdoll authoring part one
  Code/Framework/AzFramework/AzFramework/Physics/DebugDraw/CharacterPhysicsDebugDraw.cpp
  Code/Framework/AzFramework/AzFramework/Physics/DebugDraw/CharacterPhysicsDebugDraw.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Gems/AtomLyIntegration/EMotionFXAtom/Code/CMakeLists.txt
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
Labels: sig/content, sig/core

#7987 Motion Matching: Added prefab containing the automatic demo character
  Gems/MotionMatching/Assets/AutomaticDemo/CameraController_AutomaticDemo.scriptcanvas
  Gems/MotionMatching/Assets/AutomaticDemo/MotionMatching_AutoDemoCharacter.prefab
  Gems/MotionMatching/Assets/AutomaticDemo/MotionMatching_AutomaticDemo.animgraph
  Gems/MotionMatching/Assets/ControllableCharacter/CameraController_ControllableCharacter.scriptcanvas
  Gems/MotionMatching/Assets/ControllableCharacter/CharacterController.scriptcanvas
  Gems/MotionMatching/Assets/ControllableCharacter/InputBindings_ControllableCharacter.inputbindings
  Gems/MotionMatching/Assets/ControllableCharacter/MotionMatching_ControllableCharacter.animgraph
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/MotionMatching_AutomaticDemo.animgraph
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/MotionMatching_AutomaticDemo.prefab
Labels: feature/animation, sig/content

#8004 Enable prefabs for Atom automated tests.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
Labels: sig/graphics-audio

#8009 Fixes Vulkan RHI timeout in the benchmark nightly GPU test
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Buffer.h
Labels: sig/graphics-audio

#7622 Added slider to decal component to control normal map opacity
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Decals.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/Decals/ViewSrg.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Decals/DecalFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Decals/DecalBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Decals/DecalComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Decals/DecalComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Decals/DecalComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Decals/EditorDecalComponent.cpp
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/DecalRequestBus.names
Labels: sig/content, sig/graphics-audio

#8033 Add support to enable device validation for debug builds
  Gems/Atom/RHI/Code/Source/RHI/ValidationLayer.cpp
Labels: feature/graphics/rhi

#6497 feat: add cursor wrap mode viewport rough implementation
  Code/Editor/EditorViewportSettings.cpp
  Code/Editor/EditorViewportSettings.h
  Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
  Code/Editor/Lib/Tests/test_ViewportManipulatorController.cpp
  Code/Editor/ViewportManipulatorController.cpp
  Code/Editor/ViewportManipulatorController.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportMessages.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
Labels: sig/content

#8028 [Mac] Versions of MacOS < 12 still use 'Master'. We can remove the else when we no longer support BigSur.
  Gems/Microphone/Code/Source/Platform/Mac/MicrophoneSystemComponent_Mac.mm
Labels: sig/platform

#7995 Adding P1 steps to the GlobalSkylight automation
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GlobalSkylightIBLAdded.py
Labels: sig/graphics-audio

#8034 Added comments to track history of investigation about shader resourc…
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSetLayout.cpp
Labels: sig/graphics-audio

#7945 Framework For Simplifed Python Interface for Project Manager
  scripts/o3de/o3de/project_manager_interface.py
Labels: sig/content

#7650 Add `AZStd::ranges::all_of` and `AZStd::ranges::any_of`
  Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
  Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp
Labels: sig/core

#8038 The rotate camera were mapped to wrong id
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportSettings.cpp
Labels: feature/animation

#8059 Atom Tools: Extend RegExpFilter to support any regular expression
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.h
Labels: feature/scripting, sig/content, sig/graphics-audio, feature/graphics/tools

#8057 ATOM-17366 Convert Lyshine to use dynamic pass injection
  AutomatedTesting/Passes/MainPipeline.pass
  Gems/LyShine/Assets/Passes/LyShineChildPass.pass
  Gems/LyShine/Assets/Passes/LyShinePassRequest.azasset
  Gems/LyShine/Assets/Passes/LyShinePassTemplates.azasset
  Gems/LyShine/Assets/Passes/RttChildPass.pass
  Gems/LyShine/Assets/seedList.seed
  Gems/LyShine/Code/Source/LyShineFeatureProcessor.cpp
  Gems/LyShine/Code/Source/LyShineFeatureProcessor.h
  Gems/LyShine/Code/Source/LyShinePass.cpp
  Gems/LyShine/Code/Source/LyShinePass.h
  Gems/LyShine/Code/Source/LyShineSystemComponent.cpp
  Gems/LyShine/Code/lyshine_static_files.cmake
  Gems/LyShine/LyShineScript/PatchRenderPipeline.py
Labels: feature/graphics, sig/graphics-audio, feature/lyshine

#8073 fixed bug if asset job logs don't exist
  Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
Labels: sig/testing

#8076 Disabling LyTestTools in debug config
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
Labels: sig/testing

#7750 Remove Inaccurate Build Progress Estimate and Display Last Output While Building Project
  Code/Tools/ProjectManager/Resources/ProjectManager.qrc
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Resources/SpinningGears.webp
  Code/Tools/ProjectManager/Source/ProjectBuilderController.cpp
  Code/Tools/ProjectManager/Source/ProjectBuilderController.h
  Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
  Code/Tools/ProjectManager/Source/ProjectBuilderWorker.h
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: sig/content, sig/ui-ux, status/needs-ux-approval

#8072 ASV tests were failing due to previous change to this file. Adding in…
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Decals.azsli
Labels: feature/graphics/shaders

#8092 Change default MSAA samples to 4
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
Labels: sig/graphics-audio

#8063 Motion Matching: Trajectory prediction based on joystick input using exponential curve
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
  Gems/MotionMatching/Code/Source/TrajectoryQuery.h
  Gems/MotionMatching/README.md
Labels: feature/animation, sig/content

#8047 Update Multiplayer Automated Tests to use new Spawner
  AutomatedTesting/Gem/Code/CMakeLists.txt
  AutomatedTesting/Gem/Code/Source/AutoGen/NetworkPlayerSpawnerComponent.AutoComponent.xml
  AutomatedTesting/Gem/Code/Source/AutoGen/SimpleScriptPlayerComponent.AutoComponent.xml
  AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.cpp
  AutomatedTesting/Gem/Code/Source/AutomatedTestingSystemComponent.h
  AutomatedTesting/Gem/Code/Source/Components/NetworkPlayerSpawnerComponent.cpp
  AutomatedTesting/Gem/Code/Source/Components/NetworkPlayerSpawnerComponent.h
  AutomatedTesting/Gem/Code/Source/Spawners/IPlayerSpawner.h
  AutomatedTesting/Gem/Code/Source/Spawners/RoundRobinSpawner.cpp
  AutomatedTesting/Gem/Code/Source/Spawners/RoundRobinSpawner.h
  AutomatedTesting/Gem/Code/automatedtesting_files.cmake
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_RPC.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_SimpleNetworkLevelEntity.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.prefab
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network

#8029 Adding P1 tests to Bloom component automation.
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_BloomAdded.py
Labels: sig/graphics-audio

#8106 [MacOS] Update MacOS version check to use numbers instead of defines that may not exist
  Code/Editor/LogFile_mac.mm
  Gems/Microphone/Code/Source/Platform/Mac/MicrophoneSystemComponent_Mac.mm
Labels: sig/platform

#8056 Fixing material builder issues
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
Labels: sig/graphics-audio

#7997 Updating and re-adding disabled Asset Relocator tests to Sandbox.
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C30936451/TestAChild.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C30936451/TestBChild.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C30936451/test_texture_sequence000.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C30936451/test_texture_sequence001.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_dependencies/testingAssets.zip
Labels: sig/content

#8093 Fixing spawnable node in Script Canvas
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.h
Labels: sig/content

#8111 Change pass build order so the input connections from pass request ar…
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Labels: feature/graphics/rpi

#8091 DiffuseProbeGrid Irradiance Query
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseGlobalIllumination.pass
  Gems/Atom/Feature/Common/Assets/Passes/DiffuseProbeGridQuery.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridQuery.precompiledshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridquery.azshader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridquery_dx12_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridquery_null_0.azshadervariant
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridquery_vulkan_0.azshadervariant
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGrid.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGrid.h
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridQueryPass.cpp
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridQueryPass.h
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRenderPass.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
Labels: sig/graphics-audio

#8130 Animation Editor crashes when selecting a node in Skeleton Outliner
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
Labels: feature/animation, kind/bug, sig/content

#8070 Skip invalid or broken periodic tests that fail in nightly builds
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
Labels: feature/scripting, sig/content

#8085 Atom Tools: added scriptable export function to editor material component slot to enable testing
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#8097 Initial implementation of DocumentAdapter
  Code/Framework/AzCore/AzCore/DOM/DomPatch.cpp
  Code/Framework/AzCore/AzCore/DOM/DomPatch.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AdapterBuilder.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/BasicAdapter.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/BasicAdapter.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Code/Framework/AzFramework/Tests/DocumentPropertyEditor/AdapterBuilderTests.cpp
  Code/Framework/AzFramework/Tests/DocumentPropertyEditor/DocumentPropertyEditorFixture.cpp
  Code/Framework/AzFramework/Tests/DocumentPropertyEditor/DocumentPropertyEditorFixture.h
  Code/Framework/AzFramework/Tests/framework_shared_tests_files.cmake
  Code/Framework/AzFramework/Tests/frameworktests_files.cmake
Labels: sig/content, sig/core

#8101 Prevents changing the parent of an entity in a prefab
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
Labels: sig/content

#8124 Convert AtomFeatureIntegrationBenchmark level to prefab.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Benchmark_GPU.py
  AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/AtomFeatureIntegrationBenchmark.ly
  AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/AtomFeatureIntegrationBenchmark.prefab
  AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/filelist.xml
  AutomatedTesting/Levels/AtomFeatureIntegrationBenchmark/level.pak
Labels: sig/graphics-audio

#8122 Material Component P1 null renderer tests
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MaterialAdded.py
Labels: sig/graphics-audio

#8140 fixes test tools crash log not found error
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
Labels: sig/testing

#8083 Updated Material Component's exporter to sanitize material filenames …
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/FileDialog.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/FileDialog.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/AssetUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Common/AssetUtils.cpp
  Gems/Atom/RPI/Code/Tests/Utils/AssetUtilsTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_tests_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentExporter.cpp
Labels: sig/graphics-audio

#8134 Motion Matching: Performance improvement for calculating joint velocities
  Gems/MotionMatching/Code/Source/Feature.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.h
Labels: feature/animation, sig/content

#8126 Fix Multiplayer Editor Flaky Tests
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_RPC.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_SimpleNetworkLevelEntity.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/AutoComponent_NetworkInput.prefab
  AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/BasicConnectivity_Connects.prefab
  AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/Player.prefab
  AutomatedTesting/Levels/Multiplayer/SimpleNetworkLevelEntity/SimpleNetworkLevelEntity.prefab
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_editor_test_utils.py
Labels: sig/network

#8095 LuaIDE supports DPI scaling
  Code/Tools/LuaIDE/Source/Editor/LuaEditor.cpp
Labels: sig/content, sig/ui-ux

#8202 Improve ObjectTree tool to show the extents of the hovered widget during picking
  Gems/QtForPython/Editor/Scripts/show_object_tree.py
Labels: feature/editor, sig/content

#8089 Asset processor: Fix duplicate product dependencies
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/AssetManager/PathDependencyManager.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Labels: sig/content

#8196 `connect` console command uses default port if not specified
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#8146 Clear dirty entities after entity deletions to avoid double deletes
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/Physics_UndoRedoWorksOnEntityWithPhysComponents.py
  AutomatedTesting/Levels/Physics/Physics_UndoRedoWorksOnEntityWithPhysComponents/Physics_UndoRedoWorksOnEntityWithPhysComponents.prefab
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: sig/content

#7990 Security updates for Python 3.7.12
  cmake/LYPython.cmake
  python/python.cmd
  python/python.sh
Labels: sig/platform, sig/security

#8187 Atom Tools: Support different views for each document type
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentInspector.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentNotificationBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentObjectInfo.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentTypeInfo.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentTypeInfo.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/InspectorWidget.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleTableView.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#8236 Fixes ctrl-g crash with an installer when the server launcher is not found. Clarified error message.
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
Labels: sig/network

#8213 Adding P1 automation support for the Deferred Fog component
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DeferredFogAdded.py
Labels: sig/graphics-audio

#8081 Added basic game/server launcher connection test.
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
Labels: sig/network

#8128 Prevent invalid resolutions from being entered for a UI Canvas.
  Gems/LyShine/Code/Editor/CanvasSizeToolbarSection.cpp
Labels: sig/content

#8224 Add Treemap ImGui widget and Atom memory viz
  Gems/Atom/Utils/Code/CMakeLists.txt
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
  Gems/Profiler/Code/Include/Profiler/ImGuiTreemap.h
  Gems/Profiler/Code/Source/ImGuiTreemap.cpp
  Gems/Profiler/Code/Source/ImGuiTreemapImpl.h
  Gems/Profiler/Code/Source/ProfilerImGuiSystemComponent.cpp
  Gems/Profiler/Code/Source/ProfilerImGuiSystemComponent.h
  Gems/Profiler/Code/profiler_imgui_shared_files.cmake
Labels: feature/azcore, feature/graphics/tools, feature/graphics/rhi

#8245 Deleting unused platform traits from material editor and SMC
  Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Linux/MaterialEditor_Traits_Linux.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Linux/MaterialEditor_Traits_Platform.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Linux/platform_linux_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Mac/MaterialEditor_Traits_Mac.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Mac/MaterialEditor_Traits_Platform.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Mac/platform_mac_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Windows/MaterialEditor_Traits_Platform.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Windows/MaterialEditor_Traits_Windows.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Platform/Windows/platform_windows_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Linux/ShaderManagementConsole_Traits_Linux.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Linux/ShaderManagementConsole_Traits_Platform.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Linux/platform_linux_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Mac/ShaderManagementConsole_Traits_Mac.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Mac/ShaderManagementConsole_Traits_Platform.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Mac/platform_mac_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Windows/ShaderManagementConsole_Traits_Platform.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Windows/ShaderManagementConsole_Traits_Windows.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Platform/Windows/platform_windows_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#8247 Atom Tools: fixing issues opening and saving documents in shader management console
  Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#8238 Motion Matching: Use facing direction option + a few fixes
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.cpp
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.h
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
  Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
  Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
  Gems/MotionMatching/Code/Source/TrajectoryQuery.h
Labels: feature/animation, sig/content

#7412 Moving Multiplayer Tests into Main Suite
  AutomatedTesting/Gem/PythonTests/Multiplayer/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_NetworkInput/Player.prefab
Labels: sig/network

#8249 Atom Tools: displaying full file path in create document dialog plus bug fixes
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#8144 Number of fixes. Mostly within the RHI layer
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/Decals/ViewSrg.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Decals/DecalFeatureProcessorInterface.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Metal/Code/Source/Platform/Mac/RHI/Conversions_Mac.cpp
  Gems/Atom/RHI/Metal/Code/Source/Platform/Mac/RHI/Conversions_Mac.h
  Gems/Atom/RHI/Metal/Code/Source/Platform/iOS/RHI/Conversions_iOS.cpp
  Gems/Atom/RHI/Metal/Code/Source/Platform/iOS/RHI/Conversions_iOS.h
  Gems/Atom/RHI/Metal/Code/Source/RHI.Reflect/PipelineLayoutDescriptor.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ArgumentBuffer.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ArgumentBuffer.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Metal.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineLibrary.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/AttachmentReadback.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
Labels: sig/graphics-audio, feature/graphics/rhi

#8273 Atom Tools: Making SMC project/gem configuration and inclusion match ME
  Code/Framework/AzCore/AzCore/Name/NameDictionary.h
  Gems/Atom/Tools/CMakeLists.txt
  Gems/Atom/Tools/ShaderManagementConsole/CMakeLists.txt
  Gems/Atom/Tools/ShaderManagementConsole/Code/CMakeLists.txt
  Gems/Atom/Tools/ShaderManagementConsole/gem.json
  Gems/Atom/Tools/ShaderManagementConsole/preview.png
  Gems/Atom/gem.json
  Gems/AtomLyIntegration/AtomBridge/Code/CMakeLists.txt
  Gems/AtomLyIntegration/AtomBridge/gem.json
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#8248 Focus Mode | Show helpers even when they're not selectable, but keep the current behavior for icons.
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
Labels: feature/editor, sig/content, feature/prefabs, feature/viewport

#8284 Added editorsv_hidden switch.
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network

#7969 Fix the StringToNumber Script Canvas node
  Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Math_StringToNumber.names
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Math/MathGenerics.h
Labels: sig/core

#8235 Feature: Focus Mode Editor Mode Feedback Effect
  Code/Framework/AzFramework/AzFramework/API/ApplicationAPI.h
  Code/Framework/AzFramework/AzFramework/Application/Application.cpp
  Code/Framework/AzFramework/AzFramework/Application/Application.h
  Gems/Atom/Feature/Common/Assets/Passes/EditorModeBlur.pass
  Gems/Atom/Feature/Common/Assets/Passes/EditorModeDesaturation.pass
  Gems/Atom/Feature/Common/Assets/Passes/EditorModeFeedbackParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/EditorModeMask.pass
  Gems/Atom/Feature/Common/Assets/Passes/EditorModeOutline.pass
  Gems/Atom/Feature/Common/Assets/Passes/EditorModeTint.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Passes/PostProcessParent.pass
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeBlur.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeBlur.shader
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeCommon.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeDepthTransition.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeDesaturation.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeDesaturation.shader
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeMask.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeMask.material
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeMask.materialtype
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeMask.shader
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeOutline.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeOutline.shader
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeTint.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/EditorModeTint.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/PostProcess/EditorModeFeedback/EditorModeFeedbackInterface.h
  Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcess/ColorGrading/HDRColorGradingSettings.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeBlurPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeBlurPass.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeDesaturationPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeDesaturationPass.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeFeedbackParentPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeFeedbackParentPass.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeFeedbackPassBase.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeFeedbackPassBase.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeOutlinePass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeOutlinePass.h
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeTintPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/EditorModeTintPass.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Module.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/EditorModeFeedback/EditorEditorModeFeedbackSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/EditorModeFeedback/EditorEditorModeFeedbackSystemComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
Labels: sig/content, sig/ui-ux

#7735 Expand AZ::Name functionality
  Code/Framework/AzCore/AzCore/Module/Module.h
  Code/Framework/AzCore/AzCore/Name/Name.cpp
  Code/Framework/AzCore/AzCore/Name/Name.h
  Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp
  Code/Framework/AzCore/AzCore/Name/NameDictionary.h
  Code/Framework/AzCore/Tests/Name/NameBenchmarks.cpp
  Code/Framework/AzCore/Tests/Name/NameTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/core

#8305 Multiplayer RPC Test Removing Flaky RemoteConsole
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_NetworkInput.py
Labels: feature/networking, sig/network

#8183 Fix container node naming issue and warning message
  Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
  Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/MethodConfiguration.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/MethodOverloaded.cpp
Labels: feature/scripting

#8309 Add propagation benchmarks for adding, removing and updating component
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/PrefabBenchmarkFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/PrefabBenchmarkFixture.h
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Propagation/SingleInstanceMultipleEntityBenchmarks.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content

#8275 [Terrain] Added support for custom handling of image gradient data
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyRowWidget.cpp
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Source/Components/GradientTransformComponent.cpp
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestHelpers.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestHelpers.h
Labels: sig/content

#8299 CubeMap Capture Component
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CubeMapCapture/CubeMapCaptureFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapCapture.cpp
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapCapture.h
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapCaptureFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapCaptureFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.cpp
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.h
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.h
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CubeMapCapture/EditorCubeMapCaptureBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/CubeMapCaptureComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/CubeMapCaptureComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/CubeMapCaptureComponentConstants.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/CubeMapCaptureComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/CubeMapCaptureComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/EditorCubeMapCaptureComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/EditorCubeMapCaptureComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/EditorCubeMapRenderer.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CubeMapCapture/EditorCubeMapRenderer.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Module.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/EditorReflectionProbeComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ReflectionProbe/ReflectionProbeComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_files.cmake
Labels: sig/graphics-audio

#8331 Fixes linking issues with game and server launchers in release monolithic mode
  Code/Legacy/CryCommon/ISystem.h
  Code/Legacy/CrySystem/DllMain.cpp
Labels: sig/build, sig/core

#8335 Add Atom memory CSV capture save and load
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
Labels: feature/graphics/tools

#8252 Build fixes for INSTALL target.
  Code/Tools/SerializeContextTools/Converter.cpp
  Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseGemSystemComponent.cpp
Labels: sig/graphics-audio

#8326 Motion Matching: Unifying joint velocity calculations
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.h
  Gems/MotionMatching/Code/Source/Feature.cpp
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.h
Labels: feature/animation, sig/content

#8317 Atom/qingtao/atom 4394
  Gems/Atom/RHI/Code/Include/Atom/RHI/Device.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHISystemInterface.h
  Gems/Atom/RHI/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/Device_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermathGpuCrashTracker_Windows.h
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/NsightAftermath_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/SwapChain_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/AliasedHeap.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandListBase.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/DX12.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/DX12.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/Fence.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/IndirectBufferSignature.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/QueryPool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: feature/graphics/rhi

#8361 [Linux] Set Icon for Project Manager Executable
  Code/Tools/ProjectManager/Source/Application.cpp
Labels: platform/linux, sig/content, sig/ui-ux

#8075 Terrain: Optimization: Terrain Physics incremental updates
  Code/Framework/AzFramework/AzFramework/Physics/Common/PhysicsSceneQueries.h
  Code/Framework/AzFramework/AzFramework/Physics/Common/PhysicsTypes.h
  Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
  Code/Framework/AzFramework/AzFramework/Physics/Mocks/MockHeightfieldProviderBus.h
  Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.cpp
  Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.h
  Gems/PhysX/Code/Mocks/PhysX/MockPhysXHeightfieldProviderComponent.h
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
  Gems/PhysX/Code/Source/HeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/HeightfieldColliderComponent.h
  Gems/PhysX/Code/Source/Utils.cpp
  Gems/PhysX/Code/Source/Utils.h
  Gems/PhysX/Code/Tests/EditorHeightfieldColliderComponentTests.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
  Gems/Terrain/Code/Tests/TerrainPhysicsColliderTests.cpp
Labels: feature/terrain

#8318 Display Mapper P1 test expansion
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DisplayMapperAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DisplayMapperAdded.py
Labels: sig/graphics-audio

#8367 Lyn 11472
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_direct_preload_dependency/TestC.slice
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_direct_preload_dependency/TestD.slice
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/TestA.slice
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/TestB.slice
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/assets_with_nested_preload_dependency/TestD.slice
Labels: sig/content

#8382 Lytesttools project path bug fix
  Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
  Tools/LyTestTools/ly_test_tools/environment/file_system.py
  Tools/LyTestTools/tests/unit/test_abstract_resource_locator.py
  Tools/LyTestTools/tests/unit/test_file_system.py
Labels: sig/testing

#8372 Motion Matching: Added query pose and query joint velocity debug visualization and new CVARs for debug rendering control
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureVelocity.h
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
  Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
Labels: feature/animation, sig/content

#7855 Local View Bookmarks System
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/MainWindow.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/LocalViewBookmarkLoader.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/SharedViewBookmarkComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/SharedViewBookmarkComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkLoaderInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewBookmarkSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content, feature/viewport

#8315 Update Multiplayer Tests to Store their Cached Folder Level Assets
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
Labels: sig/network

#8362 Adding precise keyword to match other shaders to fix depth precision …
  Gems/Atom/Feature/Common/Assets/Materials/Types/BasePBR_ForwardPass.azsl
Labels: sig/graphics-audio

#6704 [Linux] Improve thread name support
  Code/Framework/AzCore/AzCore/std/parallel/thread.h
  Code/Framework/AzCore/Platform/Linux/AzCore/std/parallel/internal/thread_Linux.cpp
  Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceComponent.cpp
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
Labels: sig/core

#8363 Parallel terrain query benchmarks
  Gems/GradientSignal/Code/Include/GradientSignal/Components/SurfaceAltitudeGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/GradientSampler.h
  Gems/GradientSignal/Code/Source/Components/SurfaceAltitudeGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Components/SurfaceMaskGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Components/SurfaceSlopeGradientComponent.cpp
  Gems/LmbrCentral/Code/Source/Shape/ReferenceShapeComponent.cpp
  Gems/SurfaceData/Code/Source/SurfacePointList.cpp
  Gems/SurfaceData/Code/Tests/SurfaceDataTest.cpp
  Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Tests/TerrainSystemBenchmarks.cpp
  Gems/Terrain/Code/Tests/TerrainTestFixtures.cpp
  Gems/Terrain/Code/Tests/TerrainTestFixtures.h
  Gems/Vegetation/Code/Source/Components/AreaBlenderComponent.cpp
Labels: sig/content

#8406 Add Resolution, MSAA, and RPI AssetStreamingImagePool usage to the Editor ImGui overlay
  Gems/AtomLyIntegration/AtomViewportDisplayInfo/Code/Source/AtomViewportDisplayInfoSystemComponent.cpp
Labels: sig/graphics-audio

#8229 Inspector transform component parent entity id hide the clear button when set to instance container #7465
  Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockFocusModeInterface.h
Labels: sig/content, sig/ui-ux, status/needs-ux-approval

#7809 chore: replace usage of MCore::LinearInterpolate with AZ::Lerp
  Code/Framework/AzCore/AzCore/Math/MathUtils.h
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeAccumTransformNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeSmoothingNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTransformNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/KeyTrackLinearDynamic.h
  Gems/EMotionFX/Code/EMotionFX/Source/KeyTrackLinearDynamic.inl
  Gems/EMotionFX/Code/EMotionFX/Source/Pose.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/SpringSolver.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Transform.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendSpace1DNodeWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendSpace2DNodeWidget.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendSpaceNodeWidget.cpp
  Gems/Gestures/Code/Include/Gestures/GestureRecognizerPinch.h
  Gems/Gestures/Code/Include/Gestures/GestureRecognizerRotate.h
  Gems/MotionMatching/Code/Source/TrajectoryHistory.cpp
Labels: sig/content, sig/core, feature/math

#7714 Updated Visual Studio Version to 16.11 and 17.0
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
Labels: sig/build

#8401 Parallel terrain components
  Gems/Terrain/Code/Include/Terrain/Ebuses/TerrainAreaSurfaceRequestBus.h
  Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainHeightGradientListComponent.h
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.h
  Gems/Terrain/Code/Source/Components/TerrainWorldDebuggerComponent.cpp
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainSurfaceGradientListComponent.cpp
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystemBus.h
  Gems/Terrain/Code/Tests/TerrainSystemBenchmarks.cpp
Labels: sig/content

#8208 [LY-116947] Asset processor: Fix duplicate Source/Job Dependencies
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
Labels: sig/content

#8416 Motion Matching: Multi-threaded feature extraction
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingData.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingData.h
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingSystemComponent.cpp
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.cpp
  Gems/MotionMatching/Code/Source/PoseDataJointVelocities.h
Labels: feature/animation, sig/content

#8370 [Terrain] Height blending / bug fixes
  Code/Framework/AzFramework/AzFramework/Terrain/TerrainDataRequestBus.h
  Code/Framework/AzFramework/Tests/Mocks/Terrain/MockTerrainDataRequestBus.h
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/GeneralCommonPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/MetallicPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ParallaxPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/RoughnessPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ShaderEnable.lua
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/LuaMaterialFunctor.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/LuaMaterialFunctorSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/LuaMaterialFunctor.cpp
  Gems/Terrain/Assets/Materials/Terrain/TerrainDetailMaterial.materialtype
  Gems/Terrain/Assets/Materials/Terrain/TerrainOverrideParallax.lua
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldComponent.h
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.h
Labels: sig/content, feature/terrain

#8438 Sandboxing shader reload Linux test to investigate why its sometimes failing.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
Labels: sig/graphics-audio

#6862 AP: Job Dependency product SubId dependencies
  Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.cpp
  Code/Tools/AssetProcessor/native/tests/FileProcessor/FileProcessorTests.h
  Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/PipelineLayoutDescriptor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderComponent.cpp
Labels: sig/content

#8433 [Linux] Fix No Minimum Size For Project Manager
  Code/Framework/AzQtComponents/AzQtComponents/Components/WindowDecorationWrapper.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Tests/WindowDecoratorWrapperTests.cpp
  Code/Framework/AzQtComponents/AzQtComponents/azqtcomponents_testing_files.cmake
Labels: sig/content, sig/platform, sig/ui-ux, feature/project-manager

#8446 Remove obsolete _nomsaa shader files
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseComposite_nomsaa.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseGlobalFullscreen_nomsaa.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseProbeGridDownsample_nomsaa.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionComposite_nomsaa.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionGlobalFullscreen_nomsaa.azsl
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
Labels: sig/graphics-audio

#8425 Occlusion Culling Plane component P1 null render test expansion
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_OcclusionCullingPlaneAdded.py
Labels: sig/graphics-audio

#8461 Removed now unused gradient signal imageasset/settings
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/GradientImageConversion.h
  Gems/GradientSignal/Code/Include/GradientSignal/ImageAsset.h
  Gems/GradientSignal/Code/Include/GradientSignal/ImageSettings.h
  Gems/GradientSignal/Code/Source/GradientImageConversion.cpp
  Gems/GradientSignal/Code/Source/GradientSignalSystemComponent.cpp
  Gems/GradientSignal/Code/Source/GradientSignalSystemComponent.h
  Gems/GradientSignal/Code/Source/ImageAsset.cpp
  Gems/GradientSignal/Code/Source/ImageSettings.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.h
  Gems/GradientSignal/Code/Tests/ImageAssetTests.cpp
  Gems/GradientSignal/Code/gradientsignal_files.cmake
  Gems/GradientSignal/Code/gradientsignal_tests_files.cmake
  Gems/Vegetation/Code/Source/VegetationSystemComponent.cpp
Labels: sig/content

#8352 Remove redundant transmission parameters from LightingData
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedSurface_ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.azsl
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/BackLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/LightingData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DirectionalLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DiskLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PointLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/TransmissionSurfaceData.azsli
Labels: sig/graphics-audio

#8427 Add missing override to auto generated RpcStructs deriving from IRpcParamStruct
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#8366 Use system default OpenSSL on Linux
  cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Linux/OpenSSL_linux.cmake
  cmake/3rdParty/Platform/Linux/cmake_linux_files.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
  cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Labels: sig/network, sig/platform

#8040 Provide config.yml to provide control over GitHub issue templates. Disable blank issues, add security and docs reporting links.
  .github/ISSUE_TEMPLATE/config.yml
Labels: sig/security

#8226 Ragdoll authoring part two
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CapsuleViewportEdit.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentModes/CapsuleViewportEdit.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/PhysX/Code/Editor/ColliderCapsuleMode.cpp
  Gems/PhysX/Code/Editor/ColliderCapsuleMode.h
Labels: sig/content, sig/core

#8039 Provide initial SECURITY.md for O3DE
  SECURITY.MD
Labels: sig/security

#7729 Texture Settings UI refactor, fixes, and improvements.
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/Backward.png
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/Forward.png
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/Resources.qrc
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/info.png
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/refresh-active.png
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/refresh.png
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/reset.png
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Editor/warning.png
  Gems/Atom/Asset/ImageProcessingAtom/Code/CMakeLists.txt
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/arrow_left-default.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/arrow_right-default.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/info.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/question.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/refresh-active.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/refresh.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Icons/warning.svg
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/ImageProcessing.qrc
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/MipmapSettingWidget.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/MipmapSettingWidget.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/PresetInfoPopup.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/PresetInfoPopup.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/ResolutionSettingItemWidget.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/ResolutionSettingWidget.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/ResolutionSettingWidget.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePreviewWidget.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePreviewWidget.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePropertyEditor.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePropertyEditor.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePropertyEditor.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/imageprocessing_files.cmake
Labels: sig/graphics-audio, sig/ui-ux, status/ux-approved, ui-ux/in-design

#8340 Updated occlusion plane materials to fix warnings about old material …
  Gems/Atom/Feature/Common/Assets/Materials/OcclusionCullingPlane/OcclusionCullingPlaneTransparentVisualization.material
  Gems/Atom/Feature/Common/Assets/Materials/OcclusionCullingPlane/OcclusionCullingPlaneVisualization.material
Labels: sig/graphics-audio

#8474 Fixed a bug in MaterialComponent that prevented UV overrides from bei…
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Labels: sig/graphics-audio

#8442 {lyn9162} Auto test for UDP feature
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/tests/UserDefinedProperties_Works.py
Labels: feature/asset-pipeline, sig/content

#8497 Update the iOS OpenSSL package used by O3DE
  cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Labels: sig/network

#8587 Don't render grid component if size <= 0
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.cpp
Labels: sig/content, sig/graphics-audio

#8586 Atom Tools: Removing shadow catcher opacity from lighting presets
  AutomatedTesting/LightingPresets/greenwich_park_02.lightingconfig.json
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/LightingPreset.h
  Gems/Atom/Feature/Common/Code/Source/Utils/LightingPreset.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Viewport/MaterialCanvasViewportWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
  Gems/AtomLyIntegration/CommonFeatures/Assets/EnvHDRi/photo_studio_01.lightingconfig.json
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#8606 Moving Multiplayer Automated-Review Tests into Sandbox
  AutomatedTesting/Gem/PythonTests/Multiplayer/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network
