Repository o3de/o3de, pull requests merged in 2022-09, with the labels that each got.

#11665 Material Canvas: Initial support for creating and editing shader config and dynamic node config files plus other fixes
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocumentNotificationBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsAnyDocumentRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsAnyDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/CreateDocumentDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeSlotConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Textures/sample_texture_2d.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
Labels: feature/graphics, sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11636 Adds pre-validation before issuing an RPC so that the sender knows they have issued an RPC from an incorrect role
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#11606 Show rotation feedback when editing PhysX collider
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Gems/PhysX/Code/Editor/ColliderRotationMode.cpp
Labels: feature/physics, sig/content, sig/simulation

#11716 Material Editor: Change asset browser duplicate action to save in the same folder
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
Labels: sig/content, sig/graphics-audio

#10510 chore(WhiteBox): update cvar constants based on functionality
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxDefaultMode.cpp
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxEdgeRestoreMode.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeScaleModifier.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeTranslationModifier.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxEdgeTranslationModifier.h
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonScaleModifier.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonTranslationModifier.h
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxVertexTranslationModifier.h
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxViewportConstants.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxViewportConstants.h
Labels: feature/whitebox, sig/content

#11686 Improve error messaging when users need to update scripts to new spawnable APIs
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
Labels: feature/scripting, sig/content

#11265 Removed Identical Condition
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/NodeGraph.cpp
Labels: sig/simulation

#11706 Motion Matching: Added standard scaler
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.cpp
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.h
  Gems/MotionMatching/Code/Source/FeatureMatrixStandardScaler.cpp
  Gems/MotionMatching/Code/Source/FeatureMatrixStandardScaler.h
  Gems/MotionMatching/Code/Source/FeatureMatrixTransformer.h
  Gems/MotionMatching/Code/Source/MotionMatchingData.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingData.h
  Gems/MotionMatching/Code/Tests/MinMaxScalerTests.cpp
  Gems/MotionMatching/Code/Tests/StandardScalerTests.cpp
  Gems/MotionMatching/Code/motionmatching_files.cmake
  Gems/MotionMatching/Code/motionmatching_tests_files.cmake
Labels: feature/animation, sig/simulation

#11715 Update Server launcher play-in-editor error message to be more explicit about paths examined.
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network, WF6

#11659 Disable parenting an entity to another instance
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Labels: sig/content, feature/prefabs

#11593 Fixed Asset Browser operation
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.ui
Labels: sig/content

#11277 bugfix(Editor): correctly handle update fov settings from Global Preferences
  Code/Editor/EditorPreferencesPageViewportGeneral.cpp
  Code/Editor/EditorViewportSettings.cpp
  Code/Editor/EditorViewportSettings.h
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Editor/Settings.cpp
  Code/Editor/Settings.h
  Code/Editor/ViewPane.cpp
  Code/Editor/Viewport.cpp
  Code/Editor/ViewportTitleDlg.cpp
Labels: feature/editor, kind/bug, sig/content

#11766 bugfix(Script Canvas): Unable to edit Tag in property field
  Code/Framework/AzCore/AzCore/Math/Crc.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyCRCCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyCRCCtrl.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h
Labels: feature/scripting, kind/bug, sig/content

#11806 Hide the create new image option if paint feature isn't enabled
  Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
Labels: sig/content

#11787 Prefab | Remove deprecated delete API in public interface
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDeleteTests.cpp
Labels: sig/content, feature/prefabs

#11828 Exposed level requests to python
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
Labels: sig/content

#11625 Separate DPE from RPE
  Code/Framework/AzCore/AzCore/DOM/DomUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/IPropertyEditor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content

#11231 Changed AzTest to fail when no tests were found.
  Code/Framework/AzTest/AzTest/AzTest.cpp
  Code/Framework/AzTest/AzTest/AzTest.h
  Gems/AWSCore/Code/CMakeLists.txt
  Gems/Blast/Code/CMakeLists.txt
  Gems/Compression/Code/CMakeLists.txt
  Gems/MotionMatching/Code/CMakeLists.txt
  Gems/RecastNavigation/Code/CMakeLists.txt
  Gems/SceneProcessing/Code/CMakeLists.txt
  Gems/Streamer/StreamerProfiler/Code/CMakeLists.txt
  Templates/CppToolGem/Template/Code/Platform/Android/PAL_android.cmake
  Templates/CppToolGem/Template/Code/Platform/Linux/PAL_linux.cmake
  Templates/CppToolGem/Template/Code/Platform/Mac/PAL_mac.cmake
  Templates/CppToolGem/Template/Code/Platform/Windows/PAL_windows.cmake
  Templates/CppToolGem/Template/Code/Platform/iOS/PAL_ios.cmake
  Templates/DefaultGem/Template/Code/Platform/Android/PAL_android.cmake
  Templates/DefaultGem/Template/Code/Platform/Linux/PAL_linux.cmake
  Templates/DefaultGem/Template/Code/Platform/Mac/PAL_mac.cmake
  Templates/DefaultGem/Template/Code/Platform/Windows/PAL_windows.cmake
  Templates/DefaultGem/Template/Code/Platform/iOS/PAL_ios.cmake
  Templates/PythonToolGem/Template/Code/Platform/Linux/PAL_linux.cmake
  Templates/PythonToolGem/Template/Code/Platform/Mac/PAL_mac.cmake
  Templates/PythonToolGem/Template/Code/Platform/Windows/PAL_windows.cmake
Labels: sig/testing

#11840 Fix AzNetworking unit test failures on Ubuntu 22.04
  Code/Framework/AzNetworking/AzNetworking/Utilities/QuantizedValues.inl
Labels: platform/linux, sig/network

#11699 Prefab | Update delete-entity workflow to improve editor performance
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndo.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndo.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
Labels: sig/content, feature/prefabs

#11819 Ensure entity is created at local (0, 0, 0) if created from the Entity Outliner
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/EditorContextMenuBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/EditorContextMenu.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
  Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
  Gems/Camera/Code/Source/CameraEditorSystemComponent.h
  Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp
  Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.h
Labels: sig/ui-ux, feature/viewport, status/ux-approved, RTE

#11763 Multiplayer: Add Viewport Message When Users Incorrectly Load Level
  Code/Framework/AzFramework/AzFramework/Entity/EntityDebugDisplayBus.h
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/AtomDebugDisplayViewportInterface.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
Labels: sig/network

#11829 Updated lua builder error message for files which do not look like lua references
  Gems/LmbrCentral/Code/Source/Builders/LuaBuilder/LuaBuilderComponent.cpp
  Gems/LmbrCentral/Code/Source/Builders/LuaBuilder/LuaBuilderWorker.cpp
Labels: feature/scripting

#11859 Fixed bolding & size of title text on scene settings UI
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.cpp
Labels: feature/asset-pipeline, kind/bug

#11719 Replaced scene settings saving popup with save status cards
  Code/Editor/Plugins/EditorAssetImporter/AssetBrowserContextProvider.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporter.qrc
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.ui
  Code/Editor/Plugins/EditorAssetImporter/CMakeLists.txt
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.cpp
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.h
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.ui
  Code/Framework/AzQtComponents/AzQtComponents/Components/StyledDetailsTableModel.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/StyledDetailsTableModel.h
  Code/Tools/SceneAPI/SceneCore/Containers/SceneManifest.cpp
  Code/Tools/SceneAPI/SceneUI/CommonWidgets/ProcessingOverlayWidget.cpp
  Code/Tools/SceneAPI/SceneUI/CommonWidgets/ProcessingOverlayWidget.h
  Code/Tools/SceneAPI/SceneUI/CommonWidgets/ProcessingOverlayWidget.ui
  Code/Tools/SceneAPI/SceneUI/CommonWidgets/SceneSettingsCard.cpp
  Code/Tools/SceneAPI/SceneUI/CommonWidgets/SceneSettingsCard.h
  Code/Tools/SceneAPI/SceneUI/SceneUI.qrc
  Code/Tools/SceneAPI/SceneUI/SceneUI_files.cmake
Labels: status/ux-approved

#11755 Treat duplicate MarkForRemoval as acceptable
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
Labels: sig/network

#11797 Support for cylinders in Editor Collider Component
  Code/Framework/AzFramework/AzFramework/Physics/Shape.h
  Gems/Blast/Code/Tests/Mocks/BlastMocks.h
  Gems/PhysX/Code/Editor/ColliderComponentMode.cpp
  Gems/PhysX/Code/Editor/Source/ComponentModes/PhysXSubComponentModeBase.h
  Gems/PhysX/Code/Include/PhysX/EditorColliderComponentRequestBus.h
  Gems/PhysX/Code/Mocks/PhysX/MockPhysicsShape.h
  Gems/PhysX/Code/Source/EditorColliderComponent.cpp
  Gems/PhysX/Code/Source/EditorColliderComponent.h
  Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
  Gems/PhysX/Code/Source/EditorRigidBodyComponent.h
  Gems/PhysX/Code/Source/Shape.cpp
  Gems/PhysX/Code/Source/Shape.h
  Gems/PhysX/Code/Source/Utils.cpp
  Gems/PhysX/Code/Tests/RigidBodyComponentTests.cpp
  Gems/PhysX/Code/Tests/TestColliderComponent.h
  Gems/ScriptCanvasPhysics/Code/Tests/ScriptCanvasPhysicsTest.cpp
Labels: feature/physics, sig/simulation

#11642 feat(Python Console): add clear option to python console
  Code/Editor/Controls/ConsoleSCB.cpp
  Code/Editor/Controls/ConsoleSCB.h
  Code/Editor/Controls/ConsoleSCB.ui
  Code/Framework/AzToolsFramework/AzToolsFramework/PythonTerminal/ScriptTermDialog.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/PythonTerminal/ScriptTermDialog.ui
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/ConsoleTextEdit.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content, sig/ui-ux, status/ux-approved

#11767 Improve the Shader Variant List File Save Workflow
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
  Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py
Labels: sig/graphics-audio

#11886 Fix for Eliding Label spacing in shared columns
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Labels: sig/content

#11562 Add 'Character' root node to skeleton outliner treeview (#10962)
  Gems/EMotionFX/Code/EMotionFX/Source/Node.h
  Gems/EMotionFX/Code/Source/Editor/ColliderHelpers.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/SkeletonOutlinerPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/SimulatedObjectHelpers.cpp
  Gems/EMotionFX/Code/Source/Editor/SkeletonModel.cpp
  Gems/EMotionFX/Code/Source/Editor/SkeletonModel.h
  Gems/EMotionFX/Code/Source/Editor/SkeletonModelJointWidget.cpp
  Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteColliders.cpp
  Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteJointLimits.cpp
  Gems/EMotionFX/Code/Tests/UI/CanAddJointAndChildren.cpp
  Gems/EMotionFX/Code/Tests/UI/CanAddSimulatedObject.cpp
  Gems/EMotionFX/Code/Tests/UI/CanAddToSimulatedObject.cpp
  Gems/EMotionFX/Code/Tests/UI/CanChangeParametersInSimulatedObject.cpp
  Gems/EMotionFX/Code/Tests/UI/ClothColliderTests.cpp
  Gems/EMotionFX/Code/Tests/UI/RagdollEditTests.cpp
Labels: feature/animation, sig/simulation

#11980 Fix Network Transform Event Handler Assert Upon Reactivation
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
Labels: sig/network

#11920 Check whether a source file is an LFS pointer file when it failed to be processed
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/Validators/LfsPointerFileValidator.cpp
  Code/Tools/AssetProcessor/native/AssetManager/Validators/LfsPointerFileValidator.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/Validators/LfsPointerFileValidatorTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/Validators/LfsPointerFileValidatorTests.h
Labels: sig/content

#12008 remove actor scale rule and motion scale rule, replace it with the coordinate system rule.
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Motion/MotionDataBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/ActorGroupBehavior.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionGroupBehavior.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/ActorScaleRule.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/ActorScaleRule.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/IActorScaleRule.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/IMotionScaleRule.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MotionScaleRule.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MotionScaleRule.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/sceneapi_ext_files.cmake
Labels: feature/animation

#12023 Script Canvas: Support for selecting asset IDs from nodes
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetSelectionModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
  Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.cpp
  Gems/ScriptCanvas/Code/Editor/GraphCanvas/DataInterfaces/ScriptCanvasAssetIdDataInterface.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/SourceHandlePropertyAssetCtrl.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Translation/GraphToLuaUtility.cpp
Labels: sig/content, sig/graphics-audio

#11745 [GHI-11704] Number of selected joints in Skeleton LOD rule in FBX settings is incorrect
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/LodRule.cpp
Labels: feature/animation, sig/simulation

#11248 FileWatcher_linux: Don't give up on a directory if a sub-entry couldn't be watched
  Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.cpp
  Code/Tools/AssetProcessor/Platform/Linux/native/FileWatcher/FileWatcher_linux.h
Labels: sig/content

#12051 CMake referenced Gems external_subdirectories fixes
  CMakeLists.txt
  cmake/GeneralSettings.cmake
  cmake/Subdirectories.cmake
Labels: sig/core

#11662 Asset processor dependency update
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Slice/SliceDependencyBrowserComponent.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.cpp
  Code/Tools/AssetProcessor/native/AssetDatabase/AssetDatabase.h
  Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/SourceFileRelocatorTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetdatabase/AssetDatabaseTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/JobDependencySubIdTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/ModtimeScanningTests.h
  Code/Tools/AssetProcessor/native/ui/AssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/AssetDetailsPanel.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessingStateDataUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
Labels: feature/asset-pipeline, sig/content

#12024 Merge GHI-7588 and GHI-9598 from development to stabalization
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
  Code/Tools/SceneAPI/SceneCore/Containers/Utilities/SceneGraphUtilities.cpp
  Code/Tools/SceneAPI/SceneCore/Containers/Utilities/SceneGraphUtilities.h
  Code/Tools/SceneAPI/SceneCore/DataTypes/Rules/IClothRule.h
  Code/Tools/SceneAPI/SceneCore/Utilities/SceneGraphSelector.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/SceneGraphSelector.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.h
  Gems/Atom/TestData/TestData/Objects/SkinnedMesh/MeshOptimization/sameposition_differentjointids_shouldnotweldvertices.fbx
  Gems/NvCloth/Code/Source/Pipeline/SceneAPIExt/ClothRule.cpp
  Gems/SceneProcessing/Code/Source/Generation/Components/MeshOptimizer/MeshOptimizerComponent.cpp
  Registry/sceneassetimporter.setreg
Labels: sig/core

#12053 DPE: Support horizontal rules in AssetEditor similar to the RPE
  Code/Editor/Style/Editor.qss
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Labels: sig/content

#12014 Hide prefab reference assignment in node inspector
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableEntitiesInterface.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeable_Source.jinja
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/CreateSpawnTicketNodeable.ScriptCanvasNodeable.xml
Labels: sig/content

#12066 Material Canvas: Fix toolbar to be docked with viewport. Fix asset browser menu button style.
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetBrowser/AtomToolsAssetBrowser.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.ui
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/Icons/menu.svg
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Registry/layouts.materialcanvas.setreg
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Registry/layouts.materialeditor.setreg
Labels: sig/content, sig/graphics-audio

#12070 Material Canvas: Fixing screen turning red from invalid entity bounds
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/ViewportInputBehavior.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorController.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorControllerInterface.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportContent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/DollyCameraBehavior.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/OrbitCameraBehavior.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/PanCameraBehavior.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/RotateCameraBehavior.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/ViewportInputBehavior.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorController.cpp
Labels: sig/content, sig/graphics-audio

#12019 Improved an error message about missing shader assets.
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
Labels: sig/graphics-audio, sig/ui-ux

#12017 Add installer parameters
  scripts/build/Platform/Linux/pipeline.json
  scripts/build/Platform/Windows/pipeline.json
Labels: sig/build, sig/release

#11986 Removed joint components restriction on the lead entity to be a collider
  Gems/PhysX/Code/Editor/EditorJointConfiguration.cpp
  Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsComponentMode.cpp
  Gems/PhysX/Code/Editor/Source/ComponentModes/Joints/JointsSubComponentModeRotation.cpp
  Gems/PhysX/Code/Source/EditorBallJointComponent.cpp
  Gems/PhysX/Code/Source/EditorFixedJointComponent.cpp
  Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp
  Gems/PhysX/Code/Source/EditorJointComponent.cpp
  Gems/PhysX/Code/Source/EditorJointComponent.h
  Gems/PhysX/Code/Source/JointComponent.cpp
  Gems/PhysX/Code/Source/JointComponent.h
  Gems/PhysX/Code/Source/Utils.cpp
  Gems/PhysX/Code/Source/Utils.h
Labels: sig/simulation

#12052 fix for animation editor picking not working until render options are…
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
Labels: sig/simulation

#12022 Set smaller minimum sizes for UI animation panes
  Gems/LyShine/Code/Editor/Animation/UiAnimViewCurveEditor.ui
  Gems/LyShine/Code/Editor/Animation/UiAnimViewKeyPropertiesDlg.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.ui
Labels: sig/ui-ux

#12029 DiffuseProbeGrid Edge Blend IBL Option
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender-nomsaa_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender-nomsaa_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender-nomsaa_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridrender_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Code/Include/DiffuseProbeGrid/DiffuseProbeGridFeatureProcessorInterface.h
  Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.cpp
  Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.h
  Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
  Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.h
Labels: sig/graphics-audio

#11880 Prefab | Remove entity DOM cache in prefab undo cache
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGeneratorInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoCache.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoCache.h
Labels: sig/content, feature/prefabs

#12068 Update AP job icons for reflecting the failure/error state and keeping consistency with other tables
  Code/Framework/AzQtComponents/AzQtComponents/Components/img/logging/failure.svg
  Code/Framework/AzQtComponents/AzQtComponents/Components/img/logging/warning.svg
  Code/Framework/AzQtComponents/AzQtComponents/Components/resources.qrc
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.h
Labels: feature/asset-pipeline, sig/content

#12092 Update the content details table to display/hide automatically
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessorConfig.ini
  Code/Tools/AssetProcessor/native/ui/style/AssetsTab.qss
Labels: status/ux-approved

#12108 New error log line in AP Jobs pane
  Code/Tools/AssetProcessor/AssetBuilder/TraceMessageHook.cpp
Labels: status/ux-approved

#12020 Added a popup message when the scene file or scene manifest is changed
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Editor/Plugins/EditorAssetImporter/SceneSerializationHandler.cpp
  Code/Editor/Plugins/EditorAssetImporter/SceneSerializationHandler.h
  Code/Tools/SceneAPI/SceneCore/Events/SceneSerializationBus.h
  Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidget.cpp
  Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidget.h
Labels: sig/content, sig/ui-ux

#12112 Mesh scale fix for non FBX files
  Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
Labels: feature/asset-pipeline, sig/content

#12016 {lyn15166} Adding context during update manifest event handling
  Code/Tools/SceneAPI/SceneBuilder/SceneImportRequestHandler.h
  Code/Tools/SceneAPI/SceneCore/Containers/SceneManifest.h
  Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
  Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.h
  Code/Tools/SceneAPI/SceneCore/Import/ManifestImportRequestHandler.h
  Code/Tools/SceneAPI/SceneCore/Mocks/Events/MockAssetImportRequest.h
  Code/Tools/SceneAPI/SceneCore/Tests/Events/AssetImporterRequestTests.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/Reporting.h
  Code/Tools/SceneAPI/SceneData/Behaviors/AnimationGroup.h
  Code/Tools/SceneAPI/SceneData/Behaviors/BlendShapeRuleBehavior.h
  Code/Tools/SceneAPI/SceneData/Behaviors/LodRuleBehavior.h
  Code/Tools/SceneAPI/SceneData/Behaviors/MeshAdvancedRule.h
  Code/Tools/SceneAPI/SceneData/Behaviors/MeshGroup.h
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.h
  Code/Tools/SceneAPI/SceneData/Behaviors/SkeletonGroup.h
  Code/Tools/SceneAPI/SceneData/Behaviors/SkinGroup.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/ActorGroupBehavior.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/LodRuleBehavior.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MorphTargetRuleBehavior.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionGroupBehavior.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionRangeRuleBehavior.h
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/SkeletonOptimizationRuleBehavior.h
  Gems/NvCloth/Code/Source/Pipeline/SceneAPIExt/ClothRuleBehavior.h
  Gems/PhysX/Code/Source/Pipeline/MeshBehavior.h
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
  Gems/SceneLoggingExample/Code/Behaviors/LoggingGroupBehavior.h
  Gems/SceneLoggingExample/Code/Processors/LoadingTrackingProcessor.h
  Gems/SceneProcessing/Code/Source/Config/Components/SceneProcessingConfigSystemComponent.h
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
Labels: sig/simulation

#12061 Prefab | Add parent DOM update in instantiate-prefab
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
Labels: sig/content, feature/prefabs

#11845 Add Ubuntu 22.04 nightly job
  scripts/build/Platform/Linux/build_config.json
Labels: sig/build, sig/platform

#12140 Material Canvas: Fixing issues with node configuration editor and saving untitled documents
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeConfig.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManager.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeManagerRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeSlotConfig.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeManager.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodePaletteItem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeSlotConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocumentRequestBus.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
Labels: sig/content, sig/graphics-audio

#12126 New multiplayer entity context menu
  Gems/Multiplayer/Code/CMakeLists.txt
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
Labels: sig/network, sig/ui-ux, status/ux-approved

#11906 Enable component mode switcher by default
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/ComponentModeSwitcher.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/ViewportSettings.cpp
Labels: status/ux-approved

#12154 Prefab Fix | Set parent of direct entities to null in create-prefab
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
Labels: sig/content, feature/prefabs

#12193 bugfix(Script Canvas): fix crash when highlighting a variable
  Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/GraphicsItems/GraphicsEffect.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/GraphicsItems/GraphicsEffectBus.h
Labels: feature/scripting, sig/content

#12082 Fixed the "open in explorer" button for scene settings
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.cpp
Labels: feature/asset-pipeline, sig/content

#12130 ComponentAdapter PR
  Code/Framework/AzCore/AzCore/std/any.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content

#12211 Material Canvas: Fix dynamic nodes to respect title overrides
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNode.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNodeConfig.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNode.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodePaletteItem.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/StyleSheet/materialcanvas_style.json
  Gems/GraphModel/Code/Include/GraphModel/Integration/Helpers.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/NodePalette/StandardNodePaletteItem.h
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
Labels: sig/content, sig/graphics-audio

#12192 Material Canvas: Fixing crash/refresh bug in node config editor
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNodeSlotConfig.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/PropertyWidgets/PropertyStringBrowseEditCtrl.h
Labels: sig/content, sig/graphics-audio

#12210 Material Canvas: Fixing graph canvas and graph model data interfaces to send notifications after values are edited
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/AssetIdNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/ComboBoxNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/EntityIdNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/NumericNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/StringNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/StringNodePropertyDisplay.h
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.cpp
  Gems/GraphCanvas/Code/Source/Components/NodePropertyDisplays/VectorNodePropertyDisplay.h
  Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/VectorDataInterface.inl
  Gems/GraphModel/Code/Source/Integration/BooleanDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/FloatDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
  Gems/GraphModel/Code/Source/Integration/IntegerDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/ReadOnlyDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/StringDataInterface.cpp
Labels: sig/content, sig/graphics-audio

#12153 Last Processing Job Duration shows most significant time units first
  Code/Tools/AssetProcessor/native/resourcecompiler/JobsModel.cpp
Labels: status/ux-approved

#12254 Disabling ReflectionProbeAdded null render test
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
Labels: sig/graphics-audio

#11855 {ghi11827} Fixed memory leaks with Graph Proxy Object unit tests
  Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
  Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.h
  Code/Tools/SceneAPI/SceneCore/Containers/SceneGraph.cpp
  Code/Tools/SceneAPI/SceneCore/Mocks/MockBehaviorUtils.h
  Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
Labels: sig/content

#12194 bugfix(Script Canvas): improve dragging behavior for spinbox for script canvas
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SpinBox.cpp
Labels: feature/scripting, sig/content

#12215 refactor(Lua Editor): consolidate LUAEditorPlainTextEdit
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/PlainTextEdit.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/PlainTextEdit.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Tools/LuaIDE/Source/LUA/LUAEditorFindResults.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorFindResults.ui
  Code/Tools/LuaIDE/Source/LUA/LUAEditorFoldingWidget.hxx
  Code/Tools/LuaIDE/Source/LUA/LUAEditorPlainTextEdit.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorPlainTextEdit.hxx
Labels: sig/content

#12295 disabling atom tests which add axis aligned box shape
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
Labels: sig/graphics-audio

#12285 disabling tests which add axis aligned box
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
Labels: sig/graphics-audio

#12041 Remove legacy Joint Outliner (#11311)
  Gems/EMotionFX/Assets/Editor/Layouts/Character.layout
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/PluginManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeWindow/NodeWindowPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/NodeWindow/NodeWindowPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/standardplugins_files.cmake
  Gems/EMotionFX/Code/Tests/UI/CanSeeJoints.cpp
  Gems/EMotionFX/Code/Tests/UI/LODSkinnedMeshTests.cpp
Labels: do-not-merge/blocked-paths, feature/animation, sig/simulation
