Repository o3de/o3de, pull requests merged in 2022-08, with the labels that each got.

#10545 Asset processor intermediate assets UI
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.cpp
  Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/ui/AssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/AssetDetailsPanel.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.h
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.ui
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.h
  Code/Tools/AssetProcessor/native/ui/style/AssetProcessor.qss
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: sig/content

#10441 Display project engines and versions and allow changing project engine
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Source/EngineInfo.cpp
  Code/Tools/ProjectManager/Source/EngineInfo.h
  Code/Tools/ProjectManager/Source/FormComboBoxWidget.cpp
  Code/Tools/ProjectManager/Source/FormComboBoxWidget.h
  Code/Tools/ProjectManager/Source/GemCatalog/GemModel.cpp
  Code/Tools/ProjectManager/Source/ProjectBuilderWorker.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.h
  Code/Tools/ProjectManager/Source/ProjectInfo.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.h
  Code/Tools/ProjectManager/Source/ProjectManagerWindow.cpp
  Code/Tools/ProjectManager/Source/ProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.h
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.h
  Code/Tools/ProjectManager/Source/PythonBindingsInterface.h
  Code/Tools/ProjectManager/Source/Settings.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectSettingsScreen.h
  Code/Tools/ProjectManager/project_manager_files.cmake
  cmake/Projects.cmake
  scripts/o3de/o3de/manifest.py
  scripts/o3de/o3de/project_properties.py
  scripts/o3de/o3de/register.py
  scripts/o3de/tests/test_manifest.py
Labels: feature/project-manager

#11005 Bug fix: Asset Processor debug build crashes due to BuilderInfoMetricsModel index inconsistencies
  Code/Tools/AssetProcessor/native/ui/BuilderData.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderData.h
  Code/Tools/AssetProcessor/native/ui/BuilderDataItem.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderDataItem.h
  Code/Tools/AssetProcessor/native/ui/BuilderInfoMetricsModel.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderInfoMetricsModel.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Labels: sig/content

#10519 feat: improve about dialog
  Code/Editor/AboutDialog.cpp
  Code/Editor/AboutDialog.h
  Code/Editor/AboutDialog.ui
  Code/Editor/CryEdit.cpp
  Code/Editor/StartupLogoDialog.cpp
  Code/Editor/StartupLogoDialog.h
  Code/Editor/StartupLogoDialog.ui
  Code/Editor/editor_lib_files.cmake
Labels: sig/content, sig/ui-ux, status/ux-approved

#10849 chore: cleanup Vector2Tests
  Code/Framework/AzCore/AzCore/Math/SimdMath.h
  Code/Framework/AzCore/AzCore/Math/SimdMathVec1.h
  Code/Framework/AzCore/AzCore/Math/SimdMathVec2.h
  Code/Framework/AzCore/AzCore/Math/SimdMathVec4.h
  Code/Framework/AzCore/Tests/Math/Vector2Tests.cpp
Labels: feature/azcore, sig/core, feature/math

#10843 chore: cleanup Vector4Tests
  Code/Framework/AzCore/Tests/Math/Vector4Tests.cpp
Labels: feature/azcore, sig/core, feature/math

#10847 chore: cleanup Vector3Tests
  Code/Framework/AzCore/Tests/Math/Vector3Tests.cpp
Labels: feature/azcore, sig/core, feature/math

#10973 Asset Processor - Fix Reprocess Folder on scanfolder parent path
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Labels: feature/asset-pipeline, sig/content

#10995 chore: fix spelling mistake FirstTimeAddedToRejectedList
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
Labels: sig/content, priority/minor

#10994 bugfix: fix rendering of arrow for tableview for linux
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TableView.qss
Labels: kind/bug, sig/core, sig/platform

#10979 {lyn13342} added an asset cache server test for local changes
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_cache_server.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/acs_local_change/test_00.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/acs_local_change/test_01.png
Labels: sig/content

#11009 [LYN-14013] Asset Manager - Fix old asset references destroying containers for current loads
  Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline, sig/content

#11044 Material Canvas: fixing graph view key bindings
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/GraphView/GraphView.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphCanvasEditor/GraphCanvasAssetEditorMainWindow.cpp
Labels: sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#10870 Fix for test script ScriptCanvasComponent_OnEntityActivatedDeactivated_PrintMessage
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvasComponent_OnEntityActivatedDeactivated_PrintMessage.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_tools.py
  AutomatedTesting/ScriptCanvas/OnEntityActivatedScripts/activator.scriptcanvas
  AutomatedTesting/ScriptCanvas/OnEntityActivatedScripts/controller.scriptcanvas
  AutomatedTesting/ScriptCanvas/OnEntityActivatedScripts/deactivator.scriptcanvas
Labels: feature/scripting, sig/content

#11034 Added setreg for UI viewport and animation viewport to limit feature …
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Registry/AnimViewport.setreg
  Gems/LyShine/Code/Source/UiRenderer.cpp
  Gems/LyShine/Registry/UiViewport.setreg
Labels: feature/graphics

#11064 Added friendly types for Multiplayer auto-components
  Code/Framework/AzFramework/AzFramework/Spawnable/Spawnable.h
Labels: sig/network

#11060 Material Canvas: fixed more shortcuts by adding shortcut context to asset browser actions
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11071 Viewport Visual Feedback Improvements (Prefabs Focus Mode) V3
  Code/Editor/CMakeLists.txt
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/ViewportTitleDlg.h
  Code/Editor/ViewportTitleDlg.ui
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/Child/EditorModeBlur.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/Child/EditorModeBlurParent.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/Child/EditorModeDesaturation.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/Child/EditorModeFeedback_ChildPassTemplates.azasset
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/Child/EditorModeOutline.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/Child/EditorModeTint.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/EditorModeBlurVertical.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/EditorModeFeedbackParent.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/EditorModeFeedback_PassRequest.azasset
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Passes/EditorModeMask.pass
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Shaders/EditorModeBufferCopy.azsl
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Shaders/EditorModeBufferCopy.shader
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Shaders/EditorModeMask.shader
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Shaders/EditorModeOutline.azsl
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Include/EditorModeFeedback/EditorStateRequestsBus.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/DrawableMeshEntity.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/DrawableMeshEntity.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMaskRenderer.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMaskRenderer.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMeshDrawPacket.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Draw/EditorStateMeshDrawPacket.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackFeatureProcessor.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackSystemComponent.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackSystemComponent.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/FocusedEntity/FocusedMeshEntity.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/FocusedEntity/FocusedMeshEntity.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeBlurPass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeBlurPass.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeDesaturationPass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeDesaturationPass.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeFeedbackChildPassBase.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeFeedbackChildPassBase.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeOutlinePass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeOutlinePass.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeTintPass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/Child/EditorModeTintPass.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorModeFeedbackParentPass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystem.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/EditorStatePassSystemUtils.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBase.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBase.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPass.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateBufferCopyPassData.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPass.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPass.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/EditorStateParentPassData.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityState.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/FocusedEntityState.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityState.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/Pass/State/SelectedEntityState.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/editormodefeedback_editor_files.cmake
Labels: sig/content, sig/ui-ux, needs-ux-action, needs-ux-info

#11078 Fixed grammatical errors
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector2Functions_SetX.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector2Functions_SetY.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector3Functions_SetX.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector3Functions_SetY.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector3Functions_SetZ.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetW.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetX.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetY.names
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_Vector4Functions_SetZ.names
Labels: feature/scripting

#11079 Added Landscape Canvas support or Axis Aligned Box Shape
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/AxisAlignedBoxShapeNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/AxisAlignedBoxShapeNode.h
  Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
  Gems/LandscapeCanvas/Code/landscapecanvas_editor_static_files.cmake
Labels: sig/content

#11075 Improved gradient baker workflow to detect and set connection between baker and image gradient
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/Ebuses/ImageGradientRequestBus.h
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientBakerComponent.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
  Gems/LandscapeCanvas/Assets/LandscapeCanvas/StyleSheet/graphcanvas_style.json
  Gems/LandscapeCanvas/Code/Source/Editor/Core/Core.h
  Gems/LandscapeCanvas/Code/Source/Editor/Core/DataTypes.h
  Gems/LandscapeCanvas/Code/Source/Editor/Core/GraphContext.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/GradientBakerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ImageGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ImageGradientNode.h
Labels: sig/content

#11108 Add missing FPs for anim editor
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Registry/AnimViewport.setreg
Labels: feature/graphics, feature/animation

#10989 Editor Server Reports Server Crash
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerConnectionViewportMessageSystemComponent.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network

#10626 Set the default enum for Multi-Position Audio Component
  Gems/LmbrCentral/Code/Source/Audio/EditorAudioMultiPositionComponent.h
Labels: sig/graphics-audio

#11029 Updating HDRi Skybox automation to P1
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRiSkyboxAdded.py
Labels: sig/graphics-audio

#11117 Fixed false positive invalid font family warning in Graph Canvas
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/Parser.cpp
Labels: sig/content

#11059 Remove AR artifact upload spam
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/testing

#11072 [LYN-14352] Asset Manager - Fix deadlock issue caused by calling GetAsset inside AssetBus callback
  Code/Framework/AzCore/AzCore/Asset/AssetContainer.cpp
  Code/Framework/AzCore/AzCore/Asset/AssetContainer.h
  Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
  Code/Framework/AzCore/AzCore/Asset/AssetManager_private.h
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline, sig/content

#11157 Corrected codegen for rewindable array network properties
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#11062 Adding a GPU periodic HDR Color Grading generate LUT test
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/periodic_AtomEditorComponents_HDRColorGradingAdded.py
Labels: sig/graphics-audio

#11030 Fix being able to uninstall gems that have AWS set as the origin
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
Labels: sig/network

#11055 Fix function node slot reset crash
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/SlotConfigurations.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Serialization/DatumSerializer.cpp
Labels: sig/content

#11120 Prefab/Add template propagation when entering and exiting prefab focus mode
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
Labels: sig/content

#10951 Multiplayer Client-Server Fix
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/IMultiplayerSpawnerMock.h
  Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
Labels: sig/content, sig/network

#11176 Fixes an issue with AZ::Interface<T>::Get()
  Code/Framework/AzCore/AzCore/Interface/Interface.h
Labels: feature/azcore, kind/bug, sig/core

#11167 Use container card header in EmotionFX
  Gems/EMotionFX/Assets/Editor/Images/Icons/ArrowRightGray.png
  Gems/EMotionFX/Code/MysticQt/Source/DialogStack.cpp
  Gems/EMotionFX/Code/MysticQt/Source/DialogStack.h
Labels: feature/animation, sig/simulation

#11153 P1 null render tests for PostFX Radius Weight Modifier
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PostFXRadiusWeightModifierAdded.py
Labels: sig/graphics-audio

#11184 Fixed typos in Script Canvas math nodes
  Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Multiply_E9BB45A1-AE96-47B0-B2BF-2927D420A28C.names
  Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Subtract_D0615D0A-027F-47F6-A02B-E35DAF22F431.names
Labels: feature/scripting

#11177 Removed explicit dependency on Vegetation gem from Landscape Canvas
  Gems/LandscapeCanvas/Code/CMakeLists.txt
  Gems/LandscapeCanvas/Code/Include/LandscapeCanvas/LandscapeCanvasBus.h
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.h
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/BaseAreaNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/FastNoiseGradientNode.h
  Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.cpp
  Gems/LandscapeCanvas/Code/Source/LandscapeCanvasSystemComponent.h
  Gems/LandscapeCanvas/gem.json
Labels: sig/content

#11202 Asset Manager Unit Tests - Fix asset cleanup
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline, sig/content

#10852 feat(AZCore): add CreateFromEuler/Radians/Degrees(XYZ,YXZ,ZYX)
  Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
  Code/Framework/AzCore/AzCore/Math/Quaternion.h
  Code/Framework/AzCore/AzCore/Math/Quaternion.inl
  Code/Framework/AzCore/Tests/Math/QuaternionPerformanceTests.cpp
  Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
Labels: feature/azcore, sig/core

#11065 chore: update Framework and remove usage of VectorConversions
  Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ManipulatorView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewportScreenTests.cpp
Labels: sig/core

#9649 Initial Sky Atmosphere
  Gems/Atom/Feature/Common/Assets/Passes/OpaqueParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Passes/SkyAtmosphere.pass
  Gems/Atom/Feature/Common/Assets/Passes/SkyAtmosphereParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/SkyRayMarching.pass
  Gems/Atom/Feature/Common/Assets/Passes/SkyTransmittanceLUT.pass
  Gems/Atom/Feature/Common/Assets/Passes/SkyViewLUT.pass
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyAtmosphereCommon.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyRayMarching.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyRayMarching.shader
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyRayMarching.shadervariantlist
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyTransmittanceLUT.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyTransmittanceLUT.shader
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyViewLUT.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyViewLUT.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkyAtmosphere/SkyAtmosphereFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereParentPass.cpp
  Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmosphereParentPass.h
  Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmospherePass.cpp
  Gems/Atom/Feature/Common/Code/Source/SkyAtmosphere/SkyAtmospherePass.h
  Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ComputePass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/FullscreenTrianglePass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/FullscreenTrianglePass.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/SkyAtmosphere/SkyAtmosphereComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Module.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/EditorSkyAtmosphereComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/EditorSkyAtmosphereComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/SkyAtmosphereComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/SkyAtmosphereComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/SkyAtmosphereComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/SkyAtmosphereComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SkyAtmosphere/SkyAtmosphereComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
Labels: feature/graphics, sig/graphics-audio

#11206 Fixes ComponentApplication shutdown in Launcher
  Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasAutoGenRegistry.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammarRegistry_Source.jinja
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen/ScriptCanvasNodeableRegistry_Source.jinja
  Gems/ScriptCanvas/Code/Source/ScriptCanvasCommonGem.cpp
  Gems/ScriptCanvasTesting/Code/Source/Framework/ScriptCanvasTestFixture.h
Labels: feature/scripting, kind/bug, sig/content

#11222 Asset Manager - Fix AssetManager tests using AssetBus::ExecuteQueuedEvents
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline, sig/content

#11226 Deleted deprecated file
  Assets/Engine/textures/default_icon.png
Labels: sig/content

#11235 Asset Manager - Add some debug output for 2 unit tests to help diagnose cause of timeout
  Code/Framework/AzCore/Tests/Asset/AssetManagerLoadingTests.cpp
Labels: feature/asset-pipeline, sig/content

#11234 Material Canvas: Deleting generated files that got merged accidentally
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.material
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialtype
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4_ForwardPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4_ForwardPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.material
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialtype
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5_ForwardPass.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5_ForwardPass.shader
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11129 [EMFX] Add smoothing filter option for root motion extraction
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Motion/MotionDataBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/RootMotionExtractionRuleBehavior.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/RootMotionExtractionRule.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/RootMotionExtractionRule.h
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/MotionData.h
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/NonUniformMotionData.h
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/RootMotionExtractionData.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MotionData/RootMotionExtractionData.h
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
  Gems/EMotionFX/Code/MCore/Source/Algorithms.cpp
  Gems/EMotionFX/Code/MCore/Source/Algorithms.h
  Gems/EMotionFX/Code/Tests/MCore/AlgorithmsTests.cpp
  Gems/EMotionFX/Code/emotionfx_tests_files.cmake
Labels: feature/animation

#11247 Material Canvas: Fixing code generation failures caused by line endings
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11243 Material Canvas: Fix cut, copy, paste, duplicate clipboard operations
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicNode/DynamicNode.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicNode/DynamicNode.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#10968 [LYN-14219] Asset Processor - Fix CreateJobs Reserved Builder
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.h
  Code/Tools/AssetProcessor/native/utilities/Builder.cpp
  Code/Tools/AssetProcessor/native/utilities/Builder.h
  Code/Tools/AssetProcessor/native/utilities/BuilderList.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderList.h
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
Labels: feature/asset-pipeline, sig/content

#11236 Material Canvas: Add Material Canvas (Preview) to main editor tools menu
  Code/Framework/AzQtComponents/AzQtComponents/Images/Menu/material_canvas.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/resources.qrc
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentRequestBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialBrowserInteractions.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11250 Motion Matching: Added CSV exporter for the frame database
  Gems/MotionMatching/Code/Source/CsvSerializers.cpp
  Gems/MotionMatching/Code/Source/FeatureAngularVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureMatrix.cpp
  Gems/MotionMatching/Code/Source/FeatureMatrix.h
  Gems/MotionMatching/Code/Source/FeaturePosition.cpp
  Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/FrameDatabase.cpp
  Gems/MotionMatching/Code/Source/FrameDatabase.h
  Gems/MotionMatching/JupyterNotebooks/LearnedMotionMatching.ipynb
Labels: feature/animation, sig/simulation

#9430 Remove SelectionComponent
  Code/Editor/Plugins/ComponentEntityEditorPlugin/Objects/ComponentEntityObject.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/Outliner/OutlinerListModel.cpp
  Code/Framework/AzCore/AzCore/Component/EntitySerializer.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/SelectionComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/SelectionComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/SelectionComponentBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/GenericComponentWrapperTest.cpp
Labels: feature/editor, sig/content, feature/viewport

#10158 Expose full blend state info to shaders
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderBuilderUtility.cpp
  Gems/Atom/Feature/Common/Assets/Materials/Special/ShadowCatcher.shader
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.shader
  Gems/Atom/Feature/Common/Assets/Shaders/DiffuseGlobalIllumination/DiffuseGlobalFullscreen.shader
  Gems/Atom/Feature/Common/Assets/Shaders/ImGui/ImGui.shader
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCullingHeatmap.shader
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCullingRemap.shader
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCullingTilePrepare.shader
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/LuminanceHeatmap.shader
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/NewDepthOfFieldComposite.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionComposite.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionProbeBlendWeight.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionProbeRenderOuter.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceComposite.shader
  Gems/Atom/Feature/Common/Assets/Shaders/ScreenSpace/DeferredFog.shader
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyRayMarching.shader
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Common/JsonReportingHelper.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderSourceData.cpp
  Gems/AtomLyIntegration/AtomBridge/Assets/Shaders/SimpleTextured.shader
  Gems/AtomLyIntegration/AtomViewportDisplayIcons/Assets/Shaders/TexturedIcon.shader
  Gems/AtomLyIntegration/EditorModeFeedback/Assets/Shaders/EditorModeMask.shader
  Gems/AtomLyIntegration/ImguiAtom/Assets/Shaders/ImGuiAtom/ImGuiAtom.shader
  Gems/AtomTressFX/Assets/Shaders/HairRenderingFillPPLL.shader
  Gems/AtomTressFX/Assets/Shaders/HairRenderingResolvePPLL.shader
  Gems/AtomTressFX/Assets/Shaders/HairShortCutGeometryDepthAlpha.shader
  Gems/AtomTressFX/Assets/Shaders/HairShortCutGeometryShading.shader
  Gems/AtomTressFX/Assets/Shaders/HairShortCutResolveColor.shader
  Gems/AtomTressFX/Assets/Shaders/HairShortCutResolveDepth.shader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/DiffuseComposite.shader
  Gems/LyShine/Assets/LyShine/Shaders/LyShineUI.shader
  Gems/Meshlets/ASV_GPU_and_CPU_Demo/DebugShaderPBR_ForwardPass.shader
  Gems/Stars/Assets/Shaders/Stars/Stars.shader
Labels: sig/graphics-audio

#10676 Adding implementation of C++23 ranges::to
  Code/Framework/AzCore/AzCore/Console/Console.cpp
  Code/Framework/AzCore/AzCore/EBus/Internal/StoragePolicies.h
  Code/Framework/AzCore/AzCore/Memory/BestFitExternalMapSchema.cpp
  Code/Framework/AzCore/AzCore/Module/Environment.cpp
  Code/Framework/AzCore/AzCore/std/azstd_files.cmake
  Code/Framework/AzCore/AzCore/std/concepts/concepts.h
  Code/Framework/AzCore/AzCore/std/containers/containers_concepts.h
  Code/Framework/AzCore/AzCore/std/containers/deque.h
  Code/Framework/AzCore/AzCore/std/containers/fixed_unordered_map.h
  Code/Framework/AzCore/AzCore/std/containers/fixed_unordered_set.h
  Code/Framework/AzCore/AzCore/std/containers/fixed_vector.h
  Code/Framework/AzCore/AzCore/std/containers/forward_list.h
  Code/Framework/AzCore/AzCore/std/containers/list.h
  Code/Framework/AzCore/AzCore/std/containers/map.h
  Code/Framework/AzCore/AzCore/std/containers/node_handle.h
  Code/Framework/AzCore/AzCore/std/containers/rbtree.h
  Code/Framework/AzCore/AzCore/std/containers/set.h
  Code/Framework/AzCore/AzCore/std/containers/unordered_map.h
  Code/Framework/AzCore/AzCore/std/containers/unordered_set.h
  Code/Framework/AzCore/AzCore/std/containers/vector.h
  Code/Framework/AzCore/AzCore/std/hash_table.h
  Code/Framework/AzCore/AzCore/std/iterator.h
  Code/Framework/AzCore/AzCore/std/parallel/containers/concurrent_fixed_unordered_map.h
  Code/Framework/AzCore/AzCore/std/parallel/containers/concurrent_fixed_unordered_set.h
  Code/Framework/AzCore/AzCore/std/parallel/containers/concurrent_unordered_map.h
  Code/Framework/AzCore/AzCore/std/parallel/containers/concurrent_unordered_set.h
  Code/Framework/AzCore/AzCore/std/parallel/containers/internal/concurrent_hash_table.h
  Code/Framework/AzCore/AzCore/std/ranges/ranges.h
  Code/Framework/AzCore/AzCore/std/ranges/ranges_algorithm.h
  Code/Framework/AzCore/AzCore/std/ranges/ranges_to.h
  Code/Framework/AzCore/AzCore/std/ranges/transform_view.h
  Code/Framework/AzCore/AzCore/std/string/fixed_string.h
  Code/Framework/AzCore/AzCore/std/string/fixed_string.inl
  Code/Framework/AzCore/AzCore/std/string/string.h
  Code/Framework/AzCore/Tests/AZStd/DequeAndSimilar.cpp
  Code/Framework/AzCore/Tests/AZStd/Hashed.cpp
  Code/Framework/AzCore/Tests/AZStd/Lists.cpp
  Code/Framework/AzCore/Tests/AZStd/ListsFixed.cpp
  Code/Framework/AzCore/Tests/AZStd/Ordered.cpp
  Code/Framework/AzCore/Tests/AZStd/RangesAlgorithmTests.cpp
  Code/Framework/AzCore/Tests/AZStd/RangesUtilityTests.cpp
  Code/Framework/AzCore/Tests/AZStd/String.cpp
  Code/Framework/AzCore/Tests/AZStd/VectorAndArray.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/CvarAdapter.cpp
  Code/Tools/AssetBundler/source/ui/NewFileDialog.cpp
  Code/Tools/AssetBundler/source/ui/RulesTabWidget.cpp
Labels: sig/core

#11292 Client-server fixes with deactivate/activate for an autonomous entity
  Gems/Multiplayer/Code/Source/Components/NetworkTransformComponent.cpp
Labels: sig/network

#11276 Fixed output of pthread create_thread errors on Linux and Android
  Code/Framework/AzCore/Platform/Android/AzCore/AzCore_Traits_Android.h
  Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/std/parallel/internal/thread_UnixLike.cpp
  Code/Framework/AzCore/Platform/Linux/AzCore/AzCore_Traits_Linux.h
  Code/Framework/AzCore/Platform/Linux/AzCore/std/parallel/internal/thread_Linux.cpp
  Code/Framework/AzCore/Platform/Mac/AzCore/AzCore_Traits_Mac.h
  Code/Framework/AzCore/Platform/Windows/AzCore/AzCore_Traits_Windows.h
  Code/Framework/AzCore/Platform/iOS/AzCore/AzCore_Traits_iOS.h
  Code/Framework/AzFramework/AzFramework/Network/AssetProcessorConnection.cpp
Labels: kind/bug

#11246 Add the DiffuseProbeGridUpdatePass after the DepthPrePass
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
Labels: sig/graphics-audio

#11300 Prefabs UI | Fix Outliner code to correctly expand ancestors of current focus
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.hxx
Labels: kind/bug, sig/content

#11267 Fixed crash in GroupElementToggle when the hidden attribute was added
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
Labels: sig/content

#11298 Reflect GetOnDisconnectedEvent Description plus typo fixes
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayer.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
  Gems/Multiplayer/Code/Tests/CommonBenchmarkSetup.h
  Gems/Multiplayer/Code/Tests/MockInterfaces.h
  Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/EventHandlerTranslationUtility.h
Labels: sig/network

#9925 feat: implementation of whitebox manipulator
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/BaseManipulator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/RotationManipulators.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/ScaleManipulators.h
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponentMode.h
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.cpp
  Gems/WhiteBox/Code/Source/SubComponentModes/EditorWhiteBoxTransformMode.h
  Gems/WhiteBox/Code/Source/Util/WhiteBoxEditorDrawUtil.cpp
  Gems/WhiteBox/Code/Source/Util/WhiteBoxEditorDrawUtil.h
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonTranslationModifier.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxViewportConstants.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxViewportConstants.h
  Gems/WhiteBox/Code/whitebox_editor_supported_files.cmake
Labels: feature/whitebox, sig/content

#10508 chore(EmotionFX): update AzEulerAnglesToAzQuat with AZ::Quaternion::CreateFromEulerAnglesRadians
  Gems/EMotionFX/Code/CMakeLists.txt
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeTransformNode.cpp
  Gems/EMotionFX/Code/MCore/Source/AzCoreConversions.h
  Gems/EMotionFX/Code/Tests/MCore/AZCoreConversionsTest.cpp
  Gems/EMotionFX/Code/Tests/TransformUnitTests.cpp
  Gems/EMotionFX/Code/emotionfx_tests_files.cmake
Labels: feature/animation, sig/simulation

#11321 Scene settings button padding
  Code/Tools/SceneAPI/SceneUI/RowWidgets/ManifestVectorWidget.ui
Labels: sig/content

#10876 bugfix(Vulkan): set access bit on image barrier
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphCompiler.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/rhi

#11327 Motion Matching: Added transform space option for csv serializer
  Gems/MotionMatching/Code/Source/CsvSerializers.cpp
  Gems/MotionMatching/Code/Source/CsvSerializers.h
  Gems/MotionMatching/Code/Source/FrameDatabase.cpp
  Gems/MotionMatching/Code/Source/FrameDatabase.h
Labels: feature/animation, sig/simulation

#11338 {lyn14636} switching script buses to Automation
  Code/Tools/SceneAPI/SceneCore/Containers/Scene.cpp
  Code/Tools/SceneAPI/SceneCore/Events/ExportProductList.cpp
  Code/Tools/SceneAPI/SceneCore/Mocks/MockBehaviorUtils.h
  Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
  Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneGraphTests.cpp
  Code/Tools/SceneAPI/SceneCore/scenecore_testing_files.cmake
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
  Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneScriptRuleTests.cpp
Labels: feature/asset-pipeline

#11264 {lyn14020} added Fetch to GraphObjectProxy
  Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
  Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.h
  Code/Tools/SceneAPI/SceneCore/Tests/Containers/SceneBehaviorTests.cpp
Labels: feature/asset-pipeline

#11278 bugfix(ScriptCanvas): correctly display labels in the Node Inspector used to display [0]
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp
Labels: feature/scripting, kind/bug, sig/content

#11325 Changing material builder settings and (AtomCore) AZ::Data::InstanceId to support material editor and canvas workflows
  Code/Framework/AtomCore/AtomCore/Instance/InstanceId.cpp
  Code/Framework/AtomCore/AtomCore/Instance/InstanceId.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/Material.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials, feature/graphics/asset

#11353 Add several unit tests for NetworkEntity in Multiplayer Gem
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkEntity/NetworkEntityUpdateMessage.h
  Gems/Multiplayer/Code/Source/MultiplayerStats.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicationManager.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityTracker.h
  Gems/Multiplayer/Code/Tests/CommonNetworkEntitySetup.h
  Gems/Multiplayer/Code/Tests/NetworkEntityTests.cpp
  Gems/Multiplayer/Code/Tests/NetworkInputTests.cpp
  Gems/Multiplayer/Code/Tests/ServerHierarchyTests.cpp
  Gems/Multiplayer/Code/multiplayer_tests_files.cmake
Labels: sig/network

#11369 Motion Matching: Added option to read/write positions and/or rotation…
  Gems/MotionMatching/Code/Source/CsvSerializers.cpp
  Gems/MotionMatching/Code/Source/CsvSerializers.h
  Gems/MotionMatching/Code/Source/FrameDatabase.cpp
  Gems/MotionMatching/Code/Source/FrameDatabase.h
Labels: feature/animation, sig/simulation

#11426 Created an Alignment attribute in the DPE
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Labels: sig/content

#11379 Multiplayer PyTest Util No Longer Parses Logs
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerEditorServerBus.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorAutomation.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/multiplayer_editor_shared_files.cmake
Labels: sig/network

#11281 bugfix(ScriptCanvas): prevent multiple prompts when providing a key
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ReflectedPropertyEditor.hxx
Labels: feature/scripting, kind/bug, sig/content

#11441 bugfix(Lua Editor): correctly handle updaing font size for lua editor
  Code/Tools/LuaIDE/Source/LUA/LUAEditorPlainTextEdit.cpp
Labels: kind/bug, sig/ui-ux

#11433 bugfix(Lua Editor): better handle fetching documents by id for linux
  Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorContext.h
Labels: platform/linux, kind/bug, sig/platform

#10902 Added GetVisible() to the MeshFeatureProcessor
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Labels: sig/graphics-audio

#11481 Bug fix for Aabb assert in Recast Navigation unit tests in Debug
  Gems/RecastNavigation/Code/Source/Misc/RecastNavigationPhysXProviderComponentController.cpp
Labels: sig/simulation

#11331 Fixed Random Integer node name
  Gems/ScriptCanvas/Assets/TranslationAssets/GlobalMethods/ScriptCanvas_MathRandoms_RandomInteger.names
Labels: feature/scripting, sig/content

#11284 feat(ScriptCanvas): add vector2/3/4 and color to multiply node
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorMul.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorMul.h
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_OperatorMul.scriptcanvas
Labels: feature/scripting, sig/content

#11507 Applied secondary style to LogPanel, fixes tab close icon in AP & ME
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/LogPanel_Panel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Logging/StyledLogPanel.cpp
Labels: feature/asset-pipeline, feature/editor

#11497 Exposed ToolBar ActionManager APIs to Python
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.h
  Gems/EditorPythonBindings/Code/Source/ActionManager/ToolBarManagerBus.h
  Gems/EditorPythonBindings/Code/editorpythonbindings_common_files.cmake
Labels: sig/content

#11496 Prefab | Fix prefab save issue in create entity
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
Labels: sig/content

#11336 {lyn14000} re-insert script processing rule logic
  AutomatedTesting/Assets/ap_test_assets/script_reinsert.fbx
  AutomatedTesting/Assets/ap_test_assets/script_reinsert.fbx.assetinfo
  AutomatedTesting/Assets/ap_test_assets/script_reinsert.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/script_basics/base_example.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/script_basics/simple.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/script_basics/simple.fbx.assetinfo
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/pythonassetbuildertests.py
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.cpp
  Code/Tools/SceneAPI/SceneData/Behaviors/ScriptProcessorRuleBehavior.h
  Code/Tools/SceneAPI/SceneData/Tests/SceneManifest/SceneManifestRuleTests.cpp
Labels: feature/asset-pipeline, sig/content

#11524 Minor Code Spelling Fix in Multiplayer ImGui Code
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
Labels: sig/network

#11538 Material Editor: Ignoring empty property groups in document and inspector
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#11537 Material Canvas: Support for saving custom window layouts
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.qrc
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/Icons/menu.svg
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/Icons/view.svg
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
Labels: feature/graphics, sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11299 Prefab | Refactor instance DOM generator workflow
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGeneratorInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabInstanceUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabInstanceUtils.h
Labels: sig/content, feature/prefabs

#11569 Atom Tools: Fixed issue with properties disappearing from inspector if multiple documents are open and closed
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentInspector.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorMainWindow.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
Labels: feature/graphics, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11559 Increase wait time for processing loop in unit test to avoid spurious…
  Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
Labels: feature/asset-pipeline, sig/content

#11553 Update Asset-Processing.json
  scripts/build/build_failure_rca/rca_patterns/Asset-Processing.json
Labels: sig/testing

#11565 Launcher code deprecation
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
  Tools/LyTestTools/ly_test_tools/launchers/launcher_helper.py
Labels: sig/testing

#11602 Atom Tools: Support for registering dedicated Python scripts with SMC, ME, MC
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Registry/scripts.shadermanagementconsole.setreg
Labels: feature/graphics, sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders

#11502 DPE SharePriorColumn attribute
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
Labels: sig/content

#11550 No overlap when drawing rotate gizmo and draw start / end segments
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/AngularManipulatorCircleViewFeedback.cpp
Labels: needs-ux-approval

#11376 Fix rendering to a single mip-level of a texture with vulkan
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.h
Labels: sig/graphics-audio

#11610 Material Component: Renamed MaterialReceiver* to MaterialConsumer* plus comments
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
  Gems/Blast/Code/Source/Editor/EditorBlastMeshDataComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
Labels: sig/content, sig/graphics-audio

#11470 chore: deprecate both ConvertEulerRadiansToQuaternion and ConvertEulerDegreesToQuaternion
  Code/Framework/AzCore/AzCore/Math/Quaternion.h
  Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
Labels: feature/azcore, sig/core

#11427 Stop Non-Net Prefabs from Producing Network.Spawnable
  Gems/Multiplayer/Code/Source/Pipeline/NetworkPrefabProcessor.cpp
  Gems/Multiplayer/Code/Tests/PrefabProcessingTests.cpp
Labels: sig/content, sig/network

#11607 Material Canvas: Improving default layouts, material type descriptions, symbol and display name generation
  Code/Framework/AzQtComponents/AzQtComponents/Images/Menu/material_canvas.svg
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/combine2.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/combine3.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/combine4.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/split2.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/split3.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Functions/split4.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExamplePBR/example_pbr2.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExamplePBR/example_pbr2.materialcanvastemplate.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName.material.template
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName.materialtype.template
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.azsl.template
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/MaterialGraphName_ForwardPass.shader.template
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/experimental_pbr.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/MaterialTemplates/ExperimentalPBR/experimental_pbr.materialcanvastemplate.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/Nodes/Textures/sample_texture_2d.materialcanvasnode
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test1.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test2.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test3.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test4.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test5.materialcanvas.azasset
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/Icons/application.svg
  Gems/Atom/Tools/MaterialCanvas/Registry/layouts.materialcanvas.setreg
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Registry/layouts.materialeditor.setreg
Labels: feature/graphics, sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/shaders, feature/graphics/materials

#11286 feat(ScriptCanvas): add vector2/3/4 to divide node
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorDiv.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Operators/Math/OperatorDiv.h
  Gems/ScriptCanvasTesting/Assets/ScriptCanvas/UnitTests/LY_SC_UnitTest_OperatorDiv.scriptcanvas
Labels: feature/scripting, sig/content

#11104 Codeowners hints
  AutomatedTesting/Gem/PythonTests/editor_test_testing/TestSuite_Main.py
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/terminal_report.py
  Tools/LyTestTools/ly_test_tools/cli/__init__.py
  Tools/LyTestTools/ly_test_tools/cli/codeowners_hint.py
  Tools/LyTestTools/tests/CMakeLists.txt
  Tools/LyTestTools/tests/integ/test_o3de_codeowners.py
  Tools/LyTestTools/tests/unit/test_codeowners_hint.py
  Tools/LyTestTools/tests/unit/test_terminal_report.py
  scripts/build/codeowners_hint.py
Labels: sig/testing

#11643 Fix the problem that create double actor instances when open workspaces
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
Labels: feature/animation

#11668 Rename IsAuth/IsAuto to IsNetEntityRoleAuth/Auto
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerController.h
  Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
  Gems/Multiplayer/Code/Source/Components/MultiplayerController.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
  Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Labels: sig/network
