Repository o3de/o3de, pull requests merged in 2022-02, with the labels that each got.

#6454 Fix incorrect icon rendering
  Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/AzManipulatorTestFramework.h
  Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ViewportInteraction.h
  Code/Framework/AzManipulatorTestFramework/Source/ViewportInteraction.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/AzToolsFrameworkTestHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorVisibleEntityDataCacheInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockFocusModeInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorDefaultSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorDefaultSelection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorInteractionSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorInteractionSystemViewportSelectionRequestBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorPickEntitySelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorPickEntitySelection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorVisibleEntityDataCache.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframeworktestcommon_files.cmake
  Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
  Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewportEditorModeTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content, feature/viewport

#7301 Removed legacy PropertyResourceCtrl
  Code/Editor/Controls/BitmapToolTip.cpp
  Code/Editor/Controls/BitmapToolTip.h
  Code/Editor/Controls/QBitmapPreviewDialog.cpp
  Code/Editor/Controls/QBitmapPreviewDialog.h
  Code/Editor/Controls/QBitmapPreviewDialog.ui
  Code/Editor/Controls/QBitmapPreviewDialogImp.cpp
  Code/Editor/Controls/QBitmapPreviewDialogImp.h
  Code/Editor/Controls/QToolTipWidget.cpp
  Code/Editor/Controls/QToolTipWidget.h
  Code/Editor/Controls/ReflectedPropertyControl/PropertyCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/PropertyResourceCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/PropertyResourceCtrl.h
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVar.cpp
  Code/Editor/editor_core_files.cmake
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#7262 Script Canvas: Added a toolbar button to capture a screenshot
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/Resources/scriptcanvas_screenshot.png
  Gems/ScriptCanvas/Code/Editor/View/Windows/ScriptCanvasEditorResources.qrc
Labels: feature/scripting, sig/content

#7293 AutomatedTesting: Adding Multiplayer Authority->Client RPC Test
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_AutoComponent_RPC.py
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.prefab
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC.scriptcanvas
  AutomatedTesting/Levels/Multiplayer/AutoComponent_RPC/AutoComponent_RPC_NetLevelEntity.scriptcanvas
Labels: sig/network

#7317 Motion Matching: Added example level and assets for an automatic demo
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/CameraController_AutomaticDemo.scriptcanvas
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/CharacterController_AutomaticDemo.scriptcanvas
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/MotionMatching_AutomaticDemo.animgraph
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/MotionMatching_AutomaticDemo.ly
  Gems/MotionMatching/Assets/MotionMatching.animgraph
  Gems/MotionMatching/Assets/MotionMatching.motionset
  Gems/MotionMatching/preview.png
Labels: feature/animation, sig/content

#7261 Add overall timeout for the AR pipeline
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/build

#7328 Minor cleanup of some shader option related unit tests.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderOptionGroupLayout.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderOptionTypes.h
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderOptionGroupLayout.cpp
  Gems/Atom/RPI/Code/Tests/Material/LuaMaterialFunctorTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialFunctorTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeAssetTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
  Gems/Atom/RPI/Code/Tests/Shader/ShaderTests.cpp
Labels: sig/graphics-audio

#7276 Atom Tools: move boilerplate document management code to atom tools framework
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/PreviewRenderer/PreviewRendererCaptureState.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportComponent.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7250 Updated StandardPbr.materialtype to follow the new file material type format
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR.materialtype
Labels: sig/graphics-audio

#7313 ImGui: Added FindContainerByName() helper
  Gems/ImGui/Code/Include/LYImGuiUtils/HistogramGroup.h
  Gems/ImGui/Code/Source/LYImGuiUtils/HistogramGroup.cpp
Labels: feature/graphics, sig/content, sig/graphics-audio

#6113 Basic networking automation test
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py
  AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/BasicConnectivity_Connects.prefab
  AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/Player.prefab
  AutomatedTesting/Levels/Multiplayer/BasicConnectivity_Connects/tags.txt
Labels: sig/network

#7337 Add a new function to DynamicDrawInterface to support submiting cached …
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicDrawContext.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicDrawInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicDrawSystem.h
  Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawSystem.cpp
Labels: feature/graphics/rpi

#7304 Focus Mode | Switch instance referencing in Prefab Focus Handler to use more reliable Instance handles
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabFocus/PrefabFocusTests.cpp
Labels: feature/editor, sig/content, feature/prefabs

#7302 P1 Decal tests for null renderer
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_DecalAdded.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
  AutomatedTesting/Materials/decal/airship_symbol_decal.material
  AutomatedTesting/Materials/decal/airship_symbol_decal.tif
Labels: sig/graphics-audio

#7212 Metal pso caching support via MTLBinaryArchive
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DepthOfFieldWriteFocusDepthFromGpu.shader
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/PhysicalDeviceDescriptor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineLibrary.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineStateCache.h
  Gems/Atom/RHI/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Code/Source/RHI/PipelineStateCache.cpp
  Gems/Atom/RHI/Code/Tests/PipelineState.h
  Gems/Atom/RHI/Code/Tests/PipelineStateTests.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.h
  Gems/Atom/RHI/Metal/Code/Source/Platform/iOS/RHI/Metal_RHI_iOS.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PhysicalDevice.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineLibrary.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.h
  Gems/Atom/RHI/Null/Code/Source/RHI/PipelineLibrary.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLibrary.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Tests/Common/RHI/Stubs.h
Labels: feature/graphics/rhi

#7356 Add "Definitions" field to shader asset
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslShaderBuilderSystemComponent.cpp
  Gems/Atom/Asset/Shader/Code/Source/Editor/ShaderAssetBuilder.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Shader/ShaderSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Shader/ShaderSourceData.cpp
Labels: sig/graphics-audio, feature/graphics/shaders

#7282 Make atom render viewport the default for animation editor.
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
  Gems/EMotionFX/Assets/Editor/Layouts/AnimGraph.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Animation.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Character.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Physics.layout
  Gems/EMotionFX/Assets/Editor/Layouts/SimulatedObjects.layout
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/RenderPlugins/Source/OpenGLRender/OpenGLRenderPlugin.h
  Gems/EMotionFX/Code/Tests/Mocks/AtomRenderPlugin.h
  Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteColliders.cpp
  Gems/EMotionFX/Code/Tests/ProvidesUI/Ragdoll/CanCopyPasteJointLimits.cpp
  Gems/EMotionFX/Code/Tests/UI/CanAddToSimulatedObject.cpp
  Gems/EMotionFX/Code/Tests/UI/ClothColliderTests.cpp
  Gems/EMotionFX/Code/Tests/UI/RagdollEditTests.cpp
  Gems/EMotionFX/Code/Tests/UI/UIFixture.cpp
  Gems/EMotionFX/Code/Tests/UI/UIFixture.h
  Gems/EMotionFX/Code/emotionfx_editor_tests_files.cmake
Labels: feature/animation

#7340 Changed how pass system controls pipeline tick rate
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
Labels: sig/graphics-audio

#7341 Motion Matching: Bug fixes, adding more class descriptions, automatic target mode for trajectory query
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.cpp
  Gems/MotionMatching/Code/Source/BlendTreeMotionMatchNode.h
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/FeatureMatrix.h
  Gems/MotionMatching/Code/Source/FeatureTrajectory.h
  Gems/MotionMatching/Code/Source/Frame.h
  Gems/MotionMatching/Code/Source/FrameDatabase.cpp
  Gems/MotionMatching/Code/Source/FrameDatabase.h
  Gems/MotionMatching/Code/Source/KdTree.cpp
  Gems/MotionMatching/Code/Source/KdTree.h
  Gems/MotionMatching/Code/Source/MotionMatchingData.h
  Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
  Gems/MotionMatching/Code/Source/TrajectoryQuery.h
Labels: feature/animation, sig/content

#7392 Motion Matching: Fix for nightly build issue
  Gems/MotionMatching/Code/Source/KdTree.cpp
Labels: feature/animation, sig/content

#7332 Added preset for converting gsi images
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI16.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI32.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/GSI8.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/ImageBuilder.settings
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
Labels: sig/content, sig/graphics-audio

#7372 Focus Mode | Add unit tests for FocusOnParentOfFocusedPrefab
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabFocus/PrefabFocusTests.cpp
Labels: feature/editor, sig/content, feature/prefabs

#6795 Changed kill to protected.
  AutomatedTesting/Gem/PythonTests/automatedtesting_shared/base.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/android/launcher.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/base.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/linux/launcher.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/mac/launcher.py
  Tools/LyTestTools/ly_test_tools/launchers/platforms/win/launcher.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/tests/unit/test_launcher_android.py
  Tools/LyTestTools/tests/unit/test_launcher_base.py
  Tools/LyTestTools/tests/unit/test_launcher_linux.py
  Tools/LyTestTools/tests/unit/test_launcher_mac.py
  Tools/LyTestTools/tests/unit/test_launcher_win.py
  Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Labels: sig/testing

#7220 Create a debug material type for displaying per-vertex data
  Gems/Atom/Feature/Common/Assets/Materials/Special/DebugVertexStreams.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Special/DebugVertexStreams.material
  Gems/Atom/Feature/Common/Assets/Materials/Special/DebugVertexStreams.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Special/DebugVertexStreams.shader
  Gems/Atom/Feature/Common/Assets/Materials/Special/DebugVertexStreams_IncompatibleEnums.lua
Labels: sig/graphics-audio

#7365 Prefabs UI | Finalize RootAliasPath as a standardized instance handle system, and refactor PrefabFocusHandler to take advantage of it.
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
Labels: sig/content, feature/prefabs

#7402 Lua Editor: Prev Document Tab option from the View menu is misspelled…
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Labels: sig/content

#7221 Fix for GHI-7125 : Bitangents are flipped for models with mirrored uvs
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/TangentSpace.azsli
Labels: sig/graphics-audio

#7389 Load workspace should activate the graph by default.
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
Labels: feature/animation

#7256 Updated Light, Grid, and Physical Sky P0 tests
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_GridAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightAdded.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_PhysicalSkyAdded.py
Labels: sig/graphics-audio

#7334 Atom/qingtao/atom 16135
  Gems/Atom/Feature/Common/Assets/Textures/BRDFTexture.attimage
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/AttachmentImage.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/ImageSystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/ImageSystemInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ParentPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/AttachmentImageAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/AttachmentImageAssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Common/AnyAssetBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImage.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/AttachmentImageAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/AttachmentImageAssetCreator.cpp
Labels: sig/graphics-audio, sig/ui-ux, feature/graphics/rpi

#7339 Added support for hardware queue class on passes
  Gems/Atom/Feature/Common/Assets/Passes/SsaoCompute.pass
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridVisualizationAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/DepthOfFieldCopyFocusDepthToCpuPass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/Scope.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ScopeProducer.h
  Gems/Atom/RHI/Code/Source/RHI/Scope.cpp
  Gems/Atom/RHI/Code/Source/RHI/ScopeProducer.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/ComputePassData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/CopyPassData.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp
Labels: sig/graphics-audio

#7415 ATOM-17264 ASV: StreamingImageTest crashes
  Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawSystem.cpp
Labels: sig/graphics-audio, feature/graphics/rpi

#4877 {lyn7307} disable saving procedural prefabs in the Editor
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
Labels: sig/content

#7423 Atom Tools: Document system exposes reflected object data
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentNotificationBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicProperty.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/DynamicProperty/DynamicPropertyGroup.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicPropertyGroup.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocumentRequestBus.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/MaterialEditorApplication.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#7411 Upgrade AZSLc to version 1.7.35
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: sig/graphics-audio

#7375 Calculating uv transforms for terrain detail materials
  Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctor.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctor.h
  Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctorSourceData.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctorSourceData.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/MaterialUtils.h
  Gems/Atom/Utils/Code/Source/MaterialUtils.cpp
  Gems/Atom/Utils/Code/atom_utils_files.cmake
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
Labels: sig/graphics-audio

#7440 removing compute queue flag from SSAO
  Gems/Atom/Feature/Common/Assets/Passes/SsaoCompute.pass
Labels: sig/graphics-audio

#7386 Fix for github issue https://github.com/o3de/o3de/issues/6380
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/UserInterface_Compressed.preset
  Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/UserInterface_Lossless.preset
Labels: feature/graphics/tools

#6428 Improve and refactor Atom's light transmission in thin object mode
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Common.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_ForwardPass.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_SubsurfaceState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin_Common.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/BackLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/LightingData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/CapsuleLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DirectionalLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/DiskLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/LightTypesCommon.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/PointLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/QuadLight.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/TransmissionSurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadow.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli
  Gems/Atom/Feature/Common/Code/Source/Material/SubsurfaceTransmissionParameterFunctor.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/SubsurfaceTransmissionParameterFunctor.h
  Gems/Atom/Feature/Common/Code/Source/Material/SubsurfaceTransmissionParameterFunctorSourceData.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/SubsurfaceTransmissionParameterFunctorSourceData.h
Labels: sig/graphics-audio

#7416 Convert automated tests related to content and unused levels
  AutomatedTesting/Gem/PythonTests/Blast/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ComponentAssetCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ComponentCommands_test.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ComponentCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ComponentPropertyCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/EntityCRUDCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/EntityCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ObjectManagerCommands_test.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ObjectManagerCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/PySide_Example_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ViewPaneCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/ViewportTitleDlgCommands_test_case.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/hydra_editor_utils.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/hydra_test_utils.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/pyside_component_utils.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/character_controller/CharacterController_SwitchLevels.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_CheckDefaultShapeSettingIsPxMesh.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_MultipleSurfaceSlots.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshAutoAssignedWhenAddingRenderMeshComponent.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshAutoAssignedWhenModifyingRenderMeshComponent.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshConvexMeshCollides.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_PxMeshNotAutoAssignedWhenNoPhysicsFbx.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/force_region/ForceRegion_WithNonTriggerColliderWarning.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/material/Material_LibraryClearingAssignsDefault.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/ragdoll/Ragdoll_AddPhysxRagdollComponentWorks.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/shape_collider/ShapeCollider_CanBeAddedWitNoWarnings.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/shape_collider/ShapeCollider_InactiveWhenNoShapeComponent.py
  AutomatedTesting/Gem/PythonTests/Physics/tests/shape_collider/ShapeCollider_LargeNumberOfShapeCollidersWontCrashEditor.py
  AutomatedTesting/Gem/PythonTests/WhiteBox/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/WhiteBox/tests/WhiteBox_AddComponentToEntity.py
  AutomatedTesting/Gem/PythonTests/WhiteBox/tests/WhiteBox_SetDefaultShape.py
  AutomatedTesting/Gem/PythonTests/WhiteBox/tests/WhiteBox_SetInvisible.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Sandbox.py
  AutomatedTesting/Levels/Blast/Blast_ActorSplitsAfterCollision/Blast_ActorSplitsAfterCollision.prefab
  AutomatedTesting/Levels/Blast/Blast_ActorSplitsAfterDamage/Blast_ActorSplitsAfterDamage.prefab
  AutomatedTesting/Levels/Physics/CharacterController_SwitchLevels/CharacterController_SwitchLevels.prefab
  AutomatedTesting/Levels/WhiteBox/EmptyLevel/EmptyLevel.prefab
  AutomatedTesting/Levels/auto_test/auto_test.prefab
  AutomatedTesting/Levels/ocean_component/ocean_component.prefab
  AutomatedTesting/Levels/ocean_trackview/ocean_trackview.prefab
Labels: sig/content, sig/core

#7442 Atom Tools: fix gem autoload settings registry files
  Registry/gem_autoload.materialeditor.setreg
  Registry/gem_autoload.shadermanagementconsole.setreg
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7387 Remove -Wno-unused-value suppression for GCC
  Code/Legacy/CryCommon/ISystem.h
  Code/Legacy/CryCommon/Linux64Specific.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/FIR-Filter.cpp
  cmake/Platform/Common/GCC/Configurations_gcc.cmake
Labels: sig/build, sig/platform

#7325 Remove AZ_TRAIT_DISABLE_FAILED_PROCESS_LAUNCHER_TESTS and disabled te…
  Code/Framework/AzFramework/Tests/ProcessLaunchParseTests.cpp
Labels: sig/platform

#7444 Always store LinkIds during prefab instance serialization except when saving to disk
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndo.cpp
Labels: sig/content

#7483 PipelineState build fix for non-unity builds
  Gems/Atom/RHI/Code/Tests/PipelineState.h
Labels: feature/graphics

#7476 Fixed group and bookmark display on graph load
  Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
Labels: feature/scripting

#7467 Atom Tools: replaced document settings with settings registry
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemSettings.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemComponent.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystemSettings.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsWidget.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7491 Focus Mode | Remove const reference to prevent issues in nightly builds.
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
Labels: sig/content

#7450 Add a function to get the internal data for a disk light from it's feature processor
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DiskLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AuxGeom/AuxGeomDraw.h
Labels: sig/graphics-audio

#7446 Added server launcher sanity test.
  Tools/LyTestTools/tests/integ/sanity_tests.py
Labels: sig/network, sig/testing

#7093 Add AZ::Dom::Patch, a Generic DOM analog to JSON patch
  Code/Framework/AzCore/AzCore/DOM/DomComparison.cpp
  Code/Framework/AzCore/AzCore/DOM/DomComparison.h
  Code/Framework/AzCore/AzCore/DOM/DomPatch.cpp
  Code/Framework/AzCore/AzCore/DOM/DomPatch.h
  Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
  Code/Framework/AzCore/AzCore/DOM/DomPath.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/DOM/DomPatchBenchmarks.cpp
  Code/Framework/AzCore/Tests/DOM/DomPatchTests.cpp
  Code/Framework/AzCore/Tests/DOM/DomPathBenchmarks.cpp
  Code/Framework/AzCore/Tests/DOM/DomPathTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/core

#7437 Shader refactor (no functional changes)
  Gems/Atom/Feature/Common/Assets/Materials/Types/DepthPass_WithPS.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_DepthPass_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_ForwardPass.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Shadowmap_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedSurface_ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EnhancedParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EvaluateEnhancedSurface.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EvaluateStandardSurface.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/EvaluateTangentFrame.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/MultilayerParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/ParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/StandardGetAlphaAndClip.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/StandardGetNormalToWorld.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/StandardGetObjectToWorld.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/StandardTransformDetailUvs.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/StandardTransformUvs.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/README.md
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_DepthPass_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_ForwardPass.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Shadowmap_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_DepthPass_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ForwardPass.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_LowEndForward.shader
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_LowEndForward_EDS.shader
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_Shadowmap_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardSurface_ForwardPass.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/EnhancedSurface.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/TestData/TestData/Materials/Types/MinimalPBR_ForwardPass.azsl
Labels: sig/graphics-audio, feature/graphics/materials

#7406 Updated the image gradient component to use a streaming image asset
  Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageProcessingDefines.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/BuilderSettingManager.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/CubemapSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/MipmapSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PlatformSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/PresetSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Compressors/Compressor.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvertJob.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Tests/ImageProcessing_Test.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/imageprocessing_files.cmake
  Gems/Atom/Asset/ImageProcessingAtom/Code/imageprocessingatom_headers_files.cmake
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/GradientSignal/Code/CMakeLists.txt
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/ImageAsset.h
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/ImageAsset.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalImageTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.h
  Gems/GradientSignal/Code/Tests/GradientSignalTestHelpers.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestHelpers.h
  Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.h
  Gems/GradientSignal/Code/gradientsignal_shared_tests_files.cmake
Labels: sig/content, sig/graphics-audio

#7513 Sandbox "Sponza" level from AtomLevelLoadTest_Editor tests.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Sandbox.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_Atom_LevelLoadTest_Sandbox.py
Labels: sig/graphics-audio

#7481 Terrain default surface material
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainAreaMaterialRequestBus.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
Labels: sig/graphics-audio

#7523 Disabled tests that are reported failing on nightly builds
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
Labels: feature/scripting

#7368 Collects failed assets on LyTestTools test failures
  Tools/LyTestTools/ly_test_tools/_internal/managers/abstract_resource_locator.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/ly_test_tools/o3de/editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_editor_test_utils.py
  Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Labels: sig/testing, do-not-merge/in-review

#7509 Focus Mode | Create an integration test for Box Select while in Focus Mode
  Code/Framework/AzToolsFramework/Tests/FocusMode/ContainerEntitySelectionTests.cpp
  Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeFixture.cpp
  Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeFixture.h
  Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeSelectionFixture.h
  Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeSelectionTests.cpp
Labels: feature/editor, sig/content, feature/prefabs

#7443 Refactor EditorEntityUiHandlerBase to be explicitly Outliner-focused.
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/EditorEntityUi/EditorEntityUiHandlerBase.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/EditorEntityUi/EditorEntityUiHandlerBase.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/LevelRootUiHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/LevelRootUiHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabUiHandler.h
Labels: sig/content

#7439 LYN-8403 Prevent the same Surface Tag from getting reused
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals_Impl.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEnumComboBoxCtrl.hxx
  Gems/SurfaceData/Code/Include/SurfaceData/SurfaceTag.h
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
  Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainSurfaceGradientListComponent.h
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainSurfaceGradientListComponent.cpp
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainSurfaceGradientListComponent.h
  Gems/Terrain/Code/Source/EditorSurfaceTagListProvider.cpp
  Gems/Terrain/Code/Source/EditorSurfaceTagListProvider.h
  Gems/Terrain/Code/terrain_editor_shared_files.cmake
Labels: sig/content, feature/terrain

#7155 updating python packages py, pillow, and urllib3
  python/requirements.txt
Labels: do-not-merge/hold, sig/testing

#7534 Fix inadvertent exclusion of NetEntities during filtering and missing component notification
  Gems/Multiplayer/Code/Source/NetworkTime/NetworkTime.cpp
Labels: sig/network

#7556 Updated missing shaderball assets.
  AutomatedTesting/Levels/Graphics/macbeth_shaderballs/macbeth_shaderballs.prefab
Labels: sig/graphics-audio

#7537 Added Support For Factoring-Out Material Property Groups
  Gems/Atom/Feature/Common/Code/Source/Material/SubsurfaceTransmissionParameterFunctorSourceData.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/Transform2DFunctorSourceData.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/JsonFileLoadContext.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/JsonUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/LuaMaterialFunctorSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialFunctorSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialPropertyId.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/LuaMaterialFunctor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialFunctor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialNameContext.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Common/JsonFileLoadContext.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/LuaMaterialFunctorSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialFunctorSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialFunctorSourceDataSerializer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialPropertyId.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/MaterialSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/LuaMaterialFunctor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialFunctor.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialNameContext.cpp
  Gems/Atom/RPI/Code/Tests/Common/JsonTestUtils.h
  Gems/Atom/RPI/Code/Tests/Material/LuaMaterialFunctorTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialFunctorTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialPropertyValueSourceDataTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
  Gems/Atom/RPI/Code/atom_rpi_edit_files.cmake
  Gems/Atom/RPI/Code/atom_rpi_reflect_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
Labels: sig/graphics-audio

#7585 Disabling problematic NetBindComponent assert with a configuration
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
Labels: sig/network

#7590 Only allow streaming image assets with supported pixel formats to be selected for an image gradient
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetPicker/AssetPickerDialog.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RPIUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/GradientSignal/Code/CMakeLists.txt
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorStreamingImageAssetCtrl.h
  Gems/GradientSignal/Code/Source/GradientSignalEditorModule.cpp
  Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
Labels: sig/content

#7552 Python Tests Ensuring the Interface Project Manager Uses Exists and Signature Matches
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  scripts/o3de/o3de/download.py
  scripts/o3de/tests/test_project_manager_interface.py
Labels: sig/content

#7489 Update DXC to 1.6.2112 (+ o3de changes)
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: sig/graphics-audio

#6453 Allow SurfaceManipulator to self-intersect when holding Ctrl
  Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ActionDispatcher.h
  Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ImmediateModeActionDispatcher.h
  Code/Framework/AzManipulatorTestFramework/Source/ImmediateModeActionDispatcher.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/BaseManipulator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/SurfaceManipulator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/SurfaceManipulator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Manipulators/TranslationManipulators.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
Labels: sig/content, feature/viewport

#7553 Motion Matching: Added sections about the cost function and motion matching search to the readme
  Gems/MotionMatching/README.md
Labels: feature/animation, sig/content

#7613 Atom Tools: Moving shader management console file operations into document class
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocumentRequestBus.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleApplication.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/ShaderManagementConsoleRequestBus.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleTableView.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleTableView.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/shadermanagementconsole_files.cmake
  Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7559 Refactor the Outliner drag&drop and selection to fix UX and technical issues.
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerTreeView.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
Labels: feature/editor, sig/content

#7607 Added the DiffuseProbeGridVisualizationCompositePass
  AutomatedTesting/Passes/MainPipeline.pass
Labels: sig/graphics-audio

#7542 Change actorRenderFlag to use AZ ENUM CLASS instead of azstd::bitset
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRequestBus.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/EMStudioPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/RenderPlugin/RenderOptions.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.h
  Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.h
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderActorInstance.h
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderFlag.h
  Gems/EMotionFX/Code/Tests/RenderBackendManagerTests.cpp
Labels: feature/animation, sig/content

#7593 Optimize SurfaceData bulk queries
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SurfaceData/SurfaceDataMeshComponent.cpp
  Gems/GradientSignal/Code/Include/GradientSignal/Components/SurfaceAltitudeGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/Components/SurfaceMaskGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/Components/SurfaceSlopeGradientComponent.h
  Gems/GradientSignal/Code/Source/Components/SurfaceAltitudeGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalReferencesTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalSurfaceTests.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestMocks.h
  Gems/SurfaceData/Code/Include/SurfaceData/Components/SurfaceDataSystemComponent.h
  Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataModifierRequestBus.h
  Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataProviderRequestBus.h
  Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataSystemRequestBus.h
  Gems/SurfaceData/Code/Include/SurfaceData/SurfaceDataTypes.h
  Gems/SurfaceData/Code/Include/SurfaceData/SurfacePointList.h
  Gems/SurfaceData/Code/Include/SurfaceData/Tests/SurfaceDataTestMocks.h
  Gems/SurfaceData/Code/Source/Components/SurfaceDataColliderComponent.cpp
  Gems/SurfaceData/Code/Source/Components/SurfaceDataShapeComponent.cpp
  Gems/SurfaceData/Code/Source/SurfaceDataSystemComponent.cpp
  Gems/SurfaceData/Code/Source/SurfaceDataTypes.cpp
  Gems/SurfaceData/Code/Source/SurfacePointList.cpp
  Gems/SurfaceData/Code/Tests/SurfaceDataBenchmarks.cpp
  Gems/SurfaceData/Code/Tests/SurfaceDataColliderComponentTest.cpp
  Gems/SurfaceData/Code/Tests/SurfaceDataTest.cpp
  Gems/SurfaceData/Code/surfacedata_files.cmake
  Gems/Terrain/Code/Source/Components/TerrainSurfaceDataSystemComponent.cpp
  Gems/Vegetation/Code/Source/AreaSystemComponent.cpp
  Gems/Vegetation/Code/Source/Components/PositionModifierComponent.cpp
  Gems/Vegetation/Code/Source/Components/SurfaceMaskDepthFilterComponent.cpp
  Gems/Vegetation/Code/Source/Components/SurfaceMaskDepthFilterComponent.h
  Gems/Vegetation/Code/Source/Debugger/DebugComponent.cpp
  Gems/Vegetation/Code/Tests/VegetationMocks.h
Labels: sig/content, sig/graphics-audio

#7624 Adds support for additional VS debugger args
  Code/LauncherUnified/launcher_generator.cmake
Labels: sig/build

#7629 Atom Tools: Restoring idle behavior for viewport input behavior contoller
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/ViewportInputBehaviorController/IdleBehavior.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/IdleBehavior.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInputBehaviorController/ViewportInputBehaviorController.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7630 Prefabs UI | Refactor PrefabIntegrationManager into a separate class for save/load dialog management.
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorEntityAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EntityCompositionNotificationBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityTransformBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EntityTypes.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/SliceEditorEntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/SliceEditorEntityOwnershipServiceBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceEntityScrubber.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceEntityScrubber.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/EditorInfoRemover.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/UICore/WidgetHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabAssetFixupTests.cpp
  Code/Tools/SerializeContextTools/SliceConverter.cpp
  Gems/Prefab/PrefabBuilder/PrefabBuilderComponent.cpp
Labels: feature/editor, sig/content, feature/prefabs

#7540 Add 3p vulkan validation layer support.
  Gems/Atom/RHI/Vulkan/Code/CMakeLists.txt
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/PAL_windows.cmake
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: sig/graphics-audio

#7551 {lyn8578} adding UX for assinging a Python scene builder
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.ui
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.cpp
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.h
  Code/Editor/Plugins/EditorAssetImporter/ImporterRootDisplay.ui
  Code/Tools/SceneAPI/SceneData/Rules/ScriptProcessorRule.cpp
  Code/Tools/SceneAPI/SceneData/Rules/ScriptProcessorRule.h
Labels: sig/content, sig/ui-ux

#7561 Improved the way the Settings Registry can handle stacks/arrays.
  Code/Framework/AzCore/AzCore/Serialization/Json/JsonSystemComponent.cpp
  Code/Framework/AzCore/AzCore/Serialization/Json/RegistrationContext.h
  Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.cpp
  Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.h
  Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.inl
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/Settings/ConfigurableStackTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/content, sig/core

#7596 Atom editor screenshot test refactor for nightly GPU
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_component_helper.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomGPU_BasicLevelSetup.py
Labels: sig/graphics-audio

#7582 Animation Editor: Motion event colors aren't in sync with the event presets
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp
Labels: feature/animation, kind/bug, sig/content

#7625 Added support for several UNORM_SRGB formats
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyItem.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.h
  Code/Editor/Util/ColorUtils.cpp
  Code/Editor/Util/EditorUtils.cpp
  Code/Editor/editor_core_files.cmake
  Code/Framework/AzCore/AzCore/Math/Color.h
  Code/Framework/AzCore/AzCore/Math/Color.inl
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Converters/Gamma.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPIUtils.cpp
  Gems/LyShine/Code/Editor/Animation/Util/UiEditorUtils.cpp
Labels: sig/content, sig/core, sig/graphics-audio

#7643 EMotion FX: Colliders now also render without the collider plugins
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/EMotionFX/Code/Source/Editor/ColliderContainerWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/ColliderContainerWidget.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Cloth/ClothJointInspectorPlugin.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/HitDetection/HitDetectionJointInspectorPlugin.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeInspectorPlugin.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/SkeletonOutlinerPlugin.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SkeletonOutliner/SkeletonOutlinerPlugin.h
Labels: feature/animation, sig/content

#7610 Change rotation camera to use RMB, and add orbit rotation camera using LMB + alt
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportSettings.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportSettings.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
Labels: feature/animation

#7565 Add DomPrefixTree, a DOM path => value lookup structure
  Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
  Code/Framework/AzCore/AzCore/DOM/DomPath.h
  Code/Framework/AzCore/AzCore/DOM/DomPrefixTree.h
  Code/Framework/AzCore/AzCore/DOM/DomPrefixTree.inl
  Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
  Code/Framework/AzCore/AzCore/DOM/DomValue.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/DOM/DomPrefixTreeBenchmarks.cpp
  Code/Framework/AzCore/Tests/DOM/DomPrefixTreeTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
Labels: sig/content, sig/core

#7669 MaterialEditor fix for MSAA state
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
Labels: sig/graphics-audio

#7663 Move benchmark test metrics to their own suite outside of the GPU suite.
  AutomatedTesting/Gem/PythonTests/Atom/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Benchmark_GPU.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_GPU.py
Labels: sig/graphics-audio

#7543 Checksum of deb package needs to be recomputed after signing
  cmake/Platform/Linux/PackagingPostBuild_linux.cmake
Labels: sig/build

#7679 Removed unused Gradient Signal image builder and image processing component
  Gems/GradientSignal/Code/Include/GradientSignal/Components/ImageGradientComponent.h
  Gems/GradientSignal/Code/Include/GradientSignal/ImageAsset.h
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorImageBuilderComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorImageBuilderComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorImageProcessingSystemComponent.cpp
  Gems/GradientSignal/Code/Source/Editor/EditorImageProcessingSystemComponent.h
  Gems/GradientSignal/Code/Source/GradientSignalEditorModule.cpp
  Gems/GradientSignal/Code/Source/ImageAsset.cpp
  Gems/GradientSignal/Code/gradientsignal_editor_files.cmake
Labels: sig/content

#6555 Cleaned up issues with multiple components ? button
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
  Gems/AtomLyIntegration/AtomBridge/Code/Source/FlyCameraInputComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/RadiusWeightModifier/EditorRadiusWeightModifierComponent.cpp
  Gems/AtomTressFX/Code/Components/EditorHairComponent.cpp
  Gems/Blast/Code/Source/Editor/EditorBlastFamilyComponent.cpp
  Gems/Blast/Code/Source/Editor/EditorBlastMeshDataComponent.cpp
  Gems/FastNoise/Code/Source/EditorFastNoiseGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorConstantGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorDitherGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientTransformComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorImageGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorInvertGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorLevelsGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorMixedGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorPerlinGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorPosterizeGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorRandomGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorReferenceGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorShapeAreaFalloffGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorSmoothStepGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorSurfaceAltitudeGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorSurfaceMaskGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorSurfaceSlopeGradientComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorThresholdGradientComponent.h
  Gems/LmbrCentral/Code/Source/Scripting/EditorLookAtComponent.cpp
  Gems/LmbrCentral/Code/Source/Scripting/EditorRandomTimedSpawnerComponent.cpp
  Gems/LmbrCentral/Code/Source/Scripting/EditorSpawnerComponent.cpp
  Gems/LyShine/Code/Source/World/UiCanvasAssetRefComponent.cpp
  Gems/LyShine/Code/Source/World/UiCanvasProxyRefComponent.cpp
Labels: sig/content, sig/ui-ux

#7702 Updated SetImageAssetPath on image gradient to be more robust
  AutomatedTesting/Gem/PythonTests/largeworlds/gradient_signal/EditorScripts/ImageGradient_ModifiesSurfaces.py
  Gems/GradientSignal/Code/Source/Components/ImageGradientComponent.cpp
Labels: sig/content

#7661 [new] ATOM-17253 Using AtomTressFX gem as an example to inject hair passes to main pipeline at run-time
  AutomatedTesting/Passes/MainPipeline.pass
  Code/Editor/CryEdit.cpp
  Gems/Atom/Feature/Common/Assets/Passes/MainRenderPipeline.azasset
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/FeatureProcessor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ParentPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/RenderPipeline.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Scene.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/System/RenderPipelineDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RenderPipeline.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/System/RenderPipelineDescriptor.cpp
  Gems/AtomTressFX/Assets/Passes/AtomTressFX_PassRequest.azasset
  Gems/AtomTressFX/Assets/Passes/AtomTressFX_PassTemplates.azasset
  Gems/AtomTressFX/Assets/Passes/HairDepthToLinear.pass
  Gems/AtomTressFX/Assets/Passes/HairParentPass.pass
  Gems/AtomTressFX/Assets/Passes/HairParentShortCutPass.pass
  Gems/AtomTressFX/Assets/Passes/HairResolvePPLL.pass
  Gems/AtomTressFX/Assets/seedList.seed
  Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.cpp
  Gems/AtomTressFX/Code/Rendering/HairFeatureProcessor.h
Labels: feature/graphics, sig/graphics-audio

#7557 Adding support for blending the terain detail material with the macro material.
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainAreaMaterialRequestBus.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.h
Labels: sig/graphics-audio

#7609 [Impactful Change] Consolidate to_string implementations for math classes and add bool to_string
  Code/Framework/AzCore/AzCore/Math/MathStringConversions.cpp
  Code/Framework/AzCore/AzCore/Math/MathStringConversions.h
  Code/Framework/AzCore/AzCore/Math/ToString.cpp
  Code/Framework/AzCore/AzCore/Math/ToString.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/AzCore/std/string/conversions.h
  Code/Framework/AzCore/Tests/AZStd/String.cpp
  Code/Framework/AzCore/Tests/AZTestShared/Math/MathTestHelpers.cpp
  Code/Framework/AzCore/Tests/Math/MathStringsTests.cpp
  Code/Framework/AzCore/Tests/azcoretests_files.cmake
  Code/Framework/AzFramework/AzFramework/Components/NonUniformScaleComponent.cpp
  Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/ActionDispatcher.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorNonUniformScaleComponent.cpp
  Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
  Gems/EMotionFX/Code/MCore/Source/StringConversions.cpp
  Gems/EMotionFX/Code/MCore/Source/StringConversions.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugPerEntityReporter.cpp
  Gems/PhysX/Code/Editor/ColliderSphereMode.cpp
  Gems/PhysX/Code/Source/RigidBody.cpp
  Gems/PhysX/Code/Source/Utils.cpp
  Gems/WhiteBox/Code/Source/Core/WhiteBoxToolApi.cpp
Labels: sig/core, impactful-changes

#7529 Remove redundant ProgramVariant tag because it got deprecated.
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/MSAAResolveCustom.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurHorizontal.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceBlurVertical.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceComposite.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceTrace.shader
Labels: sig/graphics-audio

#7564 Add required support for GameLift TLS certificate
  Code/Framework/AzNetworking/AzNetworking/Utilities/EncryptionCommon.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Source/Activity/AWSGameLiftJoinSessionActivity.cpp
  Gems/AWSGameLift/Code/AWSGameLiftClient/Tests/Activity/AWSGameLiftJoinSessionActivityTest.cpp
  Gems/AWSGameLift/Code/AWSGameLiftCommon/Source/AWSGameLiftSessionConstants.h
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.cpp
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerManager.h
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/GameLiftServerSDKWrapper.cpp
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/GameLiftServerSDKWrapper.h
  Gems/AWSGameLift/Code/AWSGameLiftServer/Tests/AWSGameLiftServerManagerTest.cpp
  Gems/AWSGameLift/Code/AWSGameLiftServer/Tests/AWSGameLiftServerMocks.h
  Gems/Multiplayer/Code/Include/Multiplayer/Session/ISessionHandlingRequests.h
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/network

#7533 [development] Profiler gem cleanup
  Code/Framework/AzCore/AzCore/Debug/ProfilerBus.h
  Gems/Profiler/Code/Source/CpuProfiler.cpp
  Gems/Profiler/Code/Source/CpuProfiler.h
  Gems/Profiler/Code/Source/CpuProfilerImpl.h
  Gems/Profiler/Code/Source/ImGuiCpuProfiler.cpp
  Gems/Profiler/Code/Source/ProfilerImGuiSystemComponent.cpp
  Gems/Profiler/Code/Source/ProfilerSystemComponent.cpp
  Gems/Profiler/Code/Source/ProfilerSystemComponent.h
  Gems/Profiler/Code/profiler_files.cmake
Labels: sig/core, sig/graphics-audio

#7708 Focus Mode | Improvements to GetFocusedEntities
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/FocusMode/FocusModeSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockFocusModeInterface.h
  Code/Framework/AzToolsFramework/Tests/FocusMode/EditorFocusModeTests.cpp
Labels: feature/editor, sig/content

#7649 Focus Mode | Make Ctrl+S shortcut contextual to Prefab Focus
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEditDoc.cpp
  Code/Editor/EditorPreferencesPageGeneral.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
Labels: feature/editor, sig/content, feature/prefabs

#7628 Fixed ambiguous translation key when a property and a method share the same name
  Gems/GraphCanvas/Code/Source/Translation/TranslationSerializer.cpp
  Gems/ScriptCanvas/Assets/TranslationAssets/Classes/MaterialData.names
  Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Tests_BranchInputTypeExample.names
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
  Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
Labels: feature/scripting

#7733 Removed carriage return from errors
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Contracts/MethodOverloadContract.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Contracts/TypeContract.cpp
Labels: feature/scripting

#7720 EMotion FX: Limiting max values for playspeed, blend-in and blend-out times for the simple motion component
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.cpp
Labels: feature/animation, kind/bug, sig/content

#7713 EMotion FX: Minimized distance between wireframe and solid mesh rendering
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.h
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderActorSettings.h
Labels: feature/animation, kind/bug, sig/content

#7744 Atom Tools: Saving tool settings, made inspector configurable, moved to ATF
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentInspector.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Inspector/InspectorWidget.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/MaterialPropertyUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetGridDialog/AssetGridDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AtomToolsFrameworkSystemComponent.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentInspector.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Inspector/InspectorWidget.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/MaterialPropertyUtil.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Tests/AtomToolsFrameworkTest.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/CreateMaterialDialog/CreateMaterialDialog.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindow.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindowSettings.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialEditorWindowSettings.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/MaterialInspector/MaterialInspector.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/SettingsDialog/SettingsWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.h
  Gems/Atom/Tools/MaterialEditor/Code/materialeditor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialModelUvNameMapInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#6989 Add RoundUpToMultiple and DivideAndRoundUp functions to MathUtils.h
  Code/Framework/AzCore/AzCore/Math/MathUtils.h
  Code/Framework/AzCore/Tests/Math/MathUtilsTests.cpp
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
  Code/Framework/GridMate/GridMate/Carrier/SocketDriver.cpp
  Code/Framework/GridMate/GridMate/Carrier/SocketDriver.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Compressors/ASTCCompressor.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/PixelFormatInfo.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Bits.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ConstantsData.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchItem.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/ImageSubresource.cpp
  Gems/Atom/RHI/Code/Source/RHI/DrawList.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp
  Gems/Vegetation/Code/Source/Debugger/DebugComponent.cpp
Labels: sig/core

#7667 Prevent the character to go out of bound in animation viewport
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
Labels: feature/animation

#7617 Fix missing format parameter in RHI::Resource
  Gems/Atom/RHI/Code/Source/RHI/Resource.cpp
Labels: sig/graphics-audio

#7742 Editor | Refactor right-click context menu to improve grouping and surface most used items to the top.
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/componententityeditorplugin_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/EditorContextMenuBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.h
Labels: feature/editor, sig/content, feature/prefabs

#7747 EMotion FX: Update skeleton transforms when either solid mesh rendering or any of the debug visualizations is enabled
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/ActorComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Rendering/RenderFlag.h
Labels: feature/animation, kind/bug, sig/content

#7704 Atom Tools: fixing viewport entity initialization errors
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Viewport/MaterialViewportWidget.ui
  Gems/Atom/Tools/MaterialEditor/Code/materialeditor_files.cmake
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7753 set the shortcut to only work when the graph widget is on focus
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/BlendGraphViewWidget.cpp
Labels: feature/animation

#7739 add the render option reflection so it show up in the preference window
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
Labels: feature/animation

#7763 Focus Mode | Fix issue with cached focused TemplateId occasionally being set to Invalid by the EOS
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
Labels: feature/editor, sig/content, feature/prefabs

#7754 Fixed Heartbeat node's translation
  Gems/ScriptCanvas/Assets/TranslationAssets/Nodes/Timing_HeartBeat.names
Labels: feature/scripting

#7792 Make sure nodes always have a title
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
Labels: feature/scripting, sig/content, sig/ui-ux

#7737 Combine the 3 LoadInstanceFromPrefab methods to use a single helper method
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
Labels: sig/content

#7762 Refactored material types to share common property group definitions
  Gems/Atom/Feature/Common/Assets/Materials/Types/BasePBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Anisotropy.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_SubsurfaceState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/BaseColorPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ClearCoatPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/DetailMapsCommonFunctor.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/DetailMapsPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/EmissivePropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/GeneralCommonPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/IrradiancePropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/MetallicPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/NormalPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/OcclusionPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/OpacityPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ParallaxPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/RoughnessPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/SpecularPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/SubsurfaceAndTransmissionPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/UvPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/Skin.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ClearCoatEnableFeature.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ClearCoatState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_EmissiveState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_HandleOpacityDoubleSided.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_HandleOpacityMode.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_Metallic.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ParallaxState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_Roughness.lua
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/LuaMaterialFunctorSourceData.cpp
Labels: sig/graphics-audio

#7743 Fixed CalcImageDiffRms to compare the alpha channel too.
  Gems/Atom/Utils/Code/Source/ImageComparison.cpp
  Gems/Atom/Utils/Code/Tests/ImageComparisonTests.cpp
Labels: sig/graphics-audio

#7745 Generate AllProperties material files
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialPropertyValue.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialPropertyValueSerializer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialPropertySerializerTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialSourceDataTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialTypeSourceDataTests.cpp
  Gems/Atom/Utils/Code/Include/Atom/Utils/TestUtils/AssetSystemStub.h
  Gems/Atom/Utils/Code/Source/TestUtils/AssetSystemStub.cpp
Labels: sig/graphics-audio

#7769 Additional help page changes in #2321
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ColorGrading/EditorHDRColorGradingComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SurfaceData/EditorSurfaceDataMeshComponent.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientSurfaceDataComponent.h
  Gems/LmbrCentral/Code/Source/Shape/EditorReferenceShapeComponent.h
  Gems/LyShine/Code/Source/World/UiCanvasOnMeshComponent.cpp
  Gems/PhysX/Code/Source/EditorRigidBodyComponent.cpp
  Gems/SurfaceData/Code/Source/Editor/EditorSurfaceDataColliderComponent.h
  Gems/SurfaceData/Code/Source/Editor/EditorSurfaceDataShapeComponent.h
  Gems/Vegetation/Code/Source/Debugger/EditorAreaDebugComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorAreaBlenderComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorBlockerComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorDescriptorListCombinerComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorDescriptorListComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorDescriptorWeightSelectorComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorDistanceBetweenFilterComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorDistributionFilterComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorMeshBlockerComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorPositionModifierComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorRotationModifierComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorScaleModifierComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorShapeIntersectionFilterComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorSlopeAlignmentModifierComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorSurfaceAltitudeFilterComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorSurfaceMaskDepthFilterComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorSurfaceMaskFilterComponent.h
  Gems/Vegetation/Code/Source/Editor/EditorSurfaceSlopeFilterComponent.h
Labels: sig/content, sig/docs-community, sig/ui-ux

#7353 Update viewport/camera APIs to use `AzFramework::ScreenSize` instead of `AZ::Vector2`
  Code/Framework/AzFramework/AzFramework/Viewport/CameraState.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraState.h
  Code/Framework/AzFramework/AzFramework/Viewport/ScreenGeometry.h
  Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/ViewportScreen.h
  Code/Framework/AzFramework/AzFramework/Windowing/WindowBus.h
  Code/Framework/AzFramework/Tests/CameraState.cpp
  Code/Framework/AzManipulatorTestFramework/Include/AzManipulatorTestFramework/AzManipulatorTestFrameworkUtils.h
  Code/Framework/AzManipulatorTestFramework/Source/AzManipulatorTestFrameworkUtils.cpp
  Code/Framework/AzManipulatorTestFramework/Tests/ViewportInteractionTest.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorBoxSelect.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/InvalidClicks.cpp
  Code/Framework/AzToolsFramework/Tests/EditorTransformComponentSelectionTests.cpp
  Code/Framework/AzToolsFramework/Tests/EditorVertexSelectionTests.cpp
  Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp
  Code/Framework/AzToolsFramework/Tests/ManipulatorViewTests.cpp
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewportInteractionTests.cpp
  Code/Framework/AzToolsFramework/Tests/Viewport/ViewportScreenTests.cpp
  Code/Framework/AzToolsFramework/Tests/Visibility/EditorVisibilityTests.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/ViewportInteractionImpl.cpp
  Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.cpp
  Gems/Camera/Code/Source/CameraComponentController.cpp
  Gems/Camera/Code/Source/EditorCameraComponent.cpp
  Gems/LmbrCentral/Code/Tests/EditorComponentIntersectionTests.cpp
  Gems/WhiteBox/Code/Tests/WhiteBoxTestFixtures.h
Labels: sig/content

#7782 Added unit tests for GraphCanvas translation system
  Gems/GraphCanvas/Code/CMakeLists.txt
  Gems/GraphCanvas/Code/Source/Translation/TranslationBus.h
  Gems/GraphCanvas/Code/Source/Translation/TranslationDatabase.cpp
  Gems/GraphCanvas/Code/Tests/GraphCanvasTesting.cpp
  Gems/GraphCanvas/Code/Tests/GraphCanvasTranslation.cpp
  Gems/GraphCanvas/Code/graphcanvas_files.cmake
  Gems/GraphCanvas/Code/graphcanvas_staticlib_files.cmake
  Gems/GraphCanvas/Code/graphcanvas_tests_files.cmake
Labels: feature/scripting, sig/content

#7786 7698: Fix broken documentation link for Terrain Gem
  Gems/Terrain/gem.json
Labels: sig/content

#7767 Atom Tools: Added previews/thumbnails for material types and model presets
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerBus.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Thumbnail/ImageThumbnailSystemComponent.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Window/ViewportSettingsInspector/ViewportSettingsInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewUtils.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewer.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnailRenderer.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#7441 Addressed Warnings Reports in AtomSampleViewer Test Suite
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialConverterSystemComponent.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialSourceData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Material/MaterialAsset.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MaterialAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Material/MaterialAsset.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialAssetTests.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialSourceDataTests.cpp
Labels: sig/graphics-audio

#7833 Fix for ASV shutdown assert on IrradianceImage
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseGlobalIlluminationFeatureProcessor.cpp
Labels: sig/graphics-audio

#7812 Add right click option for reset character and cam controls
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportToolBar.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
Labels: feature/animation

#7823 Implemented the restore icon for the maximize/restore button
  Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/QDockWidget.qss
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/TitleBar.qss
  Code/Framework/AzQtComponents/AzQtComponents/Components/resources.qrc
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-close.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-maximize.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-minimize.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-popout-hover.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-popout-small.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-popout.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-restore-hover.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/Application/titlebar-restore.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/resources.qrc
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
Labels: sig/content

#7844 EMotion FX: Removing reflecting the render options from the Atom plugin
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AtomRenderPlugin.h
Labels: feature/animation, kind/bug, sig/content

#7840 Disable PSO caching for DX12
  Gems/Atom/RHI/Code/Source/RHI.Reflect/PipelineLayoutDescriptor.cpp
  Gems/Atom/RHI/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/DX12_Windows.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/PipelineLibrary.cpp
Labels: feature/graphics/rhi

#7802 P1 Mesh null renderer tests
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
Labels: sig/graphics-audio

#6484 AP startup error collector
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BaseStyleSheet.qss
  Code/Tools/AssetProcessor/assetprocessor_gui_files.cmake
  Code/Tools/AssetProcessor/native/ui/MessageWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MessageWindow.h
  Code/Tools/AssetProcessor/native/ui/MessageWindow.ui
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.h
Labels: sig/content

#7732 Partial srg compilation + Metal rendering fixes
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ImageSubresource.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Buffer.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Image.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ImageView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroup.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupPool.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/ImageSubresource.cpp
  Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp
  Gems/Atom/RHI/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroup.cpp
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupData.cpp
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/ArgumentBuffer.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ArgumentBuffer.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroup.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroup.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroup.cpp
Labels: sig/graphics-audio, feature/graphics/rhi

#7832 Switch RoundUp functions to use a template instead of uint32_t/uint64_t
  Code/Framework/AzCore/AzCore/Math/MathUtils.h
  Code/Framework/AzCore/Tests/Math/MathUtilsTests.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchItem.h
Labels: sig/core

#7852 Motion Matching: Upgraded level to prefabs and improved the camera controller
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/CameraController_AutomaticDemo.scriptcanvas
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/CharacterController_AutomaticDemo.scriptcanvas
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/MotionMatching_AutomaticDemo.ly
  Gems/MotionMatching/Assets/Levels/MotionMatching_AutomaticDemo/MotionMatching_AutomaticDemo.prefab
Labels: feature/animation, sig/content

#7772 EMotion FX: Simple motion component blend out time not working (+some more fixes)
  Gems/EMotionFX/Code/EMotionFX/Source/MotionLayerSystem.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/SimpleMotionComponent.h
  Gems/EMotionFX/Code/Tests/MotionLayerSystemTests.cpp
Labels: feature/animation, kind/bug, sig/content

#7770 EMotion FX: Moving ground plane along with the character bug fix
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportRenderer.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
Labels: feature/animation, kind/bug, sig/content

#7846 AssetBrowserWindow Search View Display Mode Refactor
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.ui
Labels: feature/editor, sig/ui-ux, priority/minor

#7859 Fixed crash due to a threading issue with PerlinGradientComponent
  Gems/GradientSignal/Code/Source/Components/PerlinGradientComponent.cpp
Labels: feature/terrain

#7760 Sandboxing test that relies on editor logs.
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
Labels: sig/content

#7768 Make RPI pass template pointed object const
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionScreenSpace/ReflectionScreenSpaceBlurPass.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassFactory.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassLibrary.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassSystemInterface.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFactory.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
Labels: sig/graphics-audio

#7803 Adding P1 support for the Light component automation
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightAdded.py
Labels: sig/graphics-audio

#5423 Multiplayer Desync Debug Logging
  Gems/EMotionFX/Code/MCore/Source/StringConversions.cpp
  Gems/EMotionFX/Code/MCore/Source/StringConversions.h
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerDebug.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerDebug.h
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerDebug.inl
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkInput/IMultiplayerComponentInput.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkInput/NetworkInput.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkInput/NetworkInputChild.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkTime/RewindableObject.h
  Gems/Multiplayer/Code/Include/Multiplayer/NetworkTime/RewindableObject.inl
  Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugAuditTrail.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugAuditTrail.h
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Debug/MultiplayerDebugSystemComponent.h
  Gems/Multiplayer/Code/Source/NetworkInput/NetworkInput.cpp
  Gems/Multiplayer/Code/Source/NetworkInput/NetworkInputChild.cpp
  Gems/Multiplayer/Code/Tests/NetworkInputTests.cpp
  Gems/Multiplayer/Code/Tests/RewindableObjectTests.cpp
  Gems/Multiplayer/Code/multiplayer_debug_files.cmake
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: sig/core, sig/network

#7531 Focused UI around GameLauncher and ServerLauncher test tool functiona…
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py
  AutomatedTesting/Gem/PythonTests/streaming/benchmark/asset_load_benchmark_test.py
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/test_tools_fixtures.py
  Tools/LyTestTools/ly_test_tools/launchers/launcher_helper.py
  Tools/LyTestTools/tests/CMakeLists.txt
  Tools/LyTestTools/tests/integ/sanity_tests.py
  Tools/LyTestTools/tests/unit/test_fixtures.py
  Tools/LyTestTools/tests/unit/test_launcher_base.py
Labels: sig/testing

#7761 Add break on assert setting with debugger attached
  Code/Framework/AzCore/AzCore/Debug/Trace.cpp
Labels: feature/azcore

#7841 Right click option shouldn't show up when mouse moved after press
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Tools/EMStudio/AnimViewportWidget.h
Labels: feature/animation

#7873 Animation Editor: Removed unused unit scale window
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/UnitScaleWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/UnitScaleWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/emstudiosdk_files.cmake
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/ActorsWindow.cpp
Labels: feature/animation, sig/content

#7875 Motion Matching: Camera controller for controllable character demo
  Gems/MotionMatching/Assets/Levels/MotionMatching_ControllableCharacter/CameraController_ControllableCharacter.scriptcanvas
  Gems/MotionMatching/Assets/Levels/MotionMatching_ControllableCharacter/InputBindings_ControllableCharacter.inputbindings
Labels: feature/animation, sig/content
