Repository o3de/o3de, pull requests merged in 2022-05, with the labels that each got.

#9308 Animation Editor: Moved motion properties to unified inspector window
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionExtractionWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionPropertiesWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionPropertiesWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.h
Labels: feature/animation, sig/simulation

#9228 Fixed: project names with more than 25 characters create a gap in the project manager
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.h
Labels: sig/content, feature/project-manager

#9134 chore: deprecate GetValue and SetValue for IAnimTrack using cryLegacy
  Code/Legacy/CryCommon/IMovieSystem.h
Labels: feature/trackview, sig/content

#9291 Update NetworkRigidBody to Require NetworkTransform
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Header.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkRigidBodyComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/NetworkCharacterComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetworkRigidBodyComponent.cpp
Labels: sig/network

#9292 Replaced PDO Shadow Bias With New Shadow Factor
  Gems/Atom/Feature/Common/Assets/Materials/Types/DepthPass_WithPS.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Common.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/EnhancedPBR_Shadowmap_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/MultilayerParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/ParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialFunctions/ParallaxShadowUtil.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/MaterialInputs/ParallaxPropertyGroup.json
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.materialtype
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Common.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Displacement.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR_Shadowmap_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_Common.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_ParallaxState.lua
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardPBR_Shadowmap_WithPS.azsl
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/Shadow.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Shadows/ProjectedShadowFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.h
  Gems/Atom/RPI/Assets/Shaders/ImagePreview.azsl
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.cpp
  Gems/Atom/TestData/TestData/Materials/StandardMultilayerPbrTestCases/002_ParallaxPdo.material
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiPassTree.inl
Labels: sig/graphics-audio

#9293 Remove nightly build failure template
  .github/ISSUE_TEMPLATE/nightly_build_failure_bug_template.md
Labels: sig/build, sig/operations

#9166 Updating reparent prefab test to test several use cases as well as undo/redo
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main_Optimized.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/reparent_prefab/ReparentPrefab_UnderAnotherPrefab.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/reparent_prefab/ReparentPrefab_UnderPrefabAndEntityHierarchies.py
Labels: sig/content, sig/testing

#9348 Fixed multiple issues for multiviewport
  Gems/Atom/Feature/Common/Code/Source/DiffuseGlobalIllumination/DiffuseProbeGridRayTracingPass.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphAttachmentDatabase.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ParentPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ParentPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassSystem.cpp
Labels: feature/graphics

#9175 Fixed Cloth gem sample assets.
  Gems/NvCloth/Assets/Objects/cloth/Chicken/Actor/chicken.fbx.assetinfo
  Gems/NvCloth/Assets/Objects/cloth/Environment/Cloth_Blinds.fbx.assetinfo
  Gems/NvCloth/Assets/Objects/cloth/Environment/Cloth_Blinds_Broken.fbx.assetinfo
  Gems/NvCloth/Assets/Objects/cloth/Environment/Cloth_Locked_Corners_Four.fbx.assetinfo
  Gems/NvCloth/Assets/Objects/cloth/Environment/Cloth_Locked_Corners_Two.fbx.assetinfo
  Gems/NvCloth/Assets/Objects/cloth/Environment/Cloth_Locked_Edge.fbx.assetinfo
  Gems/NvCloth/Assets/Objects/cloth/Environment/cloth_blinds.material
  Gems/NvCloth/Assets/Objects/cloth/Environment/cloth_blinds_broken.material
  Gems/NvCloth/Assets/Objects/cloth/Environment/cloth_locked_corners_four.material
  Gems/NvCloth/Assets/Objects/cloth/Environment/cloth_locked_corners_two.material
  Gems/NvCloth/Assets/Objects/cloth/Environment/cloth_locked_edge.material
  Gems/NvCloth/Assets/prefabs/Cloth/Chicken_Actor.prefab
  Gems/NvCloth/Assets/prefabs/Cloth/cloth_blinds.prefab
  Gems/NvCloth/Assets/prefabs/Cloth/cloth_blinds_broken.prefab
  Gems/NvCloth/Assets/prefabs/Cloth/cloth_locked_corners_four.prefab
  Gems/NvCloth/Assets/prefabs/Cloth/cloth_locked_corners_two.prefab
  Gems/NvCloth/Assets/prefabs/Cloth/cloth_locked_edge.prefab
Labels: feature/physics, sig/simulation

#9111 Initial pass at SIG-Network code ownership
  .github/CODEOWNERS
Labels: sig/network

#9360 Moved gradient preview popout icon to the left corner
  Gems/GradientSignal/Code/Source/UI/GradientPreviewWidget.cpp
Labels: sig/content

#9236 Make profiling lua script write out meta data
  Gems/AtomLyIntegration/CommonFeatures/Assets/Scripts/Profiling/OutputProfileData.lua
  Tools/LyTestTools/ly_test_tools/benchmark/data_aggregator.py
  Tools/LyTestTools/ly_test_tools/log/log_monitor.py
Labels: sig/content, sig/testing

#9290 AZ EnvironmentVariable boolean operator fixes
  Code/Framework/AzCore/AzCore/Interface/Interface.h
  Code/Framework/AzCore/AzCore/Module/Environment.h
  Code/Framework/AzCore/Tests/DLL.cpp
  Code/Framework/AzCore/Tests/DLLMainTest.cpp
  Code/Framework/AzCore/Tests/Serialization.cpp
  Code/Framework/AzCore/Tests/StreamerTests.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderReloadDebugTracker.cpp
Labels: sig/core

#9355 Motion Matching: Made debug draw independent of the mm instance
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/FeaturePosition.cpp
  Gems/MotionMatching/Code/Source/FeaturePosition.h
  Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
  Gems/MotionMatching/Code/Source/FeatureTrajectory.h
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureVelocity.h
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
Labels: feature/animation, sig/simulation

#9349 Add net_FragmentsAlwaysReliable cvar to UdpNetInterface
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.h
Labels: sig/network

#9319 Expand CODEOWNERS for sig-content
  .github/CODEOWNERS
Labels: sig/content

#9361 Updated FindWwise.cmake to check Wwise version
  cmake/3rdParty/FindWwise.cmake
Labels: feature/audio, kind/bug, sig/core

#9287 Add translation support for global method
  Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/EBusHandlerEventNodeDescriptorComponent.cpp
  Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/EBusHandlerNodeDescriptorComponent.cpp
  Gems/ScriptCanvas/Code/Editor/GraphCanvas/Components/NodeDescriptors/ScriptEventReceiverNodeDescriptorComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.cpp
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeCreateUtils.h
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.cpp
  Gems/ScriptCanvas/Code/Editor/Nodes/NodeDisplayUtils.h
  Gems/ScriptCanvas/Code/Editor/Translation/TranslationHelper.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/EBusNodePaletteTreeItemTypes.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/EBusNodePaletteTreeItemTypes.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/GeneralNodePaletteTreeItemTypes.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/NodePalette/NodePaletteModel.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/MethodConfiguration.cpp
  Gems/ScriptCanvas/Code/Tools/TranslationGeneration.cpp
  Gems/ScriptCanvas/Code/Tools/TranslationGeneration.h
Labels: sig/content

#9372 Fix the CDK version for AWSI automation tests to avoid installing CDK v2
  scripts/build/Platform/Linux/build_config.json
  scripts/build/Platform/Linux/deploy_cdk_applications.sh
  scripts/build/Platform/Linux/destroy_cdk_applications.sh
  scripts/build/Platform/Windows/build_config.json
  scripts/build/Platform/Windows/deploy_cdk_applications.cmd
  scripts/build/Platform/Windows/destroy_cdk_applications.cmd
Labels: sig/network

#9377 Invalidates thumbnail state when the asset is removed from the catalog asset
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedThumbnail.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9362 P1 automation support for HDR Color Grading component
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_HDRColorGradingAdded.py
Labels: sig/graphics-audio

#9163 First implementation of the Automation gem
  Gems/ScriptAutomation/CMakeLists.txt
  Gems/ScriptAutomation/Code/CMakeLists.txt
  Gems/ScriptAutomation/Code/Include/ScriptAutomation/ScriptAutomationBus.h
  Gems/ScriptAutomation/Code/Source/ScriptAutomationModule.cpp
  Gems/ScriptAutomation/Code/Source/ScriptAutomationScriptBindings.cpp
  Gems/ScriptAutomation/Code/Source/ScriptAutomationScriptBindings.h
  Gems/ScriptAutomation/Code/Source/ScriptAutomationSystemComponent.cpp
  Gems/ScriptAutomation/Code/Source/ScriptAutomationSystemComponent.h
  Gems/ScriptAutomation/Code/Tests/ScriptAutomationApplicationFixture.cpp
  Gems/ScriptAutomation/Code/Tests/ScriptAutomationApplicationFixture.h
  Gems/ScriptAutomation/Code/Tests/ScriptAutomationTests.cpp
  Gems/ScriptAutomation/Code/Tests/Scripts/idle_five_frames_test.lua
  Gems/ScriptAutomation/Code/Tests/Scripts/idle_one_second_test.lua
  Gems/ScriptAutomation/Code/Tests/Scripts/print_test.lua
  Gems/ScriptAutomation/Code/scriptautomation_files.cmake
  Gems/ScriptAutomation/Code/scriptautomation_header_files.cmake
  Gems/ScriptAutomation/Code/scriptautomation_shared_files.cmake
  Gems/ScriptAutomation/Code/scriptautomation_tests_files.cmake
  Gems/ScriptAutomation/gem.json
  Gems/ScriptAutomation/preview.png
  engine.json
Labels: sig/core

#9317 Action Manager | Registration API Setup
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorAction.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorAction.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorActionContext.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/EditorActionContext.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/ActionManagerSystemComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/ActionManager/ActionManagerFixture.cpp
  Code/Framework/AzToolsFramework/Tests/ActionManager/ActionManagerFixture.h
  Code/Framework/AzToolsFramework/Tests/ActionManager/ActionManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: feature/editor, sig/content

#9403 Updated CODEOWNERS for sig-graphics-audio
  .github/CODEOWNERS
Labels: sig/graphics-audio

#9408 Action Manager | Introduce API calls to trigger actions by their identifier
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h
  Code/Framework/AzToolsFramework/Tests/ActionManager/ActionManagerTests.cpp
Labels: feature/editor, sig/content

#8997 Atom/amzn tommy/atom 17289 sponza deadlock
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Common/AssetUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialSourceData.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialUtils.cpp
Labels: sig/graphics-audio

#9414 Moves icons in a sub-menu and adjusts layout (Audio Controls Editor)
  Gems/AudioSystem/Code/Source/Editor/ATLControlsPanel.cpp
Labels: feature/audio, kind/bug

#9443 disable flaky test while under investigation #9422
  AutomatedTesting/Gem/PythonTests/Physics/TestSuite_Main.py
Labels: sig/simulation

#9444 Animation Editor: Removed attachment window
  Gems/EMotionFX/Assets/Editor/Layouts/AnimGraph.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Animation.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Character.layout
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/ActorInstanceCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AttachmentCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AttachmentCommands.h
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/CommandManager.cpp
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/commandsystem_files.cmake
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/PluginManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/Workspace.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentNodesWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentNodesWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentsHierarchyWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentsHierarchyWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentsPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentsPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentsWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/Attachments/AttachmentsWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/standardplugins_files.cmake
Labels: feature/animation, sig/simulation

#9388 {lyn12122} fixes for empty scene manifest loading
  Code/Tools/SceneAPI/SceneCore/Events/AssetImportRequest.cpp
  Code/Tools/SceneAPI/SceneCore/Tests/Events/AssetImporterRequestTests.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
  Gems/SceneProcessing/Code/Tests/SceneBuilder/SceneBuilderTests.cpp
Labels: sig/content

#9396 Fix render target override issue in UiCanvasOnMesh component
  Gems/LyShine/Code/Source/UiCanvasComponent.cpp
  Gems/LyShine/Code/Source/World/UiCanvasOnMeshComponent.cpp
Labels: sig/content

#9426 Motion Matching: Using query vector for cost calculation
  Gems/MotionMatching/Assets/MotionMatching.emfxworkspace
  Gems/MotionMatching/Code/Source/Feature.cpp
  Gems/MotionMatching/Code/Source/Feature.h
  Gems/MotionMatching/Code/Source/FeaturePosition.cpp
  Gems/MotionMatching/Code/Source/FeaturePosition.h
  Gems/MotionMatching/Code/Source/FeatureTrajectory.cpp
  Gems/MotionMatching/Code/Source/FeatureTrajectory.h
  Gems/MotionMatching/Code/Source/FeatureVelocity.cpp
  Gems/MotionMatching/Code/Source/FeatureVelocity.h
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.cpp
  Gems/MotionMatching/Code/Source/MotionMatchingInstance.h
  Gems/MotionMatching/Code/Source/QueryVector.cpp
  Gems/MotionMatching/Code/Source/QueryVector.h
  Gems/MotionMatching/Code/Source/TrajectoryQuery.cpp
  Gems/MotionMatching/Code/motionmatching_files.cmake
Labels: feature/animation, sig/simulation

#9288 Fix for SC FileMenu_Default_NewAndOpen test script.
  AutomatedTesting/Gem/PythonTests/scripting/FileMenu_Default_NewAndOpen.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
Labels: feature/scripting, sig/content

#9434 Add translation manipulators for ragdoll colliders
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/PhysicsSetupColliderTranslationManipulators.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/PhysicsSetupColliderTranslationManipulators.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/PhysicsSetupManipulators.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/PhysicsSetupViewportUiCluster.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/PhysicsSetupViewportUiCluster.h
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/Ragdoll/RagdollNodeWidget.h
  Gems/EMotionFX/Code/Source/Editor/SkeletonModelJointWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/SkeletonModelJointWidget.h
  Gems/EMotionFX/Code/Source/Integration/System/CVars.h
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
  Gems/EMotionFX/Code/emotionfx_editor_files.cmake
Labels: sig/ui-ux, sig/simulation

#9455 Animation Editor: Removing the game controller window
  Gems/EMotionFX/Assets/Editor/Layouts/AnimGraph.layout
  Gems/EMotionFX/Code/EMotionFX/Source/Allocators.h
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraph.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraph.h
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphGameControllerSettings.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphGameControllerSettings.h
  Gems/EMotionFX/Code/EMotionFX/Source/EMotionFXManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/ChunkProcessors.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MemoryCategories.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPluginCallbacks.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/GameController.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/GameController.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/GameControllerWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/GameControllerWindow.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/ParameterWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/standardplugins_files.cmake
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
  Gems/EMotionFX/Code/Editor/Platform/Windows/EMotionFX_Traits_Windows.h
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
  Gems/EMotionFX/Code/Tests/EMotionFXBuilderFixture.cpp
  Gems/EMotionFX/Code/Tests/LeaderFollowerVersionTests.cpp
  Gems/EMotionFX/Code/Tests/Mocks/AnimGraph.h
Labels: feature/animation, sig/simulation

#9383 Add EditorModeFeedback support for Whitebox and Cloth components.
  Gems/AtomLyIntegration/CommonFeatures/Code/CMakeLists.txt
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Mesh/MeshHandleStateBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/CMakeLists.txt
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Include/EditorModeFeedback/EditorModeFeedbackInterface.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackSystemComponent.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/EditorModeFeedbackSystemComponent.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/FocusedEntity/FocusedMeshEntity.cpp
  Gems/AtomLyIntegration/EditorModeFeedback/Code/Source/FocusedEntity/FocusedMeshEntity.h
  Gems/AtomLyIntegration/EditorModeFeedback/Code/editormodefeedback_editor_files.cmake
  Gems/WhiteBox/Code/Include/WhiteBox/WhiteBoxBus.h
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.cpp
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.h
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxMeshAtomData.cpp
  Gems/WhiteBox/Code/Source/Rendering/WhiteBoxNullRenderMesh.cpp
  Gems/WhiteBox/Code/Source/Rendering/WhiteBoxNullRenderMesh.h
  Gems/WhiteBox/Code/Source/Rendering/WhiteBoxRenderMeshInterface.h
  Gems/WhiteBox/Code/Source/WhiteBoxComponent.cpp
  Gems/WhiteBox/Code/Source/WhiteBoxSystemComponent.cpp
  Gems/WhiteBox/Code/Source/WhiteBoxSystemComponent.h
  Gems/WhiteBox/Code/Tests/WhiteBoxComponentTest.cpp
Labels: sig/content, sig/graphics-audio

#9413 Atom Tools: update base application handling for automated testing return values and fix problems with idle wait frames
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/material_editor_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomMaterialEditor_BasicTests.py
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/Thumbnail.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/Thumbnail.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerNullComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerNullComponent.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Application/AtomToolsApplication.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystem.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Document/AtomToolsDocumentSystemRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialCanvasDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/main.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocumentRequestBus.h
  Gems/Atom/Tools/MaterialEditor/Code/Source/main.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/main.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/EditorCommonFeaturesSystemComponent.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9247 Updating all relevant Prefab tests with Undo/Redo verification
  AutomatedTesting/Gem/PythonTests/Prefab/tests/PrefabTestUtils.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_UnderAnEntity.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_UnderAnotherPrefab.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_UnderChildEntityOfAnotherPrefab.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_WithNestedEntities.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_WithNestedEntitiesAndNestedPrefabs.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/create_prefab/CreatePrefab_WithSingleEntity.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/delete_entity/DeleteEntity_UnderAnotherPrefab.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/delete_entity/DeleteEntity_UnderLevelPrefab.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/delete_prefab/DeletePrefab_ContainingASingleEntity.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/detach_prefab/DetachPrefab_UnderAnotherPrefab.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/duplicate_prefab/DuplicatePrefab_ContainingASingleEntity.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/instantiate_prefab/InstantiatePrefab_ContainingASingleEntity.py
  AutomatedTesting/Gem/PythonTests/Prefab/tests/instantiate_prefab/InstantiatePrefab_FromCreatedPrefabWithSingleEntity.py
Labels: sig/content, sig/testing

#8756 Updated and extended profiling information from AZ::IO::Streamer.
  Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
  Code/Framework/AzCore/AzCore/Asset/AssetDataStream.cpp
  Code/Framework/AzCore/AzCore/Asset/AssetDataStream.h
  Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
  Code/Framework/AzCore/AzCore/Asset/AssetManager.h
  Code/Framework/AzCore/AzCore/IO/IStreamer.h
  Code/Framework/AzCore/AzCore/IO/IStreamerProfiler.h
  Code/Framework/AzCore/AzCore/IO/IStreamerTypes.h
  Code/Framework/AzCore/AzCore/IO/Streamer/BlockCache.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/BlockCache.h
  Code/Framework/AzCore/AzCore/IO/Streamer/DedicatedCache.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/DedicatedCache.h
  Code/Framework/AzCore/AzCore/IO/Streamer/FileRequest.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/FileRequest.h
  Code/Framework/AzCore/AzCore/IO/Streamer/FullFileDecompressor.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/FullFileDecompressor.h
  Code/Framework/AzCore/AzCore/IO/Streamer/ReadSplitter.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/ReadSplitter.h
  Code/Framework/AzCore/AzCore/IO/Streamer/Scheduler.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Scheduler.h
  Code/Framework/AzCore/AzCore/IO/Streamer/Statistics.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Statistics.h
  Code/Framework/AzCore/AzCore/IO/Streamer/StorageDrive.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.h
  Code/Framework/AzCore/AzCore/IO/Streamer/StreamerComponent.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/StreamerComponent.h
  Code/Framework/AzCore/AzCore/IO/Streamer/StreamerContext.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/StreamerContext.h
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Platform/Windows/AzCore/IO/Streamer/StorageDrive_Windows.cpp
  Code/Framework/AzCore/Tests/Asset/AssetManagerStreamingTests.cpp
  Code/Framework/AzCore/Tests/Streamer/IStreamerMock.h
  Code/Framework/AzCore/Tests/TestCatalog.cpp
  Code/Framework/AzCore/Tests/TestCatalog.h
  Code/Framework/AzFramework/AzFramework/IO/RemoteStorageDrive.cpp
Labels: sig/core

#9378 Material Component: Support for editing multiple selected entities
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentRequestBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialSystemComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Labels: sig/content, sig/graphics-audio, feature/graphics/tools, feature/graphics/materials

#9452 Change the way terrain geometry is rendered to reduce draws
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFilter.cpp
  Gems/Atom/RPI/Code/Tests/Pass/PassTests.cpp
  Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Assets/Shaders/Terrain/Terrain_DepthPass.azsl
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldRendererComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
Labels: feature/graphics, sig/graphics-audio, feature/terrain, feature/graphics/mesh

#9437 Heightfield material operations optimization
  Code/Framework/AzFramework/AzFramework/Physics/HeightfieldProviderBus.h
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.cpp
  Gems/PhysX/Code/Source/EditorHeightfieldColliderComponent.h
  Gems/PhysX/Code/Source/Shape.cpp
  Gems/PhysX/Code/Source/Shape.h
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainPhysicsColliderComponent.h
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.cpp
  Gems/Terrain/Code/Source/EditorComponents/EditorTerrainPhysicsColliderComponent.h
Labels: sig/graphics-audio, sig/simulation

#9329 bugfix(Whitebox): add small margin to prevent z-fighting when working with polygon manipulator
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxManipulatorViews.cpp
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxManipulatorViews.h
  Gems/WhiteBox/Code/Source/Viewport/WhiteBoxPolygonTranslationModifier.cpp
Labels: feature/whitebox, sig/content

#9438 Expose CTest tests in project centric builds
  cmake/Findo3de.cmake
Labels: sig/core, sig/testing

#9504 Add tuple support to python bindings.
  Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
  Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
  Code/Framework/AzCore/AzCore/Serialization/SerializationUtils.cpp
  Code/Framework/AzCore/AzCore/Serialization/Utils.h
  Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.h
  Gems/EditorPythonBindings/Code/Source/PythonMarshalTuple.cpp
  Gems/EditorPythonBindings/Code/Source/PythonMarshalTuple.h
  Gems/EditorPythonBindings/Code/Tests/PythonPairTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonTupleTests.cpp
  Gems/EditorPythonBindings/Code/editorpythonbindings_common_files.cmake
  Gems/EditorPythonBindings/Code/editorpythonbindings_tests_files.cmake
Labels: sig/content, sig/core

#8431 Optimize Actor::ConstructMeshes
  Gems/EMotionFX/Code/EMotionFX/Source/Actor.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/DualQuatSkinDeformer.h
  Gems/EMotionFX/Code/EMotionFX/Source/Mesh.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Mesh.h
  Gems/EMotionFX/Code/EMotionFX/Source/Mesh.inl
  Gems/EMotionFX/Code/EMotionFX/Source/MeshDeformer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MeshDeformer.h
  Gems/EMotionFX/Code/EMotionFX/Source/MeshDeformerStack.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MorphMeshDeformer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/MorphMeshDeformer.h
  Gems/EMotionFX/Code/EMotionFX/Source/SoftSkinDeformer.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/SoftSkinDeformer.h
Labels: sig/core

#8472 Add additional validation to RPI::Buffer::UpdateData
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshRenderProxy.cpp
  Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp
  Gems/Atom/Utils/Code/Source/Utils.cpp
Labels: sig/graphics-audio

#9477 Fixed link to Asset Processor docs from Import Assets dialog
  Code/Editor/AssetImporter/UI/SelectDestinationDialog.cpp
  Code/Editor/AssetImporter/UI/SelectDestinationDialog.ui
Labels: sig/content

#9463 Fix LyTestTools cannot run more than 10 editor batched tests
  Code/Editor/CryEdit.cpp
  Tools/LyTestTools/ly_test_tools/o3de/editor_test.py
  Tools/LyTestTools/tests/unit/test_o3de_editor_test.py
Labels: sig/content, sig/testing

#9341 Fixing connecting to EBus
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/DespawnNodeable.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Spawning/SpawnNodeable.h
Labels: sig/content, sig/core

#9476 [Terrain] Clipmap smart update initial version
  Gems/Terrain/Assets/Passes/TerrainDetailClipmapGenerationPass.pass
  Gems/Terrain/Assets/Passes/TerrainMacroClipmapGenerationPass.pass
  Gems/Terrain/Assets/Shaders/Terrain/ClipmapComputeHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroClipmapGenerationPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainSrg.azsli
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/ClipmapBounds.h
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/Passes/TerrainClipmapComputePass.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainClipmapManager.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Tests/ClipmapBoundsTests.cpp
Labels: sig/content, sig/graphics-audio, feature/terrain

#9441 chore: update EncryptionCommon to work with openssl 3.0
  Code/Framework/AzNetworking/AzNetworking/Utilities/EncryptionCommon.cpp
Labels: sig/network

#9467 additional debugging features for Asset Processor
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests_2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_reprocessFileList_processesInOrder/preview_1.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_reprocessFileList_processesInOrder/preview_2.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_reprocessFileList_processesInOrder/preview_3.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_reprocessFileList_processesInOrder/preview_4.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_reprocessFileList_processesInOrder/preview_5.png
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BuilderManager.h
Labels: sig/content

#9489 Adds seperated level load test
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_PbrMaterialChart.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_ShadowTest.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_Sponza.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_hermanubis.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_hermanubis_high.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/levelLoad_Atom_macbeth_shaderballs.py
Labels: sig/graphics-audio

#9490 Diffuse Global Illumination level component P1 test expansion
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponentsLevel_DiffuseGlobalIlluminationAdded.py
Labels: sig/graphics-audio

#9527 Adding P1 automation support for Look Modification component
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LookModificationAdded.py
Labels: sig/graphics-audio

#9500 Action Manager | Python API - Action Registration
  Gems/EditorPythonBindings/Code/Source/ActionManager/ActionManagerBus.h
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.h
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonEditorAction.cpp
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonEditorAction.h
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.h
  Gems/EditorPythonBindings/Code/editorpythonbindings_common_files.cmake
Labels: sig/content

#9530 ReflectionProbe visualization sphere is incorrectly added to the raytracing scene
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp
Labels: sig/graphics-audio

#9464 {lyn12569} added an auto test ProcessSceneWithMetadata
  AutomatedTesting/Assets/ap_test_assets/default_mat.fbx
  AutomatedTesting/Gem/PythonTests/PythonAssetBuilder/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/UserDefinedProperties/Blender_With_Attributes.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/UserDefinedProperties/Max_With_Attributes.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/UserDefinedProperties/Maya_With_Attributes.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/pythonassetbuildertests.py
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
Labels: sig/content

#9470 Move Network Interfaces to SystemTick/Fix SystemTick failing to run in background
  AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/TestSuite_Main.py
  Code/Editor/CryEdit.cpp
  Code/Editor/MainWindow.cpp
  Code/Editor/Settings.cpp
  Code/Framework/AzFramework/AzFramework/TargetManagement/TargetManagementComponent.cpp
  Code/Framework/AzNetworking/AzNetworking/Framework/INetworkInterface.h
  Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.cpp
  Code/Framework/AzNetworking/AzNetworking/Framework/NetworkingSystemComponent.h
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpNetworkInterface.cpp
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpNetworkInterface.h
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.cpp
  Code/Framework/AzNetworking/AzNetworking/UdpTransport/UdpNetworkInterface.h
  Code/Framework/AzNetworking/Tests/TcpTransport/TcpTransportTests.cpp
  Code/Framework/AzNetworking/Tests/UdpTransport/UdpTransportTests.cpp
  Code/Tools/LuaIDE/Source/StandaloneToolsApplication.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
Labels: sig/core, sig/network

#9327 chore: deprecate SetParamValue/GetParamValue/Serialize Set/Pos/Rotation/Scale for IAnimNode
  Code/Legacy/CryCommon/IMovieSystem.h
Labels: sig/content, sig/core

#9374 Fix for NodePalette_HappyPath_CanSelectNode
  AutomatedTesting/Gem/PythonTests/scripting/NodePalette_HappyPath_CanSelectNode.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
Labels: feature/scripting, sig/content

#9554 Action Manager | Refactor API to future-proof property assignment on construction.
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Action/ActionManagerInterface.h
  Code/Framework/AzToolsFramework/Tests/ActionManager/ActionManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/ActionManager/MenuManagerTests.cpp
  Gems/EditorPythonBindings/Code/Source/ActionManager/ActionManagerBus.h
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.h
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
Labels: sig/content

#9557 Changed fallback irradiance color to 1.0f
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
Labels: sig/graphics-audio

#9569 Fixed UIElement ordering issue
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
  Code/Framework/AzQtComponents/AzQtComponents/Gallery/ReflectedPropertyEditorPage.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/InstanceDataHierarchy.cpp
  Code/Framework/AzToolsFramework/Tests/InstanceDataHierarchy.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.h
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorActorComponent.h
  Gems/PhysX/Code/Editor/DebugDraw.cpp
  Gems/PhysX/Code/Editor/DebugDraw.h
Labels: sig/content

#9551 Grid component: updating comments and formatting
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Grid/GridComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Grid/GridComponentController.h
Labels: sig/content, sig/graphics-audio

#9487 Fix for test script NewScriptEventButton_HappyPath_ContainsSCCategory
  AutomatedTesting/Gem/PythonTests/scripting/NewScriptEventButton_HappyPath_ContainsSCCategory.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
Labels: feature/scripting, sig/content

#9486 Change mode of "Detaching debug symbols" messages to avoid spamming stdout during build
  cmake/Platform/Linux/ProcessDebugSymbols.cmake
Labels: sig/build

#8971 AWSClientAuth: Remove confusing long spam when cognito is not configured
  Gems/AWSClientAuth/Code/Source/AWSClientAuthBus.h
  Gems/AWSClientAuth/Code/Source/AWSClientAuthSystemComponent.cpp
  Gems/AWSClientAuth/Code/Source/AWSClientAuthSystemComponent.h
  Gems/AWSClientAuth/Code/Source/UserManagement/AWSCognitoUserManagementController.h
  Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h
  Gems/AWSClientAuth/Code/Tests/AWSClientAuthSystemComponentTest.cpp
Labels: sig/network

#9279 Fix memory leaks
  Code/Framework/AzCore/AzCore/RTTI/BehaviorContext.h
  Code/Framework/AzCore/AzCore/std/createdestroy.h
  Code/Framework/AzCore/Tests/Script.cpp
  Code/Tools/SceneAPI/SceneBuilder/ImportContexts/AssImpImportContexts.cpp
  Code/Tools/SceneAPI/SceneBuilder/ImportContexts/AssImpImportContexts.h
  Code/Tools/SceneAPI/SceneBuilder/ImportContexts/ImportContexts.cpp
  Code/Tools/SceneAPI/SceneBuilder/ImportContexts/ImportContexts.h
  Gems/Blast/Code/Source/Components/BlastFamilyComponent.cpp
  Gems/PhysX/Code/Source/Module.cpp
  Gems/PhysX/Code/Source/System/PhysXSystem.cpp
  Gems/PhysX/Code/Source/System/PhysXSystem.h
  Gems/PhysX/Code/Tests/PhysXEditorTest.cpp
  Gems/PhysX/Code/Tests/PhysXTestEnvironment.cpp
  Gems/SceneProcessing/Code/Source/Config/Components/SceneProcessingConfigSystemComponent.cpp
  cmake/Platform/Common/Clang/Configurations_clang.cmake
Labels: sig/content, sig/core

#9495 Lyn 12717: Re-enable Disabled Asset Pipeline Tests into the Sandbox
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/CMakeLists.txt
Labels: sig/content

#9548 Update in-memory spawnable to support networking editor game mode
  Code/Framework/AzFramework/AzFramework/Spawnable/InMemorySpawnableAssetContainer.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/InMemorySpawnableAssetContainer.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetBus.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetHandler.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetHandler.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetUtils.cpp
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableAssetUtils.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicRequestHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/InMemorySpawnableAssetContainer.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabInMemorySpawnableConverter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Spawnable/PrefabInMemorySpawnableConverter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
Labels: sig/content

#9510 Add render target support for UiImageComponent
  Gems/LyShine/Code/Include/LyShine/Bus/UiImageBus.h
  Gems/LyShine/Code/Include/LyShine/ILyShine.h
  Gems/LyShine/Code/Source/LyShine.cpp
  Gems/LyShine/Code/Source/LyShine.h
  Gems/LyShine/Code/Source/Sprite.cpp
  Gems/LyShine/Code/Source/Sprite.h
  Gems/LyShine/Code/Source/UiImageComponent.cpp
  Gems/LyShine/Code/Source/UiImageComponent.h
Labels: sig/content

#9553 Some overload node name fix and detect deprecate node when using upgrade tool
  Code/Framework/AzCore/AzCore/Math/MathReflection.cpp
  Code/Framework/AzCore/AzCore/Math/Vector2.cpp
  Code/Framework/AzCore/AzCore/Math/Vector3.cpp
  Code/Framework/AzCore/AzCore/Math/Vector4.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/Tools/UpgradeTool/Controller.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.h
Labels: sig/content

#9599 Add new notification for Root Prefab Instance's First Load
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutorInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicNotificationBus.h
Labels: sig/content

#9635 Added additional logging for tests with unknown results.
  Tools/LyTestTools/ly_test_tools/_internal/pytest_plugin/terminal_report.py
Labels: sig/testing

#9656 Animation Editor: Centralized save dirty file callbacks and made them persistent
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/FileManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/FileManager.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MainWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/AnimGraph/AnimGraphPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetManagementWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionSetsWindow/MotionSetsWindowPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionWindow/MotionWindowPlugin.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/ActorsWindow.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/SceneManagerPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/SceneManagerPlugin.h
  Gems/EMotionFX/Code/Source/Editor/SaveDirtyFilesCallbacks.cpp
  Gems/EMotionFX/Code/Source/Editor/SaveDirtyFilesCallbacks.h
  Gems/EMotionFX/Code/emotionfx_editor_files.cmake
Labels: feature/animation, sig/simulation

#9670 Add prefab.editor.setreg for enabling in-memory spawnables related automated tests on editor console
  Registry/prefab.editor.setreg
Labels: sig/content

#9363 Read resource mapping schema from assets on Android
  Gems/AWSCore/Assets/resource_mapping_schema.json
  Gems/AWSCore/Code/CMakeLists.txt
  Gems/AWSCore/Code/Platform/Android/GetJsonSchemaPath_Android.cpp
  Gems/AWSCore/Code/Platform/Android/platform_android_files.cmake
  Gems/AWSCore/Code/Platform/Common/GetJsonSchemaPath_Common.cpp
  Gems/AWSCore/Code/Platform/Linux/platform_linux_files.cmake
  Gems/AWSCore/Code/Platform/Mac/platform_mac_files.cmake
  Gems/AWSCore/Code/Platform/Windows/platform_windows_files.cmake
  Gems/AWSCore/Code/Platform/iOS/platform_ios_files.cmake
  Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingConstants.h
  Gems/AWSCore/Code/Source/ResourceMapping/AWSResourceMappingManager.cpp
  Gems/AWSCore/Code/Tools/ResourceMappingTool/resource_mapping_tool.py
  Gems/AWSCore/Code/Tools/ResourceMappingTool/tests/unit/utils/test_json_utils.py
Labels: sig/network

#9675 P1 Light Component Automation Adjustments
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_LightAdded.py
Labels: sig/graphics-audio

#9600 Adding new test for verifying bilinear gradient image sampling
  AutomatedTesting/Gem/PythonTests/largeworlds/gradient_signal/EditorScripts/ImageGradient_BilinearFiltering.py
  AutomatedTesting/Gem/PythonTests/largeworlds/gradient_signal/TestSuite_Periodic.py
Labels: sig/content, sig/testing

#9677 Add DPE support for enums, entity IDs, and more
  Code/Framework/AzCore/AzCore/DOM/DomUtils.cpp
  Code/Framework/AzCore/AzCore/DOM/DomUtils.h
  Code/Framework/AzCore/AzCore/JSON/rapidjson.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/CvarAdapter.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentSchema.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/PropertyEditorNodes.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzFramework/Tests/DocumentPropertyEditor/CvarAdapterTests.cpp
  Code/Framework/AzQtComponents/AzQtComponents/DPEDebugViewStandalone/main.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystem.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystem.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystemInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyHandlerWidget.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
Labels: sig/content, sig/core, sig/ui-ux

#9605 [Terrain] Meshes now include height in the vertex instead of querying a heightfield
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/FastNoise/Code/Source/FastNoiseGradientComponent.cpp
  Gems/Terrain/Assets/Shaders/Terrain/SceneSrg.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainCommon.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainMacroHelpers.azsli
  Gems/Terrain/Assets/Shaders/Terrain/TerrainPBR_ForwardPass.azsl
  Gems/Terrain/Assets/Shaders/Terrain/Terrain_DepthPass.azsl
  Gems/Terrain/Code/Source/Components/TerrainWorldComponent.cpp
  Gems/Terrain/Code/Source/Components/TerrainWorldComponent.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainFeatureProcessor.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
  Gems/Terrain/Code/Source/TerrainSystem/TerrainSystem.cpp
Labels: sig/content, sig/graphics-audio

#9715 Small changes to fix Android build and deploy on Mac
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Mac/Vulkan_Traits_Mac.h
  cmake/Tools/Platform/Android/android_deployment.py
Labels: sig/platform

#9710 Added missing macro AZ_RELEASE_BUILD on release configuration.
  Code/Framework/AzCore/AzCore/PlatformDef.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
  Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
  cmake/Platform/Common/Configurations_common.cmake
Labels: sig/build, sig/network

#9698 Fix for crashes on Linux when actions related to deleting nodes are invoked in Script Canvas
  Code/Framework/AzCore/AzCore/Component/Component.cpp
  Code/Framework/AzCore/AzCore/Component/Component.h
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/ScriptCanvasBus.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.h
Labels: sig/content, sig/core

#9678 "Freeze transform before skinning" root cause bug fix
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Actor/ActorBuilder.cpp
  Gems/EMotionFX/Code/Tests/ActorBuilderTests.cpp
Labels: feature/animation, sig/simulation

#9720 Restored broken TrackView KeyUI controls
  Code/Editor/TrackView/2DBezierKeyUIControls.cpp
  Code/Editor/TrackView/AssetBlendKeyUIControls.cpp
  Code/Editor/TrackView/CaptureKeyUIControls.cpp
  Code/Editor/TrackView/CommentKeyUIControls.cpp
  Code/Editor/TrackView/ConsoleKeyUIControls.cpp
  Code/Editor/TrackView/EventKeyUIControls.cpp
  Code/Editor/TrackView/GotoKeyUIControls.cpp
  Code/Editor/TrackView/KeyUIControls.h
  Code/Editor/TrackView/ScreenFaderKeyUIControls.cpp
  Code/Editor/TrackView/SelectKeyUIControls.cpp
  Code/Editor/TrackView/SequenceKeyUIControls.cpp
  Code/Editor/TrackView/SoundKeyUIControls.cpp
  Code/Editor/TrackView/TimeRangeKeyUIControls.cpp
  Code/Editor/TrackView/TrackEventKeyUIControls.cpp
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#9647 bugfix(Whitebox): better handle updating material for whitebox mesh (GHI-9442)
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.cpp
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.h
Labels: sig/graphics-audio

#9699 chore: update calling Set/Pos/Rotation/Scale for CTrackViewAnimNode
  Code/Editor/TrackView/TrackViewAnimNode.cpp
Labels: sig/content

#9440 chore: simplify Sphere in AZCore Math
  Code/Framework/AzCore/AzCore/Math/Sphere.h
  Code/Framework/AzCore/AzCore/Math/Sphere.inl
  Code/Framework/AzCore/Tests/Math/SphereTests.cpp
Labels: sig/core

#9556 Preparation For New Shader Details Tool
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/MeshDrawPacket.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Shader/ShaderVariantAsyncLoader.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderOptionGroup.h
  Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/Shader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderVariantAsyncLoader.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderOptionGroup.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Shader/ShaderVariantKey.cpp
Labels: sig/graphics-audio

#9723 Fix TargetJoinThread attempting to Join on itself
  Code/Framework/AzFramework/AzFramework/TargetManagement/TargetManagementComponent.cpp
Labels: sig/core

#9528 Fix for test script VariableManager_Default_CreateDeleteVars
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/VariableManager_Default_CreateDeleteVars.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
Labels: feature/scripting, sig/content

#9667 {lyn12587} Asset cache server feature configuration
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCBuilder.h
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCBuilderTest.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCBuilderTest.h
  Code/Tools/AssetProcessor/native/unittests/AssetCacheServerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/MockApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/AssetServerHandler.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: sig/content

#9617 Lyn 10265 - Re-enable Passing Asset Pipeline Sandbox Tests
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_dependency_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_dependency_tests2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
Labels: sig/content

#9636 [Wwise] Fixes print formatting errors on Android/Linux
  Gems/AudioEngineWwise/Code/Source/Engine/AudioSystemImpl_wwise.cpp
  Gems/AudioEngineWwise/Code/Source/Engine/FileIOHandler_wwise.cpp
Labels: feature/audio, kind/bug, sig/core, sig/platform, sig/graphics-audio

#9697 Add undo/redo functionality to folder renames in Audio Controls Editor
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorUndo.cpp
  Gems/AudioSystem/Code/Source/Editor/AudioControlsEditorUndo.h
  Gems/AudioSystem/Code/Source/Editor/QAudioControlTreeWidget.cpp
  Gems/AudioSystem/Code/Source/Editor/QAudioControlTreeWidget.h
Labels: feature/audio, kind/bug, sig/core, sig/graphics-audio

#9773 Atom Tools: Command line options for log file and batch mode for automated tests
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
Labels: sig/content, sig/graphics-audio, feature/graphics/tools

#9784 Jjjoness/asset browser browsing assets fast in tree view results in freeze of editor 9739
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Thumbnails/ThumbnailerComponent.h
Labels: sig/content

#9492 Adding ScriptCanvas upgrade script
  Gems/ScriptCanvas/SourceModificationScripts/UpdateSpawnableNodes.py
Labels: sig/content

#9806 Remote Project Dialog UI
  Code/Tools/ProjectManager/Resources/Cloud.svg
  Code/Tools/ProjectManager/Resources/Cloud_Hover.svg
  Code/Tools/ProjectManager/Resources/ProjectManager.qrc
  Code/Tools/ProjectManager/Resources/ProjectManager.qss
  Code/Tools/ProjectManager/Resources/Select_Folder_Disabled.svg
  Code/Tools/ProjectManager/Source/AddRemoteProjectDialog.cpp
  Code/Tools/ProjectManager/Source/AddRemoteProjectDialog.h
  Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.cpp
  Code/Tools/ProjectManager/Source/NewProjectSettingsScreen.h
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/ProjectsScreen.h
  Code/Tools/ProjectManager/Source/TextOverflowWidget.cpp
  Code/Tools/ProjectManager/Source/TextOverflowWidget.h
  Code/Tools/ProjectManager/project_manager_files.cmake
  Code/Tools/ProjectManager/project_manager_tests_files.cmake
  Code/Tools/ProjectManager/tests/TextOverflowTests.cpp
Labels: feature/project-manager
