Repository o3de/o3de, pull requests merged in 2023-06, with the labels that each got.

#16008 Add missing getters to PhysX/ArticulationJointBus.
  Gems/PhysX/Code/Include/PhysX/ArticulationJointBus.h
  Gems/PhysX/Code/Source/ArticulationLinkComponent.cpp
  Gems/PhysX/Code/Source/ArticulationLinkComponent.h
Labels: feature/robotics

#16227 Fix for RayTracing MaterialInfo Vulkan validation errors
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/ReflectionProbeData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialSrg.azsli
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_dx12_0.azshadervariant
Labels: sig/graphics-audio

#15890 HttpRequestorGem: Add Timing Data
  Gems/AWSClientAuth/Code/Tests/AWSClientAuthGemMock.h
  Gems/HttpRequestor/Code/Include/HttpRequestor/HttpRequestorBus.h
  Gems/HttpRequestor/Code/Source/HttpRequestManager.cpp
  Gems/HttpRequestor/Code/Source/HttpRequestManager.h
  Gems/HttpRequestor/Code/Source/HttpRequestorSystemComponent.cpp
  Gems/HttpRequestor/Code/Source/HttpRequestorSystemComponent.h
Labels: feature/cloud-service, sig/network

#12009 [Atom] Add indirect raytracing command
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/IndirectRendering.azsli
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/IndirectBufferLayout.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/IndirectBufferLayout.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/IndirectBufferSignature.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Reflect/Conversion.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/IndirectBufferSignature.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationRayTracingPass.cpp
Labels: sig/graphics-audio
