Repository o3de/o3de, pull requests merged in 2023-03, with the labels that each got.

#14781 Add property icon and label handler for override in DPE Entity Inspector
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/OverridePropertyHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/OverridePropertyHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabAdapterInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabPropertyEditorNodes.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabInspectorOverrideTests.cpp
Labels: sig/content, feature/prefabs

#14814 Rename EnableOverridesUx to avoid confusion
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_DPEOverrides.py
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Main.py
  AutomatedTesting/Gem/PythonTests/Prefab/TestSuite_Periodic.py
  AutomatedTesting/Registry/editorpreferences.setreg
  Code/Framework/AzToolsFramework/AzToolsFramework/ContainerEntity/ContainerEntitySystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabEditorPreferences.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Labels: sig/content, feature/prefabs

#14833 Material Canvas: Updated lua scripts to check for missing options before reading them
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/HandleCastShadows.lua
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleCastShadows.lua
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleOpacityDoubleSided.lua
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleOpacityMode.lua
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/HandleShaderEnable.lua
Labels: sig/content, sig/graphics-audio

#14912 Asset Processor - AP Gui settings take command line into account
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
Labels: feature/asset-pipeline

#14932 Corrected typename for MetalResource typename for Metal RHI
  Gems/Atom/RHI/Metal/Code/Source/RHI/Memory.h
Labels: platform/macos

#14890 Fixed hit volume creation
  Gems/EMotionFX/Code/Source/Integration/Components/AnimGraphComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkHitVolumesComponent.h
  Gems/Multiplayer/Code/Source/Components/NetworkHitVolumesComponent.cpp
Labels: sig/network

#14937 Move StopEntity() into the NetBindComponent Deactivate()
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
Labels: sig/network

#14886 Graph model behavior context reflection + related updates to landscape canvas and material canvas
  AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialCanvas_Atom_BasicTests.py
  Code/Framework/AzCore/AzCore/RTTI/AzStdOnDemandReflection.inl
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/DynamicNode/DynamicNode.cpp
  Gems/Atom/Tools/MaterialCanvas/Scripts/TestGraphAPIs.py
  Gems/GraphModel/Code/Include/GraphModel/GraphModelBus.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Common.h
  Gems/GraphModel/Code/Include/GraphModel/Model/DataType.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
  Gems/GraphModel/Code/Include/GraphModel/Model/GraphContext.h
  Gems/GraphModel/Code/Include/GraphModel/Model/GraphElement.h
  Gems/GraphModel/Code/Include/GraphModel/Model/IGraphContext.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Node.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
  Gems/GraphModel/Code/Source/GraphModelSystemComponent.cpp
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
  Gems/GraphModel/Code/Source/Model/Connection.cpp
  Gems/GraphModel/Code/Source/Model/DataType.cpp
  Gems/GraphModel/Code/Source/Model/Graph.cpp
  Gems/GraphModel/Code/Source/Model/GraphContext.cpp
  Gems/GraphModel/Code/Source/Model/GraphElement.cpp
  Gems/GraphModel/Code/Source/Model/Module/InputOutputNodes.cpp
  Gems/GraphModel/Code/Source/Model/Module/ModuleNode.cpp
  Gems/GraphModel/Code/Source/Model/Node.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
  Gems/GraphModel/Code/Tests/GraphModelIntegrationTest.cpp
  Gems/GraphModel/Code/Tests/TestEnvironment.cpp
  Gems/GraphModel/Code/Tests/TestEnvironment.h
  Gems/LandscapeCanvas/Code/Source/Editor/MainWindow.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/AltitudeFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/DistributionFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaFilters/ShapeIntersectionFilterNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/PositionModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/RotationModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/ScaleModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaModifiers/SlopeAlignmentModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/AreaSelectors/AssetWeightSelectorNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/AreaBlenderNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Areas/BaseAreaNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/BaseNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/BaseGradientModifierNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/GradientModifiers/GradientMixerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/AltitudeGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/BaseGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/GradientBakerNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ImageGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Gradients/ShapeAreaFalloffGradientNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/BaseShapeNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Shapes/ReferenceShapeNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainHeightGradientListNode.cpp
  Gems/LandscapeCanvas/Code/Source/Editor/Nodes/Terrain/TerrainSurfaceGradientListNode.cpp
Labels: sig/content, sig/graphics-audio

#14631 Updated Asset Bundler tests to work with Linux.
  AutomatedTesting/Gem/PythonTests/assetpipeline/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/bundler_batch_setup_fixture.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/asset_bundler_batch_tests.py
Labels: feature/asset-pipeline

#14914 Thumbnail view context menu and hotkeys
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.h
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageProcessingSystemComponent.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/ImageProcessingSystemComponent.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/AssetBrowser/AtomToolsAssetBrowserInteractions.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowserInteractions.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/ProceduralAssetHandler.cpp
  Gems/SliceFavorites/Code/Source/FavoriteDataModel.cpp
  Gems/SliceFavorites/Code/Source/FavoriteDataModel.h
Labels: sig/content, feature/asset-browser

#14951 Material Canvas: Refresh graph view after settings change
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocumentView.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Window/AtomToolsMainWindow.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocumentView.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasMainWindow.h
  Gems/Atom/Tools/PassCanvas/Code/Source/PassCanvasApplication.cpp
  Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.cpp
  Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasMainWindow.h
Labels: sig/content, sig/graphics-audio

#14917 Add support for reverting property override in DPE Entity Inspector
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_entity_utils.py
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabPropertyEditorNodes.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverridePublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverridePublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverridePublicInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Prefab/Overrides/PrefabInspectorOverrideTests.cpp
Labels: sig/content, feature/prefabs

#14756 Multiplayer Simple Player Spawner: Expose Spawn Points
  Gems/Multiplayer/Code/Include/Multiplayer/Components/ISimplePlayerSpawner.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/SimplePlayerSpawnerComponent.h
  Gems/Multiplayer/Code/Source/Components/SimplePlayerSpawnerComponent.cpp
  Gems/Multiplayer/Code/Tests/SimplePlayerSpawnerTests.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
  Gems/Multiplayer/Code/multiplayer_tests_files.cmake
Labels: sig/network

#14817 Multiplayer Editor: Tether ServerLauncher Lifetime to Editor
  Code/Framework/AzFramework/AzFramework/Process/ProcessUtils.h
  Code/Framework/AzFramework/AzFramework/Process/ProcessWatcher.h
  Code/Framework/AzFramework/AzFramework/azframework_files.cmake
  Code/Framework/AzFramework/Platform/Android/AzFramework/Process/ProcessUtils_Android.cpp
  Code/Framework/AzFramework/Platform/Android/platform_android_files.cmake
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessUtils_Linux.cpp
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessWatcher_Linux.cpp
  Code/Framework/AzFramework/Platform/Linux/platform_linux_files.cmake
  Code/Framework/AzFramework/Platform/Mac/AzFramework/Process/ProcessUtils_Mac.cpp
  Code/Framework/AzFramework/Platform/Mac/AzFramework/Process/ProcessWatcher_Mac.cpp
  Code/Framework/AzFramework/Platform/Mac/platform_mac_files.cmake
  Code/Framework/AzFramework/Platform/Windows/AzFramework/Process/ProcessUtils_Win.cpp
  Code/Framework/AzFramework/Platform/Windows/AzFramework/Process/ProcessWatcher_Win.cpp
  Code/Framework/AzFramework/Platform/Windows/platform_windows_files.cmake
  Code/Framework/AzFramework/Platform/iOS/AzFramework/Process/ProcessUtils_iOS.cpp
  Code/Framework/AzFramework/Platform/iOS/platform_ios_files.cmake
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: sig/network

#14966 Chromatic Aberration Null render automation
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_01.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_ChromaticAberrationAdded.py
  AutomatedTesting/Levels/Graphics/base_empty/base_empty.prefab
Labels: sig/graphics-audio

#14996 Atom Tools: Adding unique suffixes and tooltips to asset selection entries
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionComboBox.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetSelection/AssetSelectionGrid.cpp
Labels: sig/content, sig/graphics-audio

#14994 Atom Tools: Updating asset browser, selectors, and enumeration to ignore the cache and intermediate asset folders
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/AssetBrowser/AtomToolsAssetBrowser.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
Labels: sig/content, sig/graphics-audio

#14962 Editable breadcrumbs UI fixes
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.qss
Labels: sig/content, feature/asset-browser

#14329 re-enable script hot reload behind setreg
  Code/Framework/AzFramework/AzFramework/Script/ScriptComponent.cpp
  Code/Framework/AzFramework/AzFramework/Script/ScriptComponent.h
Labels: feature/scripting, kind/feature

#14862 Jobs with missing source dependencies are now run later, in case the dependencies resolve
  Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
Labels: feature/asset-pipeline

#15016 Fixes asset processor warning spam
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
Labels: feature/asset-pipeline

#15025 Stars component null rhi test automation
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_StarsAdded.py
Labels: sig/graphics-audio

#14929 Asset Processor - Metadata Create Delay
  Code/Tools/AssetProcessor/assetprocessor_static_files.cmake
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/DelayRelocationTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/DelayRelocationTests.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.h
  Code/Tools/AssetProcessor/native/utilities/IMetadataUpdates.h
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.h
Labels: feature/asset-pipeline, sig/content

#14492 Update Far depth cascade if Shadow far clip is modified.
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorDirectionalLightComponent.cpp
Labels: sig/graphics-audio

#15071 Fix build for macOS
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/Scope.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/StreamingImagePoolResolver.h
Labels: platform/macos

#15010 Change graph canvas presets dialog selection behavior to entire row and update naming
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphView.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/ConstructPresetDialog/ConstructPresetDialog.cpp
Labels: sig/content, sig/graphics-audio

#15012 Material Canvas: Use a unique suffix for substitution names if a graph has multiple output nodes
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.h
Labels: sig/content, sig/graphics-audio

#15074 Sky Atmosphere rhi null test automation
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_constants.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_SkyAtmosphereAdded.py
Labels: sig/graphics-audio

#15039 Moving material assignment data types to LY integration and optimizing/batching material related notifications
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Material/MaterialAssignmentBus.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Mocks/MockMeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/OcclusionCullingPlane/OcclusionCullingPlane.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_staticlibrary_files.cmake
  Gems/AtomLyIntegration/AtomImGuiTools/Code/Include/AtomLyIntegration/AtomImGuiTools/AtomImGuiToolsBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentNotificationBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/EditorMaterialSystemComponentRequestBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialAssignment.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialAssignmentId.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Material/MaterialComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/PostProcess/DisplayMapper/DisplayMapperComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CommonFeaturesSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentSlot.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentUtil.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialModelUvNameMapInspector.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialAssignment.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialAssignmentId.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/SharedPreview/SharedPreviewContent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
  Gems/Terrain/Code/Source/TerrainRenderer/Components/TerrainSurfaceMaterialsListComponent.h
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.cpp
  Gems/WhiteBox/Code/Source/Rendering/Atom/WhiteBoxAtomRenderMesh.h
Labels: sig/content, sig/graphics-audio

#14575 Fixed Debug Rendering component name
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RenderDebugEditorComponent.cpp
Labels: sig/graphics-audio

#14931 Add editor python automated test for metadata
  AutomatedTesting/Gem/AssetProcessorGemConfig.setreg
  AutomatedTesting/Gem/PythonTests/assetpipeline/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/TestSuite.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/__init__.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/assets/bunny_material.material
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/assets/bunny_material.material.meta
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/tests/MetadataRelocation_ReferenceValidAfterRename.py
  AutomatedTesting/Levels/MetadataTest/MetadataTest.prefab
Labels: feature/asset-pipeline

#14964 Add sv_useGameLiftServer CVAR to allow local play without GameLift
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/AWSGameLiftServerSystemComponent.cpp
Labels: feature/cloud-service, sig/network

#15085 Prefab Override | Enable override in Entity Outliner by default
  AutomatedTesting/Registry/editorpreferences.setreg
  Registry/prefab.editor.setreg
Labels: sig/content, feature/prefabs

#15117 Fix graph model integer slot precision to only show scientific notation for large numbers
  Gems/GraphModel/Code/Include/GraphModel/Integration/FloatDataInterface.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/IntegerDataInterface.h
  Gems/GraphModel/Code/Source/Integration/FloatDataInterface.cpp
Labels: sig/content, sig/graphics-audio

#15111 Fix material editor/canvas viewport settings inspector data corruption
  Gems/Atom/Feature/Common/Code/Source/Utils/EditorLightingPreset.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsInspector.cpp
Labels: sig/content, sig/graphics-audio

#15100 Fix material editor not launching when motion matching is enabled
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg
  Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg
  Gems/Atom/Tools/PassCanvas/Registry/gem_autoload.passcanvas.setreg
  Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
Labels: sig/content, sig/graphics-audio

#15088 Cache link id rather than link in prefab undo node
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUpdateLink.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUpdateLink.h
Labels: sig/content, feature/prefabs

#15053 Toggle filter for "Unusable Products" and "Engine Folders" in new asset browser
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/Filter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
  Gems/Atom/RPI/Registry/asset_browser.setreg
Labels: sig/content, feature/asset-browser

#15122 Thumbnailview icon and scrollbar fixes
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzQtComponents/AzQtComponents/Images/AssetBrowser/materialtype.svg
  Code/Framework/AzQtComponents/AzQtComponents/Images/resources.qrc
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/ProceduralAssetHandler.cpp
Labels: sig/content, feature/asset-browser

#15126 Asset Processor - Improve handling of legacy UUIDs
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/PathOrUuid.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/PathOrUuid.h
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/BuilderManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/PathDependencyManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/UuidManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/SourceDependencyTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/SourceDependencyTests.h
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.h
Labels: feature/asset-pipeline, sig/content

#15159 Fix for Baked DiffuseProbeGrids on non-RT capable devices
  Gems/DiffuseProbeGrid/Assets/Passes/DiffuseProbeGridPreparePassRequest.azasset
  Gems/DiffuseProbeGrid/Assets/Passes/DiffuseProbeGridUpdate.pass
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
Labels: sig/graphics-audio

#15155 Updating graph model reflection and unbinding function causing AP asserts
  AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialCanvas_Atom_BasicTests.py
  Gems/GraphModel/Code/Include/GraphModel/Model/Common.h
  Gems/GraphModel/Code/Include/GraphModel/Model/GraphContext.h
  Gems/GraphModel/Code/Source/GraphModelSystemComponent.cpp
  Gems/GraphModel/Code/Source/Model/Connection.cpp
  Gems/GraphModel/Code/Source/Model/DataType.cpp
  Gems/GraphModel/Code/Source/Model/Graph.cpp
  Gems/GraphModel/Code/Source/Model/GraphContext.cpp
  Gems/GraphModel/Code/Source/Model/GraphElement.cpp
  Gems/GraphModel/Code/Source/Model/Node.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
Labels: sig/content

#15178 Updating atom tools auto load registry settings to disable AWS modules
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Application/AtomToolsApplication.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialCanvas/Registry/gem_autoload.materialcanvas.setreg
  Gems/Atom/Tools/MaterialEditor/Registry/gem_autoload.materialeditor.setreg
  Gems/Atom/Tools/PassCanvas/Registry/gem_autoload.passcanvas.setreg
  Gems/Atom/Tools/ShaderManagementConsole/Registry/gem_autoload.shadermanagementconsole.setreg
  Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Labels: sig/content, sig/graphics-audio

#15187 Add material instance null pointer check in editor material component
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
Labels: sig/content, sig/graphics-audio

#14549 [ShaderManagementConsole] List all material which use the selected option
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentSystem.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Data/ShaderVariantStatisticData.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Data/ShaderVariantStatisticData.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleStatisticView.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleStatisticView.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleTableView.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Window/ShaderManagementConsoleWindow.h
  Gems/Atom/Tools/ShaderManagementConsole/Code/shadermanagementconsole_files.cmake
Labels: sig/graphics-audio

#15207 Fix for DiffuseProbeGrid mode when exiting Play Game
  Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
Labels: sig/graphics-audio

#14129 Add model/texture quality setting and bus
  Code/Tools/SceneAPI/SceneCore/DataTypes/Rules/ITagRule.h
  Code/Tools/SceneAPI/SceneCore/DllMain.cpp
  Code/Tools/SceneAPI/SceneCore/scenecore_files.cmake
  Code/Tools/SceneAPI/SceneData/ManifestMetaInfoHandler.cpp
  Code/Tools/SceneAPI/SceneData/ReflectionRegistrar.cpp
  Code/Tools/SceneAPI/SceneData/Rules/TagRule.cpp
  Code/Tools/SceneAPI/SceneData/Rules/TagRule.h
  Code/Tools/SceneAPI/SceneData/SceneData_files.cmake
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Editor/TexturePresetSelectionWidget.ui
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageAssetProducer.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageAssetProducer.h
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/ImageConvert.cpp
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AssetQuality.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/AssetTagBus.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/ImageTagSystemComponent.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Model/ModelTagSystemComponent.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/StreamingImageAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Image/StreamingImageAssetCreator.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Model/ModelAsset.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Model/ModelAssetCreator.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Private/Module.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageTagSystemComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelTagSystemComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAssetCreator.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Image/StreamingImageAssetHandler.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAsset.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAssetCreator.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
Labels: sig/graphics-audio

#15102 Updated failing in assetpipeline/asset_processor_tests/asset_processor_gui_tests.py and assetpipeline/asset_processor_tests/asset_processor_gui_tests2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/C24168802/Jack.fbx.assetinfo
Labels: feature/asset-pipeline

#15206 Table view and Thumbnail view fixes
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserExpandedTableViewProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserExpandedTableView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.h
Labels: sig/content, feature/asset-browser

#15197 Asset Processor - Asset Tab Navigation fixes
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/ui/AssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/AssetTreeItem.cpp
  Code/Tools/AssetProcessor/native/ui/AssetTreeItem.h
  Code/Tools/AssetProcessor/native/ui/AssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderData.cpp
  Code/Tools/AssetProcessor/native/ui/BuilderData.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/ProductAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/ProductAssetTreeItemData.cpp
  Code/Tools/AssetProcessor/native/ui/ProductAssetTreeItemData.h
  Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeItemData.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeItemData.h
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.cpp
  Code/Tools/AssetProcessor/native/ui/SourceAssetTreeModel.h
  Code/Tools/AssetProcessor/native/utilities/IPathConversion.h
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
Labels: feature/asset-pipeline, sig/content

#15255 Asset Processor - Fix outgoing dependency not handling abs path
  Code/Tools/AssetProcessor/native/ui/SourceAssetDetailsPanel.cpp
Labels: feature/asset-pipeline

#15265 Confirmation dialog for file deletions
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
Labels: sig/content, feature/asset-browser

#15198 Asset Processor - Handle edge case of product prefix conflict
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/utilities/ProductOutputUtil.cpp
  Code/Tools/AssetProcessor/native/utilities/ProductOutputUtil.h
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
Labels: feature/asset-pipeline, sig/content

#15296 Update asset load behavior comments
  Code/Framework/AzCore/AzCore/Asset/AssetCommon.h
Labels: feature/asset-pipeline, sig/content

#15298 Asset Processor - Update error message to refer to setreg path instead of bootstrap.cfg
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationServer.cpp
Labels: feature/asset-pipeline, sig/content

#15257 Material Canvas: Fixing utility nodes to be editable in the inspector and have a title palette color
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/StyleSheet/materialcanvas_style.json
  Gems/Atom/Tools/PassCanvas/Assets/PassCanvas/StyleSheet/passcanvas_style.json
Labels: sig/content, sig/graphics-audio

#15321 EMFX: Fix crash caused by non-loading MotionSets
  Gems/EMotionFX/Code/EMotionFX/Source/Importer/Importer.cpp
Labels: feature/animation

#15327 Fix movement issues when client input id wraps around.
  Gems/Multiplayer/Code/Source/Components/LocalPredictionPlayerInputComponent.cpp
  Gems/Multiplayer/Code/Tests/ClientHierarchyTests.cpp
  Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.cpp
  Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.h
Labels: sig/network

#15328 Prefab Overrides: Fix invalid string data in DPE reflection adapter
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/Attribute.h
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/Reflection/LegacyReflectionBridge.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
Labels: sig/content, feature/prefabs

#14861 Updating assetpipline/assetprocessor tests to fix test issues.
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_cache_server_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/a.fbx.assetinfo
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/b.fbx.assetinfo
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/assets/test_TwoAssetsWithSameProductName_ShouldProcessAfterRename/rename.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/assetpipeline_utils/__init__.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/assetpipeline_utils/assetpipeline_constants.py
  Tools/LyTestTools/ly_test_tools/environment/file_system.py
  Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
  Tools/LyTestTools/tests/unit/test_file_system.py
Labels: feature/asset-pipeline

#15379 Fix error when prefab generator skips generation
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
Labels: feature/asset-pipeline, sig/content

#15251 Fixed an issue where a serialization version number went down instead…
  Gems/Prefab/PrefabBuilder/PrefabBuilderComponent.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderComponent.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Node.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/BehaviorContextUtils.cpp
Labels: feature/asset-pipeline

#15264 Prefab Overrides: Fix property-edit issues in DPE Entity Inspector
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverrideTypes.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoComponentPropertyOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoComponentPropertyOverride.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.h
Labels: feature/editor, sig/content, feature/prefabs

#15383 Check component validity before DoRefresh() in DPE component adapter
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DPEComponentAdapter.h
Labels: feature/editor, sig/content

#15175 Add OnObjectSrgCreated event
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Mesh/MeshComponentBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
Labels: sig/graphics-audio

#15385 AP - Scan Skipping Unit Tests
  Code/Tools/AssetProcessor/assetprocessor_test_files.cmake
  Code/Tools/AssetProcessor/native/tests/assetmanager/InitialScanSkippingTests.cpp
Labels: feature/asset-pipeline, sig/content

#15462 Disable warning and error message box UI in material editor and material canvas tests
  AutomatedTesting/Gem/PythonTests/Atom/atom_utils/atom_tools_utils.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialCanvas_Atom_BasicTests.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_BasicTests.py
  AutomatedTesting/Gem/PythonTests/Atom/tests/MaterialEditor_Atom_PeriodicTests.py
Labels: sig/content, sig/graphics-audio

#15438 Material Canvas: Fix checkbox and node property displays refreshing
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp
  Gems/GraphModel/Code/Include/GraphModel/Integration/BooleanDataInterface.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/FloatDataInterface.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/IntegerDataInterface.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/ReadOnlyDataInterface.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/StringDataInterface.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/VectorDataInterface.inl
  Gems/GraphModel/Code/Source/Integration/BooleanDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/FloatDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/ReadOnlyDataInterface.cpp
  Gems/GraphModel/Code/Source/Integration/StringDataInterface.cpp
Labels: sig/content, sig/graphics-audio

#15434 Material Canvas: Save and restore graph element selection on load, undo, and redo
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphView.cpp
  Gems/GraphCanvas/Code/Source/Components/SceneComponent.cpp
  Gems/GraphModel/Code/Include/GraphModel/Integration/GraphCanvasMetadata.h
  Gems/GraphModel/Code/Include/GraphModel/Integration/GraphController.h
  Gems/GraphModel/Code/Source/GraphModelSystemComponent.cpp
  Gems/GraphModel/Code/Source/Integration/GraphCanvasMetadata.cpp
  Gems/GraphModel/Code/Source/Integration/GraphController.cpp
Labels: sig/content, sig/graphics-audio

#15425 Simplify and improve prefab undo utility functions
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplateInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabFocusInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntityAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoBase.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoBase.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoComponentPropertyEdit.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoComponentPropertyOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoUtils.h
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoLinkTests.cpp
Labels: sig/content, feature/prefabs

#14560 Model import support transparent material.
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialConverterSystemComponent.cpp
Labels: sig/graphics-audio

#14523 add progress bar for ddgi bake textures.
  Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
Labels: sig/graphics-audio

#14573 Fix some material params are hidden after hiding enitiy and switching…
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponent.h
Labels: sig/graphics-audio

#15472 Asset Processor - Fix metadata creation delay not being zero initialized
  Code/Tools/AssetProcessor/native/utilities/UuidManager.h
Labels: feature/asset-pipeline, sig/content
