Repository o3de/o3de, pull requests merged in 2023-02, with the labels that each got.

#14320 Fix ASV screenshot
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
Labels: feature/graphics/rpi

#14345 Material Component: Error handling for missing assets
  Gems/Atom/Feature/Common/Code/Source/Material/MaterialAssignment.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.h
Labels: sig/content, sig/graphics-audio

#12461 Single pass luminance downsample
  Gems/Atom/Feature/Common/Assets/Passes/DownsampleSinglePassLuminance.pass
  Gems/Atom/Feature/Common/Assets/Passes/LightAdaptationParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DownsampleSinglePassLuminance.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/DownsampleSinglePassLuminance.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h
  Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
  Gems/Atom/RPI/Assets/ShaderLib/External/FidelityFX/ffx-spd/LICENSE
  Gems/Atom/RPI/Assets/ShaderLib/External/FidelityFX/ffx-spd/PackageInfo.json
  Gems/Atom/RPI/Assets/ShaderLib/External/FidelityFX/ffx-spd/ffx_a.h
  Gems/Atom/RPI/Assets/ShaderLib/External/FidelityFX/ffx-spd/ffx_spd.h
  Gems/Atom/RPI/Assets/atom_rpi_asset_files.cmake
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ComputePass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/DownsampleSinglePassLuminancePass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Shader/ShaderCommonTypes.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassFactory.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/DownsampleSinglePassLuminancePass.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
Labels: sig/graphics-audio

#14282 Improve detach prefab workflow with selective undo nodes
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDetachPrefabTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
Labels: sig/content, feature/prefabs

#14349 Fix crash in dropping fbx as new-prefab override
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
Labels: sig/content, feature/prefabs

#14433 Material Canvas: Fixing Vulkan texture sampling crash
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/SamplerState.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/SamplerState.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Sampler.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
Labels: sig/graphics-audio

#14451 EMFX: Fixes crashes and update layout
  Gems/EMotionFX/Assets/Editor/Layouts/Animation.layout
  Gems/EMotionFX/Assets/Editor/Layouts/Character.layout
  Gems/EMotionFX/Code/Source/Editor/SkeletonModel.cpp
Labels: feature/animation

#14488 EMFX: Fixes a crash that caused by not hidden the widget when no actor instance is selected
  Gems/EMotionFX/Code/Source/Editor/Plugins/ColliderWidgets/JointPropertyWidget.cpp
Labels: feature/animation

#14198 Asset Processor - Intermediate UUID Metadata
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AzToolsFrameworkModule.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetaUuidEntry.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetaUuidEntry.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/UuidUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/UuidUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Framework/AzToolsFramework/Tests/Metadata/MetadataManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/Metadata/UuidUtilTests.cpp
  Code/Framework/AzToolsFramework/Tests/aztoolsframeworktests_files.cmake
  Code/Tools/AssetProcessor/AssetBuilder/AssetBuilderApplication.cpp
  Code/Tools/AssetProcessor/native/AssetManager/ProductAsset.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.h
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.h
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/UuidManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.h
  Code/Tools/AssetProcessor/native/tests/platformconfiguration/platformconfigurationtests.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCJobTest.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.h
Labels: feature/asset-pipeline, sig/content

#14484 Provide a CharacterNotifications bus to drive association of active PhysX character and Network Character Controllers
  Code/Framework/AzFramework/AzFramework/Physics/CharacterBus.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkCharacterComponent.h
  Gems/Multiplayer/Code/Source/Components/NetworkCharacterComponent.cpp
  Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.cpp
  Gems/PhysX/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.h
  Gems/PhysX/Code/Source/RigidBodyComponent.cpp
  Gems/PhysX/Code/Source/RigidBodyComponent.h
  Gems/PhysX/Code/Source/StaticRigidBodyComponent.cpp
  Gems/PhysX/Code/Source/StaticRigidBodyComponent.h
Labels: feature/networking, feature/physics

#14448 Material Canvas: Sorting generated material type groups and properties
  Gems/Atom/RPI/Code/Include/Atom/RPI.Edit/Material/MaterialTypeSourceData.h
  Gems/Atom/RPI/Code/Source/RPI.Edit/Material/MaterialTypeSourceData.cpp
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/TestData/test_propertysorting.materialgraph
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
Labels: sig/content, sig/graphics-audio

#14505 Multiplayer "Connect" Console Command Working Via Commandline and SetReg
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Labels: sig/network

#14480 Fix for create new asset in thumbnail view
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Script/LuaEditorSystemComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialBrowserInteractions.cpp
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
Labels: sig/content, feature/asset-browser

#14428 Intermediate assets that have had their source removed are no longer processed.
  Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: feature/asset-pipeline

#14550 Fix for RayTracing terrain mesh height
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
Labels: sig/graphics-audio

#13811 Add Variable Rate Shade image support to the XR pipeline
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.h
  Gems/Atom/Feature/Common/Assets/Passes/LowEndPipelineXRLeft.pass
  Gems/Atom/Feature/Common/Assets/Passes/LowEndPipelineXRRight.pass
  Gems/Atom/Feature/Common/Assets/Passes/MultiViewForward.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/Textures/VRSTexture.attimage
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/RHI/Code/Include/Atom/RHI/Device.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/XRRenderingInterface.h
  Gems/Atom/RHI/Code/Tests/Device.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Null/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Null/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/XR/XRRenderingInterface.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/Atom/RPI/Code/Tests/Common/RHI/Stubs.h
Labels: sig/graphics-audio

#14483 Fix nested prefab bug in detach prefab operation
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDetachPrefabTests.cpp
Labels: sig/content, feature/prefabs

#14567 Add BufferPool unique allocation bytes tracking
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/MemoryUsage.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/MemoryUsage.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/BufferMemoryAllocator.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/BufferMemoryAllocator.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/MemoryTypeAllocator.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
Labels: sig/graphics-audio

#14607 Fix array/vector network serialization to have unique names.
  Code/Framework/AzNetworking/AzNetworking/Serialization/StringifySerializer.cpp
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponent.h
Labels: sig/network

#14608 bugfix: Changing "Expand by" doesn't take effect.
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorDebugDraw.cpp
Labels: feature/animation, sig/graphics-audio, sig/simulation

#14616 bugfix: Editor buttons is lack of tooltips, such as Max/Min/Restore.
  Code/Framework/AzQtComponents/AzQtComponents/Components/DockBarButton.cpp
Labels: sig/content

#14617 bugfix: Increase width of comboxes.
  Code/Editor/TrackView/SequenceBatchRenderDialog.ui
Labels: sig/content

#14627 Fix blue outline when thumbnail selection changes
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
Labels: sig/content, feature/asset-browser

#14661 add parent widget to StringDlg object.
  Code/Editor/TrackView/TrackViewNodes.cpp
Labels: sig/content

#14662 bugfix: light color on track is inconsistent.
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
Labels: sig/content

#14663 bugfix: edit event name with its old name.
  Code/Editor/TrackView/TVEventsDialog.cpp
Labels: feature/trackview, sig/content

#14664 bugfix: remove the unnecessary prompt when deleting unused events.
  Code/Editor/TrackView/TVEventsDialog.cpp
Labels: sig/content

#14665 fix uint64 value serialize/deserialize by CXmlNode.
  Code/Legacy/CrySystem/XML/xml.cpp
Labels: sig/content

#14667 fix auto recording rate inconsistent problem.
  Code/Editor/TrackView/TrackViewDialog.cpp
Labels: feature/trackview, sig/content

#14671 Save Frames options in Edit Sequence.
  Code/Editor/TrackView/TVSequenceProps.cpp
  Code/Legacy/CryCommon/IMovieSystem.h
Labels: sig/content

#14669 bugfix Find Node of Track View.
  Code/Editor/TrackView/TrackViewFindDlg.cpp
  Code/Editor/TrackView/TrackViewFindDlg.h
Labels: sig/content

#14673 fix sequence select/edit.
  Code/Editor/TrackView/TrackViewDialog.cpp
Labels: sig/content

#14658 Change RayTracing to use the Bindless Srg
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialUtils.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneUtils.azsli
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/BufferView.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBorderUpdatePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBorderUpdatePass.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.h
Labels: sig/graphics-audio

#14609 bugfix: correct change status of "Actor name".
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/SceneManager/ActorPropertiesWindow.cpp
Labels: sig/simulation

#13851 Add new AZ_Trace and AZ_Info macros
  Code/Framework/AzCore/AzCore/Debug/Trace.cpp
  Code/Framework/AzCore/AzCore/Debug/Trace.h
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponentHelper.cpp
  Code/Legacy/CrySystem/AZCoreLogSink.h
  Gems/Atom/Asset/Shader/Code/Source/Editor/AzslCompiler.cpp
Labels: sig/core

#14605 Asset Processor - UUID conflict handling
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/UuidUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/UuidUtils.h
  Code/Framework/AzToolsFramework/Tests/Metadata/MetadataManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/Metadata/UuidUtilTests.cpp
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp
  Code/Tools/AssetProcessor/native/tests/UuidManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/IntermediateAssetTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: feature/asset-pipeline

#14526 Using System Allocator to manage small objects used by Vulkan.
  Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/VkAllocator.h
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Android/RHI/WSISurface_Android.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Linux/RHI/WSISurface_Linux.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/RHI/WSISurface_Windows.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Reflect/VkAllocator.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BindlessDescriptorPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ComputePipeline.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSetLayout.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Framebuffer.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/GraphicsPipeline.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/NullDescriptorManager.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Pipeline.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLayout.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/QueryPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ReleaseContainer.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Sampler.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Semaphore.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderModule.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Vulkan.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/WSISurface.cpp
  Gems/Atom/RHI/Vulkan/Code/atom_rhi_vulkan_reflect_common_files.cmake
Labels: sig/graphics-audio

#14566 Multiplayer Component to Debug Player Id
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetworkDebugPlayerIdComponent.h
  Gems/Multiplayer/Code/Source/AutoGen/NetworkDebugPlayerIdComponent.AutoComponent.xml
  Gems/Multiplayer/Code/Source/Components/NetworkDebugPlayerIdComponent.cpp
  Gems/Multiplayer/Code/multiplayer_split_files.cmake
Labels: feature/networking, sig/network

#14641 Fix bug of ScriptTimePoint ToString method.
  Code/Framework/AzCore/AzCore/Script/ScriptTimePoint.cpp
Labels: sig/core

#14639 Add verification that script canvas filename cannot start with a number.
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Labels: sig/content

#14682 Material Canvas and Editor: Fixing property ranges, sliders, and descriptions
  Gems/Atom/RHI/Code/Source/RHI.Reflect/SamplerState.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphViewSettings.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/SettingsDialog/SettingsDialog.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Document/AtomToolsDocumentMainWindow.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/DynamicProperty/DynamicProperty.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphViewSettings.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/SettingsDialog/SettingsDialog.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Window/AtomToolsMainWindow.cpp
  Gems/Atom/Tools/MaterialEditor/Code/Source/Document/MaterialDocument.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/EditorMaterialComponentInspector.cpp
Labels: sig/content, sig/graphics-audio

#14727 Fix descriptions on generated components.
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponent_Source.jinja
Labels: sig/network

#14728 Updating conditional skips for several Asset Pipeline tests
  AutomatedTesting/Gem/PythonTests/assetpipeline/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_cache_server.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_relocator_tests.py
Labels: feature/asset-pipeline

#14686 Allow editable breadcrumbs to use and display full file paths
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
Labels: sig/content, feature/asset-browser

#14759 DiffuseProbeGrid Emissive Multiplier
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialUtils.azsli
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracing_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracinganyhit_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingclosesthit_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss.azshader
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_dx12_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_null_0.azshadervariant
  Gems/DiffuseProbeGrid/Assets/Shaders/DiffuseGlobalIllumination/diffuseprobegridraytracingmiss_vulkan_0.azshadervariant
  Gems/DiffuseProbeGrid/Code/Include/DiffuseProbeGrid/DiffuseProbeGridFeatureProcessorInterface.h
  Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentConstants.h
  Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.cpp
  Gems/DiffuseProbeGrid/Code/Source/Components/DiffuseProbeGridComponentController.h
  Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.cpp
  Gems/DiffuseProbeGrid/Code/Source/EditorComponents/EditorDiffuseProbeGridComponent.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.h
Labels: sig/graphics-audio
