Repository o3de/o3de, pull requests merged in 2023-11, with the labels that each got.

#17015 Fixed 'assign ScriptCanvas graph to entity'
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponent.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Labels: feature/scripting, sig/content

#17014 Disable duplicate action from connections context menu
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenus/ConnectionContextMenu.cpp
Labels: feature/scripting, sig/content

#17013 Added subtitles to UI Set Text nodes
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiDropdownBus.names
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiDropdownOptionBus.names
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTextBus.names
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTextInputBus.names
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTooltipBus.names
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/UiTooltipDisplayBus.names
Labels: feature/scripting, sig/content

#17023 Add Wwise seed lists for game audio and libs
  Gems/AudioEngineWwise/Assets/AudioBank_Dependencies.xml
  Gems/AudioEngineWwise/Assets/GameAudioSeedList.seed
Labels: release-note

#17032 Changes to support Tool applications(Editor, AP, AssetBundler) in non-monolithic release
  Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
  Code/Framework/AzCore/CMakeLists.txt
  Code/Framework/AzFramework/AzFramework/Archive/Archive.cpp
  Code/Framework/AzFramework/AzFramework/Archive/ArchiveVars.cpp
  Code/Framework/AzFramework/AzFramework/feature_options.cmake
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Libraries.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/UnitTesting/UnitTestingLibrary.cpp
  engine.json
Labels: release-note

#17048 Continue CloseAll operation after saving
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Labels: feature/scripting

#17109 Fixed opening graphs resulting in duplicated slots
  Gems/ScriptCanvas/Code/Editor/View/Widgets/GraphTabBar.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Core.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
Labels: feature/scripting
