Repository o3de/o3de, pull requests merged in 2023-01, with the labels that each got.

#13781 Multiplayer Editor: Increase Time Between Server Connect Attempts
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
Labels: feature/networking, sig/network

#13871 Adding 'SimplePlayerSpawner' to Multiplayer Gem
  Gems/Multiplayer/Code/Include/Multiplayer/Components/SimplePlayerSpawnerComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/IMultiplayerSpawner.h
  Gems/Multiplayer/Code/Source/Components/SimplePlayerSpawnerComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerGem.cpp
  Gems/Multiplayer/Code/multiplayer_files.cmake
Labels: feature/networking, sig/network

#13862 show secondary asset browser from context menu
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.h
Labels: sig/content, feature/asset-browser

#13787 Adding actuation to PhysX joints
  Gems/PhysX/Code/Editor/Source/Components/EditorSystemComponent.cpp
  Gems/PhysX/Code/Include/PhysX/Joint/Configuration/PhysXJointConfiguration.h
  Gems/PhysX/Code/Include/PhysX/Joint/PhysXJointRequestsBus.h
  Gems/PhysX/Code/Source/EditorHingeJointComponent.cpp
  Gems/PhysX/Code/Source/EditorHingeJointComponent.h
  Gems/PhysX/Code/Source/EditorPrismaticJointComponent.cpp
  Gems/PhysX/Code/Source/EditorPrismaticJointComponent.h
  Gems/PhysX/Code/Source/HingeJointComponent.cpp
  Gems/PhysX/Code/Source/HingeJointComponent.h
  Gems/PhysX/Code/Source/Joint/Configuration/PhysXJointConfiguration.cpp
  Gems/PhysX/Code/Source/Joint/PhysXJointUtils.cpp
  Gems/PhysX/Code/Source/JointComponent.cpp
  Gems/PhysX/Code/Source/JointComponent.h
  Gems/PhysX/Code/Source/PrismaticJointComponent.cpp
  Gems/PhysX/Code/Source/PrismaticJointComponent.h
  Gems/PhysX/Code/physx_files.cmake
Labels: feature/physics, sig/simulation

#13564 Scene test builder and runner, debug parser, and 3 scene tests with t…
  AutomatedTesting/Gem/AssetProcessorGemConfig.setreg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/__init__.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/FBXTestTexture.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/OneMeshOneMaterial.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OverrideAssetInfoForTwoMeshTwoMaterial/multiple_mesh_multiple_material.fbx.assetinfo
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/SoftNamingLOD/SceneDebug/lodtest.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/SoftNamingLOD/SceneDebug/lodtest.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/SoftNamingLOD/lodtest.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/FBXSecondTestTexture.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/FBXTestTexture.png
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/multiple_mesh_multiple_material.fbx
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/multiple_mesh_multiple_material.fbx.assetinfo
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/scene_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/tests/OneMeshOneMaterial.scenetest
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/tests/SoftNamingLOD.scenetest
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/tests/TwoMeshTwoMaterial.scenetest
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/tests/template.json
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests_fixtures/scene_test_builder.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests_fixtures/scene_test_debug_compare.py
Labels: sig/content, feature/scene-pipeline

#12843 Change UpdateManifest's default behaviour
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
Labels: sig/content

#6508 3722 auto assigning newly created assets.
  Code/Editor/AssetEditor/AssetEditorRequestsHandler.cpp
  Code/Editor/AssetEditor/AssetEditorRequestsHandler.h
  Code/Editor/AssetEditor/AssetEditorWindow.cpp
  Code/Editor/AssetEditor/AssetEditorWindow.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx
  Gems/ScriptCanvas/Code/Editor/View/Widgets/ScriptCanvasNodePaletteDockWidget.cpp
  Gems/StartingPointInput/Code/Source/InputConfigurationComponent.cpp
  Gems/StartingPointInput/Code/Source/InputConfigurationComponent.h
Labels: sig/content, sig/core, status/ux-approved

#13839 EMFX: Child motion set are not showing up correctly in the actor component
  Gems/EMotionFX/Code/EMotionFX/Source/MotionSet.cpp
  Gems/EMotionFX/Code/Include/Integration/AnimGraphComponentBus.h
  Gems/EMotionFX/Code/Source/Integration/Components/AnimGraphComponent.cpp
  Gems/EMotionFX/Code/Source/Integration/Components/AnimGraphComponent.h
  Gems/EMotionFX/Code/Tests/ProvidesUI/AnimGraph/AnimGraphActivateTests.cpp
  Gems/EMotionFX/Code/Tests/ProvidesUI/Menus/FileMenu/CanReset.cpp
  Gems/ScriptCanvas/Assets/TranslationAssets/EBus/Senders/AnimGraphComponentRequestBus.names
Labels: feature/animation

#13653 Migrate script canvas tests from hydra to multitest
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_component/editor_script_canvas.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvasComponent_OnEntityActivatedDeactivated_PrintMessage.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvas_TwoComponents_InteractSuccessfully.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptCanvas_TwoEntities_UseSimultaneously.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_Default_SendReceiveSuccessfully.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_HappyPath_SendReceiveAcrossMultiple.py
  AutomatedTesting/Gem/PythonTests/scripting/ScriptEvents_ReturnSetType_Successfully.py
  AutomatedTesting/Gem/PythonTests/scripting/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/scripting/scripting_utils/scripting_constants.py
  AutomatedTesting/ScriptCanvas/T92563191_test.scriptcanvas
Labels: feature/scripting, sig/testing

#13927 Fix create new not prompting user for rename
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Labels: sig/content, feature/asset-browser

#13915 EMFX: Add Simple State Action
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphObjectFactory.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphSimpleStateAction.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphSimpleStateAction.h
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
  Gems/EMotionFX/Code/Tests/AnimGraphActionTests.cpp
Labels: feature/animation

#13885 Scene Setting UI no longer lets you add a second default procedural prefab group
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/scene_settings_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_max_prefab_groups_is_one.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_test_messages.py
  Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.cpp
  Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.h
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroup.cpp
Labels: sig/content, feature/scene-pipeline

#13896 Downgraded a warning to a log: There is a reasonable fallback in this case
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
Labels: feature/scene-pipeline

#13883 Downgraded a warning to a log message
  Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
Labels: feature/asset-pipeline

#13965 Fix the scene setting issue when selected or the unselected node list is not provided
  Code/Tools/SceneAPI/SceneCore/Tests/Utilities/SceneGraphSelectorTests.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/SceneGraphSelector.cpp
Labels: feature/scene-pipeline

#13978 Prefab - Fix cached instance DOM update in undo delete
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.h
Labels: sig/content, feature/prefabs

#14009 Re-enables Linux tests except for a couple intermittent failures with certain components.
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_02.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Component_03.py
  AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_Level_Loads.py
Labels: sig/graphics-audio

#14033 Prefab | Rename prefab DOM generator functions
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGenerator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceDomGeneratorInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplateInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceToTemplatePropagator.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntity.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoAddEntityAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDelete.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/Benchmark/Link/SingleInstanceMultiplePatchesBenchmarks.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabEntityAliasTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceDomGeneratorTestFixture.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstanceToTemplatePropagatorTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoEditEntityTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoLinkTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateWithPatchesTests.cpp
  Code/Tools/SerializeContextTools/SliceConverter.cpp
Labels: sig/content, feature/prefabs

#14051 Multiplayer: Fix cl_connect_onstartup
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.cpp
  Gems/Multiplayer/Code/Source/MultiplayerSystemComponent.h
Labels: sig/network

#14034 EMFX: EventDataFloatArray and some bugfixes for motion events.
  Gems/EMotionFX/Code/EMotionFX/Source/EventDataFloatArray.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/EventDataFloatArray.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/EMStudioSDK/Source/MotionEventPresetManager.h
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/EventDataEditor.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/TimeView/TimeViewPlugin.cpp
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
  Gems/EMotionFX/Code/Source/Integration/System/SystemComponent.cpp
Labels: feature/animation

#13996 avoid a crash with texture arrays
  Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupData.h
Labels: sig/graphics-audio

#13966 Default prefab adding prefab adds mesh group
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/scene_settings_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_procedural_mesh_groups_test.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_remove_prefab_removes_mesh_groups.py
  Code/Tools/SceneAPI/SceneCore/Events/ManifestMetaInfoBus.h
  Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.cpp
  Code/Tools/SceneAPI/SceneUI/SceneWidgets/ManifestWidgetPage.h
  Gems/Prefab/PrefabBuilder/PrefabGroup/DefaultProceduralPrefab.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/DefaultProceduralPrefab.h
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBehavior.cpp
  Gems/Prefab/PrefabBuilder/PrefabGroup/PrefabGroupBus.h
Labels: feature/scene-pipeline

#13997 check if the raytracing pass needs the RayTracingSceneSrg
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.h
Labels: sig/graphics-audio

#14040 Set the Dispatch args in the constructor instead of LoadShader.
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
Labels: sig/graphics-audio

#14063 Lyn 17149: Move Asset Bundler Batch Tests to the Temp Workspace.
  AutomatedTesting/Gem/AssetProcessorGemConfig.setreg
  AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/ap_config_backup_fixture.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/ap_fixtures/bundler_batch_setup_fixture.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/__init__.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/asset_bundler_batch_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/Levels/TestDependenciesLevel/TestDependenciesLevel.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/Levels/TestDependenciesLevel/tags.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/SeedWithDependencies/AMA_Green_01.tif
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/SeedWithDependencies/AMA_Grey_01.tif
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/SeedWithDependencies/AMA_White_01.tif
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/SeedWithDependencies/Canvas1.uicanvas
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/SeedWithDependencies/default1024.font
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/SeedWithDependencies/default2048.font
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/multiple_corrupted_prefab/corrupted_prefab1.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/multiple_corrupted_prefab/corrupted_prefab2.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/multiple_working_prefab/working_prefab1.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/multiple_working_prefab/working_prefab2.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/single_corrupted_prefab/corrupted_prefab.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/single_working_prefab/working_prefab.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/TestAssets/single_working_prefab_override/working_prefab.prefab
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/datfile_0.dat
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/datfile_1.dat
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/datfile_2.dat
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/datfile_3.dat
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/datfile_4.dat
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/datfile_5.dat
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/txtfile_0.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/txtfile_1.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/txtfile_2.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/txtfile_3.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/txtfile_4.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/assets/asset_bundler_test_assets/txtfile_5.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/bundle_mode_in_editor_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/bundle_mode_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_bundler_tests/conftest.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/asset_processor_gui_tests_2.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/asset_processor_tests/missing_dependency_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/fbx_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/pythonassetbuildertests.py
  Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
Labels: feature/asset-pipeline, sig/content

#14005 Simplify screenshot code
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.h
Labels: feature/graphics

#13664 Asset Processor - Hook up Uuid Manager to AP
  Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.h
  Code/Framework/AzFramework/Tests/AssetRegistry.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Metadata/MetadataManager.cpp
  Code/Framework/AzToolsFramework/Tests/MetadataManagerTests.cpp
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.h
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.cpp
  Code/Tools/AssetProcessor/native/AssetManager/SourceAssetReference.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/ApplicationManagerTests.h
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
  Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/UuidManagerTests.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.h
  Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.cpp
  Code/Tools/AssetProcessor/native/unittests/AssetProcessorManagerUnitTests.h
  Code/Tools/AssetProcessor/native/unittests/UnitTestUtils.cpp
  Code/Tools/AssetProcessor/native/unittests/UnitTestUtils.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.h
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: feature/asset-pipeline, sig/content

#14130 Display Asset Browser Inspector in Tools
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
Labels: sig/content, feature/asset-browser

#14094 Bump up the scene builder version to reprocess FBX files after the non-PBR material fix (#14036)
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderComponent.cpp
Labels: feature/scene-pipeline

#13850 Add opt in OnNetworkActivated event for MultiplayerComponents
  Gems/Multiplayer/Code/Include/Multiplayer/Components/MultiplayerComponent.h
  Gems/Multiplayer/Code/Include/Multiplayer/Components/NetBindComponent.h
  Gems/Multiplayer/Code/Source/Components/MultiplayerComponent.cpp
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/EntityReplication/EntityReplicator.cpp
  Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.cpp
  Gems/Multiplayer/Code/Tests/TestMultiplayerComponent.h
Labels: sig/network

#14157 Execute the RayTracingAccelerationStructurePass in only one pipeline per scene
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Labels: sig/graphics-audio

#11968 AssetProcessor fixes during prepend
  Gems/Atom/RHI/Code/Source/RHI.Edit/Utils.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Android/Vulkan_Traits_Android.h
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Linux/Vulkan_Traits_Linux.h
  Gems/Atom/RHI/Vulkan/Code/Source/Platform/Windows/Vulkan_Traits_Windows.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
Labels: sig/content

#14061 Update the fbx/scene testing assets because of the latest assimp upgrade
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshMultipleMaterials/SceneDebug/single_mesh_multiple_materials.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshMultipleMaterials/SceneDebug/single_mesh_multiple_materials.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/Override_ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/Override_ModifiedFBXFile_ConsistentProductOutput/SceneDebug/modifiedfbxfile.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ShaderBall/SceneDebug/shaderball.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/ShaderBall/SceneDebug/shaderball.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/SoftNamingPhysics/SceneDebug/physicstest.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/SoftNamingPhysics/SceneDebug/physicstest.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshLinkedMaterials/SceneDebug/multiple_mesh_linked_materials.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshLinkedMaterials/SceneDebug/multiple_mesh_linked_materials.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshOneMaterial/SceneDebug/multiple_mesh_one_material.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshOneMaterial/SceneDebug/multiple_mesh_one_material.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/VertexColor/SceneDebug/vertexcolor.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/VertexColor/SceneDebug/vertexcolor.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/SceneDebug/cubewithline.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/fbx_tests/assets/cubewithline/SceneDebug/cubewithline.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/OneMeshOneMaterial/SceneDebug/onemeshonematerial.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material.dbgsg.xml
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_tests/assets/TwoMeshTwoMaterial/SceneDebug/multiple_mesh_multiple_material_override.dbgsg.xml
Labels: feature/scene-pipeline

#14180 Material Canvas: Fixing base and standard PBR material templates
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Common.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Depth.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_DepthPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Forward.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_ForwardPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_LowEndForward.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_MeshMotionVector.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_MultiViewForward.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_Shadowmap.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_VertexEval.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Common.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Depth.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_DepthPass.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_DepthPass_WithPS.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Forward.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_LowEndForward.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_LowEndForward_EDS.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MeshMotionVector.azsl
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MultiViewForward.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MultiViewForward_EDS.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_MultiViewTransparentForward_EDS.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Shadowmap.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_Shadowmap_WithPS.shader
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli
Labels: sig/graphics-audio

#14179 Fix folder creation in WIP Asset Browser
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.h
Labels: sig/content, feature/asset-browser

#14117 Prefab | Block duplicate operation for override editing
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabDuplicateTests.cpp
Labels: sig/content, feature/prefabs

#14201 Material Canvas: Restoring graph model caching and minor graph canvas optimizations
  Gems/GraphCanvas/Code/Source/Components/StylingComponent.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/PseudoElement.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/SelectorImplementations.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Styling/StyleManager.cpp
  Gems/GraphModel/Code/Include/GraphModel/Model/Graph.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Node.h
  Gems/GraphModel/Code/Include/GraphModel/Model/Slot.h
  Gems/GraphModel/Code/Source/Model/Graph.cpp
  Gems/GraphModel/Code/Source/Model/Node.cpp
  Gems/GraphModel/Code/Source/Model/Slot.cpp
Labels: sig/content, sig/graphics-audio

#14151 Added option to scene settings UI to clear unsaved changes
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/scene_settings_tests.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_clear_unsaved_changes.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_procedural_mesh_groups_test.py
  AutomatedTesting/Gem/PythonTests/assetpipeline/scene_settings_tests/tests/scene_settings_test_messages.py
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.ui
Labels: feature/scene-pipeline

#14200 Update prefab undo nodes to use utility functions
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndo.h
Labels: sig/content, feature/prefabs

#14107 S3 Query Metrics
  scripts/metrics/common/query_metrics.py
Labels: sig/testing

#13860 AssetProcessor: Fix new startup scan skip mode, update UX and rename tools to settings
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/ui/ProductAssetTreeModel.h
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.h
Labels: feature/asset-pipeline, sig/content

#14206 Material Canvas: Using jobs to parallelize work sorting and compiling graph data
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/DynamicNode/DynamicNodeManagerRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphCompiler.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphCompilerManager.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphCompilerRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocument.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocumentNotificationBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphDocumentRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphTemplateFileDataCache.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphTemplateFileDataCacheRequestBus.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Graph/GraphUtil.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphCompiler.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphCompilerManager.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphDocument.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/GraphTemplateFileDataCache.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/atomtoolsframework_files.cmake
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Document/MaterialGraphCompiler.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/MaterialCanvasApplication.h
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasViewportContent.cpp
  Gems/Atom/Tools/MaterialCanvas/Code/Source/Window/MaterialCanvasViewportContent.h
  Gems/Atom/Tools/PassCanvas/Code/Source/Document/PassGraphCompiler.cpp
  Gems/Atom/Tools/PassCanvas/Code/Source/Document/PassGraphCompiler.h
  Gems/Atom/Tools/PassCanvas/Code/Source/PassCanvasApplication.cpp
  Gems/Atom/Tools/PassCanvas/Code/Source/PassCanvasApplication.h
  Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasViewportContent.cpp
  Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasViewportContent.h
Labels: sig/content, sig/graphics-audio

#14281 Remove warning on irradiance color blend mode
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Labels: sig/graphics-audio

#14293 Suppress warnings generated by Breadcrumbs code
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/BreadCrumbs.cpp
Labels: sig/content

#14299 Adds sig-graphics-audio reviewers to Audio Gems
  .github/CODEOWNERS
Labels: feature/audio

#14301 Connect product filter to Asset Browser thumbnail view
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.h
Labels: sig/content, feature/asset-browser
