Repository o3de/o3de, pull requests merged in 2023-05, with the labels that each got.

#15721 feature: move random color to AnimGraph
  Gems/EMotionFX/Code/EMotionFX/CommandSystem/Source/AnimGraphNodeGroupCommands.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraph.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraph.h
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphNodeGroup.h
  Gems/EMotionFX/Code/EMotionFX/Source/Recorder.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/Recorder.h
  Gems/EMotionFX/Code/MCore/Source/Color.cpp
  Gems/EMotionFX/Code/MCore/Source/Color.h
Labels: feature/animation, sig/simulation

#15840 Update AWS GameLift gem to target Windows 2016 Server by default
  Gems/AWSGameLift/cdk/aws_gamelift/fleet_configurations.py
Labels: feature/cloud-service

#15862 Merge Entity Inspector and Asset Browser Inspector
  AutomatedTesting/Gem/PythonTests/Atom/tests/hydra_AtomEditorComponents_MeshAdded.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_PySide_Example_Works.py
  AutomatedTesting/Gem/PythonTests/editor/EditorScripts/AssetPicker_UI_UX.py
  AutomatedTesting/Gem/PythonTests/editor/EditorScripts/ComponentCRUD_Add_Delete_Components.py
  AutomatedTesting/Gem/PythonTests/editor/EditorScripts/Docking_BasicDockedTools.py
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/LyViewPaneNames.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ComponentEntityEditorPlugin.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/QComponentEntityEditorMainWindow.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/QComponentEntityEditorMainWindow.h
  Code/Editor/QtViewPaneManager.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
Labels: sig/content, status/ux-approved, feature/asset-browser

#15889 No cross-prefab reparenting in editor transform component
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerListModel.cpp
Labels: feature/prefabs

#15930 Atom Tools: Change cmake configuration files to create applications instead of executables
  Gems/Atom/Tools/MaterialCanvas/Code/CMakeLists.txt
  Gems/Atom/Tools/MaterialEditor/Code/CMakeLists.txt
  Gems/Atom/Tools/PassCanvas/Code/CMakeLists.txt
  Gems/Atom/Tools/PassCanvas/Code/Source/Window/PassCanvasViewportContent.cpp
  Gems/Atom/Tools/ShaderManagementConsole/Code/CMakeLists.txt
Labels: sig/content, sig/graphics-audio

#15929 Atom Tools: Change file enumeration to add logging and use extension checks instead of wild cards
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Util/Util.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/EntityPreviewViewport/EntityPreviewViewportSettingsSystem.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Graph/DynamicNode/DynamicNodeManager.cpp
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Util/Util.cpp
  Gems/Atom/Tools/MaterialCanvas/Scripts/TestOpenClose.py
  Gems/Atom/Tools/MaterialEditor/Scripts/UpgradeAllMaterials.py
Labels: sig/content, sig/graphics-audio

#15932 Fix SDK Layout issue related to dependencies on different OpenSSL major versions
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_aarch64.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake
Labels: kind/security, feature/cloud-service

#15983 Only enable splash screen in game
  Gems/Atom/Feature/Common/Code/Source/SplashScreen/SplashScreenFeatureProcessor.cpp
Labels: sig/content, sig/graphics-audio

#15993 Re-enable one prefab instantiation unit test
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabInstantiateTests.cpp
Labels: feature/prefabs

#15985 Handle component aliases in editor composition components
  Code/Framework/AzCore/AzCore/Component/Component.cpp
  Code/Framework/AzCore/AzCore/Component/Component.h
  Code/Framework/AzCore/AzCore/Component/Entity.cpp
  Code/Framework/AzCore/AzCore/Component/EntitySerializer.cpp
  Code/Framework/AzCore/AzCore/Component/EntitySerializer.h
  Code/Framework/AzCore/AzCore/Component/EntityUtils.cpp
  Code/Framework/AzCore/AzCore/Component/EntityUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityActionComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorDisabledCompositionComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorPendingCompositionComponent.h
  Code/Framework/AzToolsFramework/Tests/ComponentAddRemove.cpp
Labels: feature/prefabs

#16031 Create Asset Browser Inspector Panel
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.h
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.h
Labels: sig/content, feature/asset-browser
