Repository o3de/o3de, pull requests merged in 2024-08, with the labels that each got.

#18151 Fix for Audio Thread Taking 90% Frame Time
  Gems/AudioSystem/Code/Source/Engine/AudioSystem.cpp
  Gems/AudioSystem/Code/Source/Engine/AudioSystem.h
Labels: needs-sig

#17768 Allow for Entity creation and Prefab instantiation in place via viewport interactions.
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Editor/ViewManager.cpp
  Code/Editor/ViewManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Labels: sig/content

#18150 Fix several selection and focus related issues for the Asset Browser.
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/QtUtil.h
  Code/Editor/Viewport.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Favorites/AssetBrowserFavoritesView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Favorites/AssetBrowserFavoritesView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
Labels: sig/content

#18145 Further fixes for the ScriptCanvas debugging facilities
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Assets/ScriptCanvasFileHandling.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/EditorScriptCanvasBus.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.h
Labels: feature/scripting, sig/content

#18130 [Cherry-Pick] Fix Mesa 24 rendering issues on 24.09 (#17905)
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: needs-sig, sig/graphics-audio

#18064 Support inheriting device index from parent pass
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/RenderPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassData.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/RenderPassData.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
Labels: sig/graphics-audio

#18189 Fixes script-only "Quickstart" mode.
  Templates/ScriptOnlyProject/Template/package.sh
  cmake/Platform/Common/Install_common.cmake
Labels: sig/build

#18192 [Cherry Pick] Allow for Entity creation and Prefab instantiation in place via viewport interactions
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Editor/ViewManager.cpp
  Code/Editor/ViewManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Labels: needs-sig

#18194 Implement conversion from white box render data to visible geometry struct
  Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.cpp
  Code/Framework/AzFramework/AzFramework/Visibility/VisibleGeometryBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.cpp
  Gems/WhiteBox/Code/Source/EditorWhiteBoxComponent.h
  Gems/WhiteBox/Code/Source/Rendering/WhiteBoxRenderDataUtil.cpp
  Gems/WhiteBox/Code/Source/Rendering/WhiteBoxRenderDataUtil.h
  Gems/WhiteBox/Code/Source/WhiteBoxComponent.cpp
  Gems/WhiteBox/Code/Source/WhiteBoxComponent.h
  Gems/WhiteBox/Code/whitebox_supported_files.cmake
Labels: sig/content, sig/graphics-audio

#18114 Update AWSGameLiftServer 3rd Party Package Hash
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/Platform/Linux/PAL_linux.cmake
  Gems/AWSGameLift/Code/AWSGameLiftServer/Source/Platform/Windows/PAL_windows.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_aarch64.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
Labels: needs-sig

#18198 Cherrypick from stab to dev - Fixes script-only "Quickstart" mode. (#18189)
  Templates/ScriptOnlyProject/Template/package.sh
  cmake/Platform/Common/Install_common.cmake
Labels: sig/build

#18193 Cherry-pick from stab to dev - Fix several selection and focus related issues for the Asset Browser.…
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserWindow.cpp
  Code/Editor/QtUtil.h
  Code/Editor/Viewport.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderTableView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Favorites/AssetBrowserFavoritesView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Favorites/AssetBrowserFavoritesView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTreeView.h
Labels: sig/content

#18173 Multi-device masks for Images and Buffers
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/Bits.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Buffer.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferPool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceBufferPool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceImagePool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceStreamingImagePool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Image.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ImagePool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineLibrary.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/StreamingImagePool.h
  Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp
  Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceShaderResourceGroup.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameAttachment.cpp
  Gems/Atom/RHI/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImagePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/ResourcePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/Code/Tests/FrameGraphTests.cpp
Labels: needs-sig

#18220 Export Button Fixes
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectExportWorker.cpp
  scripts/o3de/o3de/export_project.py
Labels: needs-sig

#18218 Bugfix for uninitialized variable.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h
Labels: needs-sig

#17886 Setting wildcard paths in engine dependencies xml files to SourceFiles
  Gems/LmbrCentral/Code/Source/Builders/CopyDependencyBuilder/XmlBuilderWorker/XmlBuilderWorker.cpp
Labels: sig/core

#18221 Add option to set a default buffer/image view for transient buffer/image attachments
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/UnifiedAttachmentDescriptor.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/UnifiedAttachmentDescriptor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/PassAttachmentReflect.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassAttachmentReflect.cpp
Labels: sig/graphics-audio

#18209 Allow to disable mouse capture in Editor
  Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.cpp
Labels: sig/simulation

#18219 Add Pass::ChangeConnection.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Tests/Pass/PassTests.cpp
Labels: needs-sig

#18215 Prevent crash when articulation is created without Physics Scene
  Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
Labels: sig/simulation

#18206 feat: remove unused class ImageUtil
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Include/IImageUtil.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/Util/ImageUtil.cpp
  Code/Editor/Util/ImageUtil.h
  Code/Editor/Util/ImageUtil_impl.cpp
  Code/Editor/Util/ImageUtil_impl.h
  Code/Editor/editor_core_files.cmake
  Code/Editor/editor_lib_files.cmake
Labels: sig/graphics-audio

#18238 Fixes a crash when actors are in the scene and thumbnailer accesses it.
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Labels: sig/graphics-audio

#18213 feat: remove CreateQMimeData from IEditor
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Gems/LyShine/Code/Editor/HierarchyClipboard.cpp
Labels: needs-sig

#18216 bugfix - Fixes crash on close of AssetEditor when you click "save"
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
Labels: sig/content

#18253 Adjusment to error message with incompatible components activation
  Code/Framework/AzCore/AzCore/Component/Entity.cpp
Labels: needs-sig, sig/core

#18257 Fixes crash on close of Asset AssetEditor (#18216)
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
Labels: sig/content

#18254 Adjust DiffuseProbeGrid to prevent multiple SRG compilations
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBlendDistancePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBlendIrradiancePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBorderUpdatePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridClassificationPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridPreparePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRelocationPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRenderPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationPreparePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationRayTracingPass.cpp
Labels: needs-sig, sig/graphics-audio

#17748 Remove bad check for RPI::Image to return an AssetID.
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Material/MaterialComponentController.cpp
Labels: sig/graphics-audio

#18269 remove an extraneous include
  Code/Framework/AzCore/AzCore/Serialization/Json/JsonSerializationMetadata.inl
Labels: needs-sig

#18249 Fix asset browser freeze and crash when repeatedly searching.
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
Labels: sig/content
