Repository o3de/o3de, pull requests merged in 2024-10, with the labels that each got.

#18356 Cherry Pick: Fix hyper-sensitive camera rotation remote clients (#18354)
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
  Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
Labels: sig/core

#18366 Fix crash after leaving picking mode
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
Labels: sig/content

#18339 Added model change event listener to AtomActorInstance
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.cpp
  Gems/AtomLyIntegration/EMotionFXAtom/Code/Source/AtomActorInstance.h
Labels: needs-sig

#18370 Multiplayer Component Registration: Compile Time Check for Duplicates
  Gems/Multiplayer/Code/Include/Multiplayer/AutoGen/AutoComponentTypes_Source.jinja
Labels: needs-sig

#18082 Fixed flipped normals in Sponza
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_arch.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_background.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_bricks.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_ceiling.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_chain.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_columna.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_columnb.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_columnc.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_curtainblue.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_curtaingreen.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_curtainred.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_details.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_fabricblue.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_fabricgreen.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_fabricred.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_flagpole.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_floor.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_leaf.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_lion.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_vase.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_vasehanging.material
  AutomatedTesting/Gem/Sponza/Assets/objects/sponza_mat_vaseround.material
Labels: sig/content

#18347 DiffuseProbeGridVisualizationAccelerationStructurePass header missing forward declaration
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationAccelerationStructurePass.h
Labels: needs-sig

#18374 Fix issue where transient attachments are recreated
  Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp
Labels: needs-sig

#18362 Make googletest a source dependency instead of a 3rd-party package
  Code/Framework/AzCore/CMakeLists.txt
  Code/Framework/AzTest/CMakeLists.txt
  Code/Framework/AzToolsFramework/CMakeLists.txt
  Code/Tools/AzTestRunner/CMakeLists.txt
  cmake/3rdParty/Platform/Android/BuiltInPackages_android.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_aarch64.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
  cmake/3rdParty/Platform/iOS/BuiltInPackages_ios.cmake
Labels: sig/core, sig/testing

#18265 Harmonize ComputePassData and RayTracingPassData Field Names
  Gems/Atom/Feature/Common/Assets/Passes/BRDFTexture.pass
  Gems/Atom/Feature/Common/Assets/Passes/BlendColorGradingLuts.pass
  Gems/Atom/Feature/Common/Assets/Passes/BloomDownsample.pass
  Gems/Atom/Feature/Common/Assets/Passes/CheckerboardResolveColor.pass
  Gems/Atom/Feature/Common/Assets/Passes/ChromaticAberration.pass
  Gems/Atom/Feature/Common/Assets/Passes/ContrastAdaptiveSharpening.pass
  Gems/Atom/Feature/Common/Assets/Passes/DebugRayTracingPass.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthDownsample.pass
  Gems/Atom/Feature/Common/Assets/Passes/DepthOfFieldWriteFocusDepthFromGpu.pass
  Gems/Atom/Feature/Common/Assets/Passes/DownsampleLuminanceMinAvgMaxCS.pass
  Gems/Atom/Feature/Common/Assets/Passes/DownsampleMinAvgMaxCS.pass
  Gems/Atom/Feature/Common/Assets/Passes/DownsampleSinglePassLuminance.pass
  Gems/Atom/Feature/Common/Assets/Passes/EyeAdaptation.pass
  Gems/Atom/Feature/Common/Assets/Passes/FilmGrain.pass
  Gems/Atom/Feature/Common/Assets/Passes/FullscreenShadow.pass
  Gems/Atom/Feature/Common/Assets/Passes/LuminanceHistogramGenerator.pass
  Gems/Atom/Feature/Common/Assets/Passes/OpaqueParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/PaniniProjection.pass
  Gems/Atom/Feature/Common/Assets/Passes/ReflectionScreenSpaceRayTracing.pass
  Gems/Atom/Feature/Common/Assets/Passes/SkyVolumeLUT.pass
  Gems/Atom/Feature/Common/Assets/Passes/SsaoCompute.pass
  Gems/Atom/Feature/Common/Assets/Passes/SsaoParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/Taa.pass
  Gems/Atom/Feature/Common/Assets/Passes/Vignette.pass
  Gems/Atom/Feature/Common/Assets/Passes/WhiteBalance.pass
  Gems/Atom/Feature/Common/Assets/Shaders/SkyAtmosphere/SkyVolumeLUT.azsl
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPassData.h
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
Labels: sig/graphics-audio

#18402 Cherry pick two test crash fixes into the 2409.1 point release
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
  Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
Labels: sig/network, sig/graphics-audio

#18389 Cherrypick stab to dev 03
  Code/Editor/splashscreen_background.png
  Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp
  Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.h
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.h
  Code/Framework/AzFramework/Platform/Linux/AzFramework/AzFramework_Traits_Linux.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
Labels: sig/release

#18289 feat: remove ILogFile interface from IEditor
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Include/ILogFile.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/LogFileImpl.cpp
  Code/Editor/LogFileImpl.h
  Code/Editor/LogFile_mac.mm
  Code/Editor/Platform/Mac/platform_mac_files.cmake
  Code/Editor/Undo/Undo.cpp
  Code/Editor/Undo/Undo.h
  Code/Editor/Util/MemoryBlock.cpp
  Code/Editor/editor_lib_files.cmake
Labels: sig/core

#18211 feat: remove unused code from IEditor
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/Settings.h
  Code/Editor/Viewport.cpp
Labels: sig/content

#17909 feat: migrate GetValue SetValue (GHI-1933)
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
  Code/Editor/TrackView/TrackViewPythonFuncs.cpp
  Code/Legacy/CryCommon/IMovieSystem.cpp
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimPostFXNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp
  Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h
Labels: sig/content

#18414 Fixes the installer breakage by googletest
  Code/Framework/AzTest/CMakeLists.txt
Labels: sig/build

#18399 Extend Pass functionality to improve inserting passes.
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
Labels: needs-sig

#18391 Fix for Vulkan validation error when subpassMergeFeedback is not supported.
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: needs-sig

#18396 Installer fixes for point-release
  cmake/Platform/Windows/Packaging/BootstrapperTheme.wxl.in
  cmake/Platform/Windows/Packaging/PostInstallSetup.wxs
Labels: sig/build, triage/accepted

#18418 Cherrypick from pointRelease branch to dev branch - Fixes script-only mode on Windows
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.h
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  cmake/Platform/Common/MSVC/Configurations_msvc.cmake
  cmake/Platform/Common/Toolchain_scriptonly_common.cmake
  cmake/Platform/Windows/Configurations_windows.cmake
  cmake/Platform/Windows/PAL_windows.cmake
Labels: sig/build

#18428 Address various mobile fixes in the 24.09 release
  Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/AzslcHeader.azsli
  Gems/Atom/Asset/Shader/Code/AZSL/Platform/iOS/Metal/AzslcHeader.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/BicubicPcfFilters.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli
  Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
Labels: needs-sig

#18425 Fix leaking of Decal textures when reloading levels
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/IndexableList.h
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
Labels: needs-sig
