Repository o3de/o3de, pull requests merged in 2024-06, with the labels that each got.

#18003 Fixes a refresh issue with sliders in the DPE
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals_Impl.h
Labels: kind/bug, sig/content

#17978 feat: remove legacy cry object
  Code/Editor/AnimationContext.cpp
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEditDoc.cpp
  Code/Editor/EditorToolsApplication.cpp
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Editor/ErrorReport.cpp
  Code/Editor/ErrorReport.h
  Code/Editor/ErrorReportDialog.cpp
  Code/Editor/ErrorReportDialog.h
  Code/Editor/ErrorReportTableModel.cpp
  Code/Editor/GameEngine.cpp
  Code/Editor/GameResourcesExporter.cpp
  Code/Editor/GameResourcesExporter.h
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Include/HitContext.h
  Code/Editor/Include/IDisplayViewport.h
  Code/Editor/Include/IErrorReport.h
  Code/Editor/Include/IObjectManager.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/MainWindow.cpp
  Code/Editor/Objects/BaseObject.cpp
  Code/Editor/Objects/BaseObject.h
  Code/Editor/Objects/ClassDesc.h
  Code/Editor/Objects/EntityObject.cpp
  Code/Editor/Objects/EntityObject.h
  Code/Editor/Objects/ObjectLoader.cpp
  Code/Editor/Objects/ObjectLoader.h
  Code/Editor/Objects/ObjectManager.cpp
  Code/Editor/Objects/ObjectManager.h
  Code/Editor/Objects/ObjectManagerLegacyUndo.cpp
  Code/Editor/Objects/ObjectManagerLegacyUndo.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/PythonEditorFuncs.cpp
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewAnimNode.h
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.h
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Editor/TrackView/TrackViewSequence.cpp
  Code/Editor/TrackView/TrackViewSequenceManager.cpp
  Code/Editor/Undo/Undo.cpp
  Code/Editor/Util/FileUtil.cpp
  Code/Editor/Viewport.cpp
  Code/Editor/Viewport.h
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/editor_lib_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntityObjectBus.h
  Gems/LyShine/Code/Editor/Animation/AnimationContext.cpp
  Gems/LyShine/Code/Editor/Animation/UiAVSequenceProps.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewAnimNode.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewAnimNode.h
  Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.cpp
  Gems/Maestro/Code/Source/Components/EditorSequenceComponent.cpp
Labels: sig/content, sig/core

#17559 fix python exceptions raised when a test case fails
  Tools/LyTestTools/ly_test_tools/cli/codeowners_hint.py
  Tools/LyTestTools/ly_test_tools/o3de/asset_processor.py
Labels: sig/testing

#18012 Fix validation warnings due to incorrect buffer bind flags for the AABB staging buffer when building a BLAS with procedural geometry
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingBufferPools.h
  Gems/Atom/RHI/Code/Source/RHI/RayTracingBufferPools.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBufferPools.h
Labels: sig/graphics-audio

#17998 O3DE Docker support
  Docker/Dockerfile
  Docker/README.md
  Docker/build.sh
  Docker/entrypoint.sh
Labels: sig/build

#17992 Enabling get_python.sh to work on windows git bash.
  python/get_python.sh
  python/python.sh
Labels: sig/core

#18005 Fix ESM Shadow and LinearDepth for Projected light shadow.
  Gems/Atom/Feature/Common/Assets/Passes/DepthExponentiation.pass
  Gems/Atom/Feature/Common/Assets/Passes/EsmShadowmaps.pass
  Gems/Atom/Feature/Common/Assets/Passes/ShadowParent.pass
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ESM.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/ProjectedShadow.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/Shadow.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/CoreLights/ViewSrg.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Shadow/DepthExponentiation.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Shadow/KawaseShadowBlur.azsl
  Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/EsmShadowmapsPass.h
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/Math.azsli
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/EditorAreaLightComponent.cpp
Labels: sig/graphics-audio

#18036 Add fallback implementation for the ProceduralGeometryIntersectionAttributes struct if float16 is not supported by the RHI
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingIntersectionAttributes.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.shader
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHIUtils.h
  Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/DebugDraw/Assets/Shaders/ObbIntersection.azsl
  Gems/DebugDraw/Assets/Shaders/ObbIntersection.shader
  Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl
  Gems/DebugDraw/Assets/Shaders/SphereIntersection.shader
  Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.cpp
Labels: sig/graphics-audio

#18030 Add missing "SetProceduralGeometryMaterial" method to RayTracingFeatureProcessor
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Labels: sig/graphics-audio

#18032 Extended occlusion request bus interface with functions for volume to volume queries
  Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp
  Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
Labels: sig/graphics-audio

#18014 Cherrypick bugfix from stab to dev - Fixes a refresh issue with sliders in the DPE (#18003)
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/SliderCombo.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyDoubleSliderCtrl.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals_Impl.h
Labels: sig/content

#18006 Development: MiniAudio: Set the default playback volume to 100%
  Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponentConfig.h
Labels: sig/graphics-audio

#18037 Ensure Project Manager properly deletes restricted project folder when needed
  Code/Tools/ProjectManager/Source/ProjectInfo.h
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
Labels: sig/content

#18039 Cherry-pick to development: Add fallback implementation for the ProceduralGeometryIntersectionAttributes struct if float16 is not supported by the RHI
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingIntersectionAttributes.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.shader
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/DeviceFeatures.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHIUtils.h
  Gems/Atom/RHI/Code/Source/RHI/RHIUtils.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/DebugDraw/Assets/Shaders/ObbIntersection.azsl
  Gems/DebugDraw/Assets/Shaders/ObbIntersection.shader
  Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl
  Gems/DebugDraw/Assets/Shaders/SphereIntersection.shader
  Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.cpp
Labels: sig/graphics-audio

#18021 Stabilization: MiniAudio: Set the default playback volume to 100%
  Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponentConfig.h
Labels: sig/graphics-audio

#17966 Change default disk type to gp3
  scripts/build/bootstrap/incremental_build_util.py
Labels: sig/build

#17994 feat: remove legacy perforce plugin
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Include/ISourceControl.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/MainStatusBar.cpp
  Code/Editor/MainStatusBar.h
  Code/Editor/MainStatusBarItems.h
  Code/Editor/MainWindow.cpp
  Code/Editor/Plugins/CMakeLists.txt
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/UI/AssetCatalogModel.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterDocument.cpp
  Code/Editor/Plugins/PerforcePlugin/CMakeLists.txt
  Code/Editor/Plugins/PerforcePlugin/PerforcePlugin.cpp
  Code/Editor/Plugins/PerforcePlugin/PerforcePlugin.h
  Code/Editor/Plugins/PerforcePlugin/PerforceSourceControl.cpp
  Code/Editor/Plugins/PerforcePlugin/PerforceSourceControl.h
  Code/Editor/Plugins/PerforcePlugin/Platform/Linux/PAL_linux.cmake
  Code/Editor/Plugins/PerforcePlugin/Platform/Mac/PAL_mac.cmake
  Code/Editor/Plugins/PerforcePlugin/Platform/Windows/PAL_windows.cmake
  Code/Editor/Plugins/PerforcePlugin/main.cpp
  Code/Editor/Plugins/PerforcePlugin/perforceplugin_files.cmake
  Code/Editor/Util/FileUtil.cpp
  Code/Editor/editor_lib_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceSettings.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceSettings.h
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceSettings.ui
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/SourceControlAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/AudioSystem/Code/Source/Editor/AudioControlsWriter.cpp
  Gems/LyShine/Code/Editor/FileHelpers.cpp
Labels: sig/core

#18055 Revert "Fix permission issues in docker container for the installed o3de (#18047)"
  Docker/entrypoint.sh
Labels: sig/platform

#18041 feat: remove Editor Util Math
  Code/Editor/EditorDefs.h
  Code/Editor/Util/Math.h
  Code/Editor/ViewPane.cpp
  Code/Editor/Viewport.cpp
  Code/Editor/ViewportTitleDlg.cpp
  Code/Editor/editor_lib_files.cmake
  Code/Framework/AzCore/AzCore/Math/MathUtils.h
Labels: sig/core

#17990 feat: remove unused logic that references VertexFormat
  Code/Legacy/CryCommon/IRenderer.h
  Gems/ImGui/Code/Source/ImGuiManager.h
Labels: sig/core, sig/graphics-audio

#17923 feat: remove sync track to and from scene and back to track nodes
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewAnimNode.h
  Code/Editor/TrackView/TrackViewDialog.cpp
  Code/Editor/TrackView/TrackViewDialog.h
  Code/Editor/TrackView/TrackViewNode.h
  Code/Editor/TrackView/TrackViewSequence.cpp
  Code/Editor/TrackView/TrackViewSequence.h
  Code/Editor/TrackView/TrackViewTrack.cpp
  Code/Editor/TrackView/TrackViewTrack.h
  Code/Editor/TrackView/TrackViewUndo.cpp
  Code/Editor/TrackView/TrackViewUndo.h
  Code/Editor/editor_lib_files.cmake
  Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.h
  Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.h
Labels: sig/content

#17910 feat: minor refactor trackview tracknodes icons
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Editor/TrackView/TrackViewNodes.h
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.h
Labels: feature/trackview, sig/content

#18066 Fix nounity-build on Windows
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuteGroupMerged.cpp
Labels: sig/graphics-audio

#17911 feat: remove ifdefed logic releated to CEntityObject
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewNodes.h
  Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewSequence.h
Labels: sig/content
