Repository o3de/o3de, pull requests merged in 2024-04, with the labels that each got.

#17654 Shadow culling outside view frustum
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/FeatureProcessor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
Labels: sig/graphics-audio, priority/major

#17710 Fix Physics Material Assets in PhysXCommon to be processed in the AssetProcessor
  Gems/PhysX/Common/CMakeLists.txt
  cmake/Gems.cmake
Labels: sig/simulation

#17589 Python utils text
  Gems/EditorPythonBindings/Code/Include/EditorPythonBindings/PythonCommon.h
  Gems/EditorPythonBindings/Code/Include/EditorPythonBindings/PythonUtility.h
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonActionManagerHandler.cpp
  Gems/EditorPythonBindings/Code/Source/ActionManager/PythonEditorAction.h
  Gems/EditorPythonBindings/Code/Source/PythonLogSymbolsComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonLogSymbolsComponent.h
  Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonMarshalComponent.h
  Gems/EditorPythonBindings/Code/Source/PythonProxyBus.cpp
  Gems/EditorPythonBindings/Code/Source/PythonProxyBus.h
  Gems/EditorPythonBindings/Code/Source/PythonProxyObject.cpp
  Gems/EditorPythonBindings/Code/Source/PythonProxyObject.h
  Gems/EditorPythonBindings/Code/Source/PythonReflectionComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonReflectionComponent.h
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
  Gems/EditorPythonBindings/Code/Source/PythonTypeCasters.h
  Gems/EditorPythonBindings/Code/Source/PythonUtility.cpp
  Gems/EditorPythonBindings/Code/Tests/CustomTypeBindingBusTests.cpp
  Gems/EditorPythonBindings/Code/Tests/EditorPythonBindingsTest.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonAssetTypesTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonAssociativeTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonBindingLibTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonContainerAnyTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonDictionaryTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonGlobalsTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonLogSymbolsComponentTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonPairTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonPairTests.h
  Gems/EditorPythonBindings/Code/Tests/PythonProxyBusTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonProxyObjectTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonReflectionComponentTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonThreadingTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonTupleTests.cpp
  Gems/EditorPythonBindings/Code/editorpythonbindings_common_files.cmake
Labels: sig/content

#17751 [Cherry-Pick] DPE | Prevent crash on multi-edit when back of the patch is not an index.
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/AggregateAdapter.cpp
Labels: sig/content

#17713 feat: remove EditorContextMenuBus supersede by ActionManagerInterface
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ContextMenuHandlers.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Editor/EditorContextMenuBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Viewport/EditorContextMenu.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorTransformComponentSelection.h
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Gems/Camera/Code/Source/CameraEditorSystemComponent.cpp
  Gems/Camera/Code/Source/CameraEditorSystemComponent.h
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.cpp
  Gems/Multiplayer/Code/Source/Editor/MultiplayerEditorSystemComponent.h
  Gems/PhysX/Core/Code/Editor/Source/Components/EditorSystemComponent.cpp
  Gems/PhysX/Core/Code/Editor/Source/Components/EditorSystemComponent.h
  Gems/ScriptCanvas/Code/Editor/SystemComponent.h
Labels: sig/network, sig/simulation

#17677 Introduce a multi-device DispatchRaysIndirectBuffer
  Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchRaysIndirectBuffer.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceDispatchRaysItem.h
  Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
Labels: sig/graphics-audio

#17633 Support for templated level creation
  Assets/Editor/Prefabs/Basic.png
  Assets/Editor/Prefabs/Basic.prefab
  Assets/Editor/Prefabs/Default_Level.png
  Assets/Editor/Prefabs/Empty.png
  Assets/Editor/Prefabs/Empty.prefab
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/CryEditPy.cpp
  Code/Editor/EditorToolsApplication.cpp
  Code/Editor/EditorToolsApplication.h
  Code/Editor/EditorToolsApplicationAPI.h
  Code/Editor/NewLevelDialog.cpp
  Code/Editor/NewLevelDialog.h
  Code/Editor/NewLevelDialog.qrc
  Code/Editor/NewLevelDialog.ui
  Code/Editor/editor_lib_files.cmake
  Code/Editor/res/Prefab_80.svg
  Code/Framework/AzQtComponents/AzQtComponents/Components/Style.cpp
  Registry/level_template.setreg
Labels: sig/content

#17714 Prefabs themselves can be set as Editor Only.
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.ui
Labels: sig/content

#17806 Update Jenkinsfile
  scripts/build/Jenkins/Jenkinsfile
Labels: sig/build

#17804 Fix Gem Dependency checking with dependent gems that include versioning
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/editor_test_helper.py
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/editor/EditorScripts/EditorWorkflow_EditorCameraBeThisCameraIsClearedWhenChangingLevel.py
  AutomatedTesting/Gem/PythonTests/scripting/Debugger_HappyPath_TargetMultipleEntities.py
  cmake/Gems.cmake
Labels: sig/core

#17798 [Cherry-pick] Allow for Entity creation and Prefab instantiation in place via viewport interactions.
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.h
  Code/Editor/ViewManager.cpp
  Code/Editor/ViewManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/EditorMenu.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManager.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ActionManager/Menu/MenuManagerInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabIntegrationManager.cpp
Labels: sig/content

#17796 Fixes in FrameGraph* for backends
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphExecuter.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/FrameGraphExecuter.cpp
Labels: sig/graphics-audio

#17809 Cherrypick PR 17464 from development to point release
  Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp
  Code/Framework/AzToolsFramework/Tests/Input/QtEventToAzInputMapperTests.cpp
Labels: sig/content

#17816 Cherry-pick pull request #17424 from dev to point-release/23103
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbInputDeviceMouse.cpp
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.cpp
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/MockXcbInterface.h
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceMouseTests.cpp
Labels: sig/core

#17813 cherry-pick crashfix part of PR 17664 from dev into point-release/23103
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/Instance.h
Labels: sig/content

#17808 Cherry-pick PR17420 from dev to point-release
  Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
  Gems/ScriptCanvasDeveloper/Code/Include/ScriptCanvasDeveloper/ScriptCanvasDeveloperComponent.h
  Gems/ScriptCanvasDeveloper/Code/Source/ScriptCanvasDeveloperComponent.cpp
Labels: sig/content

#17812 cherry-pick from development to point-release/23103 PR #17594
  cmake/Platform/Common/Install_common.cmake
Labels: sig/build

#17815 cherry-pick from dev to point-release, PR #17697
  Code/Editor/CryEdit.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetEntryChangeset.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
Labels: sig/content

#17794 Windows build script errorlevel fixes
  scripts/build/Platform/Windows/build_windows.cmd
Labels: sig/build

#17811 CHERRY-PICK from dev to point-release/23103 PR #17526
  Code/Framework/AzCore/AzCore/IO/FileIO.h
  Code/Framework/AzCore/Platform/Android/platform_android_files.cmake
  Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/IO/FileIO_UnixLike.cpp
  Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/FileIO_WinAPI.cpp
  Code/Framework/AzCore/Platform/Linux/platform_linux_files.cmake
  Code/Framework/AzCore/Platform/Mac/platform_mac_files.cmake
  Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake
  Code/Framework/AzCore/Platform/iOS/platform_ios_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetUtils.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Code/Tools/AssetProcessor/native/AssetManager/ExcludedFolderCache.cpp
  Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp
  Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/tests/AssetCatalog/AssetCatalogUnitTests.cpp
  Code/Tools/AssetProcessor/native/tests/FileStateCache/FileStateCacheTests.cpp
  Code/Tools/AssetProcessor/native/tests/MissingDependencyScannerTests.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.cpp
  Code/Tools/AssetProcessor/native/tests/UnitTestUtilities.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/utilities/assetUtilsTest.cpp
  Code/Tools/AssetProcessor/native/unittests/UnitTestUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/UuidManager.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
Labels: sig/content, sig/core

#17817 Cherry-pick PR #17568 fromdev to point-release/23103
  Code/Editor/MainStatusBar.cpp
  Code/Editor/Plugins/PerforcePlugin/Platform/Linux/PAL_linux.cmake
  Code/Framework/AzFramework/AzFramework/Asset/AssetProcessorMessages.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetProcessorMessages.h
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemBus.h
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponent.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponent.h
  Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponentHelper.cpp
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Process/ProcessWatcher_Linux.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/SourceControl/PerforceComponent.cpp
  Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp
  Code/Tools/AssetProcessor/native/AssetManager/SourceFileRelocator.cpp
  Code/Tools/AssetProcessor/native/connection/connectionManager.h
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
  Gems/EMotionFX/Code/Tests/Editor/MotionSetLoadEscalation.cpp
Labels: sig/content, sig/core, sig/simulation

#17795 Fixes to virtual device initialization
  Gems/Atom/RHI/Code/Source/RHI/RHISystem.cpp
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/PhysicalDevice_Windows.cpp
Labels: sig/graphics-audio

#17775 Fix sphere intersection attributes not being in object space
  Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl
Labels: sig/content

#17644 Fixing crash with IBL component when the feature processor is not set yet
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ImageBasedLights/ImageBasedLightComponentController.cpp
Labels: sig/graphics-audio

#17766 Request the timeline semaphore extension for Vulkan <1.2
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: sig/graphics-audio
