Repository o3de/o3de, pull requests merged in 2024-05, with the labels that each got.

#17822 Atom/fp16 fixes for quest
  Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/AzslcHeader.azsli
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/MatrixUtility.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Microfacet/Brdf.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Microfacet/Ggx.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/ParallaxMapping.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_LightingData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_PixelGeometryData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_SurfaceEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_PixelGeometryData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_SurfaceEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_PixelGeometryData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_PixelGeometryEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_SurfaceEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialFunctions/EvaluateTangentFrame.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialFunctions/MultilayerParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialFunctions/ParallaxDepth.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialFunctions/ParallaxShadowUtil.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/ClearCoatInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/NormalInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/OcclusionInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/ParallaxInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_LightingBrdf.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_LightingEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_PixelGeometryData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_PixelGeometryData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_SurfaceEval.azsli
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/TangentSpace.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/BasePBR/MaterialGraphName_SurfaceEval.azsli
  Gems/Atom/Tools/MaterialCanvas/Assets/MaterialCanvas/GraphData/Nodes/MaterialOutputs/StandardPBR/MaterialGraphName_SurfaceEval.azsli
Labels: sig/graphics-audio

#17850 Fix for ScriptCanvas Upgrade Tool nullptr crash
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Graph.cpp
Labels: sig/content

#17825 feat: remove GameExporter
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEditDoc.cpp
  Code/Editor/GameExporter.cpp
  Code/Editor/GameExporter.h
  Code/Editor/IEditor.h
  Code/Editor/editor_lib_files.cmake
Labels: sig/content

#17868 feat: remove ITransformDelegate from CTrackViewAnimNode
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewAnimNode.h
Labels: sig/content

#17693 Added Linux Console Logging
  Code/Framework/AzCore/AzCore/Debug/Trace.cpp
  Code/Framework/AzCore/AzCore/Debug/Trace.h
  Code/Framework/AzCore/Platform/Linux/AzCore/Debug/Trace_Linux.cpp
  Code/Legacy/CrySystem/Log.cpp
Labels: sig/core

#17854 new: Project manager add project dialog to target project.json instead of any directory
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/UpdateProjectCtrl.cpp
Labels: sig/content

#17858 Update README.md to add links to the roadmap
  README.md
Labels: sig/build, sig/content, sig/core, sig/docs-community, sig/network, sig/platform, sig/graphics-audio, sig/release, sig/security, sig/testing, sig/ui-ux, sig/operations, sig/simulation

#17848 feat: add visiblity toggle for MeshComponent (GHI-17832)
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
Labels: sig/graphics-audio

#17881 Fixing bug where if a view had multiple pipelines, and …
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/LightCommon.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/LightCommon.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/SimplePointLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/SimplePointLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/SimpleSpotLightFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/SimpleSpotLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.h
Labels: sig/graphics-audio

#17863 Print Warning When Using Legacy Asset IDs
  Code/Framework/AzFramework/AzFramework/Asset/AssetCatalog.cpp
  Code/Framework/AzFramework/AzFramework/Asset/AssetRegistry.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
Labels: sig/content

#17719 Set different max path lenghts for the different platforms
  Code/Tools/AssetProcessor/Platform/Linux/AssetProcessor_Traits_Linux.h
  Code/Tools/AssetProcessor/Platform/Mac/AssetProcessor_Traits_Mac.h
  Code/Tools/AssetProcessor/Platform/Windows/AssetProcessor_Traits_Windows.h
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
Labels: sig/core, sig/platform, priority/major

#17849 Fix to ScriptCanvas' ExtractProperty failing on Linux when a property is of type int64_t
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Datum.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Data/DataTypeUtils.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/ExtractProperty.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Libraries/Core/FunctionCallNode.h
Labels: sig/content

#17777 feat: remove object manager python reflection and tests
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/TestSuite_Periodic.py
  AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_ObjectManagerCommands_Works.py
  AutomatedTesting/Gem/PythonTests/editor/EditorScripts/EntityOutliner_EntityOrdering.py
  Code/Editor/EditorToolsApplication.cpp
  Code/Editor/Lib/Tests/test_ObjectManagerPythonBindings.cpp
  Code/Editor/Objects/ObjectManager.cpp
  Code/Editor/editor_lib_test_files.cmake
Labels: sig/content

#17823 feat: remove unused interfaces from CryCommon
  Code/Legacy/CryCommon/IMNM.h
  Code/Legacy/CryCommon/IMaterial.h
  Code/Legacy/CryCommon/IPathfinder.h
  Code/Legacy/CryCommon/crycommon_files.cmake
Labels: sig/core

#17782 feat: remove unused CTemplateObjectClassDesc
  Code/Editor/Plugins/ComponentEntityEditorPlugin/ComponentEntityEditorPlugin.cpp
  Code/Editor/QtViewPane.h
  Code/Editor/QtViewPaneManager.cpp
  Code/Editor/QtViewPaneManager.h
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.h
  Code/Editor/editor_core_files.cmake
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ViewPaneOptions.h
  Gems/LyShine/Code/Editor/Animation/UiAnimViewDialog.cpp
  Gems/LyShine/Code/Editor/Animation/UiAnimViewKeyPropertiesDlg.h
Labels: sig/content

#17882 bugfix: partial fix crash when renaming a deleted node (GHI-15048)
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Editor/TrackView/TrackViewSequence.cpp
Labels: feature/trackview, sig/content

#17888 bugfix: resolve rotated entities when adding them to trackview (GHI-14978)
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Legacy/CryCommon/IMovieSystem.cpp
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/Maestro/Code/Source/Cinematics/AnimAZEntityNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimAZEntityNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimNode.h
Labels: feature/trackview, sig/content

#17889 bugfix: fix ellipsis text for track view close key/undock key (GHI-10817)
  Code/Framework/AzQtComponents/AzQtComponents/Components/DockTabBar.cpp
Labels: feature/trackview, sig/content

#17885 Linux installer improvements
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Linux/Install_linux.cmake
  cmake/Platform/Linux/Packaging/postinst.in
  cmake/Platform/Linux/Packaging/postrm.in
  cmake/Platform/Linux/Packaging_Snapcraft.cmake
  cmake/Platform/Linux/runtime_dependencies_linux.cmake.in
Labels: sig/build, sig/platform

#17709 feat: remove unused Viewport cvar from ObjectManager
  Code/Editor/IEditorImpl.cpp
  Code/Editor/Include/IObjectManager.h
  Code/Editor/Objects/ObjectManager.cpp
  Code/Editor/Objects/ObjectManager.h
Labels: sig/content

#17851 Reformat of the Asset Processor Metrics column
  Code/Tools/AssetProcessor/native/ui/BuilderInfoMetricsModel.cpp
Labels: sig/content

#17837 Fix Clang-17 compile error about enum-constexpr-conversion on Windows
  Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp
Labels: sig/graphics-audio

#17774 Extract ring buffer handling for RT buffers to separate class
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/FrameCountMaxRingBuffer.h
  Gems/Atom/RHI/Code/atom_rhi_reflect_files.cmake
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingShaderTable.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingShaderTable.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingTlas.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingShaderTable.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingShaderTable.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingTlas.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/RingBuffer.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/DynamicDraw/DynamicBufferAllocator.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/RPISystemDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/RingBuffer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicBufferAllocator.cpp
  Gems/Atom/RPI/Code/atom_rpi_public_files.cmake
  Gems/Atom/RPI/Registry/atom_rpi.setreg
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.h
Labels: sig/graphics-audio

#17716 feat: standardized math test cases for EmotionFX
  Gems/EMotionFX/Code/Tests/EmotionFXMathLibTests.cpp
Labels: sig/simulation

#17632 initialize the transform for static camera-components properly
  Gems/Camera/Code/Source/CameraComponentController.cpp
Labels: sig/graphics-audio

#17841 [Lua Editor] Fix Lua Editor not handling load and save of the settings dialog
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/LegacyFramework/Core/EditorFrameworkApplication.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorSettingsDialog.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorSettingsDialog.hxx
  Code/Tools/LuaIDE/Source/LUA/LUAEditorSettingsDialog.ui
Labels: sig/content

#17879 Partial fix for Script Canvas Debugger feature
  Code/Framework/AzFramework/AzFramework/Network/IRemoteTools.h
  Code/Framework/AzFramework/AzFramework/Network/IRemoteTools.inl
  Code/Framework/AzFramework/AzFramework/Script/ScriptDebugMsgReflection.cpp
  Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
  Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.h
  Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingDataAggregator.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/ClientTransceiver.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/ClientTransceiver.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/RuntimeComponent.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/RuntimeComponent.h
Labels: sig/content

#17884 feat: remove usage of SendEvent for ObjectManager
  Code/Editor/GameEngine.cpp
  Code/Editor/IEditorImpl.cpp
Labels: sig/content

#17807 Allow to instantiate prefab with rotation.
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicInterface.h
Labels: sig/content

#17720 change the error about unused scope attachments to a warning
  Gems/Atom/RHI/Code/Source/RHI/FrameGraph.cpp
Labels: sig/graphics-audio

#17839 Cherrypick pr fixes from pointrelease to development
  Code/Tools/AssetProcessor/native/AssetManager/AssetRequestHandler.cpp
  Code/Tools/AssetProcessor/native/AssetManager/FileStateCache.cpp
Labels: sig/content

#17838 Fixes a flaky test and possible actual crash (cherrypick from point-release to dev)
  Code/Framework/AzCore/AzCore/Component/Entity.cpp
Labels: sig/core

#17874 Cherrypick from point-release to dev - crash fix es
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.h
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.h
Labels: sig/content

#17859 Fix copy queue state hack in dx12
  Gems/Atom/RHI/DX12/Code/Source/RHI/DX12.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Scope.cpp
Labels: sig/graphics-audio

#17903 Update engine.json for 24.09
  engine.json
Labels: sig/build, sig/core

#17914 Support PGM image format in ImageProcessingAtom.
  Gems/Atom/Asset/ImageProcessingAtom/Code/Include/Atom/ImageProcessing/ImageProcessingDefines.h
Labels: sig/content, feature/robotics

#17965 AssetProcessor Analysis Stats
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
Labels: sig/content

#17756 feat: remove unused call GetSandboxObject
  Code/Editor/AnimationContext.cpp
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Editor/Include/HitContext.h
  Code/Editor/Objects/EntityObject.cpp
  Code/Editor/Objects/EntityObject.h
  Code/Editor/Plugins/ComponentEntityEditorPlugin/SandboxIntegration.cpp
  Code/Editor/ViewManager.cpp
  Code/Editor/ViewManager.h
  Code/Editor/ViewPane.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ComponentEntityObjectBus.h
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.h
  Gems/Maestro/Code/Source/Components/EditorSequenceComponent.cpp
Labels: sig/core

#17918 feat: remove legacy cry camera from trackview
  Code/Editor/TrackView/TVCustomizeTrackColorsDlg.cpp
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewAnimNode.h
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Legacy/CryCommon/Maestro/Types/AnimNodeType.h
  Code/Legacy/CryCommon/Maestro/Types/AnimParamType.h
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp
Labels: sig/content, sig/core

#17912 Script canvas logger can now identify graph and entity names
  Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasReporter.h
  Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasReporter.inl
  Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedDebugAPI.cpp
Labels: sig/content

#17908 Revert "feat: add visiblity toggle for MeshComponent"
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h
Labels: sig/content
