Repository o3de/o3de, pull requests merged in 2024-07, with the labels that each got.

#18085 Compile fix for when AZ_FORCE_CPU_GPU_INSYNC is defined.
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphExecuter.cpp
Labels: sig/graphics-audio

#18084 Bugfix for #18068: Device lost on Vulkan when switching levels on AutomatedTesting
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
Labels: sig/graphics-audio

#18075 Expose GetIntensityMode/SetIntensityMode in DirectionalLightBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/CoreLights/DirectionalLightBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/CoreLights/DirectionalLightComponentController.h
Labels: sig/content, sig/graphics-audio

#18094 DO NOT MERGE TO DEV - Makes o3de.git/stabilization/2409 use o3de-extras.git/stabilization/2409
  .automatedtesting.json
Labels: sig/build

#18103 Fix nounity-build on Windows
  Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderUtils.cpp
Labels: sig/graphics-audio

#18056 Fix several issues with importing actor assets
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.h
  Code/Tools/SceneAPI/SceneUI/Handlers/ProcessingHandlers/AsyncOperationProcessingHandler.cpp
  Code/Tools/SceneAPI/SceneUI/Handlers/ProcessingHandlers/AsyncOperationProcessingHandler.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MorphTargetExporter.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
Labels: sig/content

#18119 cherry-pick from stabilization - Fix several issues with importing actor assets (#18056)
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.cpp
  Code/Editor/Plugins/EditorAssetImporter/AssetImporterWindow.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorComponentBase.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.cpp
  Code/Tools/SceneAPI/SceneCore/Utilities/DebugOutput.h
  Code/Tools/SceneAPI/SceneUI/Handlers/ProcessingHandlers/AsyncOperationProcessingHandler.cpp
  Code/Tools/SceneAPI/SceneUI/Handlers/ProcessingHandlers/AsyncOperationProcessingHandler.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MorphTargetExporter.cpp
  Gems/SceneProcessing/Code/Source/SceneBuilder/SceneBuilderWorker.cpp
Labels: sig/content, sig/graphics-audio

#18093 Add option to disable creating a native window for game launchers
  Code/Framework/AzCore/AzCore/Component/ComponentApplicationBus.h
  Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.cpp
  Code/Framework/AzGameFramework/AzGameFramework/Application/GameApplication.cpp
  Code/Framework/AzGameFramework/AzGameFramework/Application/GameApplication.h
  Code/LauncherUnified/Launcher.cpp
  Code/LauncherUnified/Launcher.h
  Code/LauncherUnified/Platform/Android/Launcher_Traits_Android.h
  Code/LauncherUnified/Platform/Linux/Launcher_Traits_Linux.h
  Code/LauncherUnified/Platform/Mac/Launcher_Traits_Mac.h
  Code/LauncherUnified/Platform/Windows/Launcher_Traits_Windows.h
  Code/LauncherUnified/Platform/iOS/Launcher_Traits_iOS.h
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
Labels: needs-sig, sig/simulation

#18091 Fix multi-threaded creation of PipelineStates in PipelineStateCache
  Gems/Atom/RHI/Code/Include/Atom/RHI/PipelineState.h
  Gems/Atom/RHI/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/Code/Source/RHI/PipelineStateCache.cpp
Labels: needs-sig

#17970 Updates for Ubuntu 24.04 support
  scripts/build/Platform/Linux/build_config.json
  scripts/build/build_node/Platform/Linux/install-ubuntu-build-tools.sh
  scripts/build/build_node/Platform/Linux/install-ubuntu-git.sh
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-noble.txt
Labels: sig/build, sig/platform

#18131 OcclusionBus improved support for culling by entity ID
  Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp
  Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Labels: needs-sig

#18102 Implement "Debug Ray Tracing" component
  Gems/Atom/Feature/Common/Assets/Passes/DebugRayTracingPass.pass
  Gems/Atom/Feature/Common/Assets/Passes/PassTemplates.azasset
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSrgs.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugClosestHit.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugClosestHit.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugClosestHitProcedural.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugClosestHitProcedural.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugCommon.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugMiss.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugMiss.shader
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugRayGeneration.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugRayGeneration.shader
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Debug/RayTracingDebugConstants.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Debug/RayTracingDebugFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Debug/RayTracingDebugParams.inl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Debug/RayTracingDebugSettingsInterface.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Debug/RayTracingDebugSettings.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Debug/RayTracingDebugBus.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/Debug/RayTracingDebugComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponentController.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugComponentController.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugEditorComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugEditorComponent.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Module.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_editor_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_files.cmake
  Gems/AtomLyIntegration/CommonFeatures/Code/atomlyintegration_commonfeatures_public_files.cmake
  Gems/DebugDraw/Assets/Shaders/ObbIntersection.azsl
  Gems/DebugDraw/Assets/Shaders/SphereIntersection.azsl
Labels: sig/graphics-audio

#18126 Pass on `Name` to DeviceObjects
  Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h
  Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/Fence.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImagePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/IndirectBufferSignature.cpp
  Gems/Atom/RHI/Code/Source/RHI/MultiDeviceObject.cpp
  Gems/Atom/RHI/Code/Source/RHI/PipelineLibrary.cpp
  Gems/Atom/RHI/Code/Source/RHI/PipelineState.cpp
  Gems/Atom/RHI/Code/Source/RHI/QueryPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingBufferPools.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingShaderTable.cpp
  Gems/Atom/RHI/Code/Source/RHI/ResourcePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp
Labels: needs-sig

#18133 Moving the device mask to ResourcePoolDescriptor.
  Gems/Atom/Feature/Common/Code/Source/ACES/AcesDisplayMapperFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbeFeatureProcessor.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/ResourcePoolDescriptor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferPool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ImagePool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/QueryPool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ShaderResourceGroupPool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/StreamingImagePool.h
  Gems/Atom/RHI/Code/Source/RHI/BufferPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImagePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/QueryPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/Code/Tests/FrameGraphTests.cpp
  Gems/Atom/RHI/Code/Tests/FrameSchedulerTests.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceBufferTests.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceImageTests.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceIndirectBufferTests.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceQueryTests.cpp
  Gems/Atom/RHI/Code/Tests/MultiDeviceShaderResourceGroupTests.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/BufferPool.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/BufferSystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/AttachmentImagePool.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/ImageSystem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImagePool.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/BufferPool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/BufferSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/QueryPool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImagePool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/ImageSystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImagePool.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/RPISystem.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Shader/ShaderResourceGroupPool.cpp
  Gems/AtomTressFX/Code/Rendering/HairCommon.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/GradientSignal/Code/Tests/GradientSignalTestFixtures.cpp
  Gems/Terrain/Code/Tests/TerrainTestFixtures.cpp
Labels: sig/graphics-audio

#18148 Bugfix for generating Buffer Barriers in Vulkan for Transient Attachments
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/AliasedHeap.cpp
Labels: needs-sig

#18149 Fix a crash if a RPI::Buffer is destroyed during upload
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Buffer/Buffer.h
Labels: needs-sig

#18147 Cherry picking occlusion request bus updates from development branch
  Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.cpp
  Code/Framework/AzFramework/AzFramework/Visibility/OcclusionBus.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Culling.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Culling.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.cpp
Labels: needs-sig

#17925 libxcb-image0-dev and xxd added to dependencies of build nodes
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-jammy.txt
Labels: sig/build

#18140 Fix Scope linkage for Scopes running on different devices.
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferFrameAttachment.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/FrameAttachment.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/FrameGraphAttachmentDatabase.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ImageFrameAttachment.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Resource.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/TransientAttachmentPool.h
  Gems/Atom/RHI/Code/Source/RHI/BufferFrameAttachment.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameAttachment.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraph.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphLogger.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImageFrameAttachment.cpp
  Gems/Atom/RHI/Code/Source/RHI/Resource.cpp
  Gems/Atom/RHI/Code/Source/RHI/ShaderResourceGroupData.cpp
  Gems/Atom/RHI/Code/Source/RHI/TransientAttachmentPool.cpp
  Gems/Atom/RHI/Code/Tests/FrameGraphTests.cpp
  Gems/Atom/RHI/Code/Tests/Scope.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/Buffer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiFrameVisualizer.inl
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainDetailMaterialManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMacroMaterialManager.cpp
Labels: needs-sig

#18138 Increase multiplayer AR Test timeout
  AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
Labels: sig/network

#18159 Implicitly multi-device RayTracingAccelerationStructurePass
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Labels: needs-sig

#18172 Fix nounity-build on Windows
  Gems/Atom/RHI/DX12/Code/Source/RHI/FrameGraphCompiler.cpp
Labels: sig/graphics-audio

#18077 Cherrypick from stabilization to dev - Fix unparent prefab entities (#18073)
  Code/Framework/AzCore/AzCore/Serialization/EditContextConstants.inl
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEntityIdCtrl.hxx
Labels: sig/content, sig/core

#18164 Fixes a crash in test LevelEntityComponentCRUD test
  Code/Editor/NewLevelDialog.cpp
Labels: sig/content, sig/testing
