Repository o3de/o3de, pull requests merged in 2024-12, with the labels that each got.

#18465 Fix: add if check to remove left project buttons when projects.isEmpty()
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
Labels: sig/content

#18504 DocMenu: Fix broken help links, move AWS doc and remove unused methods from cryedit.h
  Code/Editor/Core/EditorActionsHandler.cpp
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Gems/AWSCore/Code/Source/Editor/Constants/AWSCoreEditorMenuNames.h
  Gems/AWSCore/Code/Source/Editor/UI/AWSCoreEditorMenu.cpp
Labels: kind/documentation, sig/docs-community

#18487 Fixes memory corruption issues in ArchiveAPI
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
  Code/Framework/AzFramework/AzFramework/Archive/ZipDirStructures.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Archive/ArchiveComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Archive/ArchiveComponent.h
  Code/Framework/AzToolsFramework/Tests/ArchiveTests.cpp
  Code/Tools/AzTestRunner/src/main.cpp
Labels: sig/core

#18525 Add current dll directory to library search path in LoadLibrary
  Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
Labels: sig/core

#18505 Fix Lua Editor: Only run regex on subset provided by parser instead of entire line
  Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorSyntaxHighlighter.hxx
Labels: feature/scripting, sig/content

#18450 Enable interoperability between rendering backends and other APIs
  Gems/Atom/RHI/Code/Include/Atom/RHI/AliasedAttachmentAllocator.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceFence.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RHIBus.h
  Gems/Atom/RHI/Code/Source/RHI/FrameScheduler.cpp
  Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
  Gems/Atom/RHI/DX12/Code/CMakeLists.txt
  Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Interface/DX12/RHIDX12Interface.h
  Gems/Atom/RHI/DX12/Code/Include/Atom/RHI.Reflect/DX12/DX12Bus.h
  Gems/Atom/RHI/DX12/Code/Source/Platform/Windows/RHI/PhysicalDevice_Windows.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI.Reflect/RHIDX12Interface.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/AliasedHeap.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/BufferD3D12MemoryAllocator.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Fence.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Fence.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/MemoryView.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/MemoryView.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/TransientAttachmentPool.cpp
  Gems/Atom/RHI/DX12/Code/atom_rhi_dx12_interface_common_files.cmake
  Gems/Atom/RHI/Metal/Code/Source/Platform/Mac/RHI/Metal_RHI_Mac.cpp
  Gems/Atom/RHI/Vulkan/Code/CMakeLists.txt
  Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Interface/Vulkan/RHIVulkanInterface.h
  Gems/Atom/RHI/Vulkan/Code/Include/Atom/RHI.Reflect/Vulkan/VulkanBus.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Interface/RHIVulkanInterface.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/AliasedHeap.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferMemory.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferMemory.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/BufferMemoryView.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Fence.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Image.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/MemoryView.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/TimelineSemaphoreFence.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/TransientAttachmentPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/VulkanMemoryAllocation.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/VulkanMemoryAllocation.h
  Gems/Atom/RHI/Vulkan/Code/atom_rhi_vulkan_interface_files.cmake
Labels: sig/graphics-audio

#18503 Don't try to evict mipchain-assets after the image has been shutdown
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Image/StreamingImage.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
Labels: sig/graphics-audio

#18529 ⌨️ Skip stride size assert when binding a typed buffer.
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceShaderResourceGroupData.h
Labels: needs-sig

#18528 AssetProcessorBatch Reflect Fix
  Code/Tools/AssetProcessor/native/utilities/BatchApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
Labels: needs-sig

#18522 Fixed TrackView example Python script
  Assets/Editor/Scripts/TrackView/example.py
Labels: needs-sig

#18527 Homogenization of file opening windows
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
  Gems/LyShine/Code/Editor/EditorMenu.cpp
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
Labels: sig/content

#17924 feat: replace old trackview icons
  Code/Editor/TrackView/AutoRecord.svg
  Code/Editor/TrackView/Loop.svg
  Code/Editor/TrackView/Pause.svg
  Code/Editor/TrackView/PlayBackward.svg
  Code/Editor/TrackView/PlayForward.svg
  Code/Editor/TrackView/RecordButton.svg
  Code/Editor/TrackView/SequenceEnd.svg
  Code/Editor/TrackView/SequenceStart.svg
  Code/Editor/TrackView/Stop.svg
  Code/Editor/TrackView/StopRecorder.svg
  Code/Editor/TrackView/TrackViewDialog.cpp
  Code/Editor/TrackView/TrackViewDialog.qrc
Labels: sig/content

#18524 Add function "Allow pipeline changes" to CameraComponent
  Gems/Camera/Code/Source/CameraComponentController.cpp
  Gems/Camera/Code/Source/CameraComponentController.h
Labels: needs-sig

#18500 Handle multiGPU Passes in ImGui Timestamp View
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
Labels: sig/graphics-audio

#18541 Refactoring the MovieSystem so that it may be moved into a gem
  Code/Editor/AnimationContext.cpp
  Code/Editor/AnimationContext.h
  Code/Editor/CryEditDoc.cpp
  Code/Editor/GameEngine.cpp
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/SelectLightAnimationDialog.cpp
  Code/Editor/SelectSequenceDialog.cpp
  Code/Editor/TrackView/SelectKeyUIControls.cpp
  Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
  Code/Editor/TrackView/SequenceKeyUIControls.cpp
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewDialog.cpp
  Code/Editor/TrackView/TrackViewFindDlg.cpp
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Editor/TrackView/TrackViewPythonFuncs.cpp
  Code/Editor/TrackView/TrackViewSequence.cpp
  Code/Editor/TrackView/TrackViewSequenceManager.cpp
  Code/Legacy/CryCommon/IMovieSystem.cpp
  Code/Legacy/CryCommon/IMovieSystem.h
  Code/Legacy/CryCommon/ISystem.h
  Code/Legacy/CrySystem/LevelSystem/LevelSystem.cpp
  Code/Legacy/CrySystem/LevelSystem/SpawnableLevelSystem.cpp
  Code/Legacy/CrySystem/System.cpp
  Code/Legacy/CrySystem/System.h
  Gems/LyShine/Code/Source/Animation/AnimSplineTrack_Vec2Specialization.cpp
  Gems/Maestro/Code/Include/Maestro/MaestroBus.h
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimSequence.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimSequence.h
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.h
  Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp
  Gems/Maestro/Code/Source/Cinematics/SequenceTrack.cpp
  Gems/Maestro/Code/Source/Components/EditorSequenceComponent.cpp
  Gems/Maestro/Code/Source/Components/SequenceComponent.cpp
  Gems/Maestro/Code/Source/Components/SequenceComponent.h
  Gems/Maestro/Code/Source/MaestroSystemComponent.cpp
Labels: feature/trackview

#18509 Added Compute Shader support in *.MaterialPipeline
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ibl.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/SimpleSpotLight.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_LightingData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Eye/Eye_VertexEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/BaseColorInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/DetailMapsInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/NormalInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/OcclusionInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/RoughnessInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/SpecularInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_VertexEval.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/StreamBufferViewsBuilderInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshInstanceGroupList.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceDrawItem.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceDrawPacket.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchItem.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DrawItem.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DrawPacket.h
  Gems/Atom/RHI/Code/Source/RHI/DrawPacket.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
Labels: sig/graphics-audio

#18540 Fix Lua Editor: greyed out FindAll if no script opened
  Code/Tools/LuaIDE/Source/LUA/LUAEditorFindDialog.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.hxx
Labels: feature/scripting, sig/content

#18485 Introduce Vulkan HOST_CACHED_BIT
  Gems/Atom/RHI/Vulkan/Code/Source/RHI.Reflect/Conversion.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp
Labels: sig/graphics-audio

#18547 Vulkan RHI: Don't expose HDR surface format when SetHDRMetadata is null
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: needs-sig, sig/graphics-audio

#18546 initialize AZ::SerializeContext to nullptr
  Code/Editor/Core/QtEditorApplication.cpp
  Code/Framework/AzCore/AzCore/Serialization/DataPatch.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ComponentMimeData.cpp
  Code/Framework/AzToolsFramework/Tests/AssetFileInfoListComparison.cpp
  Code/Framework/AzToolsFramework/Tests/AssetSeedManager.cpp
  Code/Tools/AssetBundler/source/utils/applicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
  Code/Tools/PythonBindingsExample/source/Application.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/EventDataEditor.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventEditor.cpp
  Gems/EMotionFX/Code/EMotionFX/Tools/EMotionStudio/Plugins/StandardPlugins/Source/MotionEvents/MotionEventPresetCreateDialog.cpp
  Gems/EMotionFX/Code/Source/Editor/Plugins/SimulatedObject/SimulatedObjectWidget.cpp
  Gems/EMotionFX/Code/Source/Editor/PropertyWidgets/EventDataHandler.cpp
  Gems/LmbrCentral/Code/Source/Builders/SliceBuilder/SliceBuilderWorker.cpp
  Gems/LyShine/Code/Editor/PropertiesContainer.cpp
  Gems/LyShine/Code/Pipeline/LyShineBuilder/UiCanvasBuilderWorker.cpp
  Gems/PhysX/Core/Code/Source/ForceRegion.cpp
  Gems/RemoteTools/Code/Source/RemoteToolsSystemComponent.cpp
Labels: needs-sig

#18538 Track View: Major fix for GHI# 11500
  Code/Framework/AzToolsFramework/AzToolsFramework/API/ToolsApplicationAPI.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.h
  Gems/LyShine/Code/Source/Animation/AnimSequence.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimSequence.cpp
  Gems/Maestro/Code/Source/Components/EditorSequenceAgentComponent.cpp
  Gems/Maestro/Code/Source/Components/EditorSequenceComponent.cpp
Labels: feature/trackview, sig/content

#18548 Track View: Optional fix for GHI #11500: fix prefabs previously stored with invalid entity parents.
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabDomUtils.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabLoader.cpp
Labels: feature/trackview, sig/content, feature/prefabs

#18493 New: double clicking in an item in entity outliner does a camera go-to
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
Labels: sig/content
