Repository o3de/o3de, pull requests merged in 2024-09, with the labels that each got.

#18272 Fix optional dependencies in project.json not working correctly
  cmake/Gems.cmake
Labels: needs-sig

#18277 Fix of AddScopeQueryToFrameGraph being executed multiple times.
  Gems/Atom/RPI/Code/Source/RPI.Public/GpuQuery/Query.cpp
  Gems/Atom/RPI/Code/Tests/System/GpuQueryTests.cpp
Labels: needs-sig, sig/graphics-audio

#18279 Shading rate attachment format fix
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: needs-sig

#18283 Add missing alias for Atom_AtomBridge.HeadlessServers
  Gems/AtomLyIntegration/CMakeLists.txt
Labels: sig/graphics-audio

#18252 Improve messaging for missing Tix package
  scripts/o3de/o3de/export_project.py
Labels: sig/build

#18301 Fix compile error for Mac
  Code/Framework/AzCore/Platform/Common/UnixLike/AzCore/Serialization/Locale_UnixLike.h
Labels: sig/platform

#18302 Fix parameter order in calls to EvaluateVertexGeometry_BasePBR
  Gems/Atom/Feature/Common/Assets/Materials/Types/StandardMultilayerPBR.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_VertexEval.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_LightingBrdf.azsli
Labels: sig/graphics-audio

#18282 Fix epsilon of GetInverseTransform function being too large
  Code/Framework/AzCore/AzCore/Math/Matrix4x4.cpp
  Code/Framework/AzCore/Tests/Math/Matrix4x4Tests.cpp
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/MatrixUtility.azsli
Labels: sig/core, sig/graphics-audio, sig/simulation

#18292 Ignore imported object libraries as dependency when generating runtime dependencies
  cmake/Platform/Common/RuntimeDependencies_common.cmake
Labels: sig/build

#18294 Unified Launcher Stream Error Fix
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Tests/LocalRpcTests.cpp
Labels: needs-sig

#18255 Indirect Dispatch and updated Fullscreen Dispatch for RPI::ComputePass and RPI::RayTracingPass,
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/IndirectRendering.azsli
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/BloomDownsamplePass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/FastDepthAwareBlurPasses.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/NewDepthOfFieldPasses.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/SubsurfaceScatteringPass.cpp
  Gems/Atom/Feature/Common/Code/Source/PostProcessing/SubsurfaceScatteringPass.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPassData.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/ComputePass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Pass/ComputePassData.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/ComputePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Pass/PassData.cpp
Labels: sig/graphics-audio

#18300 Cherry pick unmerged fixes from stabilization/2409 to development
  Code/Framework/AzCore/AzCore/Component/Entity.cpp
  Code/Framework/AzFramework/AzFramework/Input/System/InputSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserFilterModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Tools/ProjectManager/Source/ProjectButtonWidget.cpp
  Code/Tools/ProjectManager/Source/ProjectExportController.cpp
  Code/Tools/ProjectManager/Source/ProjectExportWorker.cpp
  Code/Tools/ProjectManager/Source/ProjectExportWorker.h
  Code/Tools/ProjectManager/Source/ProjectInfo.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBlendDistancePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBlendIrradiancePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridBorderUpdatePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridClassificationPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridPreparePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRelocationPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRenderPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationPreparePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationRayTracingPass.cpp
  Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderWorker.cpp
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasReporter.h
  Gems/ScriptCanvas/Code/Editor/Framework/ScriptCanvasReporter.inl
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Assets/ScriptCanvasFileHandling.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Bus/EditorScriptCanvasBus.h
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h
  Gems/ScriptCanvas/Code/Editor/SystemComponent.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindowTreeItems.h
  Gems/ScriptCanvas/Code/Editor/View/Windows/MainWindow.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/GraphSerialization.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/Interpreted/ExecutionInterpretedDebugAPI.cpp
  scripts/build/Platform/Linux/build_config.json
  scripts/build/bootstrap/incremental_build_util.py
  scripts/o3de/ExportScripts/export_source_android.py
  scripts/o3de/ExportScripts/export_source_built_project.py
  scripts/o3de/o3de/export_project.py
Labels: sig/core

#18271 Add android monolithic to sdk
  Code/Framework/AzAndroid/CMakeLists.txt
  Code/Framework/CMakeLists.txt
  Code/Tools/Android/CMakeLists.txt
  Code/Tools/CMakeLists.txt
  cmake/Platform/Common/Install_common.cmake
  scripts/build/Platform/Linux/build_config.json
  scripts/build/Platform/Windows/build_config.json
  scripts/build/build_node/Platform/Linux/install-ubuntu-android-tools.sh
  scripts/build/build_node/Platform/Linux/install-ubuntu.sh
  scripts/build/build_node/Platform/Windows/install-windows-android.ps1
  scripts/o3de/ExportScripts/export_source_android.py
  scripts/o3de/ExportScripts/export_source_built_project.py
  scripts/o3de/o3de/ui/export_project.py
  scripts/o3de/tests/ExportScripts/test_export_source_android.py
  scripts/o3de/tests/ExportScripts/test_export_source_built_project.py
Labels: sig/build, sig/platform

#18313 One RayTracingAccelerationStructurePass per device
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Labels: needs-sig

#18310 Cherry Pick: Unified Launcher Stream Error Fix
  Gems/Multiplayer/Code/Source/Components/NetBindComponent.cpp
  Gems/Multiplayer/Code/Source/NetworkEntity/NetworkEntityManager.cpp
  Gems/Multiplayer/Code/Tests/LocalRpcTests.cpp
Labels: needs-sig

#18317 Fixes a crash / nullptr dereference in MoveProject_MovesExpectedFiles
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/tests/UtilsTests.cpp
Labels: sig/testing

#18325 Maestro Compiler Error Fix
  Code/Legacy/CryCommon/Mocks/ICryPakMock.h
Labels: needs-sig

#18326 Fix shadows Projected + Directional shadows on Metal
  Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/Conversions.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/ImageView.cpp
Labels: needs-sig

#18334 Move RaytracingAccelerationStructurePass back to Graphics Queue for 2409
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
Labels: sig/graphics-audio

#18316 Fixes the multiplayer connectivity test timeout
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
Labels: sig/build, sig/testing

#18186 Fixing job manager stats
  Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.cpp
  Code/Framework/AzCore/AzCore/Jobs/Internal/JobManagerWorkStealing.h
  Code/Framework/AzCore/AzCore/Jobs/JobManager.h
  Gems/AWSCore/Code/Include/Framework/HttpRequestJob.h
Labels: needs-sig

#18328 Fixes a crash if you enable Script canvas developer Gem
  Gems/ScriptCanvasDeveloper/Code/CMakeLists.txt
Labels: needs-sig, sig/content

#18349 Check count buffer of indirect draw arguments before accessing.
  Gems/Atom/RHI/Code/Include/Atom/RHI/DrawArguments.h
Labels: sig/graphics-audio

#18333 Add interface to expose members that are not necessary to be kept private
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
Labels: sig/graphics-audio

#18217 Asset Processing: Handling cyclic source dependencies
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.h
Labels: needs-sig
