Repository o3de/o3de, pull requests merged in 2024-11, with the labels that each got.

#18406 Fix Linux Python Installer issues
  Assets/Editor/Scripts/TrackView/example.py
  Code/Framework/AzFramework/AzFramework/Application/Application.cpp
  Code/Tools/ProjectManager/Resources/o3de_desktop.svg
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Gems/EditorPythonBindings/Code/CMakeLists.txt
  Gems/EditorPythonBindings/Code/Source/EditorPythonBindingsModule.cpp
  Gems/EditorPythonBindings/Code/Source/Platform/Linux/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/Platform/Mac/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/Platform/Windows/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Linux/Packaging/postinst.in
  cmake/Platform/Linux/Packaging/postrm.in
  python/python.cmd
  python/python.sh
  scripts/o3de/o3de/manifest.py
Labels: sig/build, sig/release

#18441 Fix Visual Studio Requirement in Project Manager when in script only mode
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
Labels: sig/build

#18431 Remove $<TARGET_OBJECTS: from SerializeContextTools targets
  Code/Tools/SerializeContextTools/CMakeLists.txt
Labels: sig/content

#15564 Merge phases of AssImpSkinWeightsImporter
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.cpp
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpSkinWeightsImporter.h
Labels: sig/content, feature/scene-pipeline

#18442 Remove python bootstrapping from post install steps on Windows
  cmake/Platform/Windows/Packaging/PostInstallSetup.wxs
  cmake/Platform/Windows/Packaging/Template.wxs.in
Labels: needs-sig

#18440 Merging o3de pointrelease 24091 to main
  Assets/Editor/Scripts/TrackView/example.py
  AutomatedTesting/Gem/PythonTests/Multiplayer/TestSuite_Main.py
  Code/Framework/AzFramework/AzFramework/Application/Application.cpp
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/ProjectManager/Platform/Mac/ProjectUtils_mac.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp
  Code/Tools/ProjectManager/Platform/Windows/ProjectUtils_windows.cpp
  Code/Tools/ProjectManager/Resources/o3de_desktop.svg
  Code/Tools/ProjectManager/Source/ProjectInfo.cpp
  Code/Tools/ProjectManager/Source/ProjectInfo.h
  Code/Tools/ProjectManager/Source/ProjectUtils.cpp
  Code/Tools/ProjectManager/Source/ProjectUtils.h
  Code/Tools/ProjectManager/Source/ProjectsScreen.cpp
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/AzslcHeader.azsli
  Gems/Atom/Asset/Shader/Code/AZSL/Platform/iOS/Metal/AzslcHeader.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/BicubicPcfFilters.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/IndexableList.h
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArray.cpp
  Gems/Atom/Feature/Common/Code/Source/Decals/DecalTextureArrayFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI.Builders/ShaderPlatformInterface.cpp
  Gems/Atom/RPI/Code/Source/RPI.Private/RPISystemComponent.cpp
  Gems/EditorPythonBindings/Code/CMakeLists.txt
  Gems/EditorPythonBindings/Code/Source/EditorPythonBindingsModule.cpp
  Gems/EditorPythonBindings/Code/Source/Platform/Linux/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/Platform/Mac/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/Platform/Windows/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Common/MSVC/Configurations_msvc.cmake
  cmake/Platform/Common/Toolchain_scriptonly_common.cmake
  cmake/Platform/Linux/Packaging/postinst.in
  cmake/Platform/Linux/Packaging/postrm.in
  cmake/Platform/Windows/Configurations_windows.cmake
  cmake/Platform/Windows/PAL_windows.cmake
  cmake/Platform/Windows/Packaging/BootstrapperTheme.wxl.in
  cmake/Platform/Windows/Packaging/PostInstallSetup.wxs
  engine.json
  python/python.cmd
  python/python.sh
  scripts/o3de/o3de/manifest.py
Labels: sig/release

#18290 fix: viewport camera grab mouse first time opening a level
  Code/Framework/AzFramework/AzFramework/Viewport/ClickDetector.h
Labels: needs-sig

#18308 feat: remove GetReferenceCoordSys
  Code/Editor/IEditor.h
  Code/Editor/IEditorImpl.cpp
  Code/Editor/IEditorImpl.h
  Code/Editor/Lib/Tests/IEditorMock.h
  Code/Editor/Viewport.cpp
  Code/Editor/Viewport.h
Labels: needs-sig

#18454 [Cherry-Pick 24091] Fix Linux Python Installer issues
  Assets/Editor/Scripts/TrackView/example.py
  Code/Framework/AzFramework/AzFramework/Application/Application.cpp
  Code/Tools/ProjectManager/Resources/o3de_desktop.svg
  Code/Tools/ProjectManager/Source/PythonBindings.cpp
  Gems/EditorPythonBindings/Code/CMakeLists.txt
  Gems/EditorPythonBindings/Code/Source/EditorPythonBindingsModule.cpp
  Gems/EditorPythonBindings/Code/Source/Platform/Linux/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/Platform/Mac/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/Platform/Windows/InitializePython.h
  Gems/EditorPythonBindings/Code/Source/PythonSystemComponent.cpp
  cmake/Platform/Common/Install_common.cmake
  cmake/Platform/Linux/Packaging/postinst.in
  cmake/Platform/Linux/Packaging/postrm.in
  python/python.cmd
  python/python.sh
  scripts/o3de/o3de/manifest.py
Labels: sig/platform, sig/release

#18411 CopyPass improvements (mainly for multi-device usage)
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshOutputStreamManager.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshVertexStreamProperties.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferProperty.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/CopyItem.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceCopyItem.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/AttachmentEnums.cpp
  Gems/Atom/RHI/Code/Source/RHI/BufferScopeAttachment.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Conversion.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ImagePoolResolver.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Scope.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassLibrary.cpp
Labels: needs-sig

#18439 Fix TransformServiceFeatureProcessor Set/Get transform functions for negative scales
  Code/Framework/AzCore/AzCore/Math/Matrix3x4.inl
  Code/Framework/AzCore/Tests/Math/MathTestData.h
  Code/Framework/AzCore/Tests/Math/TransformTests.cpp
Labels: needs-sig

#18455 [Cherry-Pick 24091] Double-quote windows command calls to support spaces in paths
  python/python.cmd
Labels: sig/platform, sig/release

#17916 Legacy Android Script Deprecation
  cmake/Tools/Platform/Android/android_post_build.py
  scripts/build/Platform/Android/gradle_windows.cmd
  scripts/build/Platform/Android/pipeline.json
  scripts/build/Platform/Windows/pipeline.json
  scripts/build/build_node/Platform/Windows/install-windows-android.ps1
  scripts/build/build_node/Platform/Windows/install-windows-buildtools.ps1
  scripts/o3de/o3de/android_support.py
Labels: sig/build

#18461 correct spirv bytecode vector size
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderModule.cpp
Labels: needs-sig

#18457 Added functions StoreToRow/ColumnMajorFloat11 for Matrix3x3 for GPU constant buffer packing
  Code/Framework/AzCore/AzCore/Math/Matrix3x3.h
  Code/Framework/AzCore/AzCore/Math/Matrix3x3.inl
  Code/Framework/AzCore/Tests/Math/Matrix3x3Tests.cpp
  Gems/Atom/RHI/Code/Source/RHI/ConstantsData.cpp
Labels: needs-sig

#18463 Add ScopeQueries to CopyPass
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
Labels: needs-sig

#18481 Change Atom_Feature_Common.Public back to static library
  Gems/Atom/Feature/Common/Code/CMakeLists.txt
Labels: sig/graphics-audio

#18479 Make sure RHI::Images stick around while Upload - Requests are pending
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceStreamingImagePool.h
  Gems/Atom/RHI/Code/Source/RHI/DeviceStreamingImagePool.cpp
  Gems/Atom/RHI/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/StreamingImagePool.cpp
Labels: needs-sig

#18484 Fix resetting and recording of timestamps
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
Labels: needs-sig

#18462 Expose more functions to feature processor interfaces
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/CapsuleLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DirectionalLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/DiskLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PointLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PolygonLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/QuadLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/SimplePointLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/SimpleSpotLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ImageBasedLights/ImageBasedLightFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/CapsuleLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DirectionalLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/DiskLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/PointLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/PolygonLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/QuadLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/SimplePointLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/CoreLights/SimpleSpotLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/ImageBasedLights/ImageBasedLightFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
Labels: needs-sig

#18460 Fixed Json de-/serialization of BufferAssets
  Code/Framework/AzCore/AzCore/Serialization/Json/ByteStreamSerializer.cpp
  Code/Framework/AzCore/AzCore/Serialization/Json/ByteStreamSerializer.h
  Code/Framework/AzCore/AzCore/Serialization/Json/JsonSystemComponent.cpp
  Code/Framework/AzCore/AzCore/azcore_files.cmake
  Code/Framework/AzCore/Tests/Serialization/Json/ByteStreamSerializerTests.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Buffer/BufferAsset.cpp
Labels: needs-sig

#18480 Track View Fix: AzQtComponents::InputDialog should be modal (GHI-15048)
  Code/Framework/AzQtComponents/AzQtComponents/Components/InputDialog.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/InputDialog.h
Labels: needs-sig

#18478 Expose math members to behavior context level
  Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
  Code/Framework/AzCore/AzCore/Math/Transform.cpp
Labels: sig/core

#18475 Fix use case for Star Gem in console mode
  Gems/Stars/Code/Source/StarsFeatureProcessor.cpp
Labels: sig/graphics-audio

#18495 Track View Fix: Implement the public override of the externally used method, thus removing asserts (issue #14801).
  Gems/Maestro/Code/Source/Cinematics/AssetBlendTrack.cpp
  Gems/Maestro/Code/Source/Cinematics/AssetBlendTrack.h
  Gems/Maestro/Code/Source/Cinematics/Tests/AssetBlendTrackTest.cpp
Labels: sig/content

#18499 Fix RayTracingTlasDescriptor not propagating m_instanceMask to DeviceRayTracingTlasDescriptor
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
Labels: sig/graphics-audio

#18511 Bugfix: multi-device image to image copy pass fail
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/CopyPass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
Labels: needs-sig

#18512 added missing includes in srgi files
  Templates/DefaultProject/Template/ShaderLib/scenesrg.srgi
  Templates/DefaultProject/Template/ShaderLib/viewsrg.srgi
Labels: needs-sig

#18508 Fix compilation on windows
  Code/Editor/AnimationContext.h
Labels: sig/platform

#18510 Quest specular fix
  Gems/Atom/Bootstrap/Code/Source/BootstrapSystemComponent.cpp
  Gems/Atom/Feature/Common/Assets/Materials/Types/Eye.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/MaterialUtils.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Microfacet/Brdf.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Microfacet/Ggx.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/SpecularAA.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/BasePBR/BasePBR_SurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/EnhancedPBR/EnhancedPBR_SurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/Skin/Skin_SurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/StandardPBR/StandardPBR_SurfaceData.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHit.azsli
  Gems/AtomTressFX/Assets/Shaders/HairSurface.azsli
Labels: sig/graphics-audio
