Repository o3de/o3de, pull requests merged in 2025-01, with the labels that each got.

#18573 Track View: Fix issue #15042 , - update code forming UI context sub-menus for adding / managing tracks of a component.
  Code/Editor/TrackView/TrackViewNodes.cpp
Labels: feature/trackview, sig/content

#18560 Track View: Fix issues #2833 and #4590, - add switching cameras in the Editor Viewport according to a Director track keys setup.
  Code/Editor/AnimationContext.cpp
  Code/Editor/AnimationContext.h
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/EditorViewportWidget.cpp
  Code/Editor/EditorViewportWidget.h
  Code/Editor/TrackView/TrackViewDialog.cpp
  Code/Editor/TrackViewNewSequenceDialog.cpp
Labels: feature/trackview, sig/content

#18544 Fixes for rendering TrackView sequences (GHI-11268)
  Code/Editor/AnimationContext.cpp
  Code/Editor/AnimationContext.h
  Code/Editor/IEditor.h
  Code/Editor/TrackView/AtomOutputFrameCapture.cpp
  Code/Editor/TrackView/AtomOutputFrameCapture.h
  Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
  Code/Editor/TrackView/SequenceBatchRenderDialog.h
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewDialog.h
  Code/Editor/TrackView/TrackViewMessageBox.cpp
  Code/Editor/TrackView/TrackViewMessageBox.h
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Editor/TrackView/TrackViewNodes.h
  Code/Editor/TrackView/TrackViewSequenceManager.cpp
  Code/Editor/TrackView/TrackViewSequenceManager.h
  Code/Editor/editor_lib_files.cmake
  Code/Legacy/CryCommon/IMovieSystem.h
  Code/Legacy/CryCommon/Maestro/Bus/EditorSequenceComponentBus.h
  Code/Legacy/CryCommon/Maestro/Bus/SequenceComponentBus.h
  Code/Legacy/CrySystem/System.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimSequence.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Components/EditorSequenceComponent.cpp
  Gems/Maestro/Code/Source/Components/EditorSequenceComponent.h
  Gems/Maestro/Code/Source/Components/SequenceAgent.cpp
  Gems/Maestro/Code/Source/Components/SequenceComponent.cpp
  Gems/Maestro/Code/Source/Components/SequenceComponent.h
Labels: sig/content

#18589 Lua Editor : Fix issue #14153 - Crash when closing file
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Labels: feature/scripting, sig/content

#18601 Fixes Slow Icon Rendering, Issue #18567
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorViewportIconDisplayInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
  Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp
  Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.cpp
  Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.h
Labels: sig/graphics-audio

#18624 Fixed crash when opening invalid ScriptCanvas file and fixed graph de…
  Gems/ScriptCanvas/Code/Editor/Assets/ScriptCanvasFileHandling.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Execution/ExecutionStateHandler.cpp
Labels: feature/scripting, sig/content

#18590 MiniAudio: Use GetID over GetHint
  Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponentController.cpp
  Gems/MiniAudio/Code/Source/Clients/MiniAudioPlaybackComponentController.h
Labels: needs-sig

#18608 Built-in Crash Reporter : Fix and improve message box dialogs
  Code/Legacy/CrySystem/DebugCallStack.cpp
  Code/Legacy/CrySystem/DebugCallStack.h
  Code/Legacy/CrySystem/IDebugCallStack.h
  Code/Legacy/CrySystem/SystemInit.cpp
Labels: feature/editor, platform/windows, sig/content

#18625 Fixes issue #18620 - Icons not being correct And related other issues.
  Code/Framework/AzCore/AzCore/Serialization/Json/JsonDeserializer.cpp
  Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h
  Code/Framework/AzFramework/AzFramework/Spawnable/Script/SpawnableScriptAssetRef.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorEntityIconComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorEntityIconComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorInspectorComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorInspectorComponent.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/EntityPropertyEditor.hxx
  Code/Framework/AzToolsFramework/Tests/EntityInspectorTests.cpp
  Code/Framework/AzToolsFramework/Tests/UI/EntityPropertyEditorTests.cpp
  Gems/MiniAudio/Code/Include/MiniAudio/SoundAssetRef.h
  Registry/AssetProcessorPlatformConfig.setreg
Labels: sig/core

#18626 Fix Linux release + non-unity builds for Empty Project
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h
Labels: needs-sig

#18644 Fixes DX12::StreamingImagePool related deadlock.
  Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/StreamingImagePool.h
Labels: feature/graphics, sig/graphics-audio

#18633 TrackView code cleanup
  Code/Editor/TrackView/2DBezierKeyUIControls.cpp
  Code/Editor/TrackView/AssetBlendKeyUIControls.cpp
  Code/Editor/TrackView/CaptureKeyUIControls.cpp
  Code/Editor/TrackView/CharacterKeyUIControls.cpp
  Code/Editor/TrackView/CommentKeyUIControls.cpp
  Code/Editor/TrackView/CommentNodeAnimator.cpp
  Code/Editor/TrackView/CommentNodeAnimator.h
  Code/Editor/TrackView/ConsoleKeyUIControls.cpp
  Code/Editor/TrackView/DirectorNodeAnimator.cpp
  Code/Editor/TrackView/DirectorNodeAnimator.h
  Code/Editor/TrackView/EditorTrackViewEventsBus.h
  Code/Editor/TrackView/EventKeyUIControls.cpp
  Code/Editor/TrackView/GotoKeyUIControls.cpp
  Code/Editor/TrackView/ScreenFaderKeyUIControls.cpp
  Code/Editor/TrackView/SelectKeyUIControls.cpp
  Code/Editor/TrackView/SequenceBatchRenderDialog.cpp
  Code/Editor/TrackView/SequenceBatchRenderDialog.h
  Code/Editor/TrackView/SequenceKeyUIControls.cpp
  Code/Editor/TrackView/SoundKeyUIControls.cpp
  Code/Editor/TrackView/TVCustomizeTrackColorsDlg.cpp
  Code/Editor/TrackView/TVCustomizeTrackColorsDlg.h
  Code/Editor/TrackView/TVEventsDialog.cpp
  Code/Editor/TrackView/TVEventsDialog.h
  Code/Editor/TrackView/TVSequenceProps.cpp
  Code/Editor/TrackView/TVSequenceProps.h
  Code/Editor/TrackView/TimeRangeKeyUIControls.cpp
  Code/Editor/TrackView/TrackEventKeyUIControls.cpp
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewAnimNode.h
  Code/Editor/TrackView/TrackViewCurveEditor.cpp
  Code/Editor/TrackView/TrackViewCurveEditor.h
  Code/Editor/TrackView/TrackViewDialog.cpp
  Code/Editor/TrackView/TrackViewDialog.h
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
  Code/Editor/TrackView/TrackViewDopeSheetBase.h
  Code/Editor/TrackView/TrackViewDoubleSpinBox.h
  Code/Editor/TrackView/TrackViewEventNode.cpp
  Code/Editor/TrackView/TrackViewEventNode.h
  Code/Editor/TrackView/TrackViewFindDlg.cpp
  Code/Editor/TrackView/TrackViewFindDlg.h
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.h
  Code/Editor/TrackView/TrackViewMessageBox.cpp
  Code/Editor/TrackView/TrackViewNode.cpp
  Code/Editor/TrackView/TrackViewNode.h
  Code/Editor/TrackView/TrackViewNodeFactories.h
  Code/Editor/TrackView/TrackViewNodes.cpp
  Code/Editor/TrackView/TrackViewNodes.h
  Code/Editor/TrackView/TrackViewPythonFuncs.cpp
  Code/Editor/TrackView/TrackViewSequence.cpp
  Code/Editor/TrackView/TrackViewSequence.h
  Code/Editor/TrackView/TrackViewSequenceManager.cpp
  Code/Editor/TrackView/TrackViewSequenceManager.h
  Code/Editor/TrackView/TrackViewSplineCtrl.cpp
  Code/Editor/TrackView/TrackViewSplineCtrl.h
  Code/Editor/TrackView/TrackViewTimeline.h
  Code/Editor/TrackView/TrackViewTrack.cpp
  Code/Editor/TrackView/TrackViewTrack.h
Labels: feature/trackview, sig/content

#18648 Cherry-pick : Built-in Crash Reporter : Fix and improve message box dialogs (#18608)
  Code/Legacy/CrySystem/DebugCallStack.cpp
  Code/Legacy/CrySystem/DebugCallStack.h
  Code/Legacy/CrySystem/IDebugCallStack.h
  Code/Legacy/CrySystem/SystemInit.cpp
Labels: needs-sig

#18645 Cherrypick from Dev - Fixes Slow Icon rendering
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorViewportIconDisplayInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UnitTest/Mocks/MockEditorViewportIconDisplayInterface.h
  Code/Framework/AzToolsFramework/AzToolsFramework/ViewportSelection/EditorHelpers.cpp
  Code/Framework/AzToolsFramework/Tests/EditorViewportIconTests.cpp
  Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.cpp
  Gems/AtomLyIntegration/AtomViewportDisplayIcons/Code/Source/AtomViewportDisplayIconsSystemComponent.h
Labels: sig/content, sig/graphics-audio

#18611 Merging GameLift Fix to 24092
  Gems/AWSGameLift/Code/AWSGameLiftServer/CMakeLists.txt
Labels: needs-sig
