Repository o3de/o3de, pull requests merged in 2025-02, with the labels that each got.

#18627 Assimp importer use DCC (Y-Up) coordinate system by default.
  Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp
  Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
Labels: needs-sig

#18654 Track View: Fix issue #18639 : recording camera rotations.
  Code/Framework/AzCore/AzCore/Math/Quaternion.cpp
  Code/Framework/AzCore/AzCore/Math/Quaternion.h
  Code/Framework/AzCore/AzCore/Math/Quaternion.inl
  Code/Framework/AzCore/Tests/Math/QuaternionTests.cpp
  Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp
Labels: feature/trackview, sig/content

#18655 Fixes many issues discovered by the Address Sanitizer
  Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
  Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/FileRequest.h
  Code/Framework/AzCore/AzCore/IO/Streamer/Statistics.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
  Code/Framework/AzCore/AzCore/JSON/rapidjson.h
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.h
  Code/Framework/AzCore/AzCore/Metrics/EventLoggerReflectUtils.cpp
  Code/Framework/AzCore/AzCore/std/string/conversions.h
  Code/Framework/AzCore/AzCore/std/string/utf8/unchecked.h
  Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp
  Code/Framework/AzCore/Tests/AZTestShared/Math/MathTestHelpers.cpp
  Code/Framework/AzCore/Tests/Name/NameJsonSerializerTests.cpp
  Code/Framework/AzCore/Tests/Serialization/Json/StringSerializerTests.cpp
  Code/Framework/AzCore/Tests/Streamer/SchedulerTests.cpp
  Code/Framework/AzFramework/AzFramework/Entity/SliceEntityOwnershipService.cpp
  Code/Framework/AzFramework/AzFramework/Entity/SliceEntityOwnershipService.h
  Code/Framework/AzNetworking/AzNetworking/Serialization/DeltaSerializer.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/Tests/ActionManager/HotKeyManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/ComponentAddRemove.cpp
  Code/Framework/AzToolsFramework/Tests/EntityOwnershipService/SliceEntityOwnershipTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoEditEntityTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateTemplateTests.cpp
  Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
  Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
  Gems/Atom/RHI/Code/Tests/ThreadTester.cpp
Labels: sig/core

#18659 Fixes an assert that occurs if you undo/redo prefab focus
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.hxx
Labels: sig/content

#18604 Calibrated Timestamps for multi-device timestamp comparability
  Gems/Atom/RHI/Code/Include/Atom/RHI/Device.h
  Gems/Atom/RHI/Code/Tests/Device.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueue.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandQueue.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Null/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
  Gems/Atom/RPI/Code/Tests/Common/RHI/Stubs.h
  Gems/Atom/Utils/Code/Include/Atom/Utils/ImGuiGpuProfiler.h
  Gems/Atom/Utils/Code/Source/ImGuiGpuProfiler.cpp
Labels: needs-sig

#18664 Various iOS/Mac related compile, crash and rendering fixes to get those platforms working on the development branch.
  Code/Framework/AzQtComponents/AzQtComponents/Utilities/ScreenGrabber_mac.mm
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/BicubicPcfFilters.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/Shadow/DirectionalLightShadowCalculator.azsli
  Gems/Atom/RHI/Metal/Code/Source/Platform/Mac/RHI/Metal_RHI_Mac.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/AsyncUploadQueue.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/RenderPassBuilder.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/StreamingImagePoolResolver.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/TransientAttachmentPool.cpp
Labels: sig/graphics-audio

#18662 Improves the performance of making trivial edits in a large level
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabPublicHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
Labels: sig/core

#18661 [Track View] Fix for the issue #15023: Force recent changes made in TrackView when switching to Play Game mode
  Code/Editor/AnimationContext.cpp
Labels: sig/content

#18663 Update Windows Android script for GHA
  scripts/build/build_node/Platform/Windows/install-windows-android.ps1
Labels: sig/build

#18550 Vulkan RHI: HDR Support
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Labels: needs-sig

#18669 Cherry-pick ASAN fixes and Outliner Crash from dev to point release 24.09.2
  Code/Editor/Lib/Tests/test_ModularViewportCameraController.cpp
  Code/Framework/AzCore/AzCore/DOM/DomPath.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/FileRequest.h
  Code/Framework/AzCore/AzCore/IO/Streamer/Statistics.cpp
  Code/Framework/AzCore/AzCore/IO/Streamer/Streamer.cpp
  Code/Framework/AzCore/AzCore/JSON/rapidjson.h
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.h
  Code/Framework/AzCore/AzCore/Metrics/EventLoggerReflectUtils.cpp
  Code/Framework/AzCore/AzCore/std/string/conversions.h
  Code/Framework/AzCore/AzCore/std/string/utf8/unchecked.h
  Code/Framework/AzCore/Platform/Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp
  Code/Framework/AzCore/Tests/AZTestShared/Math/MathTestHelpers.cpp
  Code/Framework/AzCore/Tests/Name/NameJsonSerializerTests.cpp
  Code/Framework/AzCore/Tests/Serialization/Json/StringSerializerTests.cpp
  Code/Framework/AzCore/Tests/Streamer/SchedulerTests.cpp
  Code/Framework/AzFramework/AzFramework/Entity/SliceEntityOwnershipService.cpp
  Code/Framework/AzFramework/AzFramework/Entity/SliceEntityOwnershipService.h
  Code/Framework/AzNetworking/AzNetworking/Serialization/DeltaSerializer.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Outliner/EntityOutlinerWidget.hxx
  Code/Framework/AzToolsFramework/Tests/ActionManager/HotKeyManagerTests.cpp
  Code/Framework/AzToolsFramework/Tests/ComponentAddRemove.cpp
  Code/Framework/AzToolsFramework/Tests/EntityOwnershipService/SliceEntityOwnershipTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabTestFixture.h
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUndoEditEntityTests.cpp
  Code/Framework/AzToolsFramework/Tests/Prefab/PrefabUpdateTemplateTests.cpp
  Code/Tools/AssetProcessor/native/unittests/UtilitiesUnitTests.cpp
  Code/Tools/SceneAPI/SceneCore/Containers/GraphObjectProxy.cpp
  Gems/Atom/RHI/Code/Tests/ThreadTester.cpp
Labels: sig/release

#18636 Add Blas compaction for raytracing
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/CommandList.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingCompactionQueryPool.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Factory.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingCompactionQueryPool.h
  Gems/Atom/RHI/Code/Source/RHI/DeviceRayTracingAccelerationStructure.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceRayTracingCompactionQueryPool.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingCompactionQueryPool.cpp
  Gems/Atom/RHI/Code/Tests/Factory.cpp
  Gems/Atom/RHI/Code/Tests/Factory.h
  Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingCompactionQueryPool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingCompactionQueryPool.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/SystemComponent.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/SystemComponent.h
  Gems/Atom/RHI/DX12/Code/atom_rhi_dx12_private_common_files.cmake
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/Metal/Code/Source/RHI/SystemComponent.cpp
  Gems/Atom/RHI/Metal/Code/Source/RHI/SystemComponent.h
  Gems/Atom/RHI/Null/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/Null/Code/Source/RHI/RayTracingBlas.h
  Gems/Atom/RHI/Null/Code/Source/RHI/RayTracingCompactionQueryPool.cpp
  Gems/Atom/RHI/Null/Code/Source/RHI/RayTracingCompactionQueryPool.h
  Gems/Atom/RHI/Null/Code/Source/RHI/SystemComponent.cpp
  Gems/Atom/RHI/Null/Code/Source/RHI/SystemComponent.h
  Gems/Atom/RHI/Null/Code/atom_rhi_null_private_common_files.cmake
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/CommandList.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingCompactionQueryPool.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingCompactionQueryPool.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SystemComponent.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SystemComponent.h
  Gems/Atom/RHI/Vulkan/Code/atom_rhi_vulkan_private_common_files.cmake
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/RPISystemDescriptor.h
  Gems/Atom/RPI/Code/Source/RPI.Reflect/RPISystemDescriptor.cpp
  Gems/Atom/RPI/Code/Tests/Common/RHI/Factory.cpp
  Gems/Atom/RPI/Code/Tests/Common/RHI/Factory.h
Labels: needs-sig

#18526 Improve light culling for Disk and Spot Lights
  Gems/Atom/Feature/Common/Assets/Shaders/LightCulling/LightCulling.azsl
Labels: sig/graphics-audio, feature/graphics/lighting

#18692 Clear build results before each compilation
  Gems/ScriptCanvas/Code/Builder/ScriptCanvasBuilderDataSystem.cpp
Labels: feature/scripting, sig/content

#18681 [TrackView] Refactor and fix camera switching both in Editing and Play Game modes
  Code/Editor/AnimationContext.cpp
  Code/Editor/TrackView/KeyUIControls.h
  Code/Editor/TrackView/SelectKeyUIControls.cpp
  Code/Editor/TrackView/TrackViewDialog.cpp
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
  Code/Editor/TrackView/TrackViewTrack.cpp
  Code/Legacy/CryCommon/AnimKey.h
  Code/Legacy/CryCommon/IMovieSystem.cpp
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Source/Cinematics/Movie.cpp
  Gems/Maestro/Code/Source/Cinematics/Movie.h
  Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp
  Gems/Maestro/Code/Source/Cinematics/SceneNode.h
  Gems/Maestro/Code/Source/Cinematics/SelectTrack.cpp
  Gems/Maestro/Code/Source/Cinematics/SelectTrack.h
Labels: feature/trackview

#18673 Make the number of potential PassAttachments variable.
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
Labels: sig/graphics-audio

#18697 Script Canvas: Fixed issue with promoting variables from a node's slot
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
Labels: feature/scripting, sig/content

#18710 Update the variable's property tree on rename
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/GraphVariablesTableView.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableDockWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/VariablePanel/VariableDockWidget.h
Labels: feature/scripting, sig/content

#18707 Update slot names if the referenced variable is renamed
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/Slot.h
Labels: feature/scripting, sig/content

#18694 [TrackView] Fix issues #9141 and #10180: Make DeferredFog->FogColor->Vector3 tracks use Color editing tools: universal Vector3->Color remapping.
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Source/Cinematics/SceneNode.cpp
  Gems/Maestro/Code/Source/Cinematics/SceneNode.h
Labels: feature/trackview, sig/content

#18701 Fix issue #14746: expose Enable controls of DeferredFog to TrackView sequence
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ScreenSpace/DeferredFogParams.inl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ScreenSpace/DeferredFogSettingsInterface.h
  Gems/Atom/Feature/Common/Code/Source/ScreenSpace/DeferredFogSettings.cpp
  Gems/Atom/Feature/Common/Code/Source/ScreenSpace/DeferredFogSettings.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Include/AtomLyIntegration/CommonFeatures/ScreenSpace/DeferredFogComponentConfig.h
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/DeferredFogComponentConfig.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/ScreenSpace/DeferredFogComponentController.cpp
Labels: feature/trackview, sig/content

#18695 Updated C++ ColorSpaceId to match the Shader.
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/ColorManagement/TransformColor.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/ColorManagement/TransformColor.h
Labels: sig/graphics-audio
