Repository o3de/o3de, pull requests merged in 2025-03, with the labels that each got.

#18558 Vulkan: Allocate only one queue per queue family.
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: sig/graphics-audio

#18702 Fixes all remaining Address Sanitizer issues in gem tests
  Code/Framework/AzCore/AzCore/Asset/AssetManager.cpp
  Code/Framework/AzCore/AzCore/EBus/EventSchedulerSystemComponent.cpp
  Gems/EMotionFX/Code/Tests/AnimGraphCopyPasteTests.cpp
  Gems/EMotionFX/Code/Tests/InitSceneAPIFixture.h
  Gems/EMotionFX/Code/Tests/MotionExtractionBusTests.cpp
  Gems/EMotionFX/Code/Tests/SystemComponentFixture.h
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Tests/Tracks/AnimTrackTest.cpp
  Gems/Multiplayer/Code/Tests/CommonHierarchySetup.h
  Gems/Multiplayer/Code/Tests/CommonNetworkEntitySetup.h
  Gems/Multiplayer/Code/Tests/MultiplayerSystemTests.cpp
  Gems/Multiplayer/Code/Tests/NetworkEntityTests.cpp
  Gems/Multiplayer/Code/Tests/NetworkRigidBodyTests.cpp
  Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventSystem.cpp
  Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventSystem.h
  Gems/ScriptEvents/Code/Source/Editor/ScriptEventsSystemEditorComponent.cpp
  Gems/ScriptEvents/Code/Source/ScriptEventsSystemComponent.cpp
  Gems/SurfaceData/Code/Tests/MixedAllocatorTest.cpp
Labels: sig/content, sig/core, sig/network, sig/simulation

#18686 [WIP] Add a setting registry that allows AssImp to change behavior when importing coordinates
  Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
  Templates/DefaultProject/Template/Registry/assimp_settings.setreg
  Templates/DefaultProject/template.json
  Templates/MinimalProject/Template/Registry/assimp_settings.setreg
  Templates/MinimalProject/template.json
  Templates/ScriptOnlyProject/Template/Registry/assimp_settings.setreg
  Templates/ScriptOnlyProject/template.json
Labels: sig/content

#18712 [Track View] Add string track support, - fixing issue #9044.
  Code/Editor/TrackView/KeyUIControls.h
  Code/Editor/TrackView/StringKeyUIControls.cpp
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
  Code/Editor/TrackView/TrackViewDopeSheetBase.h
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
  Code/Editor/TrackView/TrackViewPythonFuncs.cpp
  Code/Editor/editor_lib_files.cmake
  Code/Legacy/CryCommon/AnimKey.h
  Code/Legacy/CryCommon/IMovieSystem.h
  Code/Legacy/CryCommon/Maestro/Bus/SequenceComponentBus.h
  Code/Legacy/CryCommon/Maestro/Types/AnimValueType.h
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimSerializer.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h
  Gems/Maestro/Code/Source/Cinematics/StringTrack.cpp
  Gems/Maestro/Code/Source/Cinematics/StringTrack.h
  Gems/Maestro/Code/Source/Components/SequenceAgent.cpp
  Gems/Maestro/Code/Source/Components/SequenceComponent.cpp
  Gems/Maestro/Code/maestro_static_files.cmake
Labels: feature/trackview, sig/content

#18734 ScriptCanvas: Fix crash on SC editor close
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/GraphOutliner/GraphOutlinerDockWidget.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingDataAggregator.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LiveWindowSession/LiveLoggingWindowSession.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/ExecutionLogAsset.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Asset/ExecutionLogAsset.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Bus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Logger.h
Labels: feature/scripting, kind/bug

#18732 DPE: Don't request a size update for every Dom change
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Labels: sig/content

#18736 Fixes a issue #18720 (vulkan malloc crash) and compile error
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
  Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
Labels: sig/core

#18733 [Track View] Fix Compound Tracks Keys evaluation (selection, editing, addition).
  Code/Editor/TrackView/KeyUIControls.h
  Code/Editor/TrackView/TrackViewAnimNode.cpp
  Code/Editor/TrackView/TrackViewAnimNode.h
  Code/Editor/TrackView/TrackViewCurveEditor.cpp
  Code/Editor/TrackView/TrackViewDopeSheetBase.cpp
  Code/Editor/TrackView/TrackViewKeyPropertiesDlg.cpp
  Code/Editor/TrackView/TrackViewTrack.cpp
  Code/Editor/TrackView/VectorKeyUIControls.cpp
  Code/Editor/editor_lib_files.cmake
  Code/Legacy/CryCommon/IMovieSystem.h
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack.h
  Gems/Maestro/Code/Source/Cinematics/AnimSplineTrack_Vec2Specialization.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.cpp
  Gems/Maestro/Code/Source/Cinematics/CompoundSplineTrack.h
Labels: feature/trackview, sig/content

#18725 Refactor ResourceView and rename Build*View to Get*View
  Gems/Atom/Feature/Common/Code/Source/ACES/AcesDisplayMapperFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.cpp
  Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetInputBuffers.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/Buffer.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceResource.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Image.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ImageView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/MultiDeviceObject.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Object.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/Resource.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ResourceView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/ResourceViewCache.h
  Gems/Atom/RHI/Code/Source/RHI/Buffer.cpp
  Gems/Atom/RHI/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Code/Source/RHI/CommandListValidator.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceResource.cpp
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
  Gems/Atom/RHI/Code/Source/RHI/Image.cpp
  Gems/Atom/RHI/Code/Source/RHI/ImageView.cpp
  Gems/Atom/RHI/Code/Source/RHI/Resource.cpp
  Gems/Atom/RHI/Code/Source/RHI/ResourceView.cpp
  Gems/Atom/RHI/Code/Source/RHI/ResourceViewCache.cpp
  Gems/Atom/RHI/Code/Source/RHI/ScopeAttachment.cpp
  Gems/Atom/RHI/Code/atom_rhi_public_files.cmake
  Gems/Atom/RPI/Code/Source/RPI.Public/Buffer/Buffer.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/AttachmentImage.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Image/StreamingImage.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/DownsampleSinglePassLuminancePass.cpp
  Gems/Atom/RPI/Code/Tests/ShaderResourceGroup/ShaderResourceGroupBufferTests.cpp
  Gems/Atom/RPI/Code/Tests/ShaderResourceGroup/ShaderResourceGroupImageTests.cpp
  Gems/AtomTressFX/Code/Rendering/HairRenderObject.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridQueryPass.cpp
  Gems/Meshlets/Code/Source/Meshlets/MeshletsUtilities.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
Labels: sig/graphics-audio

#18729 Whitebox Gem now compiles OpenMesh directly instead of using 3p packages
  Gems/WhiteBox/3rdParty/FindOpenMesh.cmake
  Gems/WhiteBox/3rdParty/Installer/FindOpenMesh.cmake
  Gems/WhiteBox/3rdParty/openmesh-o3de-11.0.patch
  Gems/WhiteBox/CMakeLists.txt
  Gems/WhiteBox/Code/CMakeLists.txt
  Gems/WhiteBox/Code/Source/Core/WhiteBoxToolApi.cpp
  Gems/WhiteBox/Code/Source/Platform/Common/Clang/whitebox_editor_clang.cmake
  Gems/WhiteBox/Code/Source/Platform/Common/GCC/whitebox_editor_gcc.cmake
  Gems/WhiteBox/Code/Source/Platform/Common/MSVC/whitebox_editor_msvc.cmake
  Gems/WhiteBox/Code/Source/Platform/Linux/platform_linux_tools.cmake
  Gems/WhiteBox/Code/Source/Platform/Mac/platform_mac_tools.cmake
  Gems/WhiteBox/Code/Source/Platform/Windows/platform_windows_tools.cmake
  Gems/WhiteBox/Code/Source/WhiteBoxModuleUnsupported.cpp
  Gems/WhiteBox/Code/Tests/WhiteBoxTest.cpp
  Gems/WhiteBox/Code/whitebox_unsupported_files.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_aarch64.cmake
  cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake
  cmake/3rdParty/Platform/Mac/BuiltInPackages_mac.cmake
  cmake/3rdParty/Platform/Windows/BuiltInPackages_windows.cmake
  cmake/Configurations.cmake
  cmake/PatchIfNotAlreadyPatched.cmake
  cmake/Platform/Common/Clang/Configurations_clang.cmake
  cmake/Platform/Common/GCC/Configurations_gcc.cmake
  cmake/Platform/Common/MSVC/Configurations_clang.cmake
  cmake/Platform/Common/MSVC/Configurations_msvc.cmake
Labels: sig/build, sig/core

#18728 Improve SRG compiling performance
  Code/Framework/AtomCore/AtomCore/atomcore_files.cmake
  Code/Framework/AtomCore/AtomCore/std/containers/small_vector.h
  Code/Framework/AzCore/AzCore/std/containers/fixed_vector.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/DescriptorContext.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/DescriptorSet.h
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/ShaderResourceGroupPool.cpp
Labels: sig/graphics-audio

#18737 Cherrypick from stab: Fixes a issue #18720 (vulkan malloc crash) and compile error
  Code/Framework/AzCore/AzCore/Memory/SystemAllocator.cpp
  Code/Framework/AzCore/Tests/Math/Matrix3x4Tests.cpp
Labels: sig/core

#18730 Galibzon/material mesh index
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/AlphaUtils.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/ParallaxMapping.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/AlphaInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/EmissiveInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Materials/MaterialInputs/MetallicInput.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/PostProcessing/SMAAEdgeDetection.azsl
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/StreamBufferViewsBuilderInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/BufferView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceBufferView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DrawPacket.h
  Gems/Atom/RHI/Code/Source/RHI/BufferView.cpp
  Gems/Atom/RHI/Code/Source/RHI/DrawPacket.cpp
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/ShaderResourceGroups/DefaultDrawSrg.azsli
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/TangentSpace.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/MeshDrawPacket.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshStats.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshStats.h
Labels: sig/graphics-audio

#18750 Add missing include in DX12/ShaderResourceGroupPool.h
  Gems/Atom/RHI/DX12/Code/Source/RHI/ShaderResourceGroupPool.h
Labels: sig/graphics-audio

#18749 Ensure for-each loops with AZ::RPI::Pass::m_attachmentBindings use the correct attachment binding count
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Pass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/PassAttachment.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/CopyPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Pass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/PassAttachment.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/RenderPass.cpp
Labels: sig/graphics-audio

#18748 Add missing dereference operator in deque at() function
  Code/Framework/AzCore/AzCore/std/containers/deque.h
Labels: sig/core

#18770 [TrackView] Fix Disabling Sub-Tacks.
  Gems/Maestro/Code/Source/Cinematics/AnimComponentNode.cpp
Labels: feature/trackview, sig/content
