Repository o3de/o3de, pull requests merged in 2025-06, with the labels that each got.

#18995 Fix crash on startup issue for 25050
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/AtomLyIntegration/AtomFont/Code/Source/AtomFont.cpp
Labels: sig/content, sig/graphics-audio, need-sync/to-development

#18992 Fixed crash when doing Cubemap Captures.
  Gems/Atom/Feature/Common/Code/Source/CubeMapCapture/CubeMapRenderer.cpp
Labels: sig/graphics-audio, need-sync/to-stabilization

#18997 Cherrypick from stab - Fix crash on startup issue for 25050
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/AtomLyIntegration/AtomFont/Code/Source/AtomFont.cpp
Labels: sig/graphics-audio, sync/to-development

#18998 Fix memory leak related to vertex/pixel/compute shader functions for Metal
  Gems/Atom/RHI/Metal/Code/Source/RHI/PipelineState.cpp
Labels: sig/graphics-audio, need-sync/to-development

#18988 Fix ScriptCanvasNode Template
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/Prefab/PrefabSaveLoadHandler.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Grammar/AbstractCodeModel.cpp
  Templates/ScriptCanvasNode/Template/${Name}_files.cmake
  Templates/ScriptCanvasNode/Template/CMakeLists.txt
  Templates/ScriptCanvasNode/Template/Source/${Name}.cpp
Labels: sig/content, need-sync/to-stabilization

#18900 Added possibility to extract physics shape configuration without PhysX Gem bus
  Code/Framework/AzFramework/AzFramework/Physics/Shape.h
  Code/Framework/AzFramework/AzFramework/Physics/ShapeConfiguration.h
  Gems/PhysX/Common/Code/Mocks/PhysX/MockPhysicsShape.h
  Gems/PhysX/Core/Code/Source/Shape.cpp
  Gems/PhysX/Core/Code/Source/Shape.h
  Gems/ScriptCanvasPhysics/Code/Tests/ScriptCanvasPhysicsTest.cpp
Labels: sig/simulation

#19001 Fixes various CMake related warnings CMP0177 that happen if you use SDK builds.
  cmake/Packaging.cmake
  cmake/Platform/Common/Install_common.cmake
Labels: sig/build, need-sync/to-stabilization

#18719 ScriptCanvas breakpoint support : Allow to add breakpoint on node and stop execution when breakpoint is hit (disabled behind code)
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Editor/GraphModelBus.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointActionsMenuGroup.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointActionsMenuGroup.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointContextMenuAction.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointContextMenuActions.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenuActions/BreakpointMenuActions/BreakpointContextMenuActions.h
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenus/NodeContextMenu.cpp
  Gems/GraphCanvas/Code/StaticLib/GraphCanvas/Widgets/EditorContextMenu/ContextMenus/NodeContextMenu.h
  Gems/GraphCanvas/Code/graphcanvas_staticlib_files.cmake
  Gems/ScriptCanvas/Code/Editor/Components/EditorGraph.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorGraph.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Core/ExecutionNotificationsBus.h
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/Debugger.h
Labels: feature/scripting, sig/content, status/ready-for-merge

#19009 Fix a race condition in GeometryView
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/AuxGeomBase.h
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/DynamicPrimitiveProcessor.h
  Gems/Atom/Feature/Common/Code/Source/AuxGeom/FixedShapeProcessor.h
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ReflectionProbe/ReflectionProbe.h
  Gems/Atom/Feature/Common/Code/Source/Shadows/ProjectedShadowFeatureProcessor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/GeometryView.h
  Gems/Atom/RHI/Code/Tests/MultiDeviceDrawPacketTests.cpp
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/FullscreenTrianglePass.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/Pass/Specific/ImageAttachmentPreviewPass.h
  Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp
  Gems/AtomTressFX/Code/Rendering/HairRenderObject.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGrid.h
  Gems/Stars/Code/Source/StarsFeatureProcessor.h
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
Labels: sig/graphics-audio, status/ready-for-merge

#19003 [LUA Editor] Fix autofocus issue for the goto line dialog and support also columns
  Code/Tools/LuaIDE/Source/LUA/LUAEditorGoToLineDialog.cpp
  Code/Tools/LuaIDE/Source/LUA/LUAEditorGoToLineDialog.hxx
  Code/Tools/LuaIDE/Source/LUA/LUAEditorGoToLineDialog.ui
  Code/Tools/LuaIDE/Source/LUA/LUAEditorMainWindow.cpp
Labels: sig/content, feature/lua-ide, status/ready-for-merge

#19019 DPE : Fix search linting on widgets
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/DocumentAdapter.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyHandlerWidget.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/ValueStringFilter.cpp
Labels: sig/content, feature/properties, status/ready-for-merge

#19024 Improves AP startup time and CPU Usage
  Code/Tools/AssetBundler/source/utils/applicationManager.cpp
  Code/Tools/AssetProcessor/native/assetprocessor.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCCommon.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCCommon.h
  Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/RCQueueSortModel.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rccontroller.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjob.h
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.cpp
  Code/Tools/AssetProcessor/native/resourcecompiler/rcjoblistmodel.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.cpp
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetManagerTestingBase.h
  Code/Tools/AssetProcessor/native/tests/assetmanager/AssetProcessorManagerTest.cpp
  Code/Tools/AssetProcessor/native/tests/resourcecompiler/RCControllerTest.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.cpp
  Code/Tools/AssetProcessor/native/ui/MainWindow.ui
  Code/Tools/AssetProcessor/native/unittests/RCcontrollerUnitTests.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManagerBase.cpp
  Code/Tools/AssetProcessor/native/utilities/GUIApplicationManager.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.cpp
  Code/Tools/AssetProcessor/native/utilities/PlatformConfiguration.h
  Code/Tools/AssetProcessor/native/utilities/assetUtils.cpp
  Code/Tools/AssetProcessor/native/utilities/assetUtils.h
  Gems/Atom/RPI/Code/Include/Atom/RPI.Reflect/Asset/AssetUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilderUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialBuilderUtils.h
  Gems/Atom/RPI/Code/Source/RPI.Builders/Material/MaterialTypeBuilder.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Asset/AssetUtils.cpp
  Gems/Atom/RPI/Code/Source/RPI.Reflect/Model/ModelAsset.cpp
  Registry/settings.assetprocessorbatch.setreg
Labels: feature/asset-pipeline, sig/content

#19032 Fix some issues with drag interactivity in the Asset AssetBrowser
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/AssetFolderThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserTableViewProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserViewUtils.h
Labels: sig/content

#18986 fix-vulkan12Features-missassigments
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
Labels: sig/graphics-audio, need-sync/to-stabilization

#19034 DPE : Prevent currentColumnLayout nullptr to be deref
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Labels: sig/core, need-sync/to-stabilization

#19041 Removes deprecated ConsoleHelpGen system
  Code/Legacy/CrySystem/ConsoleHelpGen.cpp
  Code/Legacy/CrySystem/ConsoleHelpGen.h
  Code/Legacy/CrySystem/XConsole.cpp
  Code/Legacy/CrySystem/XConsole.h
  Code/Legacy/CrySystem/crysystem_files.cmake
Labels: sig/core

#19035 Remove AR retry action, Windows workflow fixes
  .github/workflows/android-build.yml
  .github/workflows/linux-build.yml
  .github/workflows/windows-build.yml
Labels: sig/build

#19067 Make AZ::RHI::GeometryView constructor with one parameter explicit
  Code/Framework/AzToolsFramework/AzToolsFramework/ComponentMode/EditorBaseComponentMode.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/LegacyFramework/Core/EditorFrameworkApplication.cpp
  Code/Tools/AssetProcessor/native/utilities/ApplicationManager.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/GeometryView.h
  Gems/Atom/RPI/Code/Source/RPI.Public/Model/ModelLod.cpp
Labels: sig/graphics-audio

#19061 Fix the coordinate system transform for fbx animations.
  Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp
  Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.h
  Code/Tools/SceneAPI/SceneBuilder/SceneSystem.cpp
Labels: sig/content

#19057 Fix a potential AP crash when reprocessing assets
  Code/Tools/AssetProcessor/native/AssetManager/assetProcessorManager.cpp
Labels: sig/content

#19045 Fixes the installer o3de.sh script working on linux.
  scripts/o3de.sh
Labels: sig/platform, need-sync/to-stabilization

#19040 Fix missing restricted objects being an error
  cmake/PAL.cmake
  scripts/o3de.py
  scripts/o3de/o3de/disable_gem.py
  scripts/o3de/o3de/download.py
  scripts/o3de/o3de/engine_template.py
  scripts/o3de/o3de/global_project.py
  scripts/o3de/o3de/register.py
  scripts/o3de/o3de/repo.py
  scripts/o3de/o3de/utils.py
Labels: sig/build, sig/platform, need-sync/to-stabilization

#18989 Make the DeviceMask in RaytracingFeatureProcessor dynamic
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingCompactionQueryPool.h
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingCompactionQueryPool.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationPreparePass.cpp
Labels: sig/graphics-audio, status/ready-for-merge

#19053 Fix #19047 - Fix External scripts editor settings
  Code/Editor/AzAssetBrowser/AzAssetBrowserRequestHandler.cpp
  Code/Editor/EditorPreferencesPageFiles.cpp
  Code/Editor/Settings.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/AssetBrowserBus.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Script/LuaEditorSystemComponent.cpp
Labels: sig/content, status/ready-for-merge

#19059 fix-descriptorBindingPartiallyBound-misassignment
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/PhysicalDevice.h
Labels: sig/graphics-audio, status/ready-for-merge

#19050 Slice Level UI Removal | Remove level export and LevelBuilder (supersedes #17676)
  Code/Editor/Core/EditorActionsHandler.cpp
  Code/Editor/CryEdit.cpp
  Code/Editor/CryEdit.h
  Code/Editor/CryEditDoc.cpp
  Code/Editor/CryEditPy.cpp
  Code/Editor/Lib/Tests/test_CryEditPythonBindings.cpp
  Code/Editor/LogFile.cpp
  Code/Editor/Resource.h
  Gems/LmbrCentral/Code/Source/Builders/LevelBuilder/LevelBuilderComponent.cpp
  Gems/LmbrCentral/Code/Source/Builders/LevelBuilder/LevelBuilderComponent.h
  Gems/LmbrCentral/Code/Source/Builders/LevelBuilder/LevelBuilderWorker.cpp
  Gems/LmbrCentral/Code/Source/Builders/LevelBuilder/LevelBuilderWorker.h
  Gems/LmbrCentral/Code/Source/LmbrCentralEditor.cpp
  Gems/LmbrCentral/Code/lmbrcentral_editor_files.cmake
Labels: sig/content, sig/core, sig/ui-ux, status/ready-for-merge

#19075 Fixes potential deadlocks in Atom related to the queue system
  Gems/Atom/RHI/Code/Source/RHI/AsyncWorkQueue.cpp
  Gems/Atom/RHI/Code/Source/RHI/CommandQueue.cpp
Labels: sig/graphics-audio, need-sync/to-stabilization

#19084 Fixes a crash that occurs when meshes update in RaytraceFeatureProcessor (due to hot reload or AP finish)
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
Labels: sig/graphics-audio, need-sync/to-stabilization

#19086 Add maybe_unused to fix vegetation test gem build on MSVC latest
  Gems/Vegetation/Code/Tests/PrefabInstanceSpawnerTests.cpp
Labels: sig/build, feature/build, feature/vegetation, build_failure/development
