Repository o3de/o3de, pull requests merged in 2025-05, with the labels that each got.

#18844 Add an option for assimp importer to extract embedded textures from model files.
  Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.cpp
  Code/Tools/SceneAPI/SDKWrapper/AssImpSceneWrapper.h
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.cpp
  Code/Tools/SceneAPI/SceneBuilder/Importers/AssImpMaterialImporter.h
  Code/Tools/SceneAPI/SceneCore/Import/SceneImportSettings.cpp
  Code/Tools/SceneAPI/SceneCore/Import/SceneImportSettings.h
Labels: sig/content

#18877 Allow transient attachments to be on multiple devices
  Gems/Atom/RHI/Code/Source/RHI/FrameGraphCompiler.cpp
Labels: sig/graphics-audio

#18882 Disable RTAS compaction for models with too many submeshes
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
Labels: sig/graphics-audio

#18881 RaytracingAccelerationStructurePass: MultiDevice Refactor
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetComputePass.cpp
  Gems/Atom/Feature/Common/Code/Source/MorphTargets/MorphTargetComputePass.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingAccelerationStructurePass.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshComputePass.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshComputePass.h
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshFeatureProcessor.h
  Gems/Atom/RHI/Code/Source/RHI/DeviceShaderResourceGroupData.cpp
Labels: sig/graphics-audio

#18899 Fixing DrawLinear issue in DynamicDrawContext caused by GeometryView changes
  Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
Labels: sig/graphics-audio, need-sync/to-development

#18901 Cherrypick from dev: Fixing DrawLinear issue in DynamicDrawContext caused by GeometryView
  Gems/Atom/RPI/Code/Source/RPI.Public/DynamicDraw/DynamicDrawContext.cpp
Labels: sync/to-stabilization

#18889 Use AZ::Data::AssetHandler::SaveAssetData to serialize in memory asset in AssetEditorTab::GenerateSaveDataSnapshot().
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
Labels: sig/content

#18888 add .command_settings file to ScriptOnlyProject template, fix #18887
  Templates/ScriptOnlyProject/Template/.command_settings
  Templates/ScriptOnlyProject/template.json
Labels: sig/core

#18906 Set correct jittered matrix to view srg. (fixes #18467)
  Gems/Atom/RPI/Code/Source/RPI.Public/View.cpp
Labels: sig/graphics-audio

#18912 Moves ImGuiPass into the public API section
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ImGui/ImGuiPass.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
Labels: sig/graphics-audio, need-sync/to-development

#18911 Prevents creation of invalid project/gem/template names
  scripts/o3de/o3de/engine_template.py
Labels: sig/content, need-sync/to-development

#18926 Fixes mesh visibilty flag not being restored on level load
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/EditorMeshComponent.cpp
Labels: sig/graphics-audio, need-sync/to-development

#18916 periodic merge from stabilization/25050 to development
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lights/Ltc.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ImGui/ImGuiPass.h
  Gems/Atom/Feature/Common/Code/Source/CommonSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.cpp
  Gems/Atom/Feature/Common/Code/Source/CoreLights/ShadowmapPass.h
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiPass.cpp
  Gems/Atom/Feature/Common/Code/Source/ImGui/ImGuiSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/RenderAttachmentLayout.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/RenderAttachmentLayout.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Scene.cpp
  Gems/RecastNavigation/Code/CMakeLists.txt
  Gems/RecastNavigation/Code/recast-o3de.patch
  scripts/o3de/o3de/engine_template.py
Labels: sig/core, sync/to-development

#18892 Fix OnActiveViewChanged event in scripts
  Gems/Camera/Code/Source/CameraComponent.cpp
Labels: sig/content

#18913 Change ray tracing RHI descriptors to declarative style
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingPipelineState.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingShaderTable.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingPipelineState.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingShaderTable.h
  Gems/Atom/RHI/Code/Source/RHI/DeviceRayTracingAccelerationStructure.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceRayTracingPipelineState.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceRayTracingShaderTable.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/Code/Source/RHI/RayTracingShaderTable.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingShaderTable.cpp
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingTlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingPipelineState.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingShaderTable.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingTlas.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationPreparePass.cpp
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridVisualizationRayTracingPass.cpp
Labels: sig/graphics-audio

#18935 Cherrypick texture uniform fixes from dev to stabilization for 2505.0
  Gems/LyShine/Assets/LyShine/Shaders/LyShineUI.azsl
  Gems/Terrain/Assets/Shaders/Terrain/TerrainDetailHelpers.azsli
Labels: sig/graphics-audio, sync/to-stabilization

#18894 Add Fabrik blend tree node.
  Gems/EMotionFX/Code/EMotionFX/Source/AnimGraphObjectFactory.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFabrikNode.cpp
  Gems/EMotionFX/Code/EMotionFX/Source/BlendTreeFabrikNode.h
  Gems/EMotionFX/Code/EMotionFX/emotionfx_files.cmake
Labels: sig/simulation

#18959 Fix LightingChannelFlags in LightingChannelConfiguration
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/LightingChannel/LightingChannelConfiguration.h
  Gems/Atom/Feature/Common/Code/Source/LightingChannel/LightingChannelConfiguration.cpp
Labels: sig/graphics-audio

#18928 Vulkan: Fix HDR crash
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceSwapChain.h
  Gems/Atom/RHI/Code/Source/RHI/DeviceSwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Labels: sig/graphics-audio

#18970 Vulkan: Fix HDR crash (#18928)
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceSwapChain.h
  Gems/Atom/RHI/Code/Source/RHI/DeviceSwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Device.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/Instance.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/SwapChain.h
Labels: sig/graphics-audio, sync/to-stabilization

#18952 Improved AssetEditor recent files and last used folders
  Code/Editor/AssetEditor/AssetEditorWindow.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorTab.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetEditor/AssetEditorWidget.h
Labels: sig/content

#18953 CharacterController_FixUpDirection
  Gems/PhysX/Core/Code/Source/PhysXCharacters/API/CharacterController.cpp
  Gems/PhysX/Core/Code/Source/PhysXCharacters/Components/CharacterControllerComponent.cpp
Labels: feature/physics, sig/simulation

#18968 Fix error appearing when GPU doesn't support ray tracing.
  Gems/Atom/RHI/Code/Include/Atom/RHI/DispatchRaysItem.h
Labels: sig/graphics-audio, need-sync/to-stabilization
