Repository o3de/o3de, pull requests merged in 2025-08, with the labels that each got.

#19166 Change Atom_Feature_Common.Public target to shared library
  Gems/Atom/Feature/Common/Code/3rdParty/ACES/ACES/Aces.h
  Gems/Atom/Feature/Common/Code/CMakeLists.txt
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ACES/AcesDisplayMapperFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Base.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/CoreLights/PhotometricValue.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/DisplayMapper/DisplayMapperConfigurationDescriptor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/ImGui/ImGuiPass.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/LightingChannel/LightingChannelConfiguration.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Material/ConvertEmissiveUnitFunctor.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/MorphTargets/MorphTargetInputBuffers.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingPass.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkinnedMesh/SkinnedMeshInputBuffers.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkinnedMesh/SkinnedMeshInstance.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SkyBox/SkyBoxFogSettings.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/SplashScreen/SplashScreenSettings.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/FrameCaptureBus.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/FrameCaptureTestBus.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/GpuBufferHandler.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/LightingPreset.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Utils/ModelPreset.h
  Gems/Atom/Feature/Common/Code/Source/FrameCaptureSystemComponent.cpp
  Gems/Atom/Feature/Common/Code/Source/Utils/FrameCaptureBus.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
Labels: sig/graphics-audio, need-sync/to-stabilization

#19172 GHA AR 3P Dev Bucket
  .github/workflows/android-build.yml
  .github/workflows/linux-build.yml
  .github/workflows/windows-build.yml
Labels: sig/build

#19060 Introduce Alternate Frame Rendering capability to the engine
  Gems/AFR/CMakeLists.txt
  Gems/AFR/Code/CMakeLists.txt
  Gems/AFR/Code/Include/AFR/AFRBus.h
  Gems/AFR/Code/Include/AFR/AFRFeatureProcessor.h
  Gems/AFR/Code/Include/AFR/AFRTypeIds.h
  Gems/AFR/Code/Source/AFRFeatureProcessor.cpp
  Gems/AFR/Code/Source/AFRModuleInterface.cpp
  Gems/AFR/Code/Source/AFRModuleInterface.h
  Gems/AFR/Code/Source/Clients/AFRModule.cpp
  Gems/AFR/Code/Source/Clients/AFRSystemComponent.cpp
  Gems/AFR/Code/Source/Clients/AFRSystemComponent.h
  Gems/AFR/Code/Source/Tools/AFREditorModule.cpp
  Gems/AFR/Code/Source/Tools/AFREditorSystemComponent.cpp
  Gems/AFR/Code/Source/Tools/AFREditorSystemComponent.h
  Gems/AFR/Code/afr_api_files.cmake
  Gems/AFR/Code/afr_editor_private_files.cmake
  Gems/AFR/Code/afr_editor_shared_files.cmake
  Gems/AFR/Code/afr_private_files.cmake
  Gems/AFR/Code/afr_shared_files.cmake
  Gems/AFR/gem.json
  Gems/AFR/preview.png
  engine.json
Labels: sig/graphics-audio

#19178 Fix android license for AR
  .github/workflows/android-build.yml
Labels: sig/build

#18711 Add an option in lod importer to automatically generate missing lods to the model builder component.
  Code/Tools/SceneAPI/SceneData/Rules/LodRule.cpp
  Code/Tools/SceneAPI/SceneData/Rules/LodRule.h
  Gems/Atom/RPI/3rdParty/Findmeshoptimizer.cmake
  Gems/Atom/RPI/3rdParty/Installer/Findmeshoptimizer.cmake
  Gems/Atom/RPI/3rdParty/meshoptimizer/LICENSE.md
  Gems/Atom/RPI/Code/CMakeLists.txt
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/ModelAssetBuilderComponent.cpp
  Gems/Meshlets/CMakeLists.txt
  Gems/Meshlets/Code/CMakeLists.txt
  Gems/Meshlets/Code/Source/Meshlets/MeshletsAssets.h
  Gems/Meshlets/Code/Source/Meshlets/MeshletsData.h
  Gems/Meshlets/Code/Source/Meshlets/MeshletsFeatureProcessor.cpp
  Gems/Meshlets/Code/Source/Meshlets/MeshletsFeatureProcessor.h
  Gems/Meshlets/Code/Source/Meshlets/MeshletsRenderObject.h
  Gems/Meshlets/Code/Source/Meshlets/MeshletsRenderPass.h
  Gems/Meshlets/Code/Source/Meshlets/MultiDispatchComputePass.h
  Gems/Meshlets/External/Lib/meshoptimizer.txt
  Gems/Meshlets/External/meshoptimizer.h
Labels: sig/content, status/ready-for-merge

#19176 Remove default constructor from AZ::RHI::GeometryView
  Gems/Atom/RHI/Code/Include/Atom/RHI/GeometryView.h
Labels: sig/graphics-audio

#19175 Fix call to single-device function in multi-device RayTracingTlas::GetTlasInstancesBuffer()
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
Labels: sig/graphics-audio

#19151 Fixes blendshapes ("morph targets") not working
  Gems/Atom/RPI/Code/Source/RPI.Builders/Model/MorphTargetExporter.cpp
Labels: sig/graphics-audio, need-sync/to-stabilization

#19174 Fix#19065 Limit user's pitch input in GotoPositionDialog
  Code/Editor/GotoPositionDlg.cpp
Labels: sig/content

#19173 Add a field in MotionRangeRule that allows playback speed to be adjusted.
  Gems/EMotionFX/Code/EMotionFX/Pipeline/RCExt/Motion/MotionDataBuilder.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Behaviors/MotionRangeRuleBehavior.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MotionRangeRule.cpp
  Gems/EMotionFX/Code/EMotionFX/Pipeline/SceneAPIExt/Rules/MotionRangeRule.h
Labels: sig/simulation

#19188 Fix compile error in AFR gem due to unused variable in release build
  Gems/AFR/Code/Source/AFRFeatureProcessor.cpp
Labels: sig/graphics-audio

#19183 BUGFIX - Fixes cloth simulation rendering
  Gems/NvCloth/Code/Source/Components/ClothComponentMesh/ClothComponentMesh.cpp
Labels: sig/graphics-audio, need-sync/to-development

#19181 Filter out abstract classes when enumerating derived classes in ReflectionAdapter.
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
Labels: sig/content, sig/core

#19185 fix-editor-go-to-position v2
  Code/Editor/GotoPositionDlg.cpp
Labels: sig/content

#19184 FTUE: When patching a 3rd party library, check for GIT
  cmake/PatchIfNotAlreadyPatched.cmake
Labels: sig/build, need-sync/to-development

#19200 Fixes release only clang compiler error due to unused variable in xcb
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp
Labels: sig/core, need-sync/to-stabilization

#19204 Removes the spam during configure related to "restricted"
  cmake/Gems.cmake
  cmake/PAL.cmake
Labels: sig/build

#19186 Fix crash after resuming Android build
  Code/LauncherUnified/Platform/Android/Launcher_Android.cpp
Labels: sig/core, sig/platform

#19228 Add operator[] for vector and matrix types.
  Code/Framework/AzCore/AzCore/Math/Matrix3x3.h
  Code/Framework/AzCore/AzCore/Math/Matrix3x3.inl
  Code/Framework/AzCore/AzCore/Math/Matrix3x4.h
  Code/Framework/AzCore/AzCore/Math/Matrix3x4.inl
  Code/Framework/AzCore/AzCore/Math/Matrix4x4.h
  Code/Framework/AzCore/AzCore/Math/Matrix4x4.inl
  Code/Framework/AzCore/AzCore/Math/Vector2.h
  Code/Framework/AzCore/AzCore/Math/Vector2.inl
  Code/Framework/AzCore/AzCore/Math/Vector3.h
  Code/Framework/AzCore/AzCore/Math/Vector3.inl
  Code/Framework/AzCore/AzCore/Math/Vector4.h
  Code/Framework/AzCore/AzCore/Math/Vector4.inl
Labels: sig/core
