Repository o3de/o3de, pull requests merged in 2025-07, with the labels that each got.

#18980 Fix shared framework unit test failures
  Code/Framework/AzCore/AzCore/Asset/AssetSerializer.h
  Code/Framework/AzCore/AzCore/Component/ComponentApplication.cpp
  Code/Framework/AzCore/AzCore/Debug/Trace.cpp
  Code/Framework/AzCore/AzCore/Math/Crc.cpp
  Code/Framework/AzCore/AzCore/Module/ModuleManager.cpp
  Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h
  Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
  Code/Framework/AzCore/AzCore/Serialization/DataPatch.cpp
  Code/Framework/AzCore/AzCore/Serialization/DataPatch.h
  Code/Framework/AzCore/AzCore/Serialization/SerializeContext.cpp
  Code/Framework/AzCore/AzCore/Serialization/SerializeContext.h
  Code/Framework/AzCore/AzCore/Serialization/std/VariantReflection.inl
  Code/Framework/AzCore/AzCore/Settings/ConfigurableStack.inl
  Code/Framework/AzCore/AzCore/UnitTest/TestTypes.h
  Code/Framework/AzCore/Platform/Windows/platform_windows_files.cmake
  Code/Framework/AzCore/Tests/Patching.cpp
  Code/Framework/AzCore/Tests/Serialization.cpp
  Code/Framework/AzCore/Tests/Serialization/Json/TestCases_TypeId.cpp
  Code/Framework/AzFramework/AzFramework/Archive/ZipDirList.h
  Code/Framework/AzFramework/AzFramework/Archive/ZipDirStructures.h
  Code/Framework/AzFramework/Platform/Linux/AzFramework/Application/Application_Linux.cpp
  Code/Framework/AzFramework/Tests/Platform/Common/Xcb/XcbInputDeviceKeyboardTests.cpp
  Code/Framework/AzFramework/Tests/Platform/Linux/platform_specific_test_targets.cmake
  Code/Framework/AzTest/AzTest/GemTestEnvironment.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/EditorSelectionAccentSystemComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/aztoolsframework_files.cmake
  Code/Legacy/CrySystem/AZCoreLogSink.h
  Code/Tools/AssetProcessor/native/tests/AssetProcessorMessagesTests.cpp
  Code/Tools/ProjectManager/Platform/Linux/ProjectUtils_linux.cpp
  Code/Tools/SceneAPI/SceneCore/DllMain.cpp
  Code/Tools/SceneAPI/SceneData/DllMain.cpp
  Gems/Atom/Asset/ImageProcessingAtom/Code/Tests/ImageProcessing_Test.cpp
  Gems/Atom/RPI/Code/Source/RPI.Edit/Common/DllMain.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/DllMain.cpp
  Gems/Atom/RPI/Code/Tests.Builders/BuilderTestFixture.cpp
  Gems/Atom/RPI/Code/Tests/Common/AssetManagerTestFixture.cpp
  Gems/Atom/RPI/Code/Tests/Material/MaterialPropertySerializerTests.cpp
  Gems/EditorPythonBindings/Code/Tests/PythonGlobalsTests.cpp
  Gems/GraphModel/Code/Tests/TestEnvironment.cpp
  Gems/PhysX/Core/Code/Tests/PhysXTestEnvironment.cpp
  Gems/PhysX/Core/PhysX4/Source/Module.cpp
  Gems/PhysX/Core/PhysX5/Source/Module.cpp
  Gems/Terrain/Code/Tests/TerrainTestFixtures.cpp
  Gems/Vegetation/Code/Tests/PrefabInstanceSpawnerTests.cpp
Labels: do-not-merge/invalid-commit-message, sig/core

#19103 Fixes `main` tests running a periodic test which fails
  AutomatedTesting/Gem/PythonTests/assetpipeline/CMakeLists.txt
  AutomatedTesting/Gem/PythonTests/assetpipeline/metadata_relocation_tests/CMakeLists.txt
  AutomatedTesting/Levels/MetadataTest/MetadataTest.prefab
Labels: kind/test, sig/testing

#19129 Cherry-pick from Point Release 25.05.1 - Fix O3DE Splash Screen background for 25.05 (#19046)
  Code/Editor/splashscreen_background.png
Labels: sig/release, sync/to-development

#19131 Cherry-pick from point release 2505.1 - Fixes all `unused variable` compile warnings.
  Code/Framework/AzCore/AzCore/Instance/InstancePool.h
  Code/Framework/AzFramework/AzFramework/Spawnable/SpawnableMonitor.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/PaletteCardCollection.cpp
  Code/Framework/AzQtComponents/AzQtComponents/Components/Widgets/ColorPicker/PaletteCardCollection.h
  Code/Tools/CrashHandler/Support/platform/Windows/crash_handler_support_windows_files.cmake
  Gems/ScriptEvents/Code/Include/ScriptEvents/ScriptEventsAssetRef.h
Labels: sig/build

#19132 Defuse an assert when not using the SceneMaterialSrg (e.g. on android)
  Gems/Atom/RPI/Code/Source/RPI.Public/Material/MaterialSystem.cpp
Labels: sig/graphics-audio

#19102 Non-global DepthLinear attachment connection for SSAO
  Gems/Atom/Feature/Common/Assets/Passes/OpaqueParent.pass
  Gems/Atom/Feature/Common/Assets/Passes/SsaoParent.pass
Labels: sig/graphics-audio

#19105 Add support for additional ray tracing vertex formats
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneUtils.azsli
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/Atom/RHI/Assets/ShaderLib/Atom/RHI/IndexFormat.azsli
  Gems/Atom/RHI/Assets/ShaderLib/Atom/RHI/VertexFormat.azsli
  Gems/Atom/RHI/Assets/atom_rhi_asset_files.cmake
  Gems/Atom/RHI/Code/CMakeLists.txt
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/IndexFormat.h
  Gems/Atom/RHI/Code/Include/Atom/RHI.Reflect/VertexFormat.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceIndexBufferView.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/DeviceRayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Include/Atom/RHI/RayTracingAccelerationStructure.h
  Gems/Atom/RHI/Code/Source/RHI.Reflect/IndexFormat.cpp
  Gems/Atom/RHI/Code/Source/RHI.Reflect/VertexFormat.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceIndexBufferView.cpp
  Gems/Atom/RHI/Code/atom_rhi_reflect_files.cmake
  Gems/Atom/RHI/DX12/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RayTracingBlas.cpp
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/VertexBufferOperations.azsli
  Gems/Atom/RPI/Assets/atom_rpi_asset_files.cmake
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridFeatureProcessor.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
Labels: sig/graphics-audio

#19018 Added UiElementGroup to LyShine Gem Components.
  Gems/LyShine/Code/Include/LyShine/Bus/UiHierarchyInteractivityToggleBus.h
  Gems/LyShine/Code/Source/LyShineModule.cpp
  Gems/LyShine/Code/Source/LyShineSystemComponent.cpp
  Gems/LyShine/Code/Source/UiHierarchyInteractivityToggleComponent.cpp
  Gems/LyShine/Code/Source/UiHierarchyInteractivityToggleComponent.h
  Gems/LyShine/Code/lyshine_static_files.cmake
Labels: sig/content, do-not-merge/in-review, feature/lyshine

#19141 Convert remaining (non-lyshine) slices to prefabs
  Code/Framework/AzFramework/AzFramework/API/ApplicationAPI.h
  Code/Framework/AzFramework/AzFramework/Application/Application.cpp
  Code/Framework/AzFramework/AzFramework/Application/Application.h
  Code/Framework/AzFramework/AzFramework/Entity/EntityOwnershipService.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/EditorEntityContextComponent.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Entity/PrefabEditorEntityOwnershipService.h
  Gems/AtomContent/Sponza/Assets/slices/lightingGRP.slice
  Gems/StartingPointCamera/Assets/Prefabs/Camera/FirstPersonCamera.prefab
  Gems/StartingPointCamera/Assets/Prefabs/Camera/IsometricCamera.prefab
  Gems/StartingPointCamera/Assets/Prefabs/Camera/SecurityCamera.prefab
  Gems/StartingPointCamera/Assets/Prefabs/Camera/SideScrollerCamera.prefab
  Gems/StartingPointCamera/Assets/Prefabs/Camera/ThirdPersonCamera.prefab
  Gems/StartingPointCamera/Assets/Prefabs/Camera/TopDownCamera.prefab
  Gems/StartingPointCamera/Assets/Slices/Camera/FirstPersonCamera.slice
  Gems/StartingPointCamera/Assets/Slices/Camera/IsometricCamera.slice
  Gems/StartingPointCamera/Assets/Slices/Camera/SecurityCamera.slice
  Gems/StartingPointCamera/Assets/Slices/Camera/SideScrollerCamera.slice
  Gems/StartingPointCamera/Assets/Slices/Camera/ThirdPersonCamera.slice
  Gems/StartingPointCamera/Assets/Slices/Camera/TopDownCamera.slice
Labels: sig/content

#19164 Invalidate pointer to prevent undifined behavior in ArticulationLinkComponent
  Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
Labels: sig/simulation

#19163 Fix Clang20 compile errors
  Code/Framework/AzCore/AzCore/DOM/DomValue.cpp
  Code/Framework/AzCore/AzCore/DOM/DomValueWriter.cpp
  Code/Framework/AzCore/AzCore/Task/Internal/Task.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/AssetBrowserEntry.cpp
  Code/Legacy/CryCommon/ISplines.h
  Gems/Archive/Code/Include/Archive/Clients/ArchiveInterfaceStructs.h
  Gems/Archive/Code/Include/Archive/Clients/ArchiveInterfaceStructs.inl
  Gems/AtomTressFX/External/Code/src/Math/Vector3D.cpp
  Gems/AtomTressFX/External/Code/src/Math/Vector3D.h
  Gems/GradientSignal/Code/Source/Editor/EditorGradientImageCreatorUtils.cpp
  Gems/GradientSignal/Code/Tests/EditorGradientSignalBakerTests.cpp
  Gems/ImGui/External/ImGui/v1.82/imgui/imgui.cpp
  Gems/ImGui/External/ImGui/v1.82/imgui/imgui.h
  Gems/ImGui/External/ImGui/v1.82/imgui/imgui_draw.cpp
  Gems/ImGui/External/ImGui/v1.82/imgui/imgui_internal.h
  Gems/ImGui/External/ImGui/v1.82/imgui/imgui_tables.cpp
  Gems/ImGui/External/ImGui/v1.82/imgui/imgui_widgets.cpp
  Gems/LyShine/Code/Source/Animation/2DSpline.h
  Gems/WhiteBox/Code/Source/Core/WhiteBoxToolApi.cpp
Labels: sig/build

#19161 Fixes in Python script to properly support custom splash screens and icons in Android builds.
  scripts/o3de/o3de/android_support.py
Labels: sig/platform
