Repository o3de/o3de, pull requests merged in 2025-09, with the labels that each got.

#19123 Move MeshInfo and MaterialInfo from the RayTracingFeatureProcessor to the MeshFeatureProcessor
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/FallbackPBRMaterial/FallbackPBRMaterial.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/FallbackPBRMaterial/FallbackPBRMaterial_Defines.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/FallbackPBRMaterial/FallbackPBRStandardLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/FallbackPBRMaterial/MaterialInfo.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/FallbackPBRMaterial/MaterialInfoUtil.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/MeshInfo/MeshInfo.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/MeshInfo/MeshInfoBufferUtil.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/MeshInfo/MeshInfoUtil.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/LightingData.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Lighting/StandardLighting.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/PBR/Surfaces/StandardSurface.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingGlobalSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingMaterialUtils.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSceneUtils.azsli
  Gems/Atom/Feature/Common/Assets/ShaderLib/Atom/Features/RayTracing/RayTracingSrgs.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/FallbackPBRMaterial/SceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/MeshInfo/SceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/SceneSrg.azsli
  Gems/Atom/Feature/Common/Assets/ShaderResourceGroups/SceneSrgIncludesAll.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugClosestHit.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugClosestHitProcedural.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Debug/RayTracingDebugCommon.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHit.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHit.azsli
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingClosestHitProcedural.azsl
  Gems/Atom/Feature/Common/Assets/Shaders/Reflections/ReflectionScreenSpaceRayTracingCommon.azsli
  Gems/Atom/Feature/Common/Assets/atom_feature_common_asset_files.cmake
  Gems/Atom/Feature/Common/Code/CMakeLists.txt
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Debug/RayTracingDebugConstants.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Material/FallbackPBRMaterial.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshInfo.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshInfoBus.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingFeatureProcessorInterface.h
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/RayTracing/RayTracingPass.h
  Gems/Atom/Feature/Common/Code/Source/Material/FallbackPBRMaterial.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/FallbackPBRMaterialManager.cpp
  Gems/Atom/Feature/Common/Code/Source/Material/FallbackPBRMaterialManager.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshInfoManager.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshInfoManager.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.cpp
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingFeatureProcessor.h
  Gems/Atom/Feature/Common/Code/Source/RayTracing/RayTracingPass.cpp
  Gems/Atom/Feature/Common/Code/atom_feature_common_files.cmake
  Gems/Atom/Feature/Common/Code/atom_feature_common_public_files.cmake
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/IndexBufferOperations.azsli
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/ShaderResourceGroups/DefaultDrawSrg.azsli
  Gems/Atom/RPI/Assets/ShaderLib/Atom/RPI/VertexBufferOperations.azsli
  Gems/Atom/RPI/Code/Include/Atom/RPI.Public/MeshDrawPacket.h
  Gems/Atom/RPI/Code/Source/RPI.Public/MeshDrawPacket.cpp
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/Debug/RayTracingDebugEditorComponent.cpp
  Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.cpp
  Gems/DebugDraw/Code/Source/DebugDrawSystemComponent.h
  Gems/DiffuseProbeGrid/Code/Source/Render/DiffuseProbeGridRayTracingPass.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.cpp
  Gems/Terrain/Code/Source/TerrainRenderer/TerrainMeshManager.h
Labels: sig/graphics-audio

#19242 Use setup-gradle to ensure that Github Actions uses the right version of Gradle
  .github/workflows/android-build.yml
  scripts/build/Platform/Android/gradle_windows.cmd
Labels: sig/build

#19245 Make BufferViewIndexAndOffset/IndexBufferViewIndexAndOffset creation arguments const
  Gems/Atom/Feature/Common/Code/Include/Atom/Feature/Mesh/MeshInfo.h
  Gems/Atom/Feature/Common/Code/Source/Mesh/MeshInfoManager.cpp
Labels: sig/graphics-audio

#19251 Remove some no longer necessary const_cast expressions in Atom
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/BuilderSettings/TextureSettings.cpp
  Gems/Atom/Feature/Common/Code/Source/Mesh/StreamBufferViewsBuilder.cpp
  Gems/Atom/Feature/Common/Code/Source/SkinnedMesh/SkinnedMeshInputBuffers.cpp
  Gems/Atom/RHI/Code/Source/RHI/DeviceDrawPacket.cpp
  Gems/Atom/RHI/Code/Tests/DrawPacketTests.cpp
  Gems/Atom/RHI/Vulkan/Code/Source/RHI/RenderPass.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/Pass/Specific/DownsampleSinglePassLuminancePass.cpp
Labels: sig/graphics-audio

#19234 Fixes a missing target for compiling from install
  Gems/MiniAudio/3rdParty/Findminiaudio.cmake
Labels: sig/graphics-audio

#19255 Replaces name fields of assets in Particle with Asset References
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.h
  Code/Tools/AssetProcessor/native/AssetManager/AssetCatalog.cpp
  Gems/OpenParticleSystem/Code/Include/OpenParticleSystem/Asset/ParticleArchive.h
  Gems/OpenParticleSystem/Code/Include/OpenParticleSystem/EditorParticleSystemComponentRequestBus.h
  Gems/OpenParticleSystem/Code/Include/OpenParticleSystem/Serializer/ParticleAssetData.h
  Gems/OpenParticleSystem/Code/Include/OpenParticleSystem/Serializer/ParticleSourceData.h
  Gems/OpenParticleSystem/Code/Source/Builder/ParticleBuilder.cpp
  Gems/OpenParticleSystem/Code/Source/Editor/EditorSystemComponent.cpp
  Gems/OpenParticleSystem/Code/Source/Editor/EditorSystemComponent.h
  Gems/OpenParticleSystem/Code/Source/Editor/Serializer/ParticleAssetData.cpp
  Gems/OpenParticleSystem/Code/Source/Editor/Serializer/ParticleSourceData.cpp
  Gems/OpenParticleSystem/Code/Source/Editor/Serializer/ParticleSystemSerializer.cpp
  Gems/OpenParticleSystem/Code/Source/Editor/Serializer/ParticleSystemSerializer.h
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/AssetWidget.cpp
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/AssetWidget.h
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/ComboBoxWidget.cpp
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/ComboBoxWidget.h
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/EffectorInspector.cpp
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/EffectorInspector.h
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/ParticleGraphicsView.cpp
  Gems/OpenParticleSystem/Tools/OpenParticleSystemEditor/Window/ParticleItemWidget.cpp
Labels: sig/content

#19259 Fix monolithic builds trying to build dummy O3DE Launcher app
  Code/LauncherUnified/launcher_generator.cmake
  cmake/Platform/Common/Install_common.cmake
Labels: sig/build, need-sync/to-stabilization

#19247 Fixes a compile issue specific to clang 18
  Code/Framework/AzCore/AzCore/std/utility/expected.h
  Code/Framework/AzCore/AzCore/std/utility/pair.h
  cmake/Platform/Common/Clang/Configurations_clang.cmake
Labels: sig/build, need-sync/to-development

#19261 Revert "Delay viewport resize to prevent freezing the editor on contnuous resize (#19033)"
  Gems/Atom/Tools/AtomToolsFramework/Code/Include/AtomToolsFramework/Viewport/RenderViewportWidget.h
  Gems/Atom/Tools/AtomToolsFramework/Code/Source/Viewport/RenderViewportWidget.cpp
Labels: sig/graphics-audio

#19268 Update installer and cmake to 3.24.x
  AutomatedTesting/CMakeLists.txt
  CMakeLists.txt
  Gems/RecastNavigation/Code/recast-o3de.patch
  README.md
  Templates/DefaultProject/Template/CMakeLists.txt
  Templates/MinimalProject/Template/CMakeLists.txt
  Templates/ScriptOnlyProject/Template/CMakeLists.txt
  cmake/Packaging.cmake
  cmake/Platform/Common/runtime_dependencies_common.cmake.in
  cmake/Platform/Linux/Packaging_linux.cmake
  cmake/Platform/Linux/runtime_dependencies_linux.cmake.in
  cmake/Platform/Mac/PreInstallSteps_mac.cmake.in
  cmake/Platform/Mac/runtime_dependencies_mac.cmake.in
  cmake/Platform/Windows/Packaging/PostInstallSetup.wxs
  cmake/Platform/Windows/Packaging_windows.cmake
  python/get_python.cmake
  python/get_python_package_hash.cmake
  scripts/license_scanner/license_scanner.py
  scripts/license_scanner/scanner_config.json
  scripts/o3de/tests/test_android.py
Labels: sig/build, sig/release
