Repository o3de/o3de, pull requests merged in 2025-04, with the labels that each got.

#6202 Fixed bug induced by level name length
  Code/Editor/NewLevelDialog.cpp
Labels: sig/content

#18791 (stabilization) BUGFIX - Crash on CTRL+G if SC is open.
  Gems/ScriptCanvas/Code/CMakeLists.txt
Labels: sig/content

#18782 (Stabilization) BUGFIX - lua editor connectivty with ringbuffer error message
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp
Labels: sig/network

#15892 Remove std::is_pod from AzCore
  Code/Framework/AzCore/AzCore/Script/ScriptContext.cpp
  Code/Framework/AzCore/AzCore/Serialization/AZStdContainers.inl
  Code/Framework/AzCore/AzCore/std/azstd_files.cmake
  Code/Framework/AzCore/AzCore/std/typetraits/is_pod.h
  Code/Framework/AzCore/AzCore/std/typetraits/typetraits.h
  Code/Framework/AzCore/Tests/AZStd/Examples.cpp
  Code/Framework/AzCore/Tests/AZStd/TypeTraits.cpp
Labels: sig/core, status/stale

#15145 NetEntityId Code Comment
  Gems/Multiplayer/Code/Include/Multiplayer/MultiplayerTypes.h
Labels: sig/network, status/stale

#16538 Added valid URL in Chromatic Aberration component #16335
  Gems/AtomLyIntegration/CommonFeatures/Code/Source/PostProcess/ChromaticAberration/EditorChromaticAberrationComponent.cpp
Labels: sig/graphics-audio, status/stale

#18786 (stabilization) Compile fix - Fixes pythontestcoverage compile error if tests are disabled
  AutomatedTesting/Gem/PythonCoverage/Code/Source/PythonCoverageEditorSystemComponent.cpp
Labels: sig/build, sig/testing

#16206 Hide Slice asset type from search categories.
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Search/SearchWidget.cpp
Labels: sig/core, status/stale

#13132 Update text in Project Manager Gem catalog
  Code/Tools/ProjectManager/Source/GemCatalog/GemInspector.cpp
Labels: sig/content, status/stale

#18817 Do not buffer cmake Assets build logs
  Code/LauncherUnified/launcher_generator.cmake
Labels: sig/build

#18826 Merge from stabilization 25050 to development branch
  AutomatedTesting/Gem/PythonCoverage/Code/Source/PythonCoverageEditorSystemComponent.cpp
  Code/Framework/AzCore/AzCore/Script/ScriptPropertySerializer.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/ReflectionAdapter.cpp
  Code/Framework/AzFramework/AzFramework/DocumentPropertyEditor/SettingsRegistrar.cpp
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpConnection.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserTableView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Views/AssetBrowserThumbnailView.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Overrides/PrefabOverrideHandler.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/PrefabUndoHelpers.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Undo/PrefabUndoEntityOverrides.h
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.cpp
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/ComponentEditor.hxx
  Gems/Atom/Asset/ImageProcessingAtom/Code/Source/Processing/Utils.cpp
  Gems/PhysX/Core/Code/Source/EditorMeshColliderComponent.cpp
  Gems/ScriptCanvas/Code/CMakeLists.txt
Labels: sig/release, sync/to-development

#18828 Added PhysX locking to ArticulationLink component.
  Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
Labels: sig/simulation

#18830 Allow to modify position of root link of PhysX articulation
  Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.cpp
  Gems/PhysX/Core/Code/Source/ArticulationLinkComponent.h
Labels: sig/simulation

#11663 Script Canvas fix option to assign current graph to selected entities in the outliner
  AutomatedTesting/Levels/HW4/HW4.prefab
  Gems/ScriptCanvas/Code/Editor/Components/EditorScriptCanvasComponent.cpp
  Gems/ScriptCanvas/Code/Editor/Include/ScriptCanvas/Components/EditorScriptCanvasComponent.h
Labels: sig/content, status/stale

#18838 Fix Remote Tools Spam and restore SC live window
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.cpp
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.h
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/ScriptCanvasConstants.h
Labels: sig/content, need-sync/to-development

#18821 (Stabilization) cherry-pick from dev: DPE: Don't request a size update for every Dom change
  Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp
Labels: sync/to-stabilization

#18850 Disable google test support for monolithic
  cmake/Monolithic.cmake
Labels: sig/build, sig/core, sig/testing

#18576 XCB: Implement GetDisplayRefreshRate
  Code/Framework/AzFramework/Platform/Common/Xcb/AzFramework/XcbNativeWindow.cpp
  Code/Framework/AzFramework/Platform/Linux/platform_nativeui_linux.cmake
  Docker/Dockerfile
  cmake/Platform/Linux/Packaging_linux.cmake
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-bionic.txt
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-focal.txt
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-jammy.txt
  scripts/build/build_node/Platform/Linux/package-list.ubuntu-noble.txt
Labels: needs-sig

#18843 Don't recreate device TLAS every frame
  Gems/Atom/RHI/Code/Source/RHI/RayTracingAccelerationStructure.cpp
Labels: sig/graphics-audio

#18839 [Track View] Refactor reflected vars to enable editing ScreenFaderTrack keys.
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyCtrl.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedPropertyItem.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVar.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVar.h
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.cpp
  Code/Editor/Controls/ReflectedPropertyControl/ReflectedVarWrapper.h
  Code/Editor/CryEditDoc.cpp
  Code/Editor/TrackView/CommentKeyUIControls.cpp
  Code/Editor/TrackView/KeyUIControls.h
  Code/Editor/TrackView/ScreenFaderKeyUIControls.cpp
  Code/Editor/TrackView/SoundKeyUIControls.cpp
  Code/Editor/TrackView/TrackViewTrack.h
  Code/Editor/Util/Variable.h
  Code/Editor/Util/VariablePropertyType.cpp
  Code/Editor/Util/VariablePropertyType.h
  Code/Legacy/CryCommon/AnimKey.h
  Code/Legacy/CryCommon/Cry_Color.h
  Gems/Maestro/Code/CMakeLists.txt
  Gems/Maestro/Code/Source/Cinematics/AnimPostFXNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimScreenFaderNode.cpp
  Gems/Maestro/Code/Source/Cinematics/AnimScreenFaderNode.h
  Gems/Maestro/Code/Source/Cinematics/AnimTrack.h
  Gems/Maestro/Code/Source/Cinematics/ScreenFaderTrack.cpp
  Gems/Maestro/Code/Source/Cinematics/ScreenFaderTrack.h
  Gems/Maestro/Code/Source/Cinematics/ShadowsSetupNode.cpp
  Gems/Maestro/gem.json
Labels: sig/core

#18872 Fixes issues with undo and redo and continuous edits
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
Labels: sig/content, need-sync/to-development

#18879 Allows O3DE to compile with cmake v4.xx
  Gems/RecastNavigation/Code/CMakeLists.txt
  Gems/RecastNavigation/Code/recast-o3de.patch
  cmake/PatchIfNotAlreadyPatched.cmake
Labels: sig/build, need-sync/to-development

#18880 Merge stabilization 25.05.0 into development
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.cpp
  Code/Framework/AzNetworking/AzNetworking/TcpTransport/TcpSocket.h
  Code/Framework/AzToolsFramework/AzToolsFramework/Application/ToolsApplication.cpp
  Gems/Atom/RPI/Code/Source/RPI.Public/DllMain.cpp
  Gems/ScriptCanvas/Code/Editor/View/Widgets/LoggingPanel/LoggingWindow.cpp
  Gems/ScriptCanvas/Code/Include/ScriptCanvas/Utils/ScriptCanvasConstants.h
Labels: sig/build, sync/to-development
